#!/usr/bin/env python3
"""ML2-15 Internasjonal markedsføring + ML2-16 Økonomistyring."""
import importlib.util
from pathlib import Path
spec = importlib.util.spec_from_file_location("g", Path(__file__).parent / ".gen-shared.py")
g = importlib.util.module_from_spec(spec); spec.loader.exec_module(g)
C, ph, ex, M = g.C, g.ph, g.ex, g.M


INTERNASJ = M("InternasjonalMarkedsforing", "ml2", "ML2-15", "Markedsføring på internasjonale markeder", "🌍",
    "internasjonal-markedsforing", "ml2",
    "Verden som lekeplass — internasjonalisering gir vekst, stordriftsfordeler og risikospredning. Krever forståelse for kultur, etableringsstrategier og standardisering vs lokal tilpasning.",
    "Norsk laks-eksport er nå over 100 milliarder kroner årlig — Norges nest største eksportvare etter olje. 95 % eksporteres. Internasjonal markedsføring er nasjonens vekstmotor.",
    "Internasjonalisering er ikke bare 'å selge ut'. Det krever ydmykhet overfor lokale forskjeller — det som virker hjemme er sjelden direkte overførbart.",
    [
        ph("🌐", "Hvorfor internasjonalisere?",
           "Vekst, skala, risikospredning.",
           "Tre hovedgrunner: 1) Vekst (norsk marked er begrenset til 5,5 mill personer). 2) Stordriftsfordeler (samme produkt selges flere ganger). 3) Risikospredning (ikke avhengig av norsk konjunktur). Norske bedrifter som vokser mer enn 100x må typisk ut.",
           [("VEKST", "Norge er for lite for store ambisjoner."),
            ("RISIKO", "Spre eksponering over flere markeder.")],
           "Hvilken norsk bedrift har vokst stort gjennom internasjonalisering?",
           [ex("Hovedgrunn", "Hvorfor internasjonalisere?",
               [C("a", "Bare prestige", "Strategiske grunner."),
                C("b", "Vekst, stordriftsfordeler, risikospredning", "Riktig! Tre hovedgrunner.", correct=True),
                C("c", "Lovkrav", "Helt urelevant."),
                C("d", "Tilfeldig", "Strategisk valg.")],
               "Tomra startet i Norge, vokste til 100+ land. Norsk marked alene var ikke nok for global ambisjon."),
            ex("Norsk størrelse", "Hvor stort er norsk marked?",
               [C("a", "100 mill", "For høyt."),
                C("b", "5,5 millioner mennesker", "Riktig! Begrenser vekst-potensial for store bedrifter.", correct=True),
                C("c", "1 mrd", "Helt feil."),
                C("d", "Tilfeldig", "Konkret tall.")],
               "Med 5,5 mill innbyggere er Norge mindre enn én amerikansk delstat. Begrenser nasjonal skala."),
            ex("Risiko", "Hvordan reduserer eksport risiko?",
               [C("a", "Tilfeldig", "Strukturelt."),
                C("b", "Norsk konjunkturnedgang rammer mindre når man har inntekt fra mange markeder", "Riktig! Diversifisering.", correct=True),
                C("c", "Lovkrav", "Helt urelevant."),
                C("d", "Bare for olje", "Gjelder alle bransjer.")],
               "Da norsk olje falt i 2014, klarte bedrifter med internasjonal eksponering seg bedre.")]),
        ph("🛤️", "Etableringsstrategier",
           "Fra eksport til datterselskap.",
           "Fra lavt til høyt engasjement: 1) Eksport (selg fra Norge), 2) Lisensiering (la andre produsere), 3) Franchising (la andre drive), 4) Joint Venture (sammen med lokal partner), 5) Heleid datterselskap (full kontroll, full risiko). Ulike krav til ressurser og risiko.",
           [("LAV→HØY", "Risiko og engasjement øker fra eksport til datterselskap."),
            ("VALG", "Avhenger av marked, ressurser, kontroll-behov.")],
           "Hva er forskjellen på McDonald's franchise-modell og Apples direkte butikker?",
           [ex("Etableringsstrategier", "Hva er de 5 hovedstrategiene?",
               [C("a", "Bare eksport", "For smalt."),
                C("b", "Eksport, lisensiering, franchising, joint venture, datterselskap", "Riktig! Strukturert kontinuum.", correct=True),
                C("c", "Bare salg", "For smalt."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Velg basert på ressurser og marked-kunnskap. Lavrisiko = eksport. Høy kontroll = datterselskap."),
            ex("Joint Venture", "Når passer joint venture?",
               [C("a", "Aldri", "Brukes mye."),
                C("b", "I markeder der lokal kunnskap er kritisk eller lov krever lokalpartner", "Riktig! Mange asiatiske markeder krever JV.", correct=True),
                C("c", "Bare for små", "For store også."),
                C("d", "Tilfeldig", "Strukturert valg.")],
               "Kina krever ofte JV med kinesisk partner. Bilbransjen er klassisk eksempel."),
            ex("Heleid datter", "Når heleid datterselskap?",
               [C("a", "Aldri", "Brukes ofte."),
                C("b", "Når full kontroll er kritisk og man har ressurser til risikoen", "Riktig! Strategisk valg.", correct=True),
                C("c", "Bare for små", "For store typisk."),
                C("d", "Lovstridig", "Lovlig.")],
               "Apple bygger heleide butikker i premium-markeder. Vil ikke kompromisse opplevelsen.")]),
        ph("🎭", "Kulturell forståelse",
           "Hofstedes dimensjoner.",
           "Geert Hofstede identifiserte 6 kulturelle dimensjoner: maktavstand, individualisme/kollektivisme, maskulinitet/femininitet, usikkerhetsunngåelse, langtidsorientering, ettergivenhet. Norge skiller seg sterkt fra Asia på flere dimensjoner — påvirker både salgssamtaler og lederstil.",
           [("6 DIMENSJONER", "Måler kulturelle forskjeller systematisk."),
            ("NORGE = EKSTREMT", "Lavt maktdistanse, høy individualisme, lav maskulinitet.")],
           "Hva tror du er største kulturforskjell mellom Norge og Japan i forretningskontekst?",
           [ex("Hva", "Hva er Hofstedes dimensjoner brukt til?",
               [C("a", "Beregne valuta", "Helt feil."),
                C("b", "Forstå kulturelle forskjeller mellom land", "Riktig! Verktøy for global ledelse.", correct=True),
                C("c", "Måle BNP", "Helt feil."),
                C("d", "Finne nye markeder", "Bredere strategi.")],
               "Hofstede-modellen er fra 1980-tallet, fortsatt mye brukt i internasjonal forretningslitteratur."),
            ex("Norge", "Hvor ligger Norge?",
               [C("a", "Verdens høyeste maktdistanse", "Helt feil."),
                C("b", "Blant de laveste i maktdistanse, høyest individualisme, lavest maskulinitet", "Riktig! Norge er ekstreme på flere dimensjoner.", correct=True),
                C("c", "Gjennomsnittlig", "Norge skiller seg.")],
               "Norske ledere reiser til Asia og blir sjokkert over maktavstand. Lokal kunnskap kritisk."),
            ex("Praktisk", "Hvorfor er dette viktig for marketing?",
               [C("a", "Tilfeldig", "Strategisk."),
                C("b", "Norske direkte kommunikasjon kan oppleves uhøflig i Asia. Tilpas budskap til kultur", "Riktig! Pepsi mistet milliarder i Kina på feilmeldt tagline.", correct=True),
                C("c", "Bare for HR", "Markedsføring også."),
                C("d", "Lovkrav", "Helt urelevant.")],
               "KFC-tagline 'finger lickin' good' ble oversatt til 'eat your fingers off' i Kina. Dyrt feil.")]),
        ph("⚖️", "Standardisering vs adaptasjon",
           "Glocal — lik markedsmiks vs lokal tilpasning.",
           "Standardisering: lik markedsmiks overalt (lavere kostnad, sterkere global merkevare). Adaptasjon: lokal tilpasning (bedre kulturell relevans, høyere kostnad). De fleste store merkevarer kombinerer ('glocal'): McDonalds har Big Mac globalt + lokale spesialiteter (McSpicy Paneer i India, Rejmyre Burger i Sverige).",
           [("STANDARD = SKALA", "Stordriftsfordel + global merkebygging."),
            ("ADAPTASJON = RELEVANS", "Lokal tilpasning + kulturell sensitivitet.")],
           "Hvilke globale merker har du sett tilpasse til Norge? Hva endret de?",
           [ex("Glocal", "Hva er glocal?",
               [C("a", "Bare lokal", "For smalt."),
                C("b", "Kombinasjon av global standardisering og lokal tilpasning", "Riktig! Beste av begge verdener.", correct=True),
                C("c", "Bare global", "For smalt."),
                C("d", "Tilfeldig", "Strategisk valg.")],
               "Begrepet kombinerer 'global' og 'local'. Klassisk strategi for store merker."),
            ex("Hva tilpasses", "Hva tilpasses lokalt?",
               [C("a", "Bare logo", "Logo er typisk standard."),
                C("b", "Produkt, smaker, regelverk, sosiale normer — etter behov", "Riktig! Tilpas det som faktisk trenger lokal sensitivitet.", correct=True),
                C("c", "Alt", "For stor jobb."),
                C("d", "Ingenting", "For rigid.")],
               "Apple oversetter alt til lokale språk. Coca-Cola endret oppskrift i Mexico (mer sukker)."),
            ex("Norsk eksempel", "Hvilke tilpasninger har du sett i Norge?",
               [C("a", "Bare språk", "Mer enn språk."),
                C("b", "Språk + lokale tilbud (laksevarianter på McDonald's), bærekraft-meldinger", "Riktig! Norge er liten, men kreative tilpasninger.", correct=True),
                C("c", "Helt nytt brand", "Sjelden for kostbart."),
                C("d", "Ingenting", "Tilpasninger finnes alltid."),],
               "IKEA-pampelse-laksen er klassisk eksempel. Lokal tilpasning innenfor global ramme.")]),
        ph("📋", "Landanalysen (PESTEL)",
           "Kartlegg risiko før inntreden.",
           "PESTEL-analyse av nytt land: Politisk stabilitet, Økonomisk styrke, Sosiale normer, Teknologi-modenhet, Miljølovgivning, Lovverk. Et 50-siders PESTEL-dokument er standard før store internasjonale satsninger. Avdekker risiko du kanskje ikke hadde tenkt på.",
           [("RISK FØR INNTRED", "Bedre å oppdage risiko på papir enn i marked."),
            ("STANDARD VERKTØY", "Brukes for alle internasjonale satsninger.")],
           "Hva ville vært viktigste PESTEL-faktor om du skulle åpne norsk bedrift i Brasil?",
           [ex("PESTEL", "Hva analyserer PESTEL?",
               [C("a", "Bare økonomi", "For smalt."),
                C("b", "Politisk, Økonomisk, Sosialt, Teknologisk, Environmental, Lovmessig", "Riktig! 6 dimensjoner.", correct=True),
                C("c", "Bare salg", "Helt feil."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Hver dimensjon kan inneholde dealbreakers. Sjekk alle, ikke bare én."),
            ex("Politisk", "Hva inkluderer politisk risiko?",
               [C("a", "Bare valg", "Bredere."),
                C("b", "Stabilitet, korrupsjon, regulering, handelsavtaler", "Riktig! Politikk påvirker marked direkte.", correct=True),
                C("c", "Bare militær", "For smalt."),
                C("d", "Bare lovkrav", "Bredere.")],
               "Russland-invasjonen 2022 viste hvor raskt politisk risiko kan ramme. Vestlige bedrifter måtte trekke seg ut."),
            ex("Hvorfor", "Hvorfor gjøre PESTEL?",
               [C("a", "Pynt", "Praktisk verktøy."),
                C("b", "Avdekke risiko og muligheter — bedre å oppdage på papir enn i marked", "Riktig! Forebygger dyre feil.", correct=True),
                C("c", "Lovkrav", "Helt urelevant."),
                C("d", "Bare for store", "Brukes alle størrelser.")],
               "Mange bedrifter har kostbar læring fra å hoppe inn i nye markeder uten skikkelig analyse.")]),
        ph("💱", "Internasjonal prising",
           "Valuta, dumping, transfer pricing.",
           "Internasjonal prising er komplekst: valutasvingninger (krone-svekkelse gir norske eksportører fordel), dumping (selge under selvkost — ofte ulovlig), transfer pricing (interne priser mellom datterselskaper — strengt skattemessig regulert). Skattemyndigheter har strenge regler.",
           [("VALUTARISIKO", "Krone-svingninger påvirker eksportører dramatisk."),
            ("TRANSFER PRICING", "Strengt regulert for å hindre skatte-omgåelse.")],
           "Hva skjer med norsk laks-eksport når kronen styrker seg vs USD?",
           [ex("Valutasvingning", "Hva skjer ved sterk krone?",
               [C("a", "Norsk eksport blir billigere", "Tvert imot."),
                C("b", "Norsk eksport blir dyrere internasjonalt — vanskeligere å selge", "Riktig! Strukturell utfordring for eksportbransjer.", correct=True),
                C("c", "Ingen effekt", "Stor effekt."),
                C("d", "Bare for olje", "Gjelder alle.")],
               "Norske eksportører har historisk slitt når kronen er sterk. Importører tjener motsatt."),
            ex("Dumping", "Hva er dumping?",
               [C("a", "Lovlig prisstrategi", "Tvert imot."),
                C("b", "Selge under selvkost — ofte ulovlig som anti-konkurranse-tiltak", "Riktig! WTO-regler hindrer dumping.", correct=True),
                C("c", "Bare i Kina", "Globalt fenomen."),
                C("d", "Helt vanlig", "Ulovlig praksis.")],
               "EU har anti-dumping-tariffer mot kinesiske produkter (sykler, sko). Norge følger EU-regler via EØS."),
            ex("Transfer pricing", "Hva er det?",
               [C("a", "Frakt over landegrenser", "Helt feil tolkning."),
                C("b", "Interne priser mellom datterselskaper — strengt skattemessig regulert", "Riktig! Skattemyndigheter sikrer at multinasjonaler betaler skatt der verdien skapes.", correct=True),
                C("c", "Valutakurser", "Helt feil."),
                C("d", "Reise-utgifter", "Helt feil.")],
               "Multinasjonaler kan ellers flytte profitt til lavskatteland via interne priser. Strengt regulert.")]),
        ph("📦", "Logistikk og toll",
           "Incoterms og handelsavtaler.",
           "Incoterms (International Commercial Terms) er standardisert ramme for hvem som har ansvar for varene under transport (FOB, CIF, etc.). Tollbarrierer varierer per land. Handelsavtaler (EØS gir Norge full markedsadgang i EU). Toll og avgifter kan utgjøre 20-40 % av varens pris i fjerne markeder.",
           [("INCOTERMS", "Standardisert ansvarsfordeling for internasjonal transport."),
            ("EØS", "Norge har full markedsadgang i EU — kritisk for eksport.")],
           "Hva betyr 'EXW' eller 'CIF'? Hvilken er bedre for kjøperen?",
           [ex("Incoterms", "Hva er Incoterms?",
               [C("a", "Et IT-system", "Helt feil."),
                C("b", "Standardiserte vilkår for ansvar i internasjonal handel", "Riktig! Bestemmer hvem som har ansvaret hvor i transport-kjeden.", correct=True),
                C("c", "Tollavgifter", "Helt feil."),
                C("d", "En valuta", "Helt feil.")],
               "Incoterms vedlikeholdes av ICC. Oppdateres ca hvert 10. år. Siste versjon: Incoterms 2020."),
            ex("EØS", "Hvor viktig er EØS-avtalen?",
               [C("a", "Lite", "Kritisk for norsk eksport."),
                C("b", "Kritisk — gir Norge full markedsadgang i EU uten toll", "Riktig! 80 % av norsk eksport går til EU.", correct=True),
                C("c", "Bare olje", "Gjelder alle bransjer."),
                C("d", "Lovstridig", "Helt feil — internasjonal avtale.")],
               "Uten EØS ville norske bedrifter måttet betale EU-toll. Stor konkurranseulempe."),
            ex("Toll-andel", "Hvor mye kan toll være?",
               [C("a", "Bare 1-2 %", "Kan være mye høyere."),
                C("b", "20-40 % i fjerne markeder med høye barrierer", "Riktig! Strukturelt utfordring for eksport.", correct=True),
                C("c", "Aldri toll", "Helt feil."),
                C("d", "100 %", "Sjelden så høyt.")],
               "Brasil, India har historisk hatt høye importtoll. Strategisk barriere for utenlandske aktører.")]),
        ph("📢", "Global kommunikasjon",
           "Språk og kulturelle koder.",
           "Engelske slagord oversettes ikke alltid godt. Bilder av kvinner uten hijab vil ikke fungere i Saudi-Arabia. Lokale byråer er uvurderlige. Sentralisert global kommunikasjon kan spare penger, men risikere kulturelle blunder. Beste praksis: global ramme, lokal eksekvering.",
           [("OVERSETTELSE-RISIKO", "Direkte oversettelse gir ofte uheldige resultater."),
            ("LOKAL EKSPERTISE", "Lokale byråer kjenner kulturelle koder.")],
           "Husker du noen reklame som klart ikke fungerte fordi den ble oversatt direkte?",
           [ex("Risiko", "Hva er hovedrisiko ved global kommunikasjon?",
               [C("a", "Tilfeldig", "Strukturelt."),
                C("b", "Kulturelle blunder pga manglende lokal kunnskap", "Riktig! Klassisk feilkilde.", correct=True),
                C("c", "For dyrt", "Sekundært."),
                C("d", "Lovkrav", "Helt urelevant.")],
               "KFC, Pepsi, HSBC — alle har gjort kostbare oversettelses-feil. Lokal sjekk er ikke valgfritt."),
            ex("Beste praksis", "Hvordan håndtere?",
               [C("a", "Bare oversette mekanisk", "Risikabelt."),
                C("b", "Global merkeramme + lokal eksekvering med lokale byråer", "Riktig! Konsistens + relevans.", correct=True),
                C("c", "Bare lokalt", "Mister merkeintegritet."),
                C("d", "Tilfeldig", "Strukturert.")],
               "McDonald's: global Big Mac + lokal meny. Global merkeramme + lokal eksekvering. Beste av begge."),
            ex("Bilder", "Hva med bildebruk?",
               [C("a", "Standard overalt", "Risikabelt."),
                C("b", "Tilpas til kulturelle normer — alkohol, kvinner, religion", "Riktig! Visuelle normer varierer dramatisk.", correct=True),
                C("c", "Bare i USA", "Gjelder alle."),
                C("d", "Aldri tilpasse", "Strategisk feil.")],
               "Saudi-Arabia: ingen alkohol-bilder, kvinner med hijab, religiøse hensyn. Strenge regler.")]),
        ph("⚠️", "Risiko ute",
           "Politisk, korrupsjon, jus.",
           "Politisk risiko: regimer endres, eiendeler kan eksproprieres. Korrupsjon: nødvendig i noen markeder, ulovlig hjemme. Juridiske forskjeller: kontrakter kan være verdiløse i visse land. Forsikringer mot disse finnes (GIEK i Norge, Atradius globalt). Norske bedrifter må navigere komplekst.",
           [("POLITISK", "Regimer endres, krig, ekspropriasjon."),
            ("KORRUPSJON", "Norske bedrifter forbudt under norsk lov, selv i utlandet.")],
           "Hvilke risiko ville du vurdert før norsk bedrift ekspanderer til Russland eller Saudi-Arabia?",
           [ex("Politisk risiko", "Hva er typisk politisk risiko?",
               [C("a", "Bare valg", "Bredere."),
                C("b", "Regimeendringer, krig, ekspropriasjon, sanksjoner", "Riktig! Bredt spekter av risiko.", correct=True),
                C("c", "Bare lokal lov", "For smalt."),
                C("d", "Tilfeldig", "Strukturelt.")],
               "Russland-invasjonen 2022: vestlige bedrifter måtte trekke seg ut, tape milliarder. Politisk risiko realisert."),
            ex("Korrupsjon", "Hva sier norsk lov om korrupsjon i utlandet?",
               [C("a", "Lovlig hvis lokalt akseptert", "Helt feil."),
                C("b", "Forbudt under norsk lov — selv om praksis i utlandet", "Riktig! Norske straffeloven gjelder norske bedrifter globalt.", correct=True),
                C("c", "Bare i Norge", "Helt feil."),
                C("d", "Tilfeldig", "Streng lov.")],
               "Statoil-saken (Iran 2003): bot på 80 mill USD. Norske bedrifter holdes ansvarlige globalt."),
            ex("Forsikring", "Hvilken norsk institusjon hjelper med eksportrisiko?",
               [C("a", "Banken", "For smalt."),
                C("b", "GIEK — Garantiinstituttet for eksportkreditt", "Riktig! Statlig institusjon for eksportrisiko.", correct=True),
                C("c", "Brønnøysund", "Helt feil."),
                C("d", "Skattetaten", "Helt feil.")],
               "GIEK garanterer for eksportkreditt og politisk risiko. Kritisk for norske eksportbedrifter.")]),
        ph("🌊", "Norwegians USA-satsing",
           "Klassisk eksempel på mislykket internasjonalisering.",
           "Norwegian satset hardt på lavprisflyvninger til USA. Manglende lokalkunnskap, hard konkurranse, valutarisiko og pandemi førte til konkurs i 2020. Lærdom: lokal innsikt og finansiell bærekraft må være på plass før internasjonal vekst. Verden er ett marked, men med mange lokale sannheter.",
           [("LÆRDOM", "Lokal innsikt + finansiell bærekraft må være på plass."),
            ("YDMYKHET", "Det som virker hjemme er ikke automatisk overførbart.")],
           "Hva skulle Norwegian gjort annerledes? Hva kunne hindret konkursen?",
           [ex("Norwegian", "Hva skjedde med Norwegians USA-satsing?",
               [C("a", "Stor suksess", "Helt feil."),
                C("b", "Endte i konkurs 2020 — manglende lokalkunnskap, valutarisiko, pandemi", "Riktig! Klassisk eksempel på mislykket internasjonalisering.", correct=True),
                C("c", "Pågår fortsatt", "Avsluttet."),
                C("d", "Aldri prøvd", "Helt feil.")],
               "Norwegian Long Haul-strategien er case study i internasjonal markedsføring. Mange feil i utførelsen."),
            ex("Hovedlærdom", "Hva er strategisk lærdom?",
               [C("a", "Aldri internasjonalisere", "For dogmatisk."),
                C("b", "Lokal innsikt og finansiell bærekraft må være på plass", "Riktig! Grundig forberedelse før vekst.", correct=True),
                C("c", "Bare amerikanske aktører lykkes", "For pessimistisk."),
                C("d", "Tilfeldighet", "Strukturelle årsaker."),],
               "Mange norske bedrifter har lykkes internasjonalt — men har gjort grundig forberedelse."),
            ex("Suksess-faktor", "Hva må være på plass?",
               [C("a", "Bare penger", "Ikke nok."),
                C("b", "Lokal kunnskap, finansiell styrke, klar strategi, kulturell sensitivitet", "Riktig! Multi-dimensjonal forberedelse.", correct=True),
                C("c", "Bare reklame", "For smalt."),
                C("d", "Tilfeldig", "Strukturert."),],
               "Tomra, Equinor, Yara — alle har lykkes globalt. Felles: grundig forberedelse, ikke 'cowboy-tilnærming'.")]),
        ph("📈", "Internasjonal suksess",
           "Ydmykhet overfor lokale forskjeller.",
           "Internasjonal suksess krever ydmykhet overfor lokale forskjeller. Det som virker hjemme er ikke automatisk overførbart — kulturen, kjøpsadferden og konkurransen er alltid annerledes. Norske bedrifter som lykkes globalt: Tomra, Equinor, Yara, DNV, Mowi. Felles: respekt for det lokale.",
           [("YDMYKHET", "Strategisk dyd i internasjonal forretning."),
            ("LOKAL = STRATEGI", "Tilpasning er ikke svakhet, det er strategi.")],
           "Hvilke norske bedrifter ser du som lykkes internasjonalt? Hva gjør dem annerledes?",
           [ex("Suksess-faktor", "Hva er felles for vellykkede norske eksportbedrifter?",
               [C("a", "Bare lave priser", "For smalt."),
                C("b", "Respekt for lokale forskjeller + langsiktig satsing + finansiell styrke", "Riktig! Multi-dimensjonal forklaring.", correct=True),
                C("c", "Bare offentlig støtte", "Sekundært."),
                C("d", "Tilfeldighet", "Strukturelle drivere.")],
               "Tomra: 30+ år i internasjonalisering. Equinor: lokal partnerskap globalt. Yara: tilpasset gjødsel per region."),
            ex("Norske eksempler", "Hvilken norsk bedrift er størst internasjonalt?",
               [C("a", "Bare Equinor", "Mange er store."),
                C("b", "Equinor, Yara, Mowi, Telenor, DNV, Hydro — flere milliarder USD i internasjonal omsetning", "Riktig! Norge har flere globale aktører.", correct=True),
                C("c", "Bare Vipps", "For smalt — Vipps er nasjonal."),
                C("d", "Ingen", "Helt feil.")],
               "Norge har relativt mange globale selskaper for sin størrelse. Olje + maritim + sjømat har bygget eksport-kompetanse."),
            ex("Lærdom", "Hva er hovedlærdommen?",
               [C("a", "Internasjonalisering er enkelt", "Tvert imot."),
                C("b", "Krever ydmykhet, forberedelse, finansiell styrke og tålmodighet", "Riktig! Modne strategi.", correct=True),
                C("c", "Bare for store", "Mange små lykkes."),
                C("d", "Tilfeldig", "Strukturerte krav.")],
               "'Verden er ett marked, men med mange lokale sannheter.' — moderne motto for internasjonal markedsføring.")]),
    ],
    ["Du forstår de 3 hovedgrunnene til internasjonalisering: vekst, skala, risikospredning",
     "Du kan velge etableringsstrategi (eksport → datterselskap) basert på risiko og kontroll-behov",
     "Du kjenner Hofstedes dimensjoner og hvorfor kulturell forståelse er strategisk",
     "Du behersker glocal-strategien — global ramme + lokal tilpasning",
     "Du kjenner Incoterms, EØS-effekt, og norske institusjoner som GIEK"])


OKONOMI = M("OkonomistyringKalkulasjonBudsjettering", "ml2", "ML2-16", "Økonomistyring, kalkulasjon og budsjettering", "💰",
    "okonomistyring-kalkulasjon-budsjettering", "ml2",
    "Tallenes tale — kalkulasjon, dekningsbidrag og budsjett som beslutningsgrunnlag for markedsføreren. Markedsføring uten økonomisk forståelse mister troverdighet i ledelsen.",
    "Markedsdirektører som kan vise ROI behold budsjett. De som ikke kan, taper det. Økonomisk språk er marketing-direktørens viktigste verktøy.",
    "Markedsføring som ikke kan begrunnes med tall mister først budsjett, så stemme i ledelsen, så plass. Lær økonomi-språket.",
    [
        ph("💰", "Økonomi og markedsføring",
           "Markedsføreren må forstå regnskapet.",
           "Markedsføreren må forstå regnskapet for å få budsjetter. Argumentet 'kampanjen var kreativ' faller flatt i toppledelsen. Argumentet 'ROI 4,2 og dekningsmargin 32 %' åpner kassen. Økonomisk språk er marketing-direktørens viktigste verktøy.",
           [("SPRÅK", "Økonomi er ledelsens språk — marketing må snakke det."),
            ("BUDSJETT", "Forsvar krever tall, ikke følelser.")],
           "Har du sett markedsføring forsvart med tall? Hva ble effektivt?",
           [ex("Hvorfor", "Hvorfor må marketing forstå økonomi?",
               [C("a", "Tilfeldig", "Strategisk."),
                C("b", "For å forsvare budsjett og bygge troverdighet i ledelsen", "Riktig! Tall snakker høyere enn ord.", correct=True),
                C("c", "Bare for store", "Gjelder alle."),
                C("d", "Lovkrav", "Helt urelevant.")],
               "Marketing-direktører som mestrer økonomi blir promotert til CEO. De som ikke gjør det, blir værende i marketing."),
            ex("Argument", "Hvilket argument fungerer i ledelsen?",
               [C("a", "'Kampanjen var kreativ'", "Faller flatt."),
                C("b", "'ROI 4,2 og dekningsmargin 32 %'", "Riktig! Konkrete tall vinner debatten.", correct=True),
                C("c", "'Folk likte den'", "For vagt."),
                C("d", "'Vi hadde det gøy'", "Helt feil tilnærming.")],
               "Test: kan du beskrive marketing-effekten i tall? Hvis nei, vil du tape budsjett-debatten."),
            ex("Verdi", "Hva er marketing-direktørens viktigste verktøy?",
               [C("a", "Bare kreativitet", "For smalt."),
                C("b", "Økonomisk språk — kombinert med kreativitet", "Riktig! Begge må være på plass.", correct=True),
                C("c", "Bare nettverk", "For smalt."),
                C("d", "Tilfeldig", "Strukturert."),],
               "Phil Kotler: 'Marketing is too important to be left to the marketing department.' Marketing er hele bedriften.")]),
        ph("📊", "Kalkulasjonsmetoder",
           "Bidragsmetoden vs selvkostmetoden.",
           "Bidragsmetoden: variable kostnader + dekningsbidrag. Brukes for kortsiktige beslutninger ('skal vi ta neste ordre?'). Selvkostmetoden: alle kostnader + påslag. Brukes for langsiktige beslutninger ('er produktet lønnsomt?'). Begge har sin plass.",
           [("BIDRAG = KORTSIKT", "Variable kostnader + dekningsbidrag."),
            ("SELVKOST = LANGSIKT", "Alle kostnader + påslag.")],
           "Når ville du brukt selvkost vs bidragsmetoden?",
           [ex("Bidrag", "Når brukes bidragsmetoden?",
               [C("a", "Langsiktige beslutninger", "Det er selvkost."),
                C("b", "Kortsiktige beslutninger med ledig kapasitet", "Riktig! Når faste kostnader er allerede dekket.", correct=True),
                C("c", "Aldri", "Brukes mye."),
                C("d", "Bare for offentlig", "Privat sektor."),],
               "Hotell med ledig kapasitet: bidragsmetoden viser at last-minute-rabatt fortsatt er lønnsom."),
            ex("Selvkost", "Når brukes selvkost?",
               [C("a", "Aldri", "Brukes mye."),
                C("b", "Langsiktige beslutninger om produktets reelle lønnsomhet", "Riktig! Dekker alle kostnader for full vurdering.", correct=True),
                C("c", "Bare i offentlig sektor", "Brukes overalt."),
                C("d", "Aldri kortsiktig", "Det er korrekt — bidrag er kortsiktig."),],
               "Settes priser for hele året: selvkost. Vurderes om man skal kutte produktet: selvkost."),
            ex("Forskjell", "Hva er hovedforskjellen?",
               [C("a", "De er det samme", "Helt feil."),
                C("b", "Selvkost inkluderer alle kostnader; bidrag bare variable", "Riktig! Strukturell forskjell som styrer beslutninger.", correct=True),
                C("c", "Lovkrav", "Strategiske valg."),
                C("d", "Bare for små", "Begge brukes overalt.")],
               "Norske bedrifter bruker oftest bidragsmetoden i operasjonelle beslutninger, selvkost i strategiske.")]),
        ph("📈", "Dekningsbidrag",
           "Hva sitter vi igjen med per enhet?",
           "Dekningsbidrag = Salgspris - Variable kostnader. Hvor mye sitter vi igjen med per solgte enhet til å dekke faste kostnader og fortjeneste? Avgjør hvilke produkter som er verdt å selge. Dekningsgrad = dekningsbidrag i prosent av salgspris.",
           [("FORMEL", "DB = Pris - Variable kostnader."),
            ("BESLUTNING", "Lavt DB = vanskelig å være lønnsom selv ved høyt volum.")],
           "Et produkt selges for 100 kr. Variable kostnader 60 kr. Hva er dekningsbidraget?",
           [ex("Definisjon", "Hva er dekningsbidrag?",
               [C("a", "Total inntekt", "Bruttoinntekt, ikke DB."),
                C("b", "Salgspris minus variable kostnader", "Riktig! Det som er igjen til faste kostnader og overskudd.", correct=True),
                C("c", "Bare overskudd", "For smalt — DB inkluderer faste kostnader."),
                C("d", "Faste kostnader", "Helt feil.")],
               "Dekningsbidrag = 100 - 60 = 40 kr per enhet. Disse 40 kr skal dekke faste kostnader."),
            ex("Dekningsgrad", "Hva er dekningsgrad i samme eksempel?",
               [C("a", "20 %", "Feil regning."),
                C("b", "40 % (40/100)", "Riktig! DB i prosent av salgspris.", correct=True),
                C("c", "60 %", "Det er variable kostnaders andel."),
                C("d", "100 %", "Helt feil.")],
               "Dekningsgrad er nyttig for sammenligning på tvers av produkter med ulik pris."),
            ex("Avanse vs DG", "Hva er forskjellen på avanse og dekningsgrad?",
               [C("a", "De er det samme", "Helt feil."),
                C("b", "Avanse = av innkjøpspris. Dekningsgrad = av salgspris", "Riktig! Klassisk feil i butikkdrift.", correct=True),
                C("c", "Bare for B2B", "Begge brukes overalt."),
                C("d", "Bare i USA", "Brukes globalt."),],
               "50 % avanse = 33 % dekningsgrad. Mange nye butikkeiere blander disse — kan gå konkurs.")]),
        ph("🎯", "Nullpunktsanalyse (break-even)",
           "Hvor mange må selge for å gå i null?",
           "Break-even point = faste kostnader / dekningsbidrag per enhet. Eksempel: faste kostnader 1 mill, DB 100 kr/enhet → må selge 10 000 enheter for å gå i null. Kritisk for prising og lansering. Hvis du tror du selger 8 000 = stopp.",
           [("FORMEL", "Break-even = Faste kostnader / DB per enhet."),
            ("BRUK", "Lansering, prising, kapasitetsplanlegging.")],
           "Faste kostnader 500 000. DB per enhet 250 kr. Hva er break-even?",
           [ex("Definisjon", "Hva er break-even?",
               [C("a", "Når bedriften går konkurs", "Tvert imot."),
                C("b", "Punktet der inntekter dekker totale kostnader — verken tap eller fortjeneste", "Riktig! Kritisk milestone.", correct=True),
                C("c", "Når lageret er tomt", "Helt feil."),
                C("d", "Når kapitalen er brukt opp", "Helt feil.")],
               "Break-even forteller minimumsvolum for lønnsomhet. Under = tap, over = profitt."),
            ex("Beregning", "Faste kostnader 500 000. DB 250 kr. Break-even?",
               [C("a", "1 000 enheter", "Feil regning."),
                C("b", "2 000 enheter (500000 / 250)", "Riktig! Klassisk break-even-beregning.", correct=True),
                C("c", "5 000 enheter", "Feil regning."),
                C("d", "10 000 enheter", "Helt feil.")],
               "Sjekk neste: kan vi realistisk selge 2000+ enheter? Hvis ikke, ikke lansér."),
            ex("Lansering", "Hvordan brukes break-even ved lansering?",
               [C("a", "Bare etter lansering", "Bør være før."),
                C("b", "Beregn FØR lansering — sammenlign med realistisk salgsestimat", "Riktig! Avdekker urealistiske planer.", correct=True),
                C("c", "Aldri", "Brukes mye."),
                C("d", "Tilfeldig", "Strukturert."),],
               "Hvis break-even = 50 000 enheter, men markedet er bare 30 000 totalt — ikke lansér.")]),
        ph("📋", "Budsjettering",
           "Resultatbudsjett vs likviditetsbudsjett.",
           "Budsjettering: planlegging av fremtidige inntekter og kostnader. Resultatbudsjett (lønnsomhet over perioden), likviditetsbudsjett (kontanter måned for måned), investeringsbudsjett (anleggsmidler). Alle tre må stemme — kan være lønnsom på papiret, men gå konkurs av likviditetsmangel.",
           [("3 BUDSJETTER", "Resultat + likviditet + investering."),
            ("LIKVIDITET KRITISK", "Kan gå konkurs selv med overskudd på papiret.")],
           "Hva er forskjellen på lønnsomhet og likviditet for en bedrift?",
           [ex("3 typer", "Hvilke 3 budsjetter?",
               [C("a", "Bare resultat", "For smalt."),
                C("b", "Resultatbudsjett, likviditetsbudsjett, investeringsbudsjett", "Riktig! Komplett budsjett-pakke.", correct=True),
                C("c", "Bare salg", "For smalt."),
                C("d", "Tilfeldig", "Strukturert."),],
               "Alle tre må stemme. Mange bedrifter glemmer likviditet — det dreper dem."),
            ex("Likviditet", "Hva er likviditetsbudsjett?",
               [C("a", "Plan for forventet overskudd", "Det er resultatbudsjett."),
                C("b", "Oversikt over innbetalinger og utbetalinger måned for måned", "Riktig! Ser om det er penger til å betale regninger.", correct=True),
                C("c", "Bare for konkursvurdering", "Brukes løpende."),
                C("d", "Tilfeldig", "Strukturert."),],
               "Salg gir ikke likviditet umiddelbart — kunder betaler senere. Krevende cash-flow-styring."),
            ex("Lønnsom men konkurs", "Hvordan kan dette skje?",
               [C("a", "Tilfeldig", "Strukturelt."),
                C("b", "Salg på faktura skaper inntekt på papiret, men ikke kontant — leverandører må betales nå", "Riktig! Klassisk vekstbedrift-utfordring.", correct=True),
                C("c", "Bare i krise", "Vanlig problem."),
                C("d", "Bare offentlig sektor", "Privat også."),],
               "Norwegian rapporterte rekordtall 2019. Gikk konkurs 2020 — likviditetskrise. Klassisk eksempel.")]),
        ph("💧", "Likviditetsstyring",
           "Cash is king.",
           "Likviditet: bedriftens evne til å betale løpende forpliktelser. Mange lønnsomme bedrifter går konkurs av likviditetskrise. Kunder som betaler sent + leverandører som krever rask betaling = likviditetskrise selv om regnskapet ser bra ut. 'Cash is king' — også for vekstbedrifter.",
           [("KASSEFLYT", "Sikre at det er penger til å betale når det trengs."),
            ("VEKSTPARADOKS", "Vekst kan øke likviditetsbehov dramatisk.")],
           "Hva ville du gjort hvis kunden ikke betaler i tide?",
           [ex("Definisjon", "Hva er likviditet?",
               [C("a", "Total formue", "For bredt."),
                C("b", "Bedriftens evne til å betale løpende forpliktelser", "Riktig! Kortsiktig betalingsevne.", correct=True),
                C("c", "Bare overskudd", "For smalt."),
                C("d", "Tilfeldig", "Strukturert.")],
               "'Cash is king' i forretningslivet. Likviditet > lønnsomhet i nedgangstider."),
            ex("Vekst-paradoks", "Hvorfor er vekst risikabelt for likviditet?",
               [C("a", "Tilfeldig", "Strukturelt."),
                C("b", "Salg vokser → må kjøpe mer lager + lønne mer + betale leverandører — før kunder betaler", "Riktig! Klassisk vekstbedrift-utfordring.", correct=True),
                C("c", "Vekst er alltid bra", "Kan være risikabelt."),
                C("d", "Lovstridig", "Helt urelevant.")],
               "Mange suksessbedrifter går konkurs midt i veksten. Likviditet må følges nøye."),
            ex("Tiltak", "Hvordan styrke likviditet?",
               [C("a", "Bare øke salg", "Kan forverre."),
                C("b", "Raskere kundeinnbetalinger + lengre leverandørgjeld + lavere lager", "Riktig! Arbeidskapital-styring.", correct=True),
                C("c", "Bare lån mer", "Sekundært tiltak."),
                C("d", "Tilfeldig", "Strukturerte tiltak."),],
               "Klassiske tiltak: tilbud om rabatt for rask betaling, faktura-rapportering, factoring.")]),
        ph("📊", "Investeringsanalyse",
           "Lønnsomt prosjekt eller ikke?",
           "Investeringsanalyse: er det lønnsomt å starte dette prosjektet? Nåverdimetoden (NPV — diskonterte fremtidige kontantstrømmer minus investering), internrente, payback-periode (hvor lang tid før investeringen er tilbakebetalt). Tidsverdien av penger er sentralt: 100 kr i dag er verdt mer enn 100 kr om fem år.",
           [("NPV", "Nåverdi av fremtidige kontantstrømmer."),
            ("PAYBACK", "Hvor lang tid til investeringen tilbakebetales.")],
           "Investering 1 mill. Forventet årlig kontantstrøm 250 000 kr. Hva er payback?",
           [ex("Tidsverdi", "Hvorfor er 100 kr i dag verdt mer enn 100 kr om 5 år?",
               [C("a", "Tilfeldig", "Strukturelt."),
                C("b", "Kan investere de 100 i dag og få avkastning over 5 år", "Riktig! Tidsverdien av penger.", correct=True),
                C("c", "Inflasjon", "Også en faktor, men ikke kjernen."),
                C("d", "Lovkrav", "Helt urelevant.")],
               "Diskonteringsrente representerer alternativ avkastning. Sentralt i NPV-beregning."),
            ex("Payback", "Investering 1 mill. Årlig kontantstrøm 250 000. Payback?",
               [C("a", "1 år", "Feil regning."),
                C("b", "4 år (1 000 000 / 250 000)", "Riktig! Enkel beregning.", correct=True),
                C("c", "10 år", "Feil regning."),
                C("d", "20 år", "Helt feil.")],
               "Payback er enkel og populær, men ignorerer tidsverdien av penger."),
            ex("Beste metode", "Hvilken metode er teoretisk best?",
               [C("a", "Payback", "Enkel, men ufullstendig."),
                C("b", "NPV — Net Present Value", "Riktig! Tar hensyn til tidsverdien av penger.", correct=True),
                C("c", "Magefølelse", "Subjektiv."),
                C("d", "Tilfeldig", "Strukturert.")],
               "NPV er gullstandarden. Payback brukes som supplement for likviditetshensyn.")]),
        ph("📐", "Nøkkeltall",
           "Rentabilitet, likviditet, soliditet.",
           "Tre hovedkategorier: Rentabilitet (avkastning på investert kapital), Likviditet (evne til å betale løpende), Soliditet (egenkapital som andel av totalkapital). Nøkkeltall gir rask vurdering av økonomisk helse. Brukes av investorer, banker, ledelse for å sammenligne bedrifter.",
           [("3 KATEGORIER", "Rentabilitet, likviditet, soliditet."),
            ("BENCHMARK", "Sammenlign mot bransjegjennomsnitt.")],
           "Hvilke nøkkeltall ville du sjekket før investering i en bedrift?",
           [ex("Kategorier", "Hva er de 3 hovedkategoriene?",
               [C("a", "Bare rentabilitet", "For smalt."),
                C("b", "Rentabilitet, likviditet, soliditet", "Riktig! Tre dimensjoner av økonomisk helse.", correct=True),
                C("c", "Bare overskudd", "For smalt."),
                C("d", "Tilfeldig", "Strukturert."),],
               "Hver kategori har egne nøkkeltall. Komplett bilde krever alle tre."),
            ex("Soliditet", "Hva måler soliditet?",
               [C("a", "Salgsvolum", "Helt feil."),
                C("b", "Egenkapital som andel av totalkapital — robusthet mot tap", "Riktig! Buffer mot dårlige tider.", correct=True),
                C("c", "Bare lønninger", "Helt feil."),
                C("d", "Tilfeldig", "Strukturert."),],
               "Norsk standard: soliditet > 30 % regnes som solid. Under 10 % er risikabelt."),
            ex("Bruk", "Hvem bruker nøkkeltall?",
               [C("a", "Bare ledelsen", "Bredere bruk."),
                C("b", "Investorer, banker, leverandører, ledelsen, ansatte", "Riktig! Alle interessenter.", correct=True),
                C("c", "Bare offentlige", "Privat sektor like aktivt."),
                C("d", "Lovkrav", "Strategisk verktøy.")],
               "Banker krever nøkkeltall før de gir lån. Investorer ser på nøkkeltall før de kjøper aksjer.")]),
        ph("🎯", "ROI i markedsføring",
           "Avkastning på markedsbudsjett.",
           "ROI = (gevinst - kostnad) / kostnad × 100. Inkluderer alle marketing-kostnader (også internt arbeid). Hvis ROI er 30 %, er hver krone investert verdt 1,30 kr. Vanskelig å beregne presist for merkebygging — men kritisk for å rettferdiggjøre marketing-budsjett i ledelsen.",
           [("FORMEL", "ROI = (gevinst - kostnad) / kostnad × 100."),
            ("HELHETLIG", "Inkluder alle kostnader, ikke bare annonser.")],
           "Hvordan ville du beregnet ROI for en kampanje du har sett?",
           [ex("Definisjon", "Hva er ROI?",
               [C("a", "Bare omsetning", "For smalt."),
                C("b", "(Gevinst - kostnad) / kostnad × 100", "Riktig! Standard formel for avkastning.", correct=True),
                C("c", "Bare kostnad", "For smalt."),
                C("d", "Tilfeldig", "Strukturert.")],
               "ROI 30 % = 1.30 kr tilbake per krone investert. Standard finansielt mål."),
            ex("Inkluder", "Hva må inkluderes i marketing-kostnad?",
               [C("a", "Bare annonser", "For smalt."),
                C("b", "Annonser + internt arbeid + byråer + teknologi", "Riktig! Helhetlig kostnadsbilde.", correct=True),
                C("c", "Bare lønninger", "For smalt."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Mange undervurderer marketing-kostnad ved å glemme internt arbeid. Gir feilaktig høy ROI."),
            ex("Vanskelig", "Hvorfor er merkebygging vanskelig å attribuere?",
               [C("a", "Tilfeldig", "Strukturelle årsaker."),
                C("b", "Effekt skjer over år, mange faktorer påvirker, ikke direkte salg-link", "Riktig! Strukturell utfordring.", correct=True),
                C("c", "Bare for B2B", "Gjelder alle."),
                C("d", "Lovstridig", "Helt urelevant.")],
               "Coca-Cola kan ikke beregne nøyaktig ROI for julekampanjen. Men de vet at kjennskap holdes høyt — strategisk verdi.")]),
        ph("📈", "Hvorfor økonomisk forståelse er kritisk",
           "Marketing uten økonomi mister troverdighet.",
           "Uten økonomisk kontroll dør selv den beste markedsstrategi. Markedsføring som ikke kan begrunnes med tall mister først budsjett, så stemme i ledelsen, så plass. Marketing-direktører som mestrer økonomi blir promotert. De som ikke gjør det, blir værende i marketing.",
           [("TROVERDIGHET", "Tall snakker høyere enn ord i ledelsen."),
            ("KARRIERE", "Økonomi-mestring skiller marketing-direktører som blir CEO.")],
           "Hva er de viktigste tallene en marketing-leder bør forstå?",
           [ex("Konsekvens", "Hva skjer med marketing uten tall?",
               [C("a", "Ingenting", "Stort tap."),
                C("b", "Mister budsjett, stemme, og til slutt plass i ledelsen", "Riktig! Klassisk forløp.", correct=True),
                C("c", "Blir mer kreativ", "Ikke nødvendigvis."),
                C("d", "Tilfeldig", "Strukturelt."),],
               "I nedgangstider er marketing-budsjett ofte først ut. Tall-baserte argumenter beskytter."),
            ex("Karriere", "Hva skiller marketing-direktører som blir CEO?",
               [C("a", "Bare kreativitet", "For smalt."),
                C("b", "Økonomisk forståelse + strategi + folk-kompetanse", "Riktig! Multi-dimensjonal kompetanse.", correct=True),
                C("c", "Bare nettverk", "For smalt."),
                C("d", "Tilfeldig", "Strukturelt mønster."),],
               "Coca-Cola, P&G, Unilever — mange CEO-er kommer fra marketing. Felles: økonomisk mestring."),
            ex("Utvikling", "Hvordan utvikle økonomisk forståelse?",
               [C("a", "Bare kurs", "For smalt."),
                C("b", "Lær regnskap + jobb tett med CFO + les bedriftens regnskap", "Riktig! Praktisk + formell læring.", correct=True),
                C("c", "Bare lese bøker", "For passivt."),
                C("d", "Tilfeldig", "Strukturert."),],
               "Marketing-leder bør kunne lese resultatregnskap, balanse, kontantstrøm. Grunnleggende ferdighet.")]),
    ],
    ["Du forstår at marketing må snakke økonomi-språket for å vinne i ledelsen",
     "Du behersker bidragsmetoden vs selvkostmetoden — riktig metode per beslutning",
     "Du kan beregne dekningsbidrag, dekningsgrad og break-even",
     "Du kjenner forskjellen på resultatbudsjett, likviditetsbudsjett og investeringsbudsjett",
     "Du forstår NPV, payback og hvordan tidsverdien av penger styrer investeringsbeslutninger"])


g.write_modules([INTERNASJ, OKONOMI], "ML2-15 + ML2-16")
