#!/usr/bin/env python3
"""ML2-17 Markedsplanen — siste i Batch B."""
import importlib.util
from pathlib import Path
spec = importlib.util.spec_from_file_location("g", Path(__file__).parent / ".gen-shared.py")
g = importlib.util.module_from_spec(spec); spec.loader.exec_module(g)
C, ph, ex, M = g.C, g.ph, g.ex, g.M


PLAN = M("Markedsplanen", "ml2", "ML2-17", "Markedsplanen", "📋",
    "markedsplanen", "ml2",
    "Markedsplanen er det viktigste verktøyet for en markedsleder. Binder strategi til handling, gir alle samme retning, gjør markedsføring til forretningsdisiplin — ikke kreativ aktivitet alene.",
    "Bedrifter med dokumentert markedsplan har 30 % høyere måloppnåelse enn de uten. Plan tvinger frem disiplin og koordinering.",
    "En 1-side-plan som alle kan handle på er bedre enn 200 sider som ingen leser. Klarhet slår omfang.",
    [
        ph("📋", "Hva er en markedsplan?",
           "Styringsdokument for én periode.",
           "Markedsplanen samler analyse, mål og tiltak for én periode (typisk ett år). Brukt riktig: kompass og målbevis for hele organisasjonen. Brukt feil: et dokument i en skuff ingen leser. Forskjellen ligger i implementering.",
           [("STYRING", "Brukes som referanse gjennom året."),
            ("DOKUMENTERT", "Skriftlig plan beats muntlige avtaler.")],
           "Har bedriften du jobber for / kjenner en markedsplan? Brukes den faktisk?",
           [ex("Hva", "Hva er hovedhensikten?",
               [C("a", "Imponere ledelsen", "For overflatisk."),
                C("b", "Styringsdokument som samler analyse, mål og tiltak for én periode", "Riktig! Praktisk verktøy.", correct=True),
                C("c", "Erstatte regnskapet", "Helt feil."),
                C("d", "Bare reklame", "For smalt.")],
               "Markedsplanen er marketing-funksjonens 'forretningsplan' — strategisk dokument."),
            ex("Frekvens", "Hvor ofte lages en?",
               [C("a", "Aldri", "For lite."),
                C("b", "Årlig — med kvartalsvis review", "Riktig! Standard frekvens.", correct=True),
                C("c", "Daglig", "For ofte."),
                C("d", "Bare ved kriser", "For reaktivt.")],
               "Årlig hovedplan + månedlig oppfølging + kvartalsvis review = standard prosess."),
            ex("Verdi", "Hva gir en god plan?",
               [C("a", "Pynt", "Praktisk verdi."),
                C("b", "Felles retning + koordinering + målbar fremdrift + læring", "Riktig! Multi-dimensjonal verdi.", correct=True),
                C("c", "Bare for ledelsen", "For hele organisasjonen."),
                C("d", "Lovkrav", "Strategisk verktøy."),],
               "Bedrifter med plan har dokumentert bedre resultater enn de uten. Disiplin lønner seg.")]),
        ph("🔍", "Situasjonsanalyse (SWOT)",
           "Hvor er vi nå?",
           "Situasjonsanalyse: indre arbeidsbetingelser (styrker/svakheter) og ytre (muligheter/trusler). Grunnlaget for alle videre valg. Uten ærlig analyse blir resten skinnplanlegging. SWOT er klassikeren — TOWS-matrisen tar det videre ved å koble faktorene.",
           [("INDRE + YTRE", "S+W internt, O+T eksternt."),
            ("ÆRLIG", "Skinn-SWOT er verdiløs. Tør å se svakhetene.")],
           "Lag en quick SWOT for bedriften du kjenner. Hva er ærlig vurderingen?",
           [ex("Steg", "Hva er situasjonsanalysens rolle?",
               [C("a", "Pynt", "Strategisk grunnlag."),
                C("b", "Grunnlag for alle videre valg — uten analyse blir mål gjetning", "Riktig! Steg 0 i strategi.", correct=True),
                C("c", "Bare for konsulenter", "For ledelsen først."),
                C("d", "Lovkrav", "Strategisk valg.")],
               "Hopp over situasjonsanalysen, og du planlegger basert på ønsker, ikke realitet."),
            ex("SWOT", "Hva betyr SWOT?",
               [C("a", "Tilfeldig", "Strukturert akronym."),
                C("b", "Strengths, Weaknesses, Opportunities, Threats", "Riktig! Klassisk modell.", correct=True),
                C("c", "Salgs-, Vekst-, Optimerings-, Tekniske mål", "Helt feil."),
                C("d", "Strategi, Vekst, Optimal, Tjeneste", "Helt feil.")],
               "S+W = internt (du kontrollerer). O+T = eksternt (markedet kontrollerer)."),
            ex("Ærlighet", "Hva skiller god SWOT fra dårlig?",
               [C("a", "Lengde", "Ikke avgjørende."),
                C("b", "Ærlig vurdering — særlig av svakheter", "Riktig! Skinn-SWOT med bare positive ord er verdiløs.", correct=True),
                C("c", "Antall punkter", "Kvalitet > kvantitet."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Best praksis: la kritisk venn / konsulent gjøre SWOT. Egen blindsone gjør deg blind for svakhetene.")]),
        ph("🎯", "Målsetting (SMART)",
           "Hvor skal vi?",
           "Mål bør være SMART: Spesifikt, Målbart, Ambisiøst, Realistisk, Tidsbestemt. 'Øke markedsandelen i Trondheim fra 12 % til 18 % innen 31.12' er SMART. 'Vokse litt' er det ikke. Alle 5 kriterier må være oppfylt for at målet skal være styrbart.",
           [("ALLE 5 KRITERIER", "Mangler ett, taper målet styringsverdi."),
            ("KONKRET", "Konkrete tall slår vage formuleringer.")],
           "Skriv et SMART-mål for skoleåret. Hva er spesifikt, målbart, ambisiøst, realistisk, tidsbestemt?",
           [ex("Hva", "Hva betyr SMART?",
               [C("a", "Smarte ideer", "For overflatisk."),
                C("b", "Spesifikt, Målbart, Ambisiøst, Realistisk, Tidsbestemt", "Riktig! 5 kriterier alle må oppfylles.", correct=True),
                C("c", "Strategi, Marked, Aktivitet, Resultat, Tiltak", "Helt feil tolkning."),
                C("d", "Bare målbart", "Bredere.")],
               "SMART-konseptet er fra 1981. Fortsatt grunnleggende i målstyring."),
            ex("Eksempel", "Hvilket er SMART?",
               [C("a", "Vi skal vokse", "For vagt — målbart? Tidsbestemt?"),
                C("b", "Øke omsetning i Norge med 15 % innen 31.12 sammenlignet med fjoråret", "Riktig! Alle 5 kriterier oppfylt.", correct=True),
                C("c", "Selge mer", "For vagt."),
                C("d", "Få mest mulig kunder", "For vagt.")],
               "Test: kan to mennesker tolke målet på samme måte? Hvis nei, ikke spesifikt nok."),
            ex("Tid", "Hvorfor må mål være tidsbestemt?",
               [C("a", "Pynt", "Praktisk funksjon."),
                C("b", "Uten frist mister målet drivkraft og målbarhet — utsettes alltid", "Riktig! 'Innen' tvinger frem prioritering.", correct=True),
                C("c", "Lovkrav", "Helt urelevant."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Bruk konkrete datoer: '31.12.2025', ikke 'snart'. Da er det målbart.")]),
        ph("🎚️", "Strategivalg (STP)",
           "Hvem skal vi satse på?",
           "STP: Segmentering (dele markedet), Targeting/Målgruppevalg (velge segmenter), Posisjonering (skille seg ut). Strategien er broen mellom mål og tiltak. Klar STP gjør alle taktiske valg lettere — uklar STP gir hodepine i hver beslutning.",
           [("S → T → P", "Strukturert tre-stegs-prosess."),
            ("STRATEGISK BRO", "Mellom mål og taktikk.")],
           "Hvilke segmenter satser bedrifter du kjenner på? Hvordan posisjonerer de seg?",
           [ex("STP", "Hva er STP?",
               [C("a", "Tilfeldig", "Strukturert."),
                C("b", "Segmentering, Targeting, Posisjonering", "Riktig! Strategisk modell.", correct=True),
                C("c", "Salg, Tilbud, Pris", "Helt feil."),
                C("d", "Bare salg", "For smalt.")],
               "STP er kjernen i strategisk markedsføring. Uten STP er strategi gjetning."),
            ex("Posisjonering", "Hva er kjernen i posisjonering?",
               [C("a", "Bare pris", "For smalt."),
                C("b", "Eie ett ord i kundens bevissthet — Volvo = sikkerhet, Apple = innovasjon", "Riktig! Klassisk konsept.", correct=True),
                C("c", "Bare reklame", "For smalt."),
                C("d", "Tilfeldig", "Strategisk.")],
               "Test: hvilket ord forbinder kundene med ditt merke? Hvis du ikke vet, har du ikke posisjonert."),
            ex("Velge bort", "Hvorfor må STP velge bort?",
               [C("a", "Tilfeldig", "Strategisk."),
                C("b", "Du kan ikke vinne alle — fokus gir resultater", "Riktig! Velge bort = velge inn.", correct=True),
                C("c", "Lovkrav", "Helt urelevant."),
                C("d", "Bare for store", "Gjelder alle."),],
               "Stormberg valgte 'norske familier som vil ha rimelige turklær med god kvalitet'. Sa nei til luksus-segmentet.")]),
        ph("📦", "Handlingsplan (markedsmiksen)",
           "Hva skal vi gjøre konkret?",
           "Handlingsplanen detaljerer tiltak innen produkt, pris, plass, kommunikasjon (og folk i tjenestebedrifter). Hvert tiltak må knyttes til ansvarlig person og frist. Uten konkrete handlinger er strategi bare ord. Tabell-format med kolonner: tiltak, ansvarlig, frist, budsjett, mål.",
           [("KONKRET", "Hver handling med ansvarlig + frist + budsjett."),
            ("TABELL-FORMAT", "Strukturert oversikt slår tekst.")],
           "Lag en handlingsplan-tabell for et lite prosjekt: 5 tiltak, ansvar, frist, budsjett.",
           [ex("Hva", "Hva er handlingsplanens rolle?",
               [C("a", "Bare oversikt", "Konkret styring."),
                C("b", "Detaljerte tiltak med ansvar, frist, budsjett — bro fra strategi til handling", "Riktig! Operasjonalisering av strategi.", correct=True),
                C("c", "Pynt", "Praktisk verktøy."),
                C("d", "Lovkrav", "Helt urelevant."),],
               "Uten handlingsplan blir strategi bare slagord. Konkrete tiltak skaper resultater."),
            ex("Format", "Hva er beste format?",
               [C("a", "Lang tekst", "Vanskelig å bruke."),
                C("b", "Tabell med kolonner: tiltak, ansvarlig, frist, budsjett, KPI", "Riktig! Strukturert og handlingsrettet.", correct=True),
                C("c", "Bare punktliste", "Mangler struktur."),
                C("d", "Tilfeldig", "Strukturert."),],
               "Kanban-tavle eller Excel/Google Sheet er praktisk. Excel er overlegen for små bedrifter."),
            ex("Ansvar", "Hvorfor må hvert tiltak ha ansvarlig?",
               [C("a", "Tilfeldig", "Strukturelt."),
                C("b", "Felles ansvar = ingen ansvar — én person må eie hver oppgave", "Riktig! Klassisk RACI-prinsipp.", correct=True),
                C("c", "Lovkrav", "Helt urelevant."),
                C("d", "Bare for store", "Gjelder alle.")],
               "RACI-matrise: Responsible, Accountable, Consulted, Informed. Klargjør hvem som gjør hva.")]),
        ph("💰", "Budsjett",
           "Hva koster det og hva forventer vi å tjene?",
           "Budsjett: kostnader per tiltak, forventet inntekts-effekt, ROI-beregning. Ledelsen vil se tall — ikke bare ord. Uten budsjett kan ingen vurdere om planen er realistisk eller verdifull. Tre vanlige metoder: prosent av omsetning, konkurranse, mål-og-oppgave.",
           [("TALL > ORD", "Ledelsen krever budsjett, ikke beskrivelser."),
            ("MÅL-OG-OPPGAVE", "Beste metode — definer mål, beregn kostnad.")],
           "Hvordan ville du forsvart en kampanje på 500 000 kr internt?",
           [ex("Innhold", "Hva må budsjettet inneholde?",
               [C("a", "Bare kostnader", "For smalt."),
                C("b", "Kostnader per tiltak, forventet inntekt, ROI-beregning", "Riktig! Helhetlig økonomisk vurdering.", correct=True),
                C("c", "Bare omsetning", "For smalt."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Test: kan du svare 'hva koster det?' og 'hva får vi tilbake?' med tall? Hvis nei, ikke godt nok budsjett."),
            ex("Beste metode", "Hvilken budsjettmetode er mest strategisk?",
               [C("a", "Prosent av omsetning", "Enkelt, men reaktivt."),
                C("b", "Mål-og-oppgavemetoden — definer mål, beregn ressursbehov", "Riktig! Krever mer arbeid, men gir riktig allokering.", correct=True),
                C("c", "Følg konkurrentene", "Reaktivt."),
                C("d", "Bare gjenta i fjor", "Ingen strategi.")],
               "Mål-og-oppgave tvinger frem realisme — avslører ofte at mål er urealistiske med eksisterende budsjett."),
            ex("Underbudsjett", "Hva er klassisk feil?",
               [C("a", "For mye", "Sjelden."),
                C("b", "Underbudsjettere kommunikasjon ved lansering", "Riktig! Lansering uten kommunikasjons-budsjett dør.", correct=True),
                C("c", "Tilfeldig", "Strukturert problem."),
                C("d", "Lovstridig", "Helt urelevant.")],
               "Tommelfingerregel: lansering trenger 20-50 % av forventet første-års-omsetning i kommunikasjon.")]),
        ph("📊", "Oppfølging og kontroll",
           "Hvordan måle om vi lykkes?",
           "KPI-er definert per mål. Rapporteringsfrekvens (månedlig/kvartalsvis). Hvem rapporterer hva til hvem. Avviksanalyse: hvorfor ble det annerledes enn planlagt? Uten oppfølging blir planen et dokument i skuffen. Disiplinerte bedrifter har faste plan-møter månedlig.",
           [("KPI PER MÅL", "Hvert mål må kunne måles."),
            ("AVVIK = LÆRING", "Når ble det annerledes — hvorfor?")],
           "Hvilke KPI-er ville du brukt for å måle en kampanje?",
           [ex("Hva", "Hva er KPI?",
               [C("a", "Tilfeldig", "Strukturert mål."),
                C("b", "Key Performance Indicator — målbare suksess-indikatorer", "Riktig! Standard ledelsesterm.", correct=True),
                C("c", "Bare salg", "For smalt."),
                C("d", "Lovkrav", "Strategisk valg.")],
               "Hver mål må ha tilhørende KPI. 'Øke salg' er ikke nok — 'øke omsetning med 15 %' er KPI."),
            ex("Frekvens", "Hvor ofte rapportere?",
               [C("a", "Aldri", "For lite."),
                C("b", "Månedlig minimum, kvartalsvis review", "Riktig! Bygger disiplin uten å bli for tungt.", correct=True),
                C("c", "Daglig", "For ofte."),
                C("d", "Årlig", "For sjelden.")],
               "Månedlig review tvinger frem disiplin. Kvartalsvis tillater større justeringer."),
            ex("Avvik", "Hvorfor analysere avvik?",
               [C("a", "Tilfeldig", "Strukturelt."),
                C("b", "Læring — hvorfor ble det annerledes? Justering for fremtiden", "Riktig! Avvik = læringspoeng.", correct=True),
                C("c", "Lovkrav", "Helt urelevant."),
                C("d", "Bare for å straffe", "Helt feil tilnærming."),],
               "Beste praksis: 'no-blame'-kultur ved avviksanalyse. Fokus på læring, ikke skyld.")]),
        ph("🚀", "Implementering",
           "Få planen ut i livet.",
           "Implementering: hvordan engasjere organisasjonen? Internkommunikasjon, opplæring, ansvarsfordeling. Mange planer dør fordi de aldri kommer ut av møterommet og inn i hverdagen. Krever bevisst arbeid — strategi-planlegging er ofte 30 % av jobben, implementering er 70 %.",
           [("70 % JOBBEN", "Implementering er hovedjobben, ikke planlegging."),
            ("INTERN KOMM", "Folk må forstå og tro på planen.")],
           "Hva ville du gjort for å sikre at en plan faktisk gjennomføres?",
           [ex("Andel", "Hvor stor del av jobben er implementering?",
               [C("a", "10 %", "Underestimert."),
                C("b", "70 % — planlegging er bare 30 %", "Riktig! Klassisk regel.", correct=True),
                C("c", "Bare 1 %", "For lavt."),
                C("d", "Tilfeldig", "Strukturelt.")],
               "Mange bruker 80 % av tiden på planlegging og 20 % på implementering. Bør være motsatt."),
            ex("Hovedfeil", "Hva mislykkes oftest?",
               [C("a", "Selve planen", "Plan er typisk OK."),
                C("b", "Planen kommer aldri ut av møterommet og inn i hverdagen", "Riktig! Klassisk feil.", correct=True),
                C("c", "For mange møter", "Symptom."),
                C("d", "For dyrt", "Sjelden hovedårsak.")],
               "Test: spør tilfeldig ansatt om markedsplanen. Hvis hun ikke kjenner, har du implementeringsproblem."),
            ex("Tiltak", "Hvordan sikre implementering?",
               [C("a", "Bare god plan", "Plan uten utførelse er ingenting."),
                C("b", "Internkommunikasjon + opplæring + tydelig ansvar + månedlig oppfølging", "Riktig! Helhetlig systemarbeid.", correct=True),
                C("c", "Bare penger", "For smalt."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Implementering er disiplin. Følg opp månedlig, juster basert på data, kommuniser konstant.")]),
        ph("🔄", "Læringssløyfen",
           "Plan → utfør → mål → lær → ny plan.",
           "Markedsplanen er ikke et engangsdokument — den er del av en kontinuerlig læringssyklus. PDCA: Plan-Do-Check-Act. Hver runde gir innsikt for neste. Mange bedrifter glemmer dette og gjør samme feil år etter år. Disiplinert review er konkurransefortrinn.",
           [("PDCA", "Plan-Do-Check-Act — læringssyklus."),
            ("KUMULATIV", "Læring akkumuleres over år.")],
           "Hva har du lært av siste prosjekt? Hvordan brukes læringen videre?",
           [ex("PDCA", "Hva er PDCA?",
               [C("a", "Plan, Direkte, Cancel, Avslutt", "Helt feil."),
                C("b", "Plan-Do-Check-Act — kontinuerlig forbedringssyklus", "Riktig! Klassisk modell fra kvalitetsledelse.", correct=True),
                C("c", "Tilfeldig", "Strukturert."),
                C("d", "Bare for produksjon", "Brukes overalt.")],
               "PDCA er fra 1950-tallet, fortsatt relevant. Edwards Deming populariserte det i Japan."),
            ex("Hvorfor", "Hvorfor er læringssyklus viktig?",
               [C("a", "Tilfeldig", "Strukturelt."),
                C("b", "Akkumulert læring over år gir konkurransefortrinn", "Riktig! Bedrifter som lærer slår de som gjentar.", correct=True),
                C("c", "Lovkrav", "Helt urelevant."),
                C("d", "Bare for store", "Gjelder alle."),],
               "Bedrifter som dokumenterer læring konsistent har 3-5x bedre marketing-effekt over år."),
            ex("Vanlig feil", "Hva er klassisk feil?",
               [C("a", "For mye refleksjon", "Sjelden problem."),
                C("b", "Hopper rett til ny plan uten å lære av forrige", "Riktig! Mister verdifull innsikt.", correct=True),
                C("c", "For mye dokumentasjon", "Lite problem."),
                C("d", "Tilfeldig", "Strukturert problem.")],
               "Lag retrospektiv etter hver kampanje. Hva virket? Hva ikke? Hva gjør vi annerledes neste gang?")]),
        ph("📈", "Markedsplanen som styringsverktøy",
           "Det viktigste verktøyet for marketing-leder.",
           "Markedsplanen er det viktigste verktøyet for en markedsleder. Binder strategi til handling, gir alle samme retning, gjør markedsføring til forretningsdisiplin — ikke kreativ aktivitet. Ledere som mestrer planlegging vinner langsiktig. De som improviserer brenner seg ut.",
           [("DISIPLIN", "Plan tvinger frem strukturert tenkning."),
            ("KONKURRANSEFORTRINN", "Bedrifter med plan slår de uten.")],
           "Hva er den viktigste lærdommen om markedsplanlegging du tar med deg?",
           [ex("Verdi", "Hva er markedsplanens hovedverdi?",
               [C("a", "Pynt", "Praktisk verdi."),
                C("b", "Binder strategi til handling — gjør marketing til forretningsdisiplin", "Riktig! Strukturell verdi.", correct=True),
                C("c", "Bare for store", "Gjelder alle."),
                C("d", "Lovkrav", "Strategisk valg.")],
               "Tine sin årlige markedsplan inkluderer historisk analyse, mål, kampanjer, lanseringer, budsjett. Følges opp månedlig."),
            ex("Verdi", "Hva sa forskning om plan vs ikke plan?",
               [C("a", "Ingen forskjell", "Stor forskjell."),
                C("b", "30 % høyere måloppnåelse for bedrifter med dokumentert plan", "Riktig! Dokumentasjon tvinger frem disiplin.", correct=True),
                C("c", "Plan gir lavere resultater", "Helt feil."),
                C("d", "Tilfeldig", "Strukturelt mønster.")],
               "Strukturert planlegging gir konsekvent bedre resultater enn improvisasjon. Standard funn i forskning."),
            ex("Lærdom", "Hva er den viktigste lærdommen?",
               [C("a", "Plan er overflødig", "Tvert imot."),
                C("b", "Markedsføring uten plan er kreativ aktivitet — markedsføring med plan er forretning", "Riktig! Strukturell forskjell.", correct=True),
                C("c", "Bare for ledelsen", "For hele organisasjonen."),
                C("d", "Tilfeldig", "Strukturert."),],
               "Modne marketing-funksjoner har plan, KPI-er, månedlig review. Umodne er ad hoc og improviserer.")]),
    ],
    ["Du forstår at markedsplanen er styringsdokument som binder strategi til handling",
     "Du kan strukturere en plan: situasjonsanalyse → SMART-mål → STP → handlingsplan → budsjett → kontroll",
     "Du behersker SMART-mål-rammeverket og hvorfor alle 5 kriterier må oppfylles",
     "Du forstår at 70 % av jobben er implementering — ikke planlegging",
     "Du kjenner PDCA-syklusen og verdien av læring fra hver runde"])


g.write_modules([PLAN], "ML2-17 Markedsplanen")
