#!/usr/bin/env python3
"""ENT1 kap 1-3: Innovatøren, Kreativitet, Behov/marked/segmentering."""
import importlib.util
from pathlib import Path
spec = importlib.util.spec_from_file_location("g", Path(__file__).parent / ".gen-shared.py")
g = importlib.util.module_from_spec(spec); spec.loader.exec_module(g)
C, ph, ex, M = g.C, g.ph, g.ex, g.M


INNOV = M("InnovatorenOgEntreprenoren", "ent1", "ENT1-01", "Innovatøren og entreprenøren", "💡",
    "innovatoren-og-entreprenoren", "ent1",
    "Entreprenørskap er en arbeidsmåte og en holdning til problemløsning — ikke bare 'å starte bedrift'. Det handler om å identifisere muligheter og mobilisere ressurser for å skape verdi.",
    "Norske gründere som Else Marie Hagen (Kahoot), Brian Iversen (Vipps) og Yvon Chouinard-typer har bygget bedrifter verdt milliarder. Norske rammevilkår er gode — Innovasjon Norge støtter aktivt.",
    "Du kan være entreprenør i et stort selskap, en kommune eller en frivillig organisasjon. Det er holdningen som teller, ikke om du har bedrift på Brønnøysund.",
    [
        ph("💡", "Hva er entreprenørskap?",
           "Identifisere muligheter, mobilisere ressurser, skape verdi.",
           "Entreprenørskap er prosessen med å identifisere muligheter og mobilisere ressurser for å skape verdi — økonomisk, sosialt eller kulturelt. Det handler ikke bare om å starte bedrifter, men om en arbeidsmåte og holdning til problemløsning.",
           [("3 STEG", "Identifisere mulighet → mobilisere ressurser → skape verdi."),
            ("BREDT", "Inkluderer sosial og kulturell verdiskaping, ikke bare profitt.")],
           "Hvilket problem rundt deg har du tenkt 'noen burde løse det'? Det er entreprenør-tenkning.",
           [ex("Definisjon", "Hva er entreprenørskap?",
               [C("a", "Bare å starte bedrift", "For smalt."),
                C("b", "Identifisere muligheter og mobilisere ressurser for å skape verdi", "Riktig! Bredt og strategisk.", correct=True),
                C("c", "Bare økonomisk gevinst", "For smalt — også sosial og kulturell verdi."),
                C("d", "Tilfeldig", "Strukturert prosess.")],
               "Schumpeter introduserte begrepet i moderne form. 'Skapende ødeleggelse' er hans bidrag."),
            ex("Bredt", "Inkluderer entreprenørskap kun bedrifter?",
               [C("a", "Ja, bare bedrifter", "For smalt."),
                C("b", "Nei — også sosial, kulturell, organisatorisk verdiskaping", "Riktig! Bredt definert.", correct=True),
                C("c", "Bare i offentlig sektor", "Helt feil."),
                C("d", "Tilfeldig", "Strukturert."),],
               "Sosialt entreprenørskap er voksende felt. Patagonia, Tomra, Warm Up er eksempler."),
            ex("Holdning", "Hva er entreprenør-holdning?",
               [C("a", "Bare å være sjef", "For smalt."),
                C("b", "Se muligheter, ta initiativ, tåle usikkerhet, lære av feil", "Riktig! Holdning som kan trenes.", correct=True),
                C("c", "Tilfeldig", "Strukturert."),
                C("d", "Bare for unge", "Aldersnøytralt.")],
               "Du kan være entreprenør i en stor bedrift også — det kalles intraprenørskap.")]),
        ph("🎨", "Innovasjonstyper",
           "Schumpeter: 4 typer.",
           "Joseph Schumpeter identifiserte 4 innovasjonstyper: produktinnovasjon (ny vare), prosessinnovasjon (ny måte å lage på), markedsinnovasjon (ny måte å selge på) og organisasjonsinnovasjon (ny struktur). Apple kombinerer ofte alle fire — iPhone var produkt + marked + organisasjon.",
           [("4 TYPER", "Produkt, prosess, marked, organisasjon."),
            ("KOMBINASJONER", "Sterke innovasjoner kombinerer flere typer.")],
           "Hvilken innovasjon de siste årene synes du har vært mest revolusjonerende?",
           [ex("Antall", "Hvor mange innovasjonstyper?",
               [C("a", "2", "For få."),
                C("b", "4 — produkt, prosess, marked, organisasjon", "Riktig! Schumpeters klassifisering.", correct=True),
                C("c", "10", "For mange."),
                C("d", "Bare 1", "For lite.")],
               "Schumpeter publiserte i 1934. Fortsatt grunnleggende rammeverk for innovasjon-typer."),
            ex("Apple", "Hvilke innovasjonstyper kombinerte iPhone?",
               [C("a", "Bare produkt", "Mer enn det."),
                C("b", "Produkt + marked (App Store) + organisasjon (vertical integration)", "Riktig! Multipel innovasjon.", correct=True),
                C("c", "Bare prosess", "For smalt."),
                C("d", "Tilfeldig", "Strukturert."),],
               "Sterke innovasjoner kombinerer typer. Det gjør dem vanskeligere å kopiere."),
            ex("Markedsinnovasjon", "Hva er markedsinnovasjon?",
               [C("a", "Bare reklame", "For smalt."),
                C("b", "Ny måte å selge / nå kunder på — Amazon, Spotify, Tesla direkte salg", "Riktig! Distribusjons- og forretningsmodell-innovasjon.", correct=True),
                C("c", "Bare ny pris", "For smalt."),
                C("d", "Tilfeldig", "Strukturert."),],
               "Tesla direktedistribusjon (uten forhandlere) er klassisk markedsinnovasjon.")]),
        ph("👤", "Egenskaper hos en gründer",
           "4 kjerneegenskaper.",
           "Forskning peker på 4 kjerneegenskaper: utholdenhet (slå seg gjennom motgang), risikovilje (tåle usikkerhet), kreativitet (se nye løsninger), sosiale ferdigheter (selge ideen til andre). Ingen er født med alt — det meste kan trenes. Men noen folk har bedre utgangspunkt.",
           [("4 EGENSKAPER", "Utholdenhet, risikovilje, kreativitet, sosiale ferdigheter."),
            ("KAN TRENES", "Egenskaper er dynamiske, ikke statiske.")],
           "Hvilke av de 4 egenskapene har du? Hvilke kan du jobbe med?",
           [ex("Hvilke 4", "Hva er kjerneegenskapene?",
               [C("a", "Bare penger", "For smalt."),
                C("b", "Utholdenhet, risikovilje, kreativitet, sosiale ferdigheter", "Riktig! Forskningsbasert.", correct=True),
                C("c", "Bare høy IQ", "Ikke nok alene."),
                C("d", "Tilfeldig", "Strukturert."),],
               "Forskning viser at IQ alene ikke predikerer entreprenør-suksess. Disse 4 egenskapene gjør det."),
            ex("Trening", "Kan egenskapene trenes?",
               [C("a", "Nei", "Tvert imot."),
                C("b", "Ja — alle 4 kan utvikles bevisst over tid", "Riktig! Vekst-tankegang.", correct=True),
                C("c", "Bare i ungdom", "Hele livet."),
                C("d", "Bare for menn", "Helt urelevant og feil."),],
               "Carol Dweck: 'growth mindset' vs 'fixed mindset'. Tro på egen utvikling er selv en forutsetning for utvikling."),
            ex("Viktigst", "Hvilken er ofte viktigst?",
               [C("a", "IQ", "Ikke kjerneegenskap."),
                C("b", "Utholdenhet — kan bære deg gjennom de tøffe periodene", "Riktig! Mange bedrifter dør i 'valley of death' — første 2-3 år.", correct=True),
                C("c", "Bare risikovilje", "For smalt."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Angela Duckworth: 'Grit' (utholdenhet) er sterkeste prediksjon på langtidssuksess.")]),
        ph("🏢", "Intraprenørskap",
           "Innovasjon innad i bedrifter.",
           "Intraprenørskap = innovasjon innad i eksisterende bedrifter. Ansatte som tenker som gründere, men har ressursene og sikkerheten i en stor organisasjon. 3M sin Post-it kom fra et intraprenørskapsprosjekt — ansatte fikk 15 % av tiden til egne prosjekter.",
           [("INNAD I BEDRIFT", "Entreprenør-tenkning uten å starte selv."),
            ("RESSURSFORDEL", "Eksisterende infrastruktur, kunder, kapital.")],
           "Kjenner du noen som er 'intraprenør' i jobben sin? Hva gjør dem annerledes?",
           [ex("Definisjon", "Hva er intraprenørskap?",
               [C("a", "Internasjonal entreprenør", "Helt feil."),
                C("b", "Innovasjon innad i eksisterende bedrifter", "Riktig! Intern entreprenørskap.", correct=True),
                C("c", "Internett-bedrifter", "Helt feil."),
                C("d", "Investering", "Helt feil.")],
               "Begrepet ble populært på 1980-tallet. Kombinasjon av 'internal' og 'entrepreneur'."),
            ex("Eksempel", "Hva er klassisk intraprenørskap-eksempel?",
               [C("a", "Tilfeldig", "Strukturert."),
                C("b", "3M Post-it — kom fra ansatt med 15 % free time", "Riktig! Klassisk eksempel på vellykket intraprenørskap.", correct=True),
                C("c", "Apple iPhone", "Toppledelse-drevet."),
                C("d", "Tesla", "Gründer-startup.")],
               "Google har 20 % free time som har gitt Gmail, Google News, AdSense. Strukturelt insentiv."),
            ex("Fordel", "Hva er fordelen?",
               [C("a", "Bare lønn", "For smalt."),
                C("b", "Eksisterende ressurser + sikkerhet — kan ta større risiko", "Riktig! Beste av begge verdener.", correct=True),
                C("c", "Tilfeldig", "Strukturelt."),
                C("d", "Bare pensjon", "For smalt.")],
               "Intraprenører kan eksperimentere med store ideer uten å risikere personlig økonomi.")]),
        ph("💎", "Verdiskaping",
           "3 former: økonomisk, sosial, kulturell.",
           "Verdiskaping kan ta tre former: økonomisk verdi (overskudd, lønninger, skatt), sosial verdi (samfunnsnytte, jobber, folkehelse), kulturell verdi (opplevelser, mangfold, identitet). Bedrifter skaper alle tre — ofte samtidig. Stormberg er eksempel på alle tre.",
           [("3 DIMENSJONER", "Økonomisk + sosial + kulturell verdi."),
            ("OFTE SAMTIDIG", "God bedrift skaper i alle dimensjoner.")],
           "Hvilken bedrift du kjenner skaper sterk sosial verdi? Eller kulturell?",
           [ex("3 typer", "Hva er de 3 verdiformene?",
               [C("a", "Bare økonomisk", "For smalt."),
                C("b", "Økonomisk, sosial, kulturell", "Riktig! Bredt verdibegrep.", correct=True),
                C("c", "Bare sosial", "For smalt."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Triple Bottom Line er beslektet — Profit, People, Planet. Bredere verdiramme."),
            ex("Stormberg", "Hvilken verdi skaper Stormberg?",
               [C("a", "Bare økonomisk", "Mer enn det."),
                C("b", "Økonomisk (overskudd) + sosial (ansetter folk med hull i CV) + miljømessig", "Riktig! Multi-dimensjonal verdi.", correct=True),
                C("c", "Bare miljø", "Bredere."),
                C("d", "Tilfeldig", "Strukturert."),],
               "Stormberg-modellen er studie-objekt internasjonalt. Sosialt entreprenørskap som kommersiell strategi."),
            ex("Sosialt entreprenørskap", "Hva er det?",
               [C("a", "Bare donasjoner", "For smalt."),
                C("b", "Bedrifter der samfunnsmål er viktigere enn økonomisk profitt", "Riktig! Voksende kategori.", correct=True),
                C("c", "Tilfeldig", "Strukturert kategori."),
                C("d", "Lovkrav", "Frivillig kategori."),],
               "Allmenn Praksis (lavterskel helse), Skobi (jobbskaping for utsatte unge) er norske eksempler.")]),
        ph("🇳🇴", "Entreprenørskap i Norge",
           "Gode rammevilkår, lavere takt.",
           "Norge har gode rammevilkår: stabilt politisk system, godt utdannet befolkning, sterke støtteordninger via Innovasjon Norge. Likevel er småbedrifters andel av sysselsettingen lavere enn i USA og Sverige. Norsk velferdsstat reduserer 'pull-faktor' for entreprenørskap.",
           [("GODE RAMMER", "Stabilitet, utdanning, støtteordninger."),
            ("LAVERE TAKT", "Tryggere ansettelse reduserer 'push' til selvstendighet.")],
           "Hvorfor tror du det er færre norske gründere enn amerikanske?",
           [ex("Rammevilkår", "Hvordan er norske rammevilkår?",
               [C("a", "Verste i Europa", "Helt feil."),
                C("b", "Gode — stabilitet, utdanning, støtteordninger via Innovasjon Norge", "Riktig! Internasjonalt rangert høyt.", correct=True),
                C("c", "Tilfeldig", "Strukturert.")],
               "World Bank Doing Business-rangering plasserer Norge konsistent høyt for å starte bedrift."),
            ex("Innovasjon Norge", "Hva gjør de?",
               [C("a", "Bare reklame", "For smalt."),
                C("b", "Tilskudd, lån, mentor, internasjonalisering — støtteordninger for gründere", "Riktig! Statlig hjelpe-organisasjon.", correct=True),
                C("c", "Bare for store", "Spesifikt for små og oppstart."),
                C("d", "Tilfeldig", "Strukturert."),],
               "Innovasjon Norge er et av Norges beste 'eksport-produkter' — modell mange land har kopiert."),
            ex("Hvorfor lavere", "Hvorfor færre gründere enn USA?",
               [C("a", "Vi er dummere", "Helt feil."),
                C("b", "Velferdsstaten reduserer 'push' — sikker jobb er attraktiv", "Riktig! Strukturell forklaring.", correct=True),
                C("c", "Bare flaks", "Strukturelle årsaker."),
                C("d", "Tilfeldig", "Strukturelt mønster.")],
               "USA: starter du ikke bedrift, har du sjelden sikkerhetsnett. Norge: trygdesystemet er en 'safety net' som reduserer push-faktor.")]),
        ph("🌱", "Bærekraftig entreprenørskap",
           "Løse sosiale eller miljømessige utfordringer.",
           "Bærekraftig entreprenørskap: bedrifter som løser sosiale eller miljømessige utfordringer gjennom forretningsmodellen. Ikke 'CSR på siden', men kjernevirksomheten. Tomra (resirkulering), Allmenn Praksis (tilgjengelig helse), Kahoot (digital læring). Bærekraft som forretningsmodell, ikke vedlegg.",
           [("KJERNE", "Bærekraft i forretningsmodellen, ikke som vedlegg."),
            ("VEKSTOMRÅDE", "Yngre forbrukere prioriterer dette segmentet.")],
           "Hvilken bærekraftig forretningsmodell synes du er smartest?",
           [ex("Definisjon", "Hva er bærekraftig entreprenørskap?",
               [C("a", "Bare donasjoner", "For smalt."),
                C("b", "Løse sosiale/miljømessige utfordringer gjennom forretningsmodellen", "Riktig! Strukturell tilnærming.", correct=True),
                C("c", "Bare reklame", "For smalt."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Forskjell fra CSR: bærekraft er kjernevirksomheten, ikke noe som gjøres på siden."),
            ex("Eksempel", "Hvilken bedrift er klassisk eksempel?",
               [C("a", "Tradisjonell oljebedrift", "Helt feil."),
                C("b", "Tomra — pant og sortering = sirkulær økonomi som forretning", "Riktig! Bærekraft = inntekt.", correct=True),
                C("c", "Tilfeldig", "Strukturert."),
                C("d", "Bare amerikanske", "Norske gjør det også.")],
               "Tomra ble verdsatt over 30 mrd NOK på Oslo Børs. Bærekraft-fokus er strategisk fortrinn."),
            ex("Vekst", "Hvorfor er dette voksende?",
               [C("a", "Tilfeldig", "Strukturelle drivere."),
                C("b", "Yngre forbrukere prioriterer det + lovverk + investorer (ESG)", "Riktig! Multi-faktor vekst.", correct=True),
                C("c", "Lovkrav", "En av flere drivere."),
                C("d", "Mode", "Strukturell endring.")],
               "ESG-fond har vokst over 30 trillion USD globalt. Penger flyter mot bærekraft.")]),
        ph("📉", "Feiling som læring",
           "Fail fast, learn faster.",
           "Silicon Valley feirer feilsuksess. De fleste vellykkede gründere har minst én konkurs i bagasjen. Hver feil gir dyrebar læring som neste forsøk drar nytte av. Feile er ikke å mislykkes — det er å lære. Norge har historisk vært strengere på 'feiling' enn USA. Endrer seg.",
           [("FAIL FAST", "Test raskt, lær raskt, juster raskt."),
            ("KULTUR", "USA = feile er læring. Tradisjonelt Norge = stigma.")],
           "Har du selv feilet med noe? Hva lærte du? Brukes læringen videre?",
           [ex("Filosofi", "Hva er 'fail fast, learn faster'?",
               [C("a", "Mislykkes raskt", "For overflatisk."),
                C("b", "Test ideer raskt, lær fra feil, juster og prøv igjen", "Riktig! Iterativ tilnærming.", correct=True),
                C("c", "Aldri prøve", "Helt feil."),
                C("d", "Bare prøve én gang", "Tvert imot.")],
               "Lean Startup-metoden er bygget rundt dette prinsippet. Eric Ries populariserte det."),
            ex("Suksess", "Har vellykkede gründere feilet?",
               [C("a", "Aldri", "Tvert imot."),
                C("b", "De fleste har minst én konkurs eller stor feil bak seg", "Riktig! Feiling er normal del av reisen.", correct=True),
                C("c", "Bare i USA", "Globalt."),
                C("d", "Tilfeldig", "Strukturelt mønster.")],
               "Steve Jobs ble sparket fra Apple, Walt Disney sa opp fra første jobb. Feil og suksess er ofte koblet."),
            ex("Norsk kultur", "Hvordan er norsk kultur til feiling?",
               [C("a", "Helt akseptert", "Tradisjonelt mer stigma."),
                C("b", "Tradisjonelt strengere enn USA, men endrer seg", "Riktig! Strukturell endring i kultur.", correct=True),
                C("c", "Verre enn andre", "I bevegelse."),
                C("d", "Tilfeldig", "Strukturelt mønster.")],
               "Yngre generasjoner er mer åpne om feil. Janteloven utfordres av startup-kultur.")]),
        ph("🎯", "Erna Solberg som intraprenør",
           "Endring innenfra.",
           "Da Erna Solberg ble Høyre-leder, drev hun en form for intraprenørskap: hentet nye velgergrupper, modernisert kommunikasjon, fornyet politikken. Hun var ikke gründer i tradisjonell forstand, men endret partiet innenfra. Det er essensen i intraprenørskap — endring fra eksisterende posisjon.",
           [("ENDRING INNENFRA", "Intraprenørskap er ikke bare i bedrifter."),
            ("BREDT FENOMEN", "Politikk, frivillig sektor, offentlig sektor — alle har intraprenører.")],
           "Hvem andre har du sett endre en organisasjon innenfra?",
           [ex("Bredt", "Inkluderer intraprenørskap politikk?",
               [C("a", "Bare bedrifter", "For smalt."),
                C("b", "Ja — endring innenfra i alle organisasjoner", "Riktig! Bredt fenomen.", correct=True),
                C("c", "Bare offentlig", "For smalt."),
                C("d", "Tilfeldig", "Strukturert."),],
               "Politiske ledere som endrer parti innenfra er klassiske intraprenører. Erna i Høyre, Jonas Gahr Støre i AP."),
            ex("Hva kreves", "Hva kreves for å endre innenfra?",
               [C("a", "Bare formell makt", "For smalt."),
                C("b", "Visjon + tålmodighet + nettverk + utholdenhet", "Riktig! Multi-dimensjonal.", correct=True),
                C("c", "Bare flaks", "Strukturerte ferdigheter."),
                C("d", "Tilfeldig", "Strukturert."),],
               "Endring innenfra er ofte vanskeligere enn å starte fra null. Krever andre ferdigheter."),
            ex("Lærdom", "Hva er lærdommen?",
               [C("a", "Bare gründere skaper endring", "For smalt."),
                C("b", "Du kan være entreprenør i jobben din — uten å starte selv", "Riktig! Demokratiserer entreprenørskap.", correct=True),
                C("c", "Bare ledere kan endre", "For smalt."),
                C("d", "Tilfeldig", "Strukturert."),],
               "Du trenger ikke organisasjonsnummer for å være entreprenør. Tenkemåten kan brukes overalt.")]),
        ph("🚀", "Entreprenørskap som arbeidsmåte",
           "Holdning, ikke bare bedrift.",
           "Entreprenørskap er en arbeidsmåte og en holdning til problemløsning. Det handler mer om å se muligheter og handle enn om å starte bedrift. Du kan være entreprenør i et stort selskap, en kommune eller en frivillig organisasjon. Holdningen kan trenes opp gjennom bevisst praksis.",
           [("HOLDNING", "Mer enn organisasjonsform — det er en måte å tenke."),
            ("OVERFØRBAR", "Brukes overalt: jobb, frivillig, samfunn.")],
           "Hva er den viktigste lærdommen om entreprenørskap du tar med deg?",
           [ex("Kjerne", "Hva er kjernen i entreprenørskap?",
               [C("a", "Bare bedrift", "For smalt."),
                C("b", "Holdning og arbeidsmåte — se muligheter, handle, lære", "Riktig! Bredt og praktisk.", correct=True),
                C("c", "Bare risikoinvest", "For smalt."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Entreprenørskap som fag har utvidet seg fra 'starte bedrift' til 'måte å tenke på'. Skifte i siste 20 år."),
            ex("Hvor", "Hvor kan entreprenør-tenkning brukes?",
               [C("a", "Bare i bedrifter", "For smalt."),
                C("b", "Overalt — jobb, frivillig, kommune, skole, hjem", "Riktig! Bredt anvendelig.", correct=True),
                C("c", "Bare i tek", "For smalt."),
                C("d", "Bare i USA", "Globalt.")],
               "Skoler underviser nå entreprenørskap som ferdighet. UE (Ungt Entreprenørskap) i Norge."),
            ex("Trening", "Kan holdningen trenes?",
               [C("a", "Nei", "Tvert imot."),
                C("b", "Ja — gjennom bevisst praksis: ta initiativ, prøve, reflektere", "Riktig! Vekst-tankegang.", correct=True),
                C("c", "Bare for unge", "Hele livet."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Entreprenørskap kan læres som hvilket som helst fag. Krever bevisst innsats over tid.")]),
    ],
    ["Du forstår entreprenørskap som arbeidsmåte og holdning — ikke bare 'starte bedrift'",
     "Du kjenner Schumpeters 4 innovasjonstyper og hvordan de kombineres",
     "Du kan vurdere de 4 kjerneegenskapene hos en gründer og hvordan de kan trenes",
     "Du forstår intraprenørskap som innovasjon innad i eksisterende organisasjoner",
     "Du ser bærekraftig entreprenørskap som voksende strategisk område"])


KREATIVITET = M("KreativitetIdeutvikling", "ent1", "ENT1-02", "Kreativitet og idéutvikling", "🎨",
    "kreativitet-ideutvikling", "ent1",
    "Kunsten å tenke nytt — teknikker som hjelper deg fra hvit ark til konkret forretningsidé. Kreativitet kan trenes gjennom riktig metode og miljø.",
    "Forskning viser at kreativitet ikke er en medfødt gave — det er en ferdighet som kan trenes. Strukturerte teknikker som SCAMPER og Design Thinking dobler ide-volum og kvalitet.",
    "Kreativitet uten metode er bare flaks. Med metode blir det forutsigbar produktiv prosess.",
    [
        ph("🎨", "Hva er kreativitet?",
           "Skape noe nytt og nyttig.",
           "Kreativitet er evnen til å skape noe som er både nytt og nyttig i en gitt kontekst. Bare nytt = ubrukelig kunst. Bare nyttig = standardvare. Kreativitet er kombinasjonen — og den kan trenes opp gjennom teknikker og riktig miljø.",
           [("NYTT + NYTTIG", "Begge kreves — bare ett er ikke nok."),
            ("KAN TRENES", "Ferdighet, ikke medfødt evne.")],
           "Hva er det mest kreative du har laget? Hva gjorde det kreativt — nytt? Nyttig? Begge?",
           [ex("Definisjon", "Hva er kreativitet?",
               [C("a", "Bare kunst", "For smalt."),
                C("b", "Skape noe som er både nytt og nyttig i kontekst", "Riktig! Praktisk definisjon.", correct=True),
                C("c", "Bare for kunstnere", "Bredt fenomen."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Definisjonen er fra forskning. 'Nyttig' tilfører praktisk verdi."),
            ex("Trening", "Kan kreativitet trenes?",
               [C("a", "Nei", "Tvert imot."),
                C("b", "Ja — gjennom teknikker, eksponering for ideer, riktig miljø", "Riktig! Forskningsbasert.", correct=True),
                C("c", "Bare for unge", "Hele livet."),
                C("d", "Bare for kunstnere", "Alle kan."),],
               "Mange tror kreativitet er medfødt. Forskningen viser tydelig at det kan utvikles."),
            ex("Bare nytt", "Hva er bare 'nytt' uten 'nyttig'?",
               [C("a", "Genialt", "For optimistisk."),
                C("b", "Ofte ubrukelig — kunst som ingen vil ha eller forstå", "Riktig! Praktisk verdi mangler.", correct=True),
                C("c", "Alltid bra", "Ikke nødvendigvis."),
                C("d", "Tilfeldig", "Strukturert."),],
               "Test: hvem har nytte av ideen din? Hvis ingen — er det kanskje kunst, ikke entreprenørskap.")]),
        ph("🔄", "Kreative prosesser",
           "4 faser: forberedelse → inkubasjon → illuminasjon → verifikasjon.",
           "Kreative prosesser har 4 faser: 1) Forberedelse (samle materiale), 2) Inkubasjon (la underbevisstheten jobbe), 3) Illuminasjon (aha-opplevelsen), 4) Verifikasjon (test og videreutvikle). Mange tror kreativitet bare er punkt 3 — men de andre er like viktige.",
           [("4 FASER", "Bevisst struktur, ikke bare 'aha-øyeblikk'."),
            ("INKUBASJON", "La underbevisstheten jobbe — ofte undervurdert.")],
           "Har du opplevd 'aha-opplevelser'? Hva gjorde du før de kom?",
           [ex("Faser", "Hva er de 4 fasene?",
               [C("a", "Tilfeldig", "Strukturert."),
                C("b", "Forberedelse, inkubasjon, illuminasjon, verifikasjon", "Riktig! Klassisk kreativ prosess.", correct=True),
                C("c", "Plan, gjennomføring, evaluering", "For generell."),
                C("d", "Bare aha-øyeblikket", "For smalt.")],
               "Wallas modell fra 1926. Fortsatt aktuell beskrivelse av kreative prosesser."),
            ex("Inkubasjon", "Hva er inkubasjon?",
               [C("a", "Bare hvile", "Mer enn det."),
                C("b", "La underbevisstheten jobbe med problemet — gå tur, dusj, sove", "Riktig! Hjernen jobber selv om bevisstheten er andre steder.", correct=True),
                C("c", "Bare lese", "For smalt."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Mange aha-øyeblikk kommer i dusjen, på tur, eller om natten. Hjernen kobler ideer i hvile."),
            ex("Verifikasjon", "Hvorfor er verifikasjon viktig?",
               [C("a", "Pynt", "Praktisk steg."),
                C("b", "Test om idéen faktisk fungerer — mange aha-ideer er flopp i praksis", "Riktig! Praktisk validering.", correct=True),
                C("c", "Tilfeldig", "Strukturert."),
                C("d", "Lovkrav", "Helt urelevant."),],
               "Mange 'genialitet' viser seg å være urealistisk når man tester. Verifikasjon sparer ressurser.")]),
        ph("⚡", "Brainstorming",
           "Idémyldring — regler er viktige.",
           "Klassisk idémyldring (brainstorming) har tre regler: 1) Ingen kritikk under ide-fasen, 2) Kvantitet foran kvalitet, 3) Bygg videre på andres ideer. Klassisk i grupper, men også effektiv individuelt — sett en timer på 15 minutter og skriv ned alt.",
           [("3 REGLER", "Ingen kritikk, kvantitet, bygge videre."),
            ("FORSKJELL", "Brainstorm + senere kritisk vurdering — ikke samtidig.")],
           "Test brainstorming på en utfordring du har. 15 min, ingen kritikk, kvantitet.",
           [ex("Regler", "Hva er klassiske brainstorm-regler?",
               [C("a", "Bare evaluer", "Tvert imot."),
                C("b", "Ingen kritikk, kvantitet > kvalitet, bygg videre", "Riktig! Tre kjerneregler.", correct=True),
                C("c", "Bare individuelt", "Begge fungerer."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Reglene utviklet av Alex Osborn på 1950-tallet. Fortsatt grunnleggende."),
            ex("Kritikk", "Hvorfor ingen kritikk?",
               [C("a", "For å være snill", "Strategisk grunn."),
                C("b", "Kritikk dreper kreativitet — folk slutter å foreslå", "Riktig! Trygghet er forutsetning for kreativitet.", correct=True),
                C("c", "Lovkrav", "Helt urelevant."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Senere kommer kritisk fase — der vurderes ideene. Men ikke under generering."),
            ex("Kvantitet", "Hvorfor kvantitet > kvalitet?",
               [C("a", "Tilfeldig", "Strukturelt."),
                C("b", "De fleste 'gode ideer' kommer etter de 50 første dårlige", "Riktig! Volum er forutsetning for kvalitet.", correct=True),
                C("c", "Pynt", "Praktisk regel."),
                C("d", "Lovkrav", "Helt urelevant."),],
               "Mål: 100+ ideer på 30 min. Kvalitet kommer naturlig av kvantitet.")]),
        ph("🎯", "SCAMPER-metoden",
           "Strukturert kreativitet.",
           "SCAMPER er sjekkliste for å transformere eksisterende ideer: Substitute (bytte ut), Combine (kombinere), Adapt (tilpasse), Modify (modifisere), Put to another use (annet bruk), Eliminate (fjerne), Reverse (snu). En time med SCAMPER gir ofte 50+ varianter.",
           [("SJEKKLISTE", "7 transformasjoner av eksisterende ide."),
            ("STRUKTURERT", "Tvinger frem ulike perspektiver.")],
           "Velg et hverdags-produkt. Bruk SCAMPER på det — hva kan endres?",
           [ex("Hva", "Hva betyr SCAMPER?",
               [C("a", "Tilfeldig", "Akronym."),
                C("b", "Substitute, Combine, Adapt, Modify, Put to another use, Eliminate, Reverse", "Riktig! 7 transformasjons-typer.", correct=True),
                C("c", "Bare 3 typer", "For få."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Bob Eberle utviklet SCAMPER på 1970-tallet. Fortsatt mye brukt."),
            ex("Bruk", "Hvordan brukes SCAMPER?",
               [C("a", "Tilfeldig", "Strukturert."),
                C("b", "Som sjekkliste — gå gjennom hver bokstav for ditt produkt/tjeneste", "Riktig! Tvinger frem nye perspektiver.", correct=True),
                C("c", "Bare i tek", "Brukes overalt."),
                C("d", "Bare for kunst", "Praktisk verktøy.")],
               "Eksempel for kafé: S-bytte ut bønner med te-blader? C-kombinere kafé med bokhandel? E-fjerne sukker?"),
            ex("Verdi", "Hva gir SCAMPER?",
               [C("a", "Tilfeldig", "Strukturert."),
                C("b", "Tvinger frem 50+ ide-varianter på en time", "Riktig! Volum-effekt.", correct=True),
                C("c", "Bare 1 idé", "For lite."),
                C("d", "Lovkrav", "Helt urelevant.")],
               "Strukturerte teknikker dobler ide-volum vs ustrukturert brainstorming. Forskningsstøttet.")]),
        ph("👥", "Design Thinking",
           "Brukersentrert metode.",
           "Design Thinking er brukersentrert metode i 5 faser: empati (forstå brukeren), definere (klart problem), idéutvikling, prototype, testing. Brukt av Apple, IDEO og Stanford d.school. Tester alltid med ekte brukere før investering. Iterativ — gå gjennom syklusen flere ganger.",
           [("BRUKERSENTRERT", "Empati for brukeren er steg 1."),
            ("ITERATIV", "Test, lær, forbedre — gjenta.")],
           "Hvilke produkter har du sett som tydelig er designet 'for brukeren' vs 'for ingeniøren'?",
           [ex("5 faser", "Hva er fasene i Design Thinking?",
               [C("a", "Tilfeldig", "Strukturert."),
                C("b", "Empati, definere, idéutvikling, prototype, testing", "Riktig! 5 iterative steg.", correct=True),
                C("c", "Bare 2 steg", "For få."),
                C("d", "Plan, gjennomføring, evaluering", "For generell.")],
               "Stanford d.school har popularisert metoden. Brukt globalt nå."),
            ex("Empati", "Hvorfor empati som steg 1?",
               [C("a", "Pynt", "Strategisk."),
                C("b", "Forstå brukerens reelle behov før du prøver å løse — ofte feil problem ellers", "Riktig! Klassisk feil: løse feil problem.", correct=True),
                C("c", "Tilfeldig", "Strukturert."),
                C("d", "Lovkrav", "Helt urelevant.")],
               "IDEO bruker observasjon i brukerens hverdag — ikke bare intervjuer. Skjuler ofte virkelige behov."),
            ex("Iterativ", "Hva betyr iterativ?",
               [C("a", "Bare en gang", "Tvert imot."),
                C("b", "Gå gjennom syklusen flere ganger — lære og forbedre", "Riktig! Prosess, ikke event.", correct=True),
                C("c", "Tilfeldig", "Strukturert."),
                C("d", "Lovkrav", "Helt urelevant.")],
               "Første prototype er sjelden riktig. Iterasjoner forbedrer dramatisk over tid.")]),
        ph("🔬", "Fra idé til mulighet",
           "Vurdere realisme.",
           "Vurder om ideen løser et faktisk problem for en betalingsvillig målgruppe. Tre spørsmål: 1) Er problemet reelt? 2) Er målgruppen stor nok? 3) Er de villige til å betale? Hvis ett svar er nei, går du tilbake til tegnebrettet. Mange ideer dør på 'betalingsvilje'-spørsmålet.",
           [("3 SPØRSMÅL", "Reelt problem? Stor målgruppe? Betalingsvilje?"),
            ("BETALINGSVILJE", "Ofte vanskeligst å validere.")],
           "Test en ide du har: er problemet reelt? Stort nok marked? Vil folk betale?",
           [ex("3 spørsmål", "Hva må valideres?",
               [C("a", "Bare ide", "For smalt."),
                C("b", "Reelt problem + stor målgruppe + betalingsvilje", "Riktig! Tre kritiske kriterier.", correct=True),
                C("c", "Bare betalingsvilje", "For smalt."),
                C("d", "Tilfeldig", "Strukturert."),],
               "Mange ideer feiler på ett av disse. Validering før investering sparer ressurser."),
            ex("Vanskeligst", "Hvilket spørsmål er ofte vanskeligst?",
               [C("a", "Tilfeldig", "Strukturelt."),
                C("b", "Betalingsvilje — folk sier ofte 'ja, jeg ville kjøpt' uten å gjøre det", "Riktig! Sier-gjør-gap er reelt.", correct=True),
                C("c", "Bare ide", "Lett å vurdere."),
                C("d", "Lovkrav", "Helt urelevant.")],
               "Test betalingsvilje før investering: be folk forhåndsbestille, kickstarter, etc."),
            ex("Når si nei", "Når bør du droppe ideen?",
               [C("a", "Aldri", "Strategi-feil."),
                C("b", "Hvis ett av de 3 kriteriene er nei", "Riktig! Disiplinert kriterieanvendelse.", correct=True),
                C("c", "Bare hvis penger mangler", "For smalt."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Mange gründere er forelsket i ideen sin. Disiplinert kriteriebruk redder fra dårlige investeringer.")]),
        ph("🚧", "Kreativitetens fiender",
           "Frykt, rutine, tidlig evaluering.",
           "Kreativitetens fiender: 1) Frykt for å 'drite seg ut' (selvkritikk), 2) Rutine-tenkning ('slik gjør vi det her'), 3) For tidlig evaluering ('det vil aldri funke'). Sterke kulturer i bedrifter kan kvele kreativitet i fødselen. Trygghet er forutsetning for kreativitet.",
           [("3 FIENDER", "Frykt, rutine, tidlig evaluering."),
            ("KULTUR-EFFEKT", "Sterk kultur kan kvele kreativitet.")],
           "Hvilke 'kreativitetsfiender' har du selv opplevd? På skolen? På jobb?",
           [ex("Fiender", "Hva er klassiske fiender?",
               [C("a", "Bare penger", "For smalt."),
                C("b", "Frykt, rutine-tenkning, for tidlig evaluering", "Riktig! 3 hovedhindre.", correct=True),
                C("c", "Bare tid", "For smalt."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Edward de Bono identifiserte disse på 1970-tallet. Fortsatt aktuelle."),
            ex("Frykt", "Hvordan reduserer frykt kreativitet?",
               [C("a", "Tilfeldig", "Strukturelt."),
                C("b", "Folk holder ideer for seg selv pga frykt for å bli latterliggjort", "Riktig! Trygghet er forutsetning.", correct=True),
                C("c", "Bare for unge", "Gjelder alle."),
                C("d", "Lovkrav", "Helt urelevant.")],
               "Google's 'psychological safety'-forskning viser dette tydelig. Trygge team innoverer mer."),
            ex("Tidlig evaluering", "Hvorfor er det fiende?",
               [C("a", "Tilfeldig", "Strukturelt."),
                C("b", "Stopper ideer før de er fullstendige — kritikk drepper kreativitet", "Riktig! Skill mellom generering og evaluering.", correct=True),
                C("c", "Pynt", "Praktisk regel."),
                C("d", "Lovkrav", "Helt urelevant.")],
               "Brainstorm-regelen 'ingen kritikk' adresserer dette. La ideen vokse før du dømmer.")]),
        ph("🛠️", "Prototype",
           "Enkel modell for å teste.",
           "En prototype er en enkel modell av produktet for å teste funksjon og få tilbakemelding tidlig. Trenger ikke være perfekt — papirskisser, Lego-modeller eller PowerPoint-mockup gir mer læring per krone enn ferdige prototyper. 'Failed fast' med billige prototyper.",
           [("ENKLE", "Trenger ikke være perfekt — bare nok til å teste."),
            ("BILLIG = LÆRING", "Mer læring per krone enn ferdige prototyper.")],
           "Hvilken prototype kunne du laget på 1 time for en ide du har?",
           [ex("Definisjon", "Hva er en prototype?",
               [C("a", "Bare ferdig produkt", "Tvert imot."),
                C("b", "Enkel modell for å teste funksjon og få tilbakemelding", "Riktig! Lærings-verktøy.", correct=True),
                C("c", "Bare for tek", "Brukes overalt."),
                C("d", "Lovkrav", "Strategisk verktøy.")],
               "Airbnb-grunnleggerne lagde første versjon med papir og luftmadrasser. Klassisk minimum viable product."),
            ex("Hvor enkel", "Hvor enkel kan en prototype være?",
               [C("a", "Bare ferdig produkt", "Tvert imot."),
                C("b", "Papirskisser, Lego, PowerPoint — så enkelt som mulig", "Riktig! Enkelt = raskt = billig læring.", correct=True),
                C("c", "Bare 3D-print", "Sjelden nødvendig."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Airbnb startet med papp og fotos. Enkel prototype, stor læring."),
            ex("Hvorfor billig", "Hvorfor enkle prototyper?",
               [C("a", "Spare penger", "Sekundært."),
                C("b", "Mer læring per krone — kan teste flere varianter, lære raskt", "Riktig! Iterativ læring.", correct=True),
                C("c", "Pynt", "Praktisk verdi."),
                C("d", "Lovkrav", "Helt urelevant.")],
               "Lean Startup-prinsipp: minst mulig prototype som tester hovedhypotesen. Spar resten.")]),
        ph("✈️", "Airbnb sin kreative reise",
           "Stor idé født av lite problem.",
           "Brian Chesky og Joe Gebbia kunne ikke betale husleia i 2007. De blåste opp luftmadrasser og leide ut til konferansegjester. Det enkle prototypen ble til Airbnb — verdt 100+ milliarder dollar i dag. Stor idé født av lite problem og enkel prototype. Klassisk eksempel.",
           [("ENKLE START", "Stor virksomhet kan starte ekstremt enkelt."),
            ("REELLE PROBLEM", "De løste eget problem først.")],
           "Hva er ditt 'lille problem' du kunne løst og som andre også har?",
           [ex("Hva", "Hvordan startet Airbnb?",
               [C("a", "Stort venture-fond", "Helt feil."),
                C("b", "Stiftere kunne ikke betale husleia, leide ut luftmadrasser til konferansegjester", "Riktig! Klassisk eksempel.", correct=True),
                C("c", "Tilfeldig", "Strukturert."),
                C("d", "Bare i SF", "Globalt nå."),],
               "Airbnb-historien er studie-objekt på Harvard Business School. Liten start, global skala."),
            ex("Lærdom", "Hva er lærdommen?",
               [C("a", "Bare flaks", "Strukturelle elementer."),
                C("b", "Stor idé kan starte ekstremt enkelt — fra eget problem", "Riktig! Demokratiserer entreprenørskap.", correct=True),
                C("c", "Bare i USA", "Globalt mønster."),
                C("d", "Tilfeldig", "Strukturelt mønster.")],
               "Dropbox, Slack, Pinterest — alle startet som løsning på grunder-problemer. Bygget bedrifter på det."),
            ex("Skalering", "Hvordan ble Airbnb stor?",
               [C("a", "Tilfeldig", "Strukturert vekst."),
                C("b", "Validerte tidlig + bygde plattform + globaliserte gradvis", "Riktig! Iterativ vekst.", correct=True),
                C("c", "Bare reklame", "For smalt."),
                C("d", "Lovkrav", "Helt urelevant.")],
               "Tok 5 år før Airbnb ble lønnsom. Tålmodig kapital + grit + iterasjon.")]),
        ph("🎓", "Kreativitet kan trenes",
           "Demokratisert evne.",
           "Alle kan trene opp sin kreativitet gjennom teknikker og riktig miljø. Det er ingen 'kreativ gen' — det er øvelse, eksponering for mange ideer, og en kultur som tør å feile. Innfør strukturert kreativitet i hverdagen: SCAMPER, Design Thinking, brainstorming.",
           [("DEMOKRATISERT", "Alle kan trene seg opp."),
            ("ØVELSE", "Trening + miljø + eksponering for ideer.")],
           "Hva er ett konkret tiltak du kan starte med for å bli mer kreativ?",
           [ex("Trening", "Kan kreativitet trenes?",
               [C("a", "Nei", "Tvert imot."),
                C("b", "Ja — gjennom teknikker og bevisst praksis", "Riktig! Forskningsbasert.", correct=True),
                C("c", "Bare for kunstnere", "For smalt."),
                C("d", "Bare for unge", "Hele livet."),],
               "Mange tror kreativitet er medfødt. Forskningen viser tydelig at det kan utvikles."),
            ex("Hvordan", "Hva kreves?",
               [C("a", "Bare flaks", "Strukturert."),
                C("b", "Teknikker (SCAMPER, brainstorming) + eksponering for nye ideer + trygt miljø", "Riktig! Multi-faktor.", correct=True),
                C("c", "Bare lese", "For passivt."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Praksis: 30 min daglig brainstorm. Sett timer. Bygg ferdighet gradvis."),
            ex("Lærdom", "Hva er hovedlærdommen?",
               [C("a", "Bare noen kan", "For pessimistisk."),
                C("b", "Alle kan bli mer kreative — det er ferdighet, ikke gave", "Riktig! Demokratiserer kreativitet.", correct=True),
                C("c", "Bare for tek", "Bredt."),
                C("d", "Tilfeldig", "Strukturert."),],
               "Skoler og bedrifter underviser kreativitet som ferdighet. Tidligere forbeholdt 'kunstnere'.")]),
    ],
    ["Du forstår at kreativitet er nytt + nyttig — og at det kan trenes",
     "Du kjenner de 4 fasene i kreativ prosess (forberedelse, inkubasjon, illuminasjon, verifikasjon)",
     "Du behersker brainstorming, SCAMPER og Design Thinking som strukturerte teknikker",
     "Du kan validere en idé på 3 kriterier: reelt problem, stor målgruppe, betalingsvilje",
     "Du forstår at enkle prototyper gir mer læring per krone enn ferdige produkter"])


BEHOV = M("BehovMarkedSegmentering", "ent1", "ENT1-03", "Behov, marked og segmentering", "🎯",
    "behov-marked-segmentering", "ent1",
    "Finn din plass i markedet — kjenn kunden bedre enn du kjenner deg selv. Behov, marked, segmentering, målgruppevalg og posisjonering er entreprenørens kjerne-rammeverk.",
    "Forskning viser at startup-suksess i 90 % av tilfellene er korrelert med markedsforståelse — ikke produkt eller team. 'Marked først' er gull-regelen.",
    "Mange gründere er forelsket i produktet sitt. De som lykkes er forelsket i kunden.",
    [
        ph("🎯", "Kundebehov",
           "Maslows behovspyramide.",
           "Maslows behovspyramide brukes for å forstå hva som driver kunden til kjøp. Fysiologi (mat, vann, søvn), trygghet, tilhørighet, anerkjennelse, selvrealisering. Mange produkter dekker mer enn ett nivå — sportsbil dekker både transport (fysiologi) og status (anerkjennelse).",
           [("PYRAMIDE", "Lavere nivåer prioriteres før høyere."),
            ("MULTI-NIVÅ", "Mange produkter dekker flere nivåer samtidig.")],
           "Hvilket Maslow-nivå dekker en mobiltelefon? Mange?",
           [ex("Maslow", "Hva er nederst i Maslows pyramide?",
               [C("a", "Selvrealisering", "Topp."),
                C("b", "Fysiologiske behov — mat, vann, søvn", "Riktig! Grunnleggende.", correct=True),
                C("c", "Tilhørighet", "Mellom."),
                C("d", "Tilfeldig", "Strukturert pyramide.")],
               "Maslow publiserte i 1943. Hierarkiet er: fysiologi → trygghet → tilhørighet → anerkjennelse → selvrealisering."),
            ex("Eksempel", "Hvilket behov dekker Rolex?",
               [C("a", "Bare tid-dekning", "For smalt."),
                C("b", "Anerkjennelse — status som kommuniserer suksess", "Riktig! Premium-merker er statussignal.", correct=True),
                C("c", "Bare fysiologi", "Helt feil."),
                C("d", "Tilfeldig", "Strukturert."),],
               "En 30 kr klokke viser tiden like presist. Rolex dekker høyere behov — status, identitet."),
            ex("Multi-nivå", "Kan ett produkt dekke flere nivåer?",
               [C("a", "Aldri", "Tvert imot."),
                C("b", "Ja — sportsbil dekker transport (fysiologi) + status (anerkjennelse)", "Riktig! Flere lag samtidig.", correct=True),
                C("c", "Bare for premium", "Gjelder mange produkter."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Apple iPhone: kommunikasjon (basisbehov) + status (anerkjennelse) + selvuttrykk (selvrealisering).")]),
        ph("🌐", "Markedet",
           "Total adresserbar marked.",
           "Markedet er summen av potensielle kunder som har et behov OG evne til å betale. En gründer må kunne kvantifisere markedet: antall potensielle kunder × gjennomsnittlig forbruk = total addressable market (TAM). Uten markedsstørrelse er forretningsplanen gjetning.",
           [("BEHOV + EVNE", "Begge må være tilstede — drømmer er ikke marked."),
            ("TAM", "Total Addressable Market = antall × forbruk.")],
           "Hva er TAM for en lokal kafé? Hvordan ville du regnet?",
           [ex("Definisjon", "Hva er markedet?",
               [C("a", "Alle som har internett", "For bredt."),
                C("b", "Potensielle kunder med behov OG evne til å betale", "Riktig! Begge kriterier.", correct=True),
                C("c", "Alle som kjenner produktet", "For bredt."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Drømmer alene = ikke marked. Behov pluss kjøpekraft = marked."),
            ex("TAM", "Hva betyr TAM?",
               [C("a", "Tilfeldig", "Akronym."),
                C("b", "Total Addressable Market — total markedsstørrelse i kroner", "Riktig! Standard begrep.", correct=True),
                C("c", "Tax And Marketing", "Helt feil."),
                C("d", "Tilfeldig", "Strukturert.")],
               "TAM-SAM-SOM: Total → Serviceable → Obtainable. Trekkingen ned for realistiske mål."),
            ex("Beregning", "Lokal kafé — hvordan beregne TAM?",
               [C("a", "Tilfeldig", "Strukturert."),
                C("b", "Antall mennesker innen 1 km × kaffe-forbruk × pris × frekvens", "Riktig! Kvantitativ tilnærming.", correct=True),
                C("c", "Bare inntekt", "For smalt."),
                C("d", "Lovkrav", "Strategisk valg.")],
               "Eksempel: 5000 mennesker × 30 % kaffe-drikkere × 30 kr × 100 ganger/år = 4,5 mill TAM.")]),
        ph("📊", "Segmentering",
           "Dele markedet i grupper.",
           "Segmentering: oppdeling av markedet i mindre grupper med fellestrekk. 4 vanlige kriterier: demografi (alder, kjønn, inntekt), geografi (sted), psykografi (livsstil, verdier), atferd (lojalitet, bruksmønster). Mest gründere bruker kombinasjon.",
           [("4 KRITERIER", "Demografi, geografi, psykografi, atferd."),
            ("KOMBINASJON", "Sterke segmenter bruker flere kriterier samtidig.")],
           "Velg en bedrift. Hvilke segmenter ser du de retter seg mot? Hvilke kriterier?",
           [ex("Kriterier", "Hva er de 4 vanlige?",
               [C("a", "Bare alder", "For smalt."),
                C("b", "Demografi, geografi, psykografi, atferd", "Riktig! Klassiske kriterier.", correct=True),
                C("c", "Bare inntekt", "For smalt."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Kotler popularierte rammeverket. Fortsatt grunnleggende i segmenteringsteori."),
            ex("Psykografi", "Hva er psykografi?",
               [C("a", "Bare alder", "Det er demografi."),
                C("b", "Livsstil, verdier, holdninger — hva motiverer kjøpsadferd", "Riktig! Dypere enn demografi.", correct=True),
                C("c", "Bare hva folk har", "For smalt."),
                C("d", "Tilfeldig", "Strukturert."),],
               "Psykografi er ofte mer prediktivt enn demografi. To 30-årige kvinner kan ha helt ulike kjøpsmønstre."),
            ex("Praksis", "Hvordan bruke kombinasjon?",
               [C("a", "Tilfeldig", "Strukturert."),
                C("b", "F.eks. 'Oslo-baserte miljøbevisste 25-40-åringer med høy inntekt'", "Riktig! Multi-kriterium gir presisjon.", correct=True),
                C("c", "Bare ett kriterium", "For lite presist."),
                C("d", "Lovkrav", "Strategisk valg."),],
               "Stormberg: 'norske familier som vil ha rimelige turklær med god kvalitet'. Multi-kriterium.")]),
        ph("🎯", "Målgruppevalg",
           "Velge mest attraktive segmenter.",
           "Målgruppevalg: velg de mest attraktive segmentene for bedriftens ressurser. En gründer kan ikke betjene alle — fokus på ett segment gir bedre resultater enn å spre seg tynt utover hele markedet. Drucker: 'Marketing er hele jobben sett fra kundens perspektiv.'",
           [("FOKUS", "Velge bort er like viktig som velge inn."),
            ("RESSURSER", "Match segment med bedriftens kapasitet.")],
           "Hva er du bedre på enn andre? Hvilket segment matcher det best?",
           [ex("Hvorfor velge", "Hvorfor velge bort segmenter?",
               [C("a", "Spare penger", "Sekundært."),
                C("b", "Fokus gir bedre resultater enn å spre seg tynt", "Riktig! Strategisk prioritering.", correct=True),
                C("c", "Lovkrav", "Helt urelevant."),
                C("d", "Tilfeldig", "Strategisk."),],
               "Drucker: 'Marketing er hele jobben sett fra kundens perspektiv.' Velg én kunde-perspektiv først."),
            ex("Test", "Hvilket segment passer din bedrift?",
               [C("a", "Tilfeldig", "Strategisk."),
                C("b", "Det som matcher bedriftens unike styrker og ressurser", "Riktig! Match til kapasitet.", correct=True),
                C("c", "Bare det største", "Ofte for tøff konkurranse."),
                C("d", "Bare det rikeste", "Ikke nødvendigvis riktig."),],
               "Test: hva gjør du bedre enn andre? Hvilket segment verdsetter det mest?"),
            ex("Konsentrert", "Hva er konsentrert målgruppestrategi?",
               [C("a", "Bare ett produkt", "For smalt."),
                C("b", "Fokuser all innsats på ett nisje-segment", "Riktig! Bli best i nisje.", correct=True),
                C("c", "Hele markedet", "Det er udifferensiert."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Stormberg startet konsentrert (norske turfolk). Vokste senere bredere fra sterk nisje-posisjon.")]),
        ph("📍", "Posisjonering",
           "Eie ett ord i kundens hode.",
           "Posisjonering: hvordan du ønsker kunden skal oppfatte deg sammenlignet med konkurrenter. Volvo = sikkerhet. Apple = innovasjon. IKEA = rimelig design. Én tydelig posisjon slår 'alt for alle' hver gang. Test: hvilket ord forbinder kundene med ditt merke?",
           [("ÉTT ORD", "Klassisk regel — én klar assosiasjon."),
            ("DIFFERENSIERING", "Skill deg fra konkurrenter, ikke kopier.")],
           "Hvilket ord eier følgende merker: Volvo? Apple? Tesla? Stormberg?",
           [ex("Hva", "Hva er kjernen i posisjonering?",
               [C("a", "Bare reklame", "For smalt."),
                C("b", "Eie ett ord/konsept i kundens bevissthet", "Riktig! Klassisk konsept.", correct=True),
                C("c", "Lavest pris", "En posisjon, ikke alle."),
                C("d", "Tilfeldig", "Strategisk valg.")],
               "Al Ries og Jack Trout populariserte 'Positioning' i 1981. Fortsatt fundamental teori."),
            ex("Test", "Hvordan teste din posisjonering?",
               [C("a", "Bare spør deg selv", "Subjektivt."),
                C("b", "Spør kundene hvilket ord de forbinder med merket", "Riktig! Posisjonering er i kundens hode, ikke ledelsens.", correct=True),
                C("c", "Tilfeldig", "Strukturert.")],
               "Hvis svarene varierer, har du ikke klar posisjonering. Konsekvens er forvirring."),
            ex("Klassiske eksempler", "Hvilket ord eier Volvo?",
               [C("a", "Hastighet", "Det er Porsche."),
                C("b", "Sikkerhet — bygget over 50 år konsistent", "Riktig! Klassisk eksempel.", correct=True),
                C("c", "Luksus", "Mer Mercedes."),
                C("d", "Tilfeldig", "Strukturert valg."),],
               "Volvo har holdt 'sikkerhet' som kjerne i 50+ år. Konsistens skaper sterk posisjon.")]),
        ph("🔍", "Markedsundersøkelser",
           "Enkle metoder for oppstartsbedrifter.",
           "Enkle metoder: 10-20 dybdeintervjuer med potensielle kunder, observasjon av eksisterende løsninger, enkle digitale spørreskjemaer (Google Forms). Trenger ikke være store undersøkelser — innsikten teller. Kvalitet > kvantitet i tidlig fase.",
           [("ENKELT", "10-20 intervjuer er ofte nok i tidlig fase."),
            ("KVALITATIV", "Dybde slår bredde for å forstå behov.")],
           "Hvis du skulle teste en ide, hvem er de 10 første du ville snakket med?",
           [ex("Volum", "Hvor mange intervjuer trengs i tidlig fase?",
               [C("a", "Tusenvis", "For mye for tidlig fase."),
                C("b", "10-20 dybdeintervjuer er ofte nok", "Riktig! Kvalitet over kvantitet.", correct=True),
                C("c", "Bare ett", "For lite."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Patrick van der Pijl: 'Etter 10 intervjuer ser du mønstre. Etter 20 har du innsikt.'"),
            ex("Type", "Hvilken type undersøkelse for tidlig fase?",
               [C("a", "Bare spørreskjema", "For overflatisk."),
                C("b", "Kvalitative dybdeintervjuer — hvorfor, ikke hvor mange", "Riktig! Forstå motivasjon.", correct=True),
                C("c", "Bare statistikk", "For sent."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Spørsmål: 'Hvordan løser du dette i dag?' avdekker ofte virkelige behov mer enn 'Vil du ha dette?'"),
            ex("Verktøy", "Hvilke gratis verktøy?",
               [C("a", "Bare bedrifts-CRM", "For komplisert tidlig."),
                C("b", "Google Forms, telefon, kafé-møter, LinkedIn-meldinger", "Riktig! Enkle, gratis verktøy.", correct=True),
                C("c", "Bare McKinsey", "Helt overdrevet."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Mange suksess-startups startet med Google Forms og 20 telefonsamtaler. Verktøy er sekundært.")]),
        ph("⚔️", "Konkurrentanalyse",
           "Hvem er de andre?",
           "Konkurrentanalyse: hvem er de andre, og hva er deres styrker og svakheter? Lag en matrise: konkurrenter på radene, dimensjoner (pris, kvalitet, service, brand) på kolonnene. Hvor er det åpning for deg? Substitutter er også konkurrenter — ikke bare direkte aktører.",
           [("MATRISE", "Strukturert oversikt over konkurransebildet."),
            ("SUBSTITUTTER", "Andre måter å løse samme behov er også konkurrenter.")],
           "Lag en konkurrent-matrise for en lokal bedrift du kjenner. Hvor er de svake?",
           [ex("Hvor", "Hvor finner du muligheter?",
               [C("a", "Tilfeldig", "Strukturert."),
                C("b", "Der konkurrentene er svake og kunden er misfornøyd", "Riktig! Klassisk strategi.", correct=True),
                C("c", "Bare lavere pris", "For smalt."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Test: hva klager kundene på når de bruker konkurrentens produkt? Det er din mulighet."),
            ex("Substitutter", "Er substitutter konkurrenter?",
               [C("a", "Aldri", "Tvert imot."),
                C("b", "Ja — alt som løser samme behov er konkurrent", "Riktig! Bredt perspektiv.", correct=True),
                C("c", "Bare i USA", "Globalt."),
                C("d", "Tilfeldig", "Strukturert."),],
               "Hjemmelaget kaffe konkurrerer med kaféen. Substitutter er ofte 'usynlige konkurrenter'."),
            ex("Format", "Hvordan strukturere?",
               [C("a", "Bare tekst", "For ustrukturert."),
                C("b", "Matrise med konkurrenter × dimensjoner (pris, kvalitet, service, brand)", "Riktig! Visuelt strukturert.", correct=True),
                C("c", "Bare en setning", "For overflatisk."),
                C("d", "Tilfeldig", "Strukturert."),],
               "Excel/Google Sheets matrise med konkurrenter på rader, dimensjoner på kolonner. Klassisk verktøy.")]),
        ph("✨", "Verdiløfte",
           "Den unike fordelen kunden får.",
           "Verdiløfte (Value Proposition): den unike fordelen kunden får ved å velge akkurat oss. Skal kunne forklares på 30 sekunder, og må være forskjellig nok fra konkurrentene til at kunden faktisk velger annerledes. Strunk regel for entreprenører.",
           [("30 SEKUNDER", "Hvis lengre — ikke klart nok."),
            ("DIFFERENSIERING", "Må være ulik nok til å motivere bytte.")],
           "Skriv ditt verdiløfte for noe du driver med. Kan du forklare det på 30 sekunder?",
           [ex("Hva", "Hva er verdiløftet?",
               [C("a", "Bare logo", "For smalt."),
                C("b", "Den unike fordelen kunden får ved å velge oss", "Riktig! Klart formulert.", correct=True),
                C("c", "Reklamebudsjett", "Helt urelevant."),
                C("d", "Tilfeldig", "Strukturert."),],
               "Strategyzer-modellen har Value Proposition Canvas — eget verktøy for å bygge dette."),
            ex("Lengde", "Hvor langt bør verdiløftet være?",
               [C("a", "5 sider", "For langt."),
                C("b", "30 sekunder å forklare — gjerne én setning", "Riktig! Korthet er klarhet.", correct=True),
                C("c", "Bare logo", "For smalt."),
                C("d", "Tilfeldig", "Strukturert."),],
               "Tesla: 'Sustainable transport for the world.' Apple: 'Think different.' Ett ord eller setning."),
            ex("Test", "Hvordan teste?",
               [C("a", "Bare spør seg selv", "Subjektivt."),
                C("b", "Forklar til en ekstern person — forsto de poenget?", "Riktig! Ekstern validering.", correct=True),
                C("c", "Tilfeldig", "Strukturert."),
                C("d", "Lovkrav", "Helt urelevant."),],
               "Hvis venner ikke kan gjenta verdiløftet etter at du har forklart, er det ikke klart nok.")]),
        ph("📈", "Kahoot sin målgruppe",
           "Én klar målgruppe = vekst.",
           "Kahoot kunne valgt mange målgrupper: bedrifter, konferanser, familier. De valgte lærere — én klar målgruppe, ett tydelig behov (engasjerende undervisning). Fokus ga eksplosiv vekst — først blant lærere, så ekspansjon til andre segmenter. Klassisk eksempel på fokusert oppstart.",
           [("ÉN MÅLGRUPPE", "Lærere — klart definert."),
            ("EKSPANSJON SENERE", "Bygg sterk base først, utvid etterpå.")],
           "Hva er din 'lærer-målgruppe' — et veldig tydelig segment du kan dominere?",
           [ex("Strategi", "Hva valgte Kahoot?",
               [C("a", "Alle målgrupper", "Tvert imot."),
                C("b", "Én tydelig målgruppe (lærere) for å bygge sterk base", "Riktig! Klassisk fokus-strategi.", correct=True),
                C("c", "Tilfeldig", "Strukturert."),
                C("d", "Bare bedrifter", "Helt feil.")],
               "Kahoot ble grunnlagt i Norge 2012. Vokste til milliardvurdering ved å starte fokusert."),
            ex("Hvorfor fokus", "Hvorfor fokus i tidlig fase?",
               [C("a", "Tilfeldig", "Strukturelt."),
                C("b", "Begrensede ressurser — bygg sterk base først, utvid etterpå", "Riktig! Strategisk prioritering.", correct=True),
                C("c", "Lovkrav", "Helt urelevant."),
                C("d", "Bare for små", "Gjelder alle.")],
               "Stormberg startet med turklær. Klassisk fokus → ekspansjon-strategi."),
            ex("Lærdom", "Hva er strategisk lærdom?",
               [C("a", "Selg til alle", "Tvert imot."),
                C("b", "Velg én tydelig målgruppe — bygg sterk base — utvid", "Riktig! Klassisk vekstmønster.", correct=True),
                C("c", "Bare for tek", "Bredt anvendelig."),
                C("d", "Tilfeldig", "Strukturert."),],
               "Mange startup-feil: prøver å selge til 'alle'. Resulterer i å selge til ingen.")]),
        ph("🎓", "Kjenne kunden",
           "Bedre enn deg selv.",
           "Kjenn din kunde bedre enn du kjenner deg selv. Gründere som baserer seg på antakelser i stedet for kundekontakt, ender ofte med produkter ingen vil ha — uansett hvor smart løsningen er teknisk. Den eneste kuren mot dette er kontinuerlig kundekontakt.",
           [("KONTAKT", "Snakk med kunder konstant — ikke bare i undersøkelser."),
            ("YDMYKHET", "Anta at du ikke vet — bekreft alt med data.")],
           "Når snakket du sist med en potensiell kunde for ideen din?",
           [ex("Regel", "Hva er gründer-regelen?",
               [C("a", "Bare lytt til ledelsen", "For internt."),
                C("b", "Kjenn kunden bedre enn du kjenner deg selv", "Riktig! Praktisk regel.", correct=True),
                C("c", "Stol på magefølelsen", "Subjektivt."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Steve Blank: 'Get out of the building.' Klassisk Lean Startup-prinsipp."),
            ex("Konsekvens", "Hva skjer uten kundekontakt?",
               [C("a", "Tilfeldig", "Strukturelt."),
                C("b", "Produkter ingen vil ha — uansett teknisk smartness", "Riktig! Klassisk startup-feil.", correct=True),
                C("c", "Bedre produkter", "Tvert imot."),
                C("d", "Lovkrav", "Helt urelevant.")],
               "70 % av startups mislykkes pga 'no market need'. Hovedårsak til feil."),
            ex("Frekvens", "Hvor ofte snakke med kunder?",
               [C("a", "Aldri", "Helt feil."),
                C("b", "Konstant — ikke bare i 'undersøkelser', men løpende dialog", "Riktig! Kontinuerlig læring.", correct=True),
                C("c", "Bare i krise", "For sjelden."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Beste gründere: 5+ kundesamtaler per uke. Lærer kontinuerlig.")]),
    ],
    ["Du forstår kundebehov via Maslow og at produkter ofte dekker flere behovsnivåer",
     "Du kan beregne TAM og forstår skillet mellom drømmer og reelt marked",
     "Du behersker segmentering på 4 kriterier (demografi, geografi, psykografi, atferd)",
     "Du kan velge målgruppe og posisjonere bedriften med ett klart konsept",
     "Du forstår at fokusert oppstart (Kahoot-modell) slår spredning"])


g.write_modules([INNOV, KREATIVITET, BEHOV], "ENT1 1-3")
