#!/usr/bin/env python3
"""ML2 kap 2-5: Visjon, Bransjeanalyse, Lederrolle, Samfunnsansvar."""
import importlib.util
from pathlib import Path
spec = importlib.util.spec_from_file_location("g", Path(__file__).parent / ".gen-shared.py")
g = importlib.util.module_from_spec(spec); spec.loader.exec_module(g)
C, ph, ex, M = g.C, g.ph, g.ex, g.M


VISJON = M("VisjonOgMal", "ml2", "ML2-02", "Visjon, mål og overordnede strategier", "🌟",
    "visjon-og-mal", "ml2",
    "Hvor skal vi? Visjonen gir retning, målene gir struktur, strategien viser veien. Uten klare mål er det umulig å vite om strategien virker.",
    "Equinor sin visjon 'Vi former fremtidens energi' kom etter Statoil-til-Equinor-skiftet i 2018 — og signaliserer overgangen fra olje til energi. En 6-ords visjon endret hele strategien.",
    "Visjonen er ikke en plakat på veggen — den er testen for hver beslutning. 'Bringer dette oss nærmere visjonen?' Hvis nei, ikke gjør det.",
    [
        ph("💡", "Forretningsidé", "Hva, for hvem, hvordan, hvorfor oss.",
           "Forretningsideen svarer på fire spørsmål: Hva skal vi gjøre? For hvem? Hvordan? Hvorfor oss? Skal kunne forklares på 30 sekunder. Klar forretningsidé skiller deg fra konkurrentene.",
           [("4 SPØRSMÅL", "Hva, for hvem, hvordan, hvorfor oss — alle må kunne besvares."),
            ("KORT", "30 sekunder eller mindre. Lengre er signal om uklarhet.")],
           "Forklar bedriften du jobber for / handler hos på 30 sekunder. Lett eller vanskelig?",
           [ex("4 spørsmål", "Hva er de 4 spørsmålene i forretningsideen?",
               [C("a", "Mål, strategi, tiltak, kontroll", "Det er strategiprosessen, ikke forretningsidé."),
                C("b", "Hva, for hvem, hvordan, hvorfor oss", "Riktig! Klassisk modell. Alle 4 må besvares klart.", correct=True),
                C("c", "Pris, produkt, plass, påvirkning", "Det er markedsmiksen."),
                C("d", "Hvor, når, hvordan, hvor mye", "Helt feil ramme.")],
               "Test deg selv: kan du svare på alle 4 om din egen jobb? De fleste sliter med 'hvorfor oss'."),
            ex("Lengde", "Hvor lang bør forretningsideen være?",
               [C("a", "Minst 5 sider", "For lang — tegn på uklart fokus."),
                C("b", "30 sekunder å forklare", "Riktig! 'Elevator pitch'. Kortere er klarere.", correct=True),
                C("c", "Kun overskriften", "For kort — mangler innhold."),
                C("d", "Uvesentlig", "Lengde signaliserer klarhet.")],
               "Hvis du må snakke i 5 minutter for å forklare hva bedriften gjør, har du et fokusproblem."),
            ex("Hvorfor oss", "Hva sikter 'hvorfor oss' til?",
               [C("a", "Geografi", "For smalt."),
                C("b", "Differensiering — hva gjør oss unike sammenlignet med konkurrenter", "Riktig! Uten klart svar er du bare en av mange.", correct=True),
                C("c", "Lønn", "Helt urelevant."),
                C("d", "Bedriftens alder", "Sjelden differensiator.")],
               "Stormberg: 'Vi ansetter folk med hull i CV-en'. Det er klart 'hvorfor oss'.")]),
        ph("🌟", "Visjon", "Et inspirerende bilde av drømmesituasjonen.",
           "Visjonen er det inspirerende bildet av bedriftens drømmesituasjon i fremtiden. Skal motivere — ikke beskrive nåværende drift. Eksempel: Tomras 'Lead the resource revolution' inspirerer ansatte til å se seg som del av noe større.",
           [("INSPIRERENDE", "Skal vekke følelser, ikke bare beskrive aktivitet."),
            ("FREMTIDIG", "Beskriver hvor vi vil — ikke hvor vi er nå.")],
           "Hva er Norges visjon? Norge har egentlig ikke en eksplisitt — diskuter om den burde finnes.",
           [ex("God visjon", "Hvilken er en god visjon?",
               [C("a", "Vi skal vokse 5 % per år", "Det er et mål, ikke visjon."),
                C("b", "Lead the resource revolution (Tomra)", "Riktig! Inspirerende, fremtidig, klart eierskap. Tomra-eksempel.", correct=True),
                C("c", "Vi skal følge alle lover", "Lovkrav, ikke visjon."),
                C("d", "Vi skal ha størst budsjett", "Internt fokus.")],
               "Test: Vekker visjonen følelser? Hvis ikke, er den for tørr."),
            ex("Funksjon", "Hva skal visjonen gjøre?",
               [C("a", "Erstatte strategi", "Visjonen er INPUT til strategi."),
                C("b", "Inspirere og forene ansatte mot felles fremtidsbilde", "Riktig! Visjon = nordstjernen. Strategien er kursen mot den.", correct=True),
                C("c", "Bare for reklame", "Internt verktøy primært."),
                C("d", "Skattefradrag", "Helt urelevant.")],
               "Test: Hvis du sletter visjonen i morgen, ville noen merke? Hvis ikke — den er ikke ekte."),
            ex("Tidshorisont", "Hvor langt frem ser visjonen?",
               [C("a", "Bare neste år", "For kort."),
                C("b", "10-30 år eller lenger — mål man kanskje aldri når", "Riktig! Visjon er nordstjernen — du kommer aldri helt frem, men den styrer kursen.", correct=True),
                C("c", "Bare neste kvartal", "Det er rapportering."),
                C("d", "100 år", "For langt for praktisk styring.")],
               "JFKs 'mann på månen' var visjon med ~10-årshorisont. Sjeldent ambisiøst, men oppnåelig.")]),
        ph("🪜", "Målhierarkiet", "Visjon → hovedmål → delmål → handlingsmål.",
           "Mål struktureres i hierarki: visjonen (lang sikt), hovedmål (3-5 år), delmål (1 år), handlingsmål (måneder). Hvert nivå konkretiserer det forrige. Visjon 'verdens beste' blir til handlingsmål 'levere innen 24 timer'.",
           [("STRUKTUR", "Hvert nivå konkretiserer det forrige."),
            ("KOBLING", "Handlingsmålet på lavt nivå skal kunne spores tilbake til visjonen.")],
           "Tegn ditt eget målhierarki for et personlig prosjekt — visjon ned til neste-uke-handling.",
           [ex("Hierarki", "Hva er riktig rekkefølge fra topp?",
               [C("a", "Handlingsmål → delmål → hovedmål → visjon", "Omvendt — visjonen er øverst."),
                C("b", "Visjon → hovedmål → delmål → handlingsmål", "Riktig! Top-down strukturering. Hvert nivå må kobles oppover.", correct=True),
                C("c", "Tilfeldig rekkefølge", "Strukturert hierarki er nødvendig."),
                C("d", "Kun visjon", "For lite konkret.")],
               "Test: kan handlingsmål spores til visjon? Hvis ikke, er det isolert aktivitet."),
            ex("Kobling", "Hvorfor må handlingsmål kobles til visjon?",
               [C("a", "Lovkrav", "Ikke lovkrav."),
                C("b", "For å sikre at daglige handlinger faktisk bygger mot langsiktig retning", "Riktig! Uten kobling blir aktivitet bare aktivitet — ikke fremgang.", correct=True),
                C("c", "Ingen god grunn", "Det er kjernehensikten."),
                C("d", "For å imponere", "Internt verktøy.")],
               "Spør per oppgave: hvilket hovedmål bygger denne mot? Hvis svaret er 'vet ikke', revurder oppgaven."),
            ex("Tidshorisonter", "Typisk tidshorisont per nivå?",
               [C("a", "Visjon = i dag, handlingsmål = 100 år", "Helt feil retning."),
                C("b", "Visjon = 10+ år, hovedmål = 3-5 år, delmål = 1 år, handlingsmål = uker/måneder", "Riktig! Hver nivå har sin tidshorisont. Konkretisering skjer som tiden krymper.", correct=True),
                C("c", "Alle nivåer er 1 år", "Mister verdi som hierarki."),
                C("d", "Tilfeldig", "Strukturert tidsfordeling er essensielt.")],
               "Quartersmål er typisk delmål-nivå. Daglige oppgaver er handlingsmål.")]),
        ph("🎯", "SMART-mål", "Spesifikt, Målbart, Ambisiøst, Realistisk, Tidsbestemt.",
           "SMART er rammeverket for gode mål. 'Vi skal vokse' er ikke SMART. 'Øke omsetningen i Norge med 15 % innen 31.12' er SMART. Alle 5 kriteriene må være oppfylt — mangler ett, taper målet styringsverdi.",
           [("ALLE 5 KRITERIER", "Spesifikt, Målbart, Ambisiøst, Realistisk, Tidsbestemt — alle må være oppfylt."),
            ("STYRING", "SMART-mål gir grunnlag for både planlegging og evaluering.")],
           "Skriv et SMART-mål for skoleåret. Hva er spesifikt, målbart, ambisiøst, realistisk og tidsbestemt?",
           [ex("Hva betyr S", "Hva står S for?",
               [C("a", "Salg", "Helt feil."),
                C("b", "Spesifikt — klart hva som skal oppnås", "Riktig! Vagt mål er ubrukbart for styring.", correct=True),
                C("c", "Stort", "Det dekkes av A og R."),
                C("d", "Strategi", "Helt feil ramme.")],
               "Test: kan to mennesker tolke målet på samme måte? Hvis nei, ikke spesifikt nok."),
            ex("M og R i konflikt", "Et 'realistisk' og 'ambisiøst' mål — hvordan balansere?",
               [C("a", "Velg det letteste", "Da blir det ikke ambisiøst."),
                C("b", "Stretch-mål: utfordrende men mulig med innsats — typisk 70-90 % suksessrate", "Riktig! Ambisjon driver innsats; realisme sikrer motivasjon. Balansen er kunsten.", correct=True),
                C("c", "Velg det umulige", "Da mister teamet motivasjon."),
                C("d", "Velg uten å tenke", "Tilfeldighet gir dårlige mål.")],
               "Klassisk regel: ambisiøst nok til å bli svett, realistisk nok til å være nåbart med innsats."),
            ex("Tid", "Hvorfor må mål være tidsbestemt?",
               [C("a", "Pynt", "Ikke estetikk — funksjon."),
                C("b", "Uten frist mister målet drivkraft og målbarhet", "Riktig! 'Innen et tidspunkt' tvinger frem prioritering. Uten frist utsettes alt.", correct=True),
                C("c", "Lovkrav", "Ikke lovkrav."),
                C("d", "Kun for store mål", "Gjelder alle mål.")],
               "Bruk konkrete datoer: '31.12.2025', ikke 'snart'. Da er det målbart.")]),
        ph("📈", "Vekststrategier", "4 veier til vekst (Ansoff).",
           "Ansoffs matrise: Markedsinntrenging (kjent produkt + kjent marked, lav risiko), Markedsutvikling (kjent produkt + nytt marked), Produktutvikling (nytt produkt + kjent marked), Diversifikasjon (nytt produkt + nytt marked, høy risiko). Risiko stiger fra 1 til 4. De fleste lykkes best med 1-2 før de prøver 3-4.",
           [("4 STRATEGIER", "Markedsinntrenging, markedsutvikling, produktutvikling, diversifikasjon."),
            ("RISIKO STIGER", "Klassisk regel: behersker du de letteste først.")],
           "En lokal kafé vil vokse. Hvilken Ansoff-strategi gir lavest risiko?",
           [ex("Mest risikabel", "Hvilken Ansoff er høyest risiko?",
               [C("a", "Markedsinntrenging", "Lavest risiko — kjent terreng."),
                C("b", "Diversifikasjon — nytt produkt i nytt marked", "Riktig! Begge dimensjoner er nye. Ofte 'bet the company'.", correct=True),
                C("c", "Produktutvikling", "Mellomrisiko."),
                C("d", "Markedsutvikling", "Mellomrisiko.")],
               "Nokia diversifiserte fra papir til mobil — lykkes. De fleste forsøk mislykkes."),
            ex("Lavrisiko", "Hvilken er lavest risiko?",
               [C("a", "Markedsinntrenging — selg mer av det du har til kunder du har", "Riktig! Begge faktorer er kjent. Lavest risiko, men også begrenset vekstpotensial.", correct=True),
                C("b", "Diversifikasjon", "Helt feil ende."),
                C("c", "Produktutvikling", "Mellomrisiko."),
                C("d", "Ingen — alle er like risikable", "Risiko varierer betydelig.")],
               "Markedsinntrenging er ofte beste startsted. Optimalisér eksisterende før du eksperimenterer."),
            ex("Norsk eksempel", "Norsk laks-eksport til Kina — hvilken Ansoff?",
               [C("a", "Markedsinntrenging", "Kina er nytt marked."),
                C("b", "Markedsutvikling — samme produkt, nytt marked", "Riktig! Klassisk eksport. Lakse-produktet er likt; kinesisk marked er nytt.", correct=True),
                C("c", "Diversifikasjon", "Bare ett av to elementer er nytt."),
                C("d", "Produktutvikling", "Produktet er likt.")],
               "Norsk fiskebransje har 50 år erfaring med markedsutvikling. Eksport er nasjonens vekstmotor.")]),
        ph("⚔️", "Konkurransestrategier", "Porters 3 generiske strategier.",
           "Porter identifiserte 3 generiske konkurransestrategier: Kostnadslederskap (vær billigst — IKEA, Ryanair), Differensiering (vær unik — Apple, Tesla), Fokusering (vær best i en nisje — Rolex, Patagonia). Den som prøver alt blir best i ingenting. Velg én og hold deg til den.",
           [("3 STRATEGIER", "Kostnadslederskap, differensiering, fokusering."),
            ("VELG ÉN", "Hybridposisjoner mislykkes ofte. Klart valg gir klarhet.")],
           "Velg en bedrift du kjenner. Hvilken Porter-strategi følger de? Lykkes de med valget?",
           [ex("Porters 3", "Hva er Porters 3 generiske strategier?",
               [C("a", "Mål, strategi, kontroll", "Helt feil ramme."),
                C("b", "Kostnadslederskap, differensiering, fokusering", "Riktig! Klassisk Porter. Alle bedrifter må velge én.", correct=True),
                C("c", "Salg, marked, produkt", "Helt feil."),
                C("d", "Vekst, modning, tilbakegang", "Det er PLC.")],
               "Hybridforsøk er ofte 'stuck in the middle' — verken billig nok eller distinkt nok."),
            ex("IKEA", "Hvilken Porter-strategi følger IKEA?",
               [C("a", "Differensiering — eksklusivt design", "Det er Hermès."),
                C("b", "Kostnadslederskap — laveste pris via masseproduksjon og flatpakker", "Riktig! IKEA er klassisk kostnadsleder. Hele forretningsmodellen er bygget for lavest pris.", correct=True),
                C("c", "Fokusering — kun premium-kunder", "Tvert imot — bredt marked."),
                C("d", "Ingen strategi", "Helt feil.")],
               "IKEA-modellen: flatpakke, selvbetjening, masseinnkjøp = lave kostnader = lave priser."),
            ex("Stuck in the middle", "Hva betyr 'stuck in the middle'?",
               [C("a", "Bedriften er midt i markedet", "For konkret tolkning."),
                C("b", "Bedriften prøver å være både billig og unik — lykkes med ingen", "Riktig! Porter-advarsel. Konkurranse-faglig dødssone — verken kostnadsleder eller differensiator.", correct=True),
                C("c", "Geografisk midt i landet", "Helt urelevant."),
                C("d", "Mellomstor bedrift", "Ikke størrelse, posisjonering.")],
               "Klassisk feil: prøve å konkurrere med Walmart på pris OG med Apple på design. Velg én ende.")]),
        ph("📊", "GAP-analyse", "Forskjellen mellom hvor vi er og hvor vi vil.",
           "GAP-analyse identifiserer avstanden mellom nåværende ytelse og ønsket ytelse. Brukes for å avdekke hvor mye innsats som kreves. Eksempel: nåværende markedsandel 12 %, mål 20 % = GAP på 8 prosentpoeng. Tiltak må adressere gapet konkret.",
           [("GAP = INNSATS", "Større GAP = større innsats kreves."),
            ("KONKRET", "Tall, ikke følelser. 'Vi må vokse' er ikke GAP-analyse.")],
           "Hva er ditt eget GAP — hvor er du, hvor vil du være? Hva er innsatsen som kreves?",
           [ex("Hva er GAP", "Hva er en GAP-analyse?",
               [C("a", "Analyse av kjønnsfordeling", "Helt feil tolkning."),
                C("b", "Forskjellen mellom nåværende og ønsket tilstand", "Riktig! Gap = avstanden å lukke. Brukes for å konkretisere innsatsen.", correct=True),
                C("c", "Geografisk avstand", "Helt feil."),
                C("d", "Lønnsforskjell", "Det er en spesifikk type GAP, ikke generelt."),],
               "Tegn pil: 'her er vi' → 'her vil vi'. Pilens lengde er gapet."),
            ex("Bruk", "Når bruker man GAP-analyse?",
               [C("a", "Aldri", "Brukes mye."),
                C("b", "For å konkretisere hva som kreves for å nå mål", "Riktig! Tvinger frem realisme om innsats og ressurser. Stoppes ofte at 'urealistiske mål' avsløres.", correct=True),
                C("c", "Bare for offentlig sektor", "Brukes overalt."),
                C("d", "Bare på regnskap", "Bredere bruk.")],
               "Spør per mål: 'hvor stort er gapet?' Hvis du ikke kan tallfeste, er målet ikke godt nok definert."),
            ex("Eksempel", "Markedsandel nå 10 %, mål 25 %. Hva er GAP?",
               [C("a", "10 prosentpoeng", "Feil regning."),
                C("b", "15 prosentpoeng", "Riktig! 25-10 = 15. Det er gapet å lukke.", correct=True),
                C("c", "25 prosentpoeng", "Det er målet, ikke gapet."),
                C("d", "Umulig å beregne", "Enkel subtraksjon.")],
               "Gapet er 15 pp. Spør: hva kreves for å vinne 15 pp markedsandel? Tiltak, ressurser, tid?")]),
        ph("⚖️", "Verdigrunnlag", "De etiske rammene som styrer hverdagen.",
           "Verdigrunnlaget er de moralske grensene for hvordan ansatte skal opptre — særlig i situasjoner der strategien settes på prøve. Eksempel: NHO sin verdiplattform inkluderer integritet, ansvar, åpenhet. Verdier viser seg i handlinger, ikke plakater. Ledelsens eksempel teller mest.",
           [("HANDLING > ORD", "Verdier vises i hva som premieres, ikke hva som ropes ut."),
            ("LEDELSENS EKSEMPEL", "Ledere setter standard. Hva de gjør betyr mer enn hva de sier.")],
           "Hvilke verdier ser du tydelig i bedrifter du kjenner? Hvilke 'står på plakaten' men er ikke ekte?",
           [ex("Hvor verdier vises", "Hvor ser man ekte verdier?",
               [C("a", "På verdiplakaten", "Plakat = ord. Ikke nødvendigvis handling."),
                C("b", "I konflikt mellom inntjening og verdier — hva ble valgt?", "Riktig! Verdier testes når det koster. Velges inntjening, er verdiene ikke ekte.", correct=True),
                C("c", "I årsrapporten", "Kan være pynt."),
                C("d", "I HR-systemet", "Bare hvis fulgt opp.")],
               "Test: sist det var konflikt mellom verdi og inntjening — hva vant? Det er den ekte verdien."),
            ex("Lederens rolle", "Hva er viktigst for verdier?",
               [C("a", "Plakater på veggen", "Pynt."),
                C("b", "Ledelsens daglige eksempel", "Riktig! 'Walk the talk'. Folk ser hva ledere faktisk gjør — kopierer det.", correct=True),
                C("c", "Ansatt-håndbok", "Dokumenter alene endrer ikke kultur."),
                C("d", "Reklame", "Eksternt — ikke kultur.")],
               "Steve Jobs: 'kultur er det som skjer når lederen ikke er i rommet'. Riktig observasjon."),
            ex("Funksjon", "Hva er verdienes hovedfunksjon?",
               [C("a", "Pynt", "Ikke estetikk."),
                C("b", "Beslutningsstøtte når strategi er uklar — verdiene viser hvordan", "Riktig! Verdier er kompass i grå-soner der reglene ikke gir svar.", correct=True),
                C("c", "Kontraktklausul", "Verdier er bredere."),
                C("d", "Skattesak", "Helt urelevant.")],
               "Når i tvil, spør: 'hva sier våre verdier?' Hvis svaret ikke gir retning, er verdiene ubrukelige.")]),
        ph("🎯", "Strategi-implementering", "Den vanskelige delen.",
           "70 % av strategier mislykkes på implementering. Hovedfeil: dårlig kommunikasjon, manglende ressurser, ingen oppfølging. Krever: tydelige KPI-er, månedlig oppfølging, ledelse-engasjement. Strategi er et verb, ikke et substantiv.",
           [("70 % MISLYKKES", "McKinsey-tall over år. Mest pga svak implementering."),
            ("KOMMUNIKASJON", "Hvis ansatte ikke forstår strategien, blir den ikke fulgt.")],
           "Hvilke endringer du har vært del av lyktes? Hva avgjorde — plan eller utførelse?",
           [ex("Suksessrate", "Hvor mange strategier lykkes typisk?",
               [C("a", "90 %", "Helt feil — mye lavere."),
                C("b", "30 % — 70 % mislykkes", "Riktig! McKinsey-data. Implementering er hardere enn planlegging.", correct=True),
                C("c", "Alle", "Helt feil."),
                C("d", "10 %", "Lavere enn realiteten.")],
               "Statistikken er stabil — ikke fordi strategi er svak, men fordi implementering er undervurdert."),
            ex("Hvor svikter", "Hvor svikter strategier mest?",
               [C("a", "I planleggings-fasen", "Planer er typisk gode."),
                C("b", "I implementering — strategien kommer aldri ut av møterommet", "Riktig! Mest vanlige feil. Krever like mye fokus som planlegging.", correct=True),
                C("c", "I analyse", "Analyse er ofte for grundig."),
                C("d", "Strategier feiler aldri", "Helt feil.")],
               "Test: spør tilfeldig ansatt — kan hun forklare strategien? Hvis ikke, har du implementeringsproblem."),
            ex("Beste fix", "Hva er beste fix for implementering?",
               [C("a", "Bare bedre planer", "Plan uten utførelse er ingenting."),
                C("b", "Tydelige KPI-er, månedlig oppfølging, ledelse-engasjement, kommunikasjon", "Riktig! Helhetlig systemarbeid. Disiplin over tid.", correct=True),
                C("c", "Mer dokumentasjon", "Dokumenter alene hjelper ikke."),
                C("d", "Bare mer penger", "Penger uten retning er bortkastet.")],
               "Implementering er en disiplin. Strategi-møter månedlig — ikke arkiver dokumentet og glem.")]),
    ],
    ["Du forstår at forretningsidé må svare på hva, for hvem, hvordan, hvorfor oss",
     "Du kan formulere SMART-mål og bygge målhierarki fra visjon til handling",
     "Du kjenner Ansoffs vekstmatrise og Porters 3 generiske konkurransestrategier",
     "Du behersker GAP-analyse som verktøy for å konkretisere innsats",
     "Du forstår at verdier vises i handling, ikke ord — og at 70 % av strategier feiler på implementering"])


BRANSJE = M("MarkedsOgBransjeanalyse", "ml2", "ML2-03", "Markeds- og bransjeanalyse", "🔍",
    "markeds-og-bransjeanalyse", "ml2",
    "Bransjeanalyse forteller hvor lønnsomt det er å være i bransjen. Porters 5 krefter er det dominerende rammeverket. Sterke krefter = lave marginer for alle. Svake krefter = lukrativ posisjon.",
    "Norsk dagligvare er kontrollert av 3 kjeder med 96 % markedsandel. Det er en av Europas mest konsentrerte bransjer — og forklarer hvorfor matprisene er som de er.",
    "Bransjeanalyse forteller deg om jobben er verdt det. Hvis 4 av 5 krefter er sterke, er det vanskelig å tjene penger uansett hvor flink du er.",
    [
        ph("🔍", "Porters 5 krefter", "Bransjens lønnsomhet bestemmes av 5 krefter.",
           "Michael Porter identifiserte 5 krefter som sammen bestemmer bransjens lønnsomhetspotensial: Rivalisering, Nyetablerere, Substitutter, Leverandørmakt, Kundemakt. Sterke krefter = lave marginer. Modellen er over 40 år gammel, fortsatt dominerende.",
           [("5 KREFTER", "Hver kraft kan være sterk eller svak."),
            ("LØNNSOMHET", "Sum av kreftene bestemmer hvor mye man tjener i bransjen.")],
           "Velg en bransje du kjenner. Vurder hver av de 5 kreftene — sterk eller svak?",
           [ex("Antall krefter", "Hvor mange krefter har Porter?",
               [C("a", "3", "For få."),
                C("b", "5", "Riktig! Rivalisering, nyetablerere, substitutter, leverandørmakt, kundemakt.", correct=True),
                C("c", "7", "For mange."),
                C("d", "10", "Helt feil.")],
               "Tegn modellen: bransjen i midten, 4 krefter rundt + intern rivalisering."),
            ex("Effekt", "Hva betyr sterke krefter?",
               [C("a", "Høy lønnsomhet", "Tvert imot."),
                C("b", "Lav lønnsomhet — alle blir presset på marginer", "Riktig! Sterke krefter spiser opp profittpotensialet.", correct=True),
                C("c", "Bedriften vokser raskt", "Ikke direkte sammenheng."),
                C("d", "Ingen effekt", "Helt feil.")],
               "Bransje med 4-5 sterke krefter: vanskelig å tjene penger uansett hvor god du er."),
            ex("Bruk", "Når brukes Porter?",
               [C("a", "Aldri", "Brukes mye."),
                C("b", "For å vurdere om en bransje er attraktiv å være i", "Riktig! Strategisk verktøy. Kan også brukes før inntreden i ny bransje.", correct=True),
                C("c", "Bare for konkurrenter", "Bredere bruk."),
                C("d", "Bare for offentlig sektor", "Brukes overalt.")],
               "Før du starter ny bransje: gjør Porter. Hvis 4-5 krefter er sterke, vurder å gå et annet sted.")]),
        ph("⚔️", "Rivalisering", "Hvor hardt kjemper aktørene mot hverandre?",
           "Rivalisering er konkurransen mellom eksisterende aktører. Sterk når: mange like aktører, lav vekst, høye fastkostnader, lite differensiering. Resultat: priskrig, lave marginer. Svak når: få aktører, høy vekst, sterk differensiering.",
           [("STERK NÅR", "Mange aktører, lav vekst, høye fastkostnader, like produkter."),
            ("PRISKRIG", "Klassisk symptom på sterk rivalisering.")],
           "Norsk dagligvare har sterk rivalisering. Hvilke symptomer ser du i butikken?",
           [ex("Hva indikerer", "Hva er klassisk symptom på sterk rivalisering?",
               [C("a", "Høye marginer", "Tvert imot."),
                C("b", "Priskrig og kampanjer", "Riktig! Aktører konkurrerer på pris fordi de ikke har annet å skille seg ut med.", correct=True),
                C("c", "Ingen reklame", "Sterk rivalisering = mer reklame."),
                C("d", "Bedrifter samarbeider", "Det er kartell, ulovlig.")],
               "Telekom-bransjen i Norge: Telia + Telenor + Ice. Stadige tilbudskampanjer = sterk rivalisering."),
            ex("Når svak", "Når er rivalisering svak?",
               [C("a", "Mange like aktører", "Det gir sterk rivalisering."),
                C("b", "Få aktører med differensierte produkter", "Riktig! Få konkurrenter med distinkte tilbud = svak rivalisering = høyere marginer.", correct=True),
                C("c", "Lav vekst i markedet", "Lav vekst gir typisk sterk rivalisering."),
                C("d", "Aldri svak", "Varierer mye.")],
               "Apple og Samsung dominerer premium-mobiler. Differensiert posisjon = bedre marginer enn generisk telefon-bransje."),
            ex("Norsk eksempel", "Hvor sterk er rivalisering i norsk dagligvare?",
               [C("a", "Svak — bare 3 kjeder", "Få aktører kan ha sterk eller svak rivalisering — avhenger av oppførsel."),
                C("b", "Sterk — 3 kjeder konkurrerer hardt på pris", "Riktig! REMA, NorgesGruppen, Coop konkurrerer hardt på pris og kampanjer. Marginer presses.", correct=True),
                C("c", "Ikke eksisterende", "Helt feil."),
                C("d", "Bare i Oslo", "Gjelder hele landet.")],
               "Selv få aktører kan konkurrere hardt. Spørsmålet er adferd, ikke bare antall.")]),
        ph("🚪", "Nyetablerere", "Hvor høy er inngangsbarrieren?",
           "Trussel fra nyetablerere avhenger av inngangsbarrierer: høye barrierer = liten trussel = etablerte aktører beskyttet. Eksempler på barrierer: kapitalkrav (oljebransje), regulering (bank), merkelojalitet (Coca-Cola), distribusjon (TINE i butikkhylla). Lave barrierer = stadig nye konkurrenter.",
           [("HØYE BARRIERER", "Beskytter etablerte aktører — gir bedre marginer."),
            ("EKSEMPLER", "Kapital, regulering, merkelojalitet, distribusjon, teknologi.")],
           "Hvor høye er inngangsbarrierene i bedriften du jobber for / kjenner? Hva beskytter dem?",
           [ex("Effekt av høye", "Hva betyr høye inngangsbarrierer?",
               [C("a", "Mange nyetablerere", "Tvert imot."),
                C("b", "Få nye aktører — etablerte beskyttet, høyere marginer", "Riktig! Høye barrierer = lukrativ posisjon for de som er inne.", correct=True),
                C("c", "Markedet krymper", "Ikke direkte sammenheng."),
                C("d", "Ingen effekt", "Helt feil.")],
               "Norsk bank: høyt regulert (krever konsesjon, kapital, kompetanse). Få nye aktører siden 1990-tallet."),
            ex("Type barriere", "Hvilken er en inngangsbarriere?",
               [C("a", "Lav pris i markedet", "Det er konsekvens, ikke barriere."),
                C("b", "Kapitalkrav — det koster milliarder å starte oljevirksomhet", "Riktig! Kapital er klassisk barriere. Hindrer at små aktører kan utfordre etablerte.", correct=True),
                C("c", "Mange kunder", "Ikke barriere."),
                C("d", "Vekst", "Vekst tiltrekker nyetablerere, ikke barriere.")],
               "Andre barrierer: patent, distribusjon, merkelojalitet, regulering. Hver bransje har sin mix."),
            ex("Lavbarriere", "Hvor er inngangsbarrierene typisk LAVE?",
               [C("a", "Olje", "Helt feil — høye barrierer."),
                C("b", "Web-startups — krever lite kapital, ingen regulering", "Riktig! Derfor er det så mange tech-startups. Lave barrierer = konstant ny konkurranse.", correct=True),
                C("c", "Bankvirksomhet", "Strengt regulert."),
                C("d", "Atomenergi", "Ekstreme barrierer.")],
               "Lave barrierer = mange konkurrenter, vanskelig å bygge varig fortrinn.")]),
        ph("🔄", "Substitutter", "Andre måter å løse samme behov.",
           "Substitutter er produkter som løser SAMME behov med annen teknologi/metode. Sykling er substitutt til buss. Hjemmelaget mat er substitutt til restaurant. Strenge substitutter setter tak på pris. Når substitutet blir bedre/billigere, må bedriften reagere — ellers tapes markedsandel.",
           [("SAMME BEHOV", "Substitutt løser kundens behov, men på annen måte."),
            ("PRISTAK", "Substitutter setter tak på hva du kan ta i pris.")],
           "Hva er substitutt for: bilkjøring, kinobillett, frisørtjeneste? Hvor sterke er substituttene?",
           [ex("Hva er substitutt", "Hva kjennetegner et substitutt?",
               [C("a", "Samme produkt fra annen produsent", "Det er konkurrent, ikke substitutt."),
                C("b", "Et annet produkt som løser samme behov", "Riktig! Eksempel: hjemmelaget kaffe substituerer kaféen. Samme behov, annen løsning.", correct=True),
                C("c", "Komplementært produkt", "Helt feil — komplementært utfyller, substitutt erstatter."),
                C("d", "Sertifisert produkt", "Helt feil ramme.")],
               "Streaming-tjenester ble substitutt for kabel-TV. Bytte fra én løsning til en annen for samme behov."),
            ex("Effekt", "Hva gjør sterke substitutter?",
               [C("a", "Øker bedriftens marginer", "Tvert imot."),
                C("b", "Setter tak på pris — kunden bytter hvis du blir for dyr", "Riktig! Substitutter er konkurrenter du kanskje ikke ser. Klassisk strategisk blindsone.", correct=True),
                C("c", "Ingen effekt", "Helt feil."),
                C("d", "Eliminerer konkurranse", "Tvert imot — øker konkurransen.")],
               "Kodak ignorerte digital som substitutt for film. Resultat: konkurs."),
            ex("Eksempel", "Hva er substitutt for fly Norge-Spania?",
               [C("a", "Et annet flyselskap", "Det er konkurrent, ikke substitutt."),
                C("b", "Bil/buss/tog/båt", "Riktig! Andre transportformer for samme behov (komme til Spania).", correct=True),
                C("c", "Hotell", "Det er komplementært, ikke substitutt."),
                C("d", "Reiseforsikring", "Komplementært tjeneste.")],
               "Substitutter er ofte 'usynlige konkurrenter'. Tenk bredere enn samme bransje.")]),
        ph("📦", "Leverandørmakt", "Kan leverandørene presse deg?",
           "Leverandørmakt er sterk når: få leverandører, byttekostnader er høye, leverandøren har sterk merkevare. Sterk leverandørmakt = du betaler mer, får dårligere vilkår. Eksempel: Apple har høy leverandørmakt mot tilfeldige tilbehør-produsenter. TINE har sterk makt mot småprodusenter av meieri-produkter.",
           [("STERK NÅR", "Få leverandører, høye byttekostnader, sterk merkevare hos leverandør."),
            ("RESULTAT", "Du betaler mer, får dårligere vilkår, mindre fleksibilitet.")],
           "Hvor sterk er leverandørmakten i bedriften du kjenner? Hvem er nøkkel-leverandører?",
           [ex("Når sterk", "Når er leverandørmakt sterk?",
               [C("a", "Mange leverandører tilgjengelig", "Det gir svak makt."),
                C("b", "Få leverandører med spesifikt produkt og høye byttekostnader", "Riktig! Få alternativer = leverandøren kan diktere vilkår.", correct=True),
                C("c", "Standard varer som finnes overalt", "Det gir svak leverandørmakt."),
                C("d", "Aldri sterk", "Varierer mye.")],
               "Microsoft har historisk sterk leverandørmakt mot bedrifter via Windows. Få alternativer = høye priser."),
            ex("Tine eksempel", "Hvor sterk er TINE som leverandør mot en småbutikk?",
               [C("a", "Svak", "Tvert imot."),
                C("b", "Sterk — TINE dominerer norsk meieri-marked", "Riktig! Småbutikker MÅ ha melk og ost. TINE dikterer vilkår.", correct=True),
                C("c", "Lik som svak konkurrent", "Helt feil."),
                C("d", "Bare lokal", "Nasjonal dominans.")],
               "Derfor er Konkurransetilsynet aktivt med å overvåke TINE — markedsmakt skal ikke misbrukes."),
            ex("Strategisk respons", "Hvordan møte sterk leverandørmakt?",
               [C("a", "Aksepter alle vilkår", "Strategi-feil."),
                C("b", "Diversifiser leverandører, vurder vertikal integrasjon", "Riktig! Reduser avhengighet til én leverandør. Apple lager mange komponenter selv av samme grunn.", correct=True),
                C("c", "Saksøk leverandøren", "Sjelden løsning."),
                C("d", "Slutt å produsere", "Ikke realistisk strategi.")],
               "Klassisk grep: utvikle sekundærleverandører selv om de er litt dyrere. Reduserer risiko.")]),
        ph("👥", "Kundemakt", "Kan kundene presse deg?",
           "Kundemakt er sterk når: få store kunder, lave byttekostnader, gjennomsiktige priser, standardiserte produkter. Eksempel: NorgesGruppen har sterk kundemakt mot småprodusenter. Det offentlige har sterk kundemakt mot leverandører via anbudsprosesser. Sterk kundemakt = du må gi rabatt, bedre vilkår.",
           [("STERK NÅR", "Få store kunder, lave byttekostnader, standardvarer."),
            ("KOMPENSASJON", "Bygg merkevare, lojalitet, eksklusive funksjoner for å redusere kundemakt.")],
           "Hvor sterk er kundemakten der du jobber? Hvem er de største kundene?",
           [ex("Når sterk", "Når er kundemakt sterk?",
               [C("a", "Mange små kunder", "Det er svak kundemakt."),
                C("b", "Få store kunder med lave byttekostnader", "Riktig! Få men store kunder kan diktere vilkår.", correct=True),
                C("c", "Helt nye kunder", "Ikke direkte sammenheng."),
                C("d", "Aldri sterk", "Varierer.")],
               "Apple har sterk kundemakt mot tilfeldige app-utviklere via App Store. 30 % takst er fast."),
            ex("Norsk eksempel", "Hvor sterk er NorgesGruppens kundemakt mot småprodusenter?",
               [C("a", "Svak", "Tvert imot."),
                C("b", "Veldig sterk — 35 % markedsandel + hyllekrav + EMV", "Riktig! Småprodusenter må ha tilgang til kjedene. Kjedene dikterer pris, hyllekrav, betingelser.", correct=True),
                C("c", "Bare i Oslo", "Nasjonal makt."),
                C("d", "Ingen makt", "Helt feil.")],
               "Derfor er det vanskelig å starte ny matprodusent i Norge. Distribusjonsbarrieren er kjedemakt."),
            ex("Hvordan motvirke", "Hvordan kan en bedrift redusere kundemakt?",
               [C("a", "Ignorere kundene", "Strategi-død."),
                C("b", "Bygge sterk merkevare og kundelojalitet", "Riktig! Lojale kunder = lavere bytte-tilbøyelighet = redusert kundemakt.", correct=True),
                C("c", "Heve priser", "Det krever sterk posisjonering først."),
                C("d", "Slutte å selge", "Helt urealistisk.")],
               "Apple-eksempel: brukere er så lojale at de ikke bytter til Samsung. Reduserer kundemakt.")]),
        ph("🗺️", "Strategiske grupper", "Konkurrenter som spiller likt.",
           "Strategiske grupper er bedrifter i samme bransje som følger like strategier. Eksempler i flybransjen: tradisjonelle (SAS, KLM, Lufthansa), lavpris (Ryanair, Wizz, Norwegian), luxury (Emirates, Singapore). De konkurrerer mest INNEN sin gruppe, mindre på tvers.",
           [("LIKE STRATEGIER", "Bedrifter med samme posisjonering, kundetype, prisnivå."),
            ("KONKURRANSE INNEN", "Mest intens konkurranse er innenfor strategisk gruppe.")],
           "Hvilke strategiske grupper finnes i norsk dagligvare? Hva skiller REMA fra Meny?",
           [ex("Hva er det", "Hva er en strategisk gruppe?",
               [C("a", "Tilfeldige bedrifter", "Bedrifter med felles strategi."),
                C("b", "Konkurrenter som følger like strategier — like kundebase, prisnivå", "Riktig! Hjelper med å forstå hvem du faktisk konkurrerer mest med.", correct=True),
                C("c", "Bedrifter i samme by", "Geografisk er ikke strategisk."),
                C("d", "Bedrifter med samme leverandør", "Helt feil ramme.")],
               "Tegn 2D-kart: pris vs kvalitet, eller kundetype vs produktbredde. Bedrifter som klumper seg er én gruppe."),
            ex("Konkurransedynamikk", "Hvor er konkurransen sterkest?",
               [C("a", "På tvers av bransjer", "Sjelden — for ulike."),
                C("b", "Innen samme strategiske gruppe", "Riktig! Norwegian konkurrerer mer mot Ryanair enn mot Emirates.", correct=True),
                C("c", "Tilfeldig", "Strukturert dynamikk."),
                C("d", "Alle mot alle", "Sjelden — strategisk segmentering."),],
               "Identifiser din strategiske gruppe — der er konkurransen mest intens. Andre grupper er sekundære."),
            ex("Norsk eksempel", "I norsk fly: hvilke er Norwegian's strategiske gruppe?",
               [C("a", "SAS — tradisjonell", "Annen gruppe."),
                C("b", "Ryanair og Wizz — lavpris", "Riktig! Norwegian er lavpris-gruppe. Konkurrerer mot Ryanair, ikke SAS-Lufthansa.", correct=True),
                C("c", "Emirates", "Premium-gruppe — annen liga."),
                C("d", "DSB-tog", "Annet transportmiddel.")],
               "Strategisk gruppering er strategisk verktøy. Forskjellig fra ren bransje-tilhørighet.")]),
        ph("🌊", "Bransjeglidning", "Når bransjer smelter sammen.",
           "Bransjeglidning skjer når tradisjonelle bransjegrenser viskes ut. Bank + forsikring (DnB selger forsikring). Telekom + medier (Telenor + TV2). Tech + bil (Apple Car-prosjektet). Skaper både muligheter (nye markeder) og trusler (uventede konkurrenter).",
           [("VISKER GRENSER", "Tradisjonelle bransje-skiller forsvinner."),
            ("OVERRASKELSE", "Konkurrenter dukker opp fra uventede hold.")],
           "Hvilke bransjer i Norge smelter sammen nå? Hvor ser du eksempler på bransjeglidning?",
           [ex("Hva er det", "Hva er bransjeglidning?",
               [C("a", "Bedrifter flytter til utlandet", "Helt feil tolkning."),
                C("b", "Tradisjonelle bransjegrenser viskes ut", "Riktig! Bank + forsikring, telekom + medier, tech + bil. Nye sammensetninger.", correct=True),
                C("c", "Bedrifter krymper", "Helt feil."),
                C("d", "Markedet stagnerer", "Helt feil.")],
               "Apple Pay gjorde Apple til finansaktør. Bransjeglidning fra tech til finans."),
            ex("Driver", "Hva driver bransjeglidning?",
               [C("a", "Tilfeldighet", "Strukturelle drivere."),
                C("b", "Digitalisering, deregulering, teknologi-konvergens", "Riktig! Disse driverne brer seg på tvers av bransjer og skaper nye sammensetninger.", correct=True),
                C("c", "Bare regulering", "Én av flere drivere."),
                C("d", "Mode", "Trend kan være driver, men ikke primær.")],
               "Plattform-økonomi (Uber, Airbnb) glidde tradisjonelle bransjer (taxi, hotell) til tech."),
            ex("Strategisk respons", "Hvordan reagere på bransjeglidning?",
               [C("a", "Ignorere", "Mister markedsmuligheter og overser trusler."),
                C("b", "Overvåke andre bransjer aktivt for trender og trusler", "Riktig! Sett opp 'svakeste signaler'-overvåking. Konkurrenter kan komme fra uventede hold.", correct=True),
                C("c", "Saksøke nykommere", "Sjelden mulig juridisk."),
                C("d", "Bare fortsette som vanlig", "Risikerer å bli disrupted.")],
               "Norske bedrifter må følge med på tech-utviklingen selv om de ikke er tech. Disrupsjon kommer ofte derfra.")]),
        ph("🌍", "Lokal vs global analyse", "Skala betyr alt.",
           "Bransjeanalyse må gjøres på riktig nivå. Lokal kafé konkurrerer ikke med Starbucks globalt — men kanskje med Starbucks-filialen i samme by. Globalt kan TINE være liten, men nasjonalt dominerende. Definer markedsgrensene først — de avgjør hele analysen.",
           [("MARKEDSGRENSER FØRST", "Definer hvem du faktisk konkurrerer med — geografisk og produktmessig."),
            ("SKALA BETYR ALT", "Liten på ett nivå, stor på et annet — sammenheng er kritisk.")],
           "Hva er markedet for en lokal frisør i Bergen? Lokal? Nasjonal? Global?",
           [ex("Hva først", "Hva må gjøres FØRST i bransjeanalyse?",
               [C("a", "Beregne markedsandel", "Krever klare grenser først."),
                C("b", "Definere markedsgrenser — geografi, produkt, kundetype", "Riktig! Uten klare grenser er hele analysen meningsløs. Steg 0.", correct=True),
                C("c", "Søk konkurrent-info", "Krever klare grenser først."),
                C("d", "Skrive konklusjon", "Aldri først.")],
               "Klassisk feil: starte analyse uten å definere markedet. Alt blir gjetning."),
            ex("Lokal eksempel", "En lokal kafé — hvilket marked konkurrerer den i?",
               [C("a", "Globalt kaffemarked", "For bredt."),
                C("b", "Lokalt — kafeer innen ~1 km radius", "Riktig! Kunden velger lokalt. Bredere markedsanalyse er meningsløs for lokal kafé.", correct=True),
                C("c", "Nasjonalt", "For bredt for daglig konkurranse."),
                C("d", "Bare egen butikk", "For smalt — ingen analyse uten konkurrenter.")],
               "Geografisk avgrensning avhenger av kundens kjøpsadferd. Kafé = lokal. Online-handel = nasjonal/global."),
            ex("Skifte nivå", "Når blir nivå-skifte viktig?",
               [C("a", "Aldri", "Kritisk for store bedrifter."),
                C("b", "Når bedriften ekspanderer geografisk eller endrer kundetype", "Riktig! Hver gang markedsgrensene endres må analysen revideres.", correct=True),
                C("c", "Bare hvert 10. år", "For sjelden."),
                C("d", "Kun ved konkurs", "Da er det for sent.")],
               "Når TINE eksporterer til Kina: ny analyse. Andre konkurrenter, andre kundepreferanser, andre regulatoriske krav.")]),
        ph("📋", "Bruk av analysen", "Fra analyse til strategi.",
           "Bransjeanalyse er ikke et mål i seg selv — den er INPUT til strategi. Hvis bransjen er attraktiv (svake krefter): satse mer. Hvis ulønnsom (sterke krefter): vurder å forlate eller posisjonere unikt. Mange selskaper gjør analysen som rituale, men handler ikke på funnene. Det er kasting bort av tid.",
           [("INPUT TIL STRATEGI", "Bransjeanalyse skal føre til strategiske valg, ikke arkiveres."),
            ("HANDLING > ANALYSE", "Beste analyse uten handling er verdiløs.")],
           "Hva ville du gjort hvis bransjeanalyse viste at hovedbransjen din ble strukturelt ulønnsom?",
           [ex("Formål", "Hva er hovedformålet med bransjeanalyse?",
               [C("a", "Pynt i strategidokument", "Aldri godt formål."),
                C("b", "Input til strategiske valg om hvor og hvordan konkurrere", "Riktig! Analyse → handling. Ellers er det bortkastet tid.", correct=True),
                C("c", "Kun for konsulenter", "Verktøy for ledelsen."),
                C("d", "Lovkrav", "Ikke lovpålagt.")],
               "Test: hvilke konkrete handlinger fulgte forrige bransjeanalyse? Hvis ingen — for du gjentakende analyser uten verdi."),
            ex("Strukturelt ulønnsom", "Hva gjør du hvis bransjen er strukturelt ulønnsom?",
               [C("a", "Fortsett som før", "Strategisk dødsfelle."),
                C("b", "Vurder å forlate, eller finn unik posisjonering med høyere marginer", "Riktig! Når kreftene er sterke, må du posisjonere deg utenfor det generiske markedet.", correct=True),
                C("c", "Investerer mer", "Sjelden løsning."),
                C("d", "Saksøke konkurrenter", "Helt urealistisk.")],
               "Klassisk eksempel: aviser. Bransjen ble strukturelt ulønnsom. De som overlevde fant nye forretningsmodeller (digital abonnement)."),
            ex("Frekvens", "Hvor ofte bør bransjeanalyse oppdateres?",
               [C("a", "Aldri", "For sjelden."),
                C("b", "Årlig + ved store endringer", "Riktig! Stabil bransje: årlig review. Disrupsjon: oftere.", correct=True),
                C("c", "Hver dag", "For ofte."),
                C("d", "Hvert 10. år", "For sjelden — verden endrer seg.")],
               "I tek-bransjer kan endringer gjøre analyse foreldet på 6 måneder. Bygg inn periodisk revisjon.")]),
    ],
    ["Du forstår Porters 5 krefter og hvordan hver kraft påvirker bransjens lønnsomhet",
     "Du kan vurdere om en bransje er attraktiv eller strukturelt ulønnsom",
     "Du kjenner forskjellen på rivalisering, nyetablerere, substitutter, leverandørmakt og kundemakt",
     "Du forstår strategiske grupper og bransjeglidning som dynamiske krefter",
     "Du kan koble bransjeanalyse til konkrete strategiske valg om posisjonering"])


LEDER = M("LederensRolle", "ml2", "ML2-04", "Lederens rolle og funksjon", "👤",
    "lederens-rolle", "ml2",
    "Lederens jobb er å få frem det beste i andre — gjøre dem produktive på vei mot felles mål. Skiller seg fra administrasjon (opprettholde) og fagutøvelse (gjøre). God ledelse er broen mellom strategi og resultat.",
    "Studier viser at den enkelte leders innflytelse er én av de største faktorene for ansattes engasjement og produktivitet. 'Folk slutter ikke i bedrifter — de slutter i sjefer.'",
    "Ledelse er ikke en tittel; det er en handling. Den beste lederen er den som folk ikke merker, men som likevel får ting til å fungere — og som folk vil følge når det stormer.",
    [
        ph("🤝", "Ledelse vs administrasjon", "Endring vs opprettholde.",
           "Ledelse skaper endring (visjon, motivasjon, retning). Administrasjon opprettholder eksisterende systemer (planer, regler, budsjett). Begge er nødvendige. Mange lederstillinger har 70 % administrasjon og 30 % ledelse — men det er de 30 % som skiller god leder fra god administrator.",
           [("LEDELSE", "Endring, visjon, motivasjon, retning."),
            ("ADMINISTRASJON", "Opprettholde, planlegge, budsjettere, kontrollere.")],
           "Tenk på en sjef du har hatt. Var hun mest leder eller administrator? Hvilke av delene var sterkest?",
           [ex("Forskjell", "Hva er hovedforskjellen?",
               [C("a", "De er det samme", "Helt feil."),
                C("b", "Ledelse skaper endring; administrasjon opprettholder", "Riktig! Begge nødvendige, men distinkte funksjoner.", correct=True),
                C("c", "Ledelse er for store bedrifter", "Begge brukes i alle størrelser."),
                C("d", "Administrasjon er for offentlig sektor", "Brukes overalt.")],
               "John Kotter: 'Management is about coping with complexity. Leadership is about coping with change.' Klar definisjon."),
            ex("Balansen", "Hva er typisk fordeling for en mellomleder?",
               [C("a", "100 % ledelse", "Urealistisk."),
                C("b", "50/50", "Sjelden — varierer med rolle."),
                C("c", "Mange jobber er 70 % administrasjon, 30 % ledelse — men de 30 % skiller god leder fra god administrator", "Riktig! Realistisk fordeling. Skill mellom oppgaver bevisst.", correct=True),
                C("d", "100 % administrasjon", "Da er det administrator-stilling.")],
               "Spør: hvor mye av tiden bruker jeg på endring/visjon vs. rapportering/møter? Det avgjør om du er leder."),
            ex("Test", "Hvordan teste om du er leder?",
               [C("a", "Stillingstittel", "Tittel sier ingenting om handling."),
                C("b", "Følger folk deg frivillig — selv uten formell makt?", "Riktig! Lederskap måles i påvirkning, ikke posisjon. Hvis folk følger deg uten at de må, er du leder.", correct=True),
                C("c", "Lønnsnivå", "Helt urelevant."),
                C("d", "Antall ansatte", "Ikke definerende.")],
               "Sjekk: når du foreslår noe i et møte, lytter folk? Det er den ekte testen.")]),
        ph("🎭", "Mintzbergs lederroller", "10 roller i 3 kategorier.",
           "Henry Mintzberg identifiserte 10 lederroller: Interpersonale (galionsfigur, leder, kontaktperson), Informasjon (overvåker, sender, talsperson), Beslutning (entreprenør, problemløser, ressursfordeler, forhandler). Lederen veksler mellom rollene gjennom dagen — ofte ubevisst.",
           [("3 KATEGORIER", "Interpersonal, informasjon, beslutning."),
            ("10 ROLLER", "Lederen veksler mellom dem etter situasjon.")],
           "Hvilke av Mintzbergs roller har du sett en sjef gjøre i løpet av en uke?",
           [ex("Antall roller", "Hvor mange lederroller identifiserte Mintzberg?",
               [C("a", "5", "For få."),
                C("b", "10", "Riktig! Klassisk modell fra 1970-tallet, fortsatt aktuelt.", correct=True),
                C("c", "20", "For mange."),
                C("d", "3", "Det er kategoriene.")],
               "Modellen er deskriptiv, ikke preskriptiv. Beskriver hva ledere faktisk gjør, ikke hva de bør gjøre."),
            ex("Kategorier", "Hva er de 3 kategoriene?",
               [C("a", "Strategi, taktikk, operativt", "Helt feil ramme."),
                C("b", "Interpersonale, informasjon, beslutning", "Riktig! Tre dimensjoner av lederarbeid.", correct=True),
                C("c", "Lønn, bonus, karriere", "Helt feil."),
                C("d", "Pris, produkt, plass", "Det er markedsmiks.")],
               "Interpersonale: hvordan lederen relaterer til folk. Informasjon: håndtering av data. Beslutning: valg under usikkerhet."),
            ex("Bruk i praksis", "Hvordan brukes modellen praktisk?",
               [C("a", "Som sjekkliste på roller man faktisk fyller", "Riktig! Bevisstgjøre fordelingen. Mange undervurderer hvor mye tid som går til informasjonsrolle.", correct=True),
                C("b", "Som lønnsmodell", "Helt urelevant."),
                C("c", "Bare for konsulenter", "Bredere bruk."),
                C("d", "Erstatte stillingsbeskrivelser", "Komplementært verktøy.")],
               "Loggfør én uke: hvilke roller fyller du? Avslører gap mellom intensjon og praksis.")]),
        ph("📚", "Fayols funksjoner", "5 klassiske lederfunksjoner.",
           "Henri Fayol (1916) identifiserte 5 lederfunksjoner: Planlegge, Organisere, Lede, Samordne, Kontrollere. Modellen er over 100 år gammel — fortsatt fundament i ledelseslitteratur. Hver funksjon krever ulike ferdigheter.",
           [("5 FUNKSJONER", "Planlegge, organisere, lede, samordne, kontrollere."),
            ("100+ ÅR GAMMEL", "Fortsatt fundament — endringene er i nyanser, ikke struktur.")],
           "Hvilke av Fayols 5 funksjoner gjør en lærer på en skole? Alle 5?",
           [ex("Antall", "Hvor mange funksjoner identifiserte Fayol?",
               [C("a", "3", "For få."),
                C("b", "5", "Riktig! Planlegge, organisere, lede, samordne, kontrollere.", correct=True),
                C("c", "7", "For mange."),
                C("d", "10", "Det er Mintzbergs roller.")],
               "Fayol var ingeniør i fransk gruveselskap — utviklet modellen fra praktisk erfaring. Holder seg fortsatt."),
            ex("Eksempel", "Hva inkluderer 'kontrollere'?",
               [C("a", "Diktere alt", "For autoritært."),
                C("b", "Måle mot mål, identifisere avvik, justere", "Riktig! Kontrollere = oppfølging, ikke micromanagement.", correct=True),
                C("c", "Spionere på ansatte", "Helt feil tolkning."),
                C("d", "Ferie-godkjenninger", "For smalt."),],
               "Kontrollere = closing the loop. Måler du mot mål, kan du justere. Uten måling er ledelse blind."),
            ex("Aktualitet", "Er Fayols modell fortsatt relevant?",
               [C("a", "Nei, helt foreldet", "Tvert imot — fortsatt fundament."),
                C("b", "Ja, fortsatt relevant — endringene er i nyanser, ikke struktur", "Riktig! Funksjonene har samme essens i 1916 som i 2024. Bare verktøyene er nye.", correct=True),
                C("c", "Bare for offentlig sektor", "Brukes overalt."),
                C("d", "Bare for små bedrifter", "Skala-uavhengig.")],
               "Det som har endret seg: hvordan vi planlegger (digitale verktøy), hvordan vi leder (flatere kultur). Funksjonene er like.")]),
        ph("🎚️", "Lederstiler", "Fra autoritær til delegerende.",
           "Klassiske lederstiler: Autoritær (sjefen bestemmer alene), Demokratisk (felles beslutning), Delegerende (ansatte bestemmer selv). Ingen er 'best' — riktig stil avhenger av situasjon. Krise = autoritær. Kreativt arbeid = demokratisk. Erfaren team = delegerende. Beste ledere veksler.",
           [("INGEN ER BEST", "Effekt avhenger av situasjon, oppgave og medarbeider."),
            ("VEKSLE", "Beste ledere bytter stil basert på kontekst — ikke etter komfort.")],
           "Hvilken lederstil har du selv? Når funker den, når funker den ikke?",
           [ex("3 stiler", "Hva er de 3 klassiske stilene?",
               [C("a", "Autoritær, demokratisk, delegerende", "Riktig! Klassisk Lewin-modell. Variasjoner finnes.", correct=True),
                C("b", "Hard, myk, mellomtøff", "Helt feil ramme."),
                C("c", "Kreativ, analytisk, sosial", "Det er personlighetstyper."),
                C("d", "Inntern, ekstern, blandet", "Helt feil.")],
               "Kurt Lewin gjorde de første eksperimentene på lederstiler i 1939. Modellen er klassisk."),
            ex("Krise", "Hvilken stil i akutt krise?",
               [C("a", "Demokratisk", "For tregt."),
                C("b", "Autoritær — rask beslutning, klar kommando", "Riktig! Kriser krever rask handling. Konsensus i krise gir lammet organisasjon.", correct=True),
                C("c", "Delegerende", "For passivt."),
                C("d", "Tilfeldig", "Krise krever struktur.")],
               "Tenk pandemi-respons. Statsministerens autoritære stil i mars 2020 var nødvendig — selv i konsensus-Norge."),
            ex("Kreativitet", "Hvilken stil for kreativt prosjekt?",
               [C("a", "Autoritær", "Kveler kreativitet."),
                C("b", "Demokratisk eller delegerende — gir rom for innspill og initiativ", "Riktig! Kreativitet trenger psykologisk trygghet. Autoritær kveler.", correct=True),
                C("c", "Tilfeldig", "Skadelig for prosess."),
                C("d", "Veksle hver dag", "Skaper forvirring.")],
               "Pixars suksess: ledere skaper ramme, lar kreatører fylle innholdet. Delegerende stil med tydelige mål.")]),
        ph("🎯", "Situasjonsbestemt ledelse", "Tilpass etter medarbeider.",
           "Hersey og Blanchards modell: tilpass lederstil etter medarbeiderens kompetanse OG motivasjon. Ny + motivert = instruere. Erfaren + motivert = delegere. Erfaren + umotivert = støtte. Ny + umotivert = veilede tett. Fire stiler matched til fire medarbeider-tilstander.",
           [("4 STILER", "Instruere, veilede, støtte, delegere."),
            ("KOMPETANSE × MOTIVASJON", "Begge dimensjoner avgjør hvilken stil som passer.")],
           "Tenk på en venn / ansatt du har — hva er deres kompetanse og motivasjon nivå? Hvilken stil passer?",
           [ex("To dimensjoner", "Hva er de 2 hoveddimensjonene?",
               [C("a", "Lønn og bonus", "Helt urelevant."),
                C("b", "Kompetanse og motivasjon", "Riktig! Disse to bestemmer hvilken stil som er optimal.", correct=True),
                C("c", "Alder og erfaring", "Bare delvis riktig."),
                C("d", "Kjønn og personlighet", "Helt urelevant for modellen.")],
               "Spør per medarbeider: kan hun? Vil hun? Svarene styrer stilvalget."),
            ex("Ny + motivert", "Ny ansatt, høy motivasjon — hvilken stil?",
               [C("a", "Delegere — la henne finne ut selv", "Risikabelt — mangler kompetanse."),
                C("b", "Instruere — gi tydelig opplæring", "Riktig! Hun vil, men kan ikke ennå. Trenger struktur og opplæring.", correct=True),
                C("c", "Ignorere", "Helt feil."),
                C("d", "Saksøke", "Helt urelevant.")],
               "Klassisk feil: kaste motiverte nye ansatte ut i dypen 'fordi de er ivrige'. Resultat: feil og frustrasjon."),
            ex("Erfaren + motivert", "Erfaren, høy motivasjon — hvilken stil?",
               [C("a", "Instruere", "Frustrerer henne — hun kan jo."),
                C("b", "Delegere — gi henne ansvar og frihet", "Riktig! Hun kan og vil. Maksimer hennes potensial via autonomi.", correct=True),
                C("c", "Mikromanagere", "Verste alternativ — kveler motivasjon."),
                C("d", "Tett oppfølging", "Unødvendig — hun klarer selv.")],
               "Erfarne folk slutter når de mikromanages. Gi dem rom — de leverer mer.")]),
        ph("🗣️", "Intern kommunikasjon", "Lederen som budbringer.",
           "Lederen er primær kanal for visjon, strategi og endring. Hvis ledelsen ikke kan forklare strategien på 30 sekunder, vil ingen lenger ned i organisasjonen huske den. Forskning viser at folk må høre samme budskap 7+ ganger før det fester seg. Repetisjon er ikke svakhet — det er nødvendig.",
           [("KLARHET KREVES", "Hvis du ikke kan forklare strategien kort, har du ikke klar strategi."),
            ("REPETISJON", "Folk må høre samme budskap 7+ ganger. Ikke vær redd for å gjenta.")],
           "Hva er strategien til bedriften du jobber for / kjenner? Kan du forklare den på 30 sekunder?",
           [ex("Strategi-test", "Hva er beste test for klar strategi?",
               [C("a", "100-siders dokument", "Lengde er motsatt indikator."),
                C("b", "Kan forklares på 30 sekunder", "Riktig! Kort = klar. Lang = uklar.", correct=True),
                C("c", "Bare ledelsen forstår", "Da er den ikke implementerbar."),
                C("d", "Skrevet på engelsk", "Helt urelevant.")],
               "Test: spør tilfeldig ansatt om bedriftens strategi. Hvis svaret varierer, er kommunikasjonen svak."),
            ex("Repetisjon", "Hvor mange ganger må folk høre budskap?",
               [C("a", "1 gang", "For få."),
                C("b", "7+ ganger før det fester seg", "Riktig! Klassisk forskning. Repetisjon er ikke kjedelig — det er nødvendig.", correct=True),
                C("c", "100 ganger", "Overdrevet."),
                C("d", "Bare 2", "For få for varig forankring.")],
               "Politikere vet dette. Samme tale gjentas i 6 måneder før den fester seg. Ledere må gjøre det samme."),
            ex("Hvor", "Hvor bør strategien kommuniseres?",
               [C("a", "Kun toppledermøter", "For smalt."),
                C("b", "Alle nivåer — fra toppmøte til kantine, gjennom flere kanaler", "Riktig! Multi-kanal, multi-nivå. Repetisjon i ulike formater fester budskapet.", correct=True),
                C("c", "Bare i e-post", "For ensformig."),
                C("d", "Aldri", "Da blir den ikke fulgt.")],
               "All-hands møter, avdelingsmøter, 1:1, e-post, intranett, kantine-snakk. Alle kanaler.")]),
        ph("⚖️", "Beslutningsprosesser", "Hvordan ta gode valg under usikkerhet.",
           "Beslutninger varierer fra rasjonelle (analyse, faktagrunnlag) til intuitive (magefølelse, mønsterklare). Erfaring gjør intuisjon mer pålitelig. Beste praksis: rasjonell analyse for store/strategiske valg, intuitiv for hverdagsbeslutninger. RACI-modell hjelper å definere hvem som bestemmer hva.",
           [("RASJONELL vs INTUITIV", "Begge har sin plass. Riktig stil per beslutningstype."),
            ("RACI", "Responsible, Accountable, Consulted, Informed. Klargjør beslutningsmyndighet.")],
           "Tenk på en stor beslutning du har tatt. Var den primært rasjonell eller intuitiv? Var det riktig stil?",
           [ex("Når rasjonell", "Når brukes rasjonell beslutning best?",
               [C("a", "Hver dag", "For tidskrevende for små valg."),
                C("b", "Store, strategiske valg med tid og data tilgjengelig", "Riktig! Når innsatsen er høy og tid finnes, er rasjonell analyse verdifull.", correct=True),
                C("c", "Aldri", "Helt feil."),
                C("d", "Bare i krise", "I krise har du sjelden tid.")],
               "Investeringsbeslutninger > 1 mill kr: alltid rasjonell analyse. Mindre beslutninger: intuisjon kan holde."),
            ex("Erfaring", "Hva gjør intuisjon mer pålitelig?",
               [C("a", "Alder", "Ikke direkte."),
                C("b", "Erfaring — mønstergjenkjenning bygd over år", "Riktig! Erfarne ledere har 'sett dette før' — intuisjon er internalisert kunnskap.", correct=True),
                C("c", "Personlighet", "Mindre relevant."),
                C("d", "Bare flaks", "Helt feil — bygges over tid.")],
               "Brannmenn tar beslutninger på sekunder basert på intuisjon. Det er erfaring komprimert."),
            ex("RACI", "Hva betyr RACI?",
               [C("a", "Tilfeldige bokstaver", "Strukturert modell."),
                C("b", "Responsible, Accountable, Consulted, Informed", "Riktig! Klassisk verktøy for å klargjøre beslutningsmyndighet i komplekse prosjekter.", correct=True),
                C("c", "Recover, Analyze, Create, Improve", "Helt feil definisjon."),
                C("d", "En type lønnsstruktur", "Helt urelevant.")],
               "Hver oppgave: én R, én A, flere C, mange I. Tvinger frem klarhet.")]),
        ph("💎", "Emosjonell intelligens (EQ)", "Viktigere enn IQ for ledelse.",
           "Daniel Goleman: 5 komponenter — selvbevissthet, selvkontroll, motivasjon, empati, sosiale ferdigheter. Forskning viser at EQ er viktigere enn IQ for lederprestasjon. Ledere uten EQ blir teknisk dyktige, men skaper toxic kultur. EQ kan trenes — er ikke statisk.",
           [("5 KOMPONENTER", "Selvbevissthet, selvkontroll, motivasjon, empati, sosiale ferdigheter."),
            ("EQ > IQ", "For ledelse, ikke for teknisk fagarbeid.")],
           "Hvilke av Golemans 5 EQ-komponenter er din sterkeste? Hvilken bør du trene mest?",
           [ex("Antall komponenter", "Hvor mange?",
               [C("a", "3", "For få."),
                C("b", "5", "Riktig! Selvbevissthet, selvkontroll, motivasjon, empati, sosiale ferdigheter.", correct=True),
                C("c", "10", "For mange."),
                C("d", "Bare empati", "For smalt.")],
               "Goleman publiserte 'Emotional Intelligence' i 1995. Boken endret moderne ledelseslitteratur."),
            ex("EQ vs IQ", "Hva er viktigere for ledelse?",
               [C("a", "IQ alene", "Ofte teknisk dyktig, dårlig leder."),
                C("b", "EQ — emosjonell intelligens — er konsistent rangert som viktigere", "Riktig! Forskning støtter dette. IQ får deg ansatt; EQ får deg promotert.", correct=True),
                C("c", "Like viktig", "EQ skiller seg ut i ledelse."),
                C("d", "Ingen forskjell", "Helt feil.")],
               "Smarte ingeniører som blir ledere uten EQ skaper ofte toxic team. Ferdigheter ≠ ledelse."),
            ex("Trening", "Kan EQ trenes?",
               [C("a", "Nei — du er født med det", "Helt feil — kan trenes hele livet."),
                C("b", "Ja — alle 5 komponentene kan utvikles", "Riktig! Selvbevissthet er startpunkt. Refleksjon, feedback, coaching hjelper.", correct=True),
                C("c", "Bare i ungdom", "Trene-kapasitet vedvarer."),
                C("d", "Bare for kvinner", "Helt urelevant.")],
               "Begin med selvbevissthet: hvordan reagerer jeg på stress? Hvordan oppfattes jeg? Mest grunnleggende ferdighet å bygge på.")]),
        ph("🚀", "Endringsledelse", "Lede gjennom endring.",
           "Endring er konstant. John Kotters 8-stegs-modell: 1) Skap nødfølelse, 2) Bygg ledende koalisjon, 3) Visjon, 4) Kommuniser, 5) Fjern hindringer, 6) Feire seire underveis, 7) Forankre, 8) Befest i kultur. 70 % av endringsprogrammer mislykkes — typisk på kommunikasjon og forankring.",
           [("8 STEG", "Kotters klassiske modell. Hopper du steg, mislykkes ofte."),
            ("70 % MISLYKKES", "Kommunikasjon og forankring er vanligste svake punkt.")],
           "Hvilken stor endring i livet ditt har du opplevd? Var Kotters steg fulgt?",
           [ex("Antall steg", "Hvor mange steg har Kotter?",
               [C("a", "3", "For få."),
                C("b", "8", "Riktig! Klassisk endringsmodell. Hver steg bygger på forrige.", correct=True),
                C("c", "12", "For mange."),
                C("d", "Bare 1", "For lite.")],
               "Kotter publiserte modellen i 1995 etter studier av 100+ endringsprogrammer. Fortsatt dominerende."),
            ex("Første steg", "Hva er første steg?",
               [C("a", "Implementere ny teknologi", "Senere steg."),
                C("b", "Skape nødfølelse — vise hvorfor endring er nødvendig", "Riktig! Uten følt behov motsetter folk endring. Skap forståelse for hvorfor først.", correct=True),
                C("c", "Skrive ny strategi", "Senere."),
                C("d", "Endre organisasjonskart", "Senere.")],
               "Mange ledere starter med strukturendring. Det blir møtt med motstand fordi folk ikke forstår hvorfor."),
            ex("Hovedsvakhet", "Hvor svikter endring oftest?",
               [C("a", "For dyrt", "Sjelden hovedårsak."),
                C("b", "Dårlig kommunikasjon og manglende forankring", "Riktig! Mest vanlige svake punkt. Strategi som ikke når ut, blir ikke implementert.", correct=True),
                C("c", "For mange møter", "Symptom."),
                C("d", "Endring fungerer alltid", "Helt feil.")],
               "Bruk minst halvparten av endringsbudsjettet på kommunikasjon. Mange bruker 90 % på prosess.")]),
    ],
    ["Du forstår forskjellen på ledelse (endring) og administrasjon (opprettholde)",
     "Du kjenner Mintzbergs 10 lederroller og Fayols 5 funksjoner",
     "Du kan velge riktig lederstil etter situasjon — særlig situasjonsbestemt ledelse",
     "Du forstår at EQ er viktigere enn IQ for ledelse, og at den kan trenes",
     "Du kjenner Kotters endringsmodell og hvorfor 70 % av endringsprogrammer mislykkes"])


SAMFUNN = M("SamfunnsansvarBaerekraftOmdomme", "ml2", "ML2-05", "Samfunnsansvar, bærekraft og omdømme", "🌱",
    "samfunnsansvar-baerekraft-omdomme", "ml2",
    "Bedriftens rolle har endret seg fra ren profitt-jakt til bredere samfunnsansvar. Triple Bottom Line, FNs bærekraftsmål og ESG-investering presser bedrifter mot ansvarlig drift. Ikke kun etisk — også strategisk konkurransefortrinn.",
    "ESG-investerte midler globalt har vokst til over 30 trillion USD. Bedrifter med dårlig ESG-score får dyrere finansiering. Bærekraft har blitt finansiell konkurranseparameter, ikke bare etisk.",
    "Samfunnsansvar er ikke kostnad — det er investering i langsiktig overlevelse. Bedrifter uten ESG-strategi taper investorer, kunder og talenter. Tre store grupper, alle viktige.",
    [
        ph("⚖️", "Triple Bottom Line", "Profit + People + Planet.",
           "Måle suksess på tre dimensjoner: økonomi (Profit), sosial nytte (People), miljø (Planet). Tradisjonelt regnskap måler bare Profit. Moderne bedrifter rapporterer på alle tre. EUs CSRD (Corporate Sustainability Reporting Directive) gjør trippelt rapportering lovpålagt for store bedrifter fra 2024.",
           [("3 DIMENSJONER", "Profit, People, Planet — alle måles."),
            ("CSRD-LOVKRAV", "EU-direktiv gjør bærekraftsrapportering lovpålagt for større bedrifter.")],
           "Hva tror du er din egen 'Triple Bottom Line'? Hva måler du selv på de tre dimensjonene?",
           [ex("3 P-er", "Hva står Triple Bottom Line for?",
               [C("a", "Penger, posisjon, prestige", "Helt feil tolkning."),
                C("b", "Profit, People, Planet", "Riktig! Tre bunnlinjer i bærekrafts-regnskap.", correct=True),
                C("c", "Pris, produkt, plass", "Det er markedsmiks."),
                C("d", "Plan, prosess, prestasjon", "Helt feil.")],
               "Begrepet ble populært etter John Elkingtons bok i 1997. Endret hvordan bedrifter måler seg selv."),
            ex("Lovkrav", "Er TBL bare frivillig?",
               [C("a", "Ja, alltid frivillig", "Helt feil — lover endrer seg."),
                C("b", "Nei — EUs CSRD gjør det lovpålagt for store bedrifter fra 2024", "Riktig! Bærekraft er nå lovpålagt rapportering for de fleste mellomstore-store bedrifter.", correct=True),
                C("c", "Bare for offentlige", "Privat sektor like rammet."),
                C("d", "Bare i USA", "Nei — EU-direktiv først.")],
               "CSRD-rapportering: ~50 000 europeiske bedrifter rammes. Ekstern revisjon kreves."),
            ex("Hvorfor", "Hvorfor måle på 3 dimensjoner?",
               [C("a", "Politisk korrekthet", "For overflatisk."),
                C("b", "Bedrifter påvirker miljø og samfunn — tradisjonelt regnskap skjuler kostnadene", "Riktig! Eksterne effekter (forurensning, sosial skade) inkluderes ikke i tradisjonelt regnskap. TBL korrigerer.", correct=True),
                C("c", "Bare for reklame", "Sekundært."),
                C("d", "Krever færre revisorer", "Tvert imot.")],
               "Klima er den største 'gratisressursen' bedrifter har historisk konsumert. TBL gjør den synlig.")]),
        ph("🤝", "Interessentanalyse", "Hvem påvirker oss, hvem påvirker vi?",
           "Interessenter (stakeholders) er alle som påvirker eller blir påvirket av bedriften: eiere, ansatte, kunder, leverandører, lokalsamfunn, miljø, myndigheter. Kartlegg dem på 2D-matrise: makt × interesse. Høy makt + høy interesse = nøkkel-interessenter — kommuniser tett.",
           [("ALLE", "Eiere, ansatte, kunder, leverandører, lokalsamfunn, miljø, myndigheter."),
            ("MAKT × INTERESSE", "Strukturert prioritering basert på påvirkning og engasjement.")],
           "Liste opp alle interessenter for bedriften du jobber for / kjenner. Hvem har høyest makt + interesse?",
           [ex("Definisjon", "Hva er en interessent?",
               [C("a", "Bare eiere", "For smalt."),
                C("b", "Alle som påvirker eller blir påvirket av bedriften", "Riktig! Bredt konsept — fra eiere til lokalsamfunn til miljø.", correct=True),
                C("c", "Bare kunder", "For smalt."),
                C("d", "Bare ansatte", "For smalt.")],
               "Klassisk skifte fra 'shareholder'-tenkning (kun eiere) til 'stakeholder'-tenkning (alle berørte)."),
            ex("Makt-interesse", "Hvilke får mest oppmerksomhet?",
               [C("a", "Tilfeldige", "Strukturert prioritering."),
                C("b", "Høy makt + høy interesse — nøkkel-interessenter", "Riktig! Kommuniser tett. Avgjør ofte bedriftens skjebne.", correct=True),
                C("c", "Lav makt + lav interesse", "Behov minimal oppmerksomhet."),
                C("d", "Bare myndigheter", "Sjelden eneste høyt prioritert.")],
               "Tegn matrisen: makt på x-akse, interesse på y-akse. Plot interessenter. Øvre høyre = nøkkel."),
            ex("Norsk eksempel", "Hvem er typisk nøkkel-interessenter for Equinor?",
               [C("a", "Bare aksjonærer", "For smalt for stort selskap."),
                C("b", "Den norske stat (eier 67 %), miljøorganisasjoner, ansatte, lokalsamfunn", "Riktig! Multi-stakeholder-bilde. Hver har stor makt og interesse.", correct=True),
                C("c", "Tilfeldige forbrukere", "Indirekte."),
                C("d", "Konkurrenter", "Konkurrenter er ikke interessenter, men kontekst.")],
               "For statlig kontrollerte selskaper er staten alltid nøkkel-interessent — politikk påvirker strategi.")]),
        ph("🌍", "FNs bærekraftsmål", "17 mål, 2030.",
           "FN vedtok i 2015 17 bærekraftsmål med 169 delmål. Globalt rammeverk for bærekraftig utvikling innen 2030. Bedrifter velger ut 2-4 mål som er mest relevante — ikke alle 17 (det blir uforpliktende). Equinor: mål 7 (energi) og 13 (klima). Tomra: mål 12 (ansvarlig forbruk).",
           [("17 MÅL", "Globalt rammeverk innen 2030."),
            ("VELG 2-4", "Fokuser på det dere faktisk kan påvirke vesentlig.")],
           "Hvilke 2-3 av FNs 17 bærekraftsmål kan en lokal bedrift du kjenner faktisk påvirke vesentlig?",
           [ex("Antall mål", "Hvor mange bærekraftsmål?",
               [C("a", "10", "For få."),
                C("b", "17 — vedtatt av FN i 2015", "Riktig! 17 mål med 169 delmål. Globalt rammeverk innen 2030.", correct=True),
                C("c", "20", "For mange."),
                C("d", "30", "Helt feil.")],
               "Norge har eget koordineringsorgan for SDGs. Stortinget rapporterer årlig på fremgang."),
            ex("Strategi", "Hvor mange mål bør en bedrift velge?",
               [C("a", "Alle 17", "For uforpliktende — kan ikke fokusere på alt."),
                C("b", "2-4 som dere faktisk kan påvirke vesentlig", "Riktig! Fokus gir resultater. Spre ressurser tynt = ingen effekt.", correct=True),
                C("c", "Bare 1", "For smalt."),
                C("d", "Tilfeldig antall", "Strukturert valg er bedre.")],
               "Test: hvilke mål kan dere måle dere selv på? Hvis svaret er 'ingen', velg andre."),
            ex("Norsk eksempel", "Hvilke mål passer Tomra?",
               [C("a", "Mål 12 — ansvarlig forbruk og produksjon (sirkulær økonomi)", "Riktig! Tomras kjernevirksomhet er resirkulering. Direkte kobling til mål 12.", correct=True),
                C("b", "Mål 4 — utdanning", "Sekundært."),
                C("c", "Mål 16 — institusjoner", "Mindre direkte."),
                C("d", "Tilfeldige", "Ikke strategisk valg.")],
               "Velg mål som er kjerne i forretningsmodellen. Da blir bærekraft strategisk, ikke pynt.")]),
        ph("💼", "CSR (Corporate Social Responsibility)", "Frivillig samfunnsbidrag.",
           "CSR er bedriftens frivillige bidrag — utover lovkrav. Investering i lokalsamfunn, etiske leverandørkjeder, miljøtiltak utover minimum. Drevet av forventninger fra kunder (særlig yngre), ansatte (rekrutteringsfortrinn), investorer (ESG-fond). Ikke alltid lønnsomt på kort sikt, men bygger merkevare langsiktig.",
           [("FRIVILLIG", "Utover lovkrav. Strategisk valg, ikke compliance."),
            ("FLERSIDIG VINNING", "Lojalere kunder, bedre rekruttering, lavere risiko, tilgang til ESG-kapital.")],
           "Hvilke bedrifter har du sett bygge konkurransefortrinn rundt CSR? Hva gjør de annerledes?",
           [ex("Definisjon", "Hva er CSR?",
               [C("a", "Lovkrav om miljø", "Frivillig — utover lovkrav."),
                C("b", "Frivillig samfunnsbidrag utover lovkrav", "Riktig! Skiller seg fra compliance ved at det er valgfritt — men strategisk viktig.", correct=True),
                C("c", "Bare donasjoner", "Bredere — inkluderer ansatte, leverandører, miljø."),
                C("d", "Reklame", "Ikke CSR — selv om CSR brukes i reklame.")],
               "CSR er ikke marketing — men resultatet er ofte bedre marketing. Forskjellen ligger i intensjon og varighet."),
            ex("Drivere", "Hvem driver CSR-engasjement?",
               [C("a", "Bare myndigheter", "Bredere driver-base."),
                C("b", "Kunder (særlig yngre), ansatte, investorer, lovverk", "Riktig! Multi-stakeholder-press. Yngre generasjoner er sterkest driver.", correct=True),
                C("c", "Bare kunder", "For smalt."),
                C("d", "Tilfeldighet", "Strukturelle drivere.")],
               "Yngre forbrukere prioriterer CSR. Det er strategisk hvis du vil vinne dem."),
            ex("Stormberg", "Hva er Stormbergs CSR-strategi?",
               [C("a", "Bare donasjoner", "De gjør mer."),
                C("b", "Ansetter folk med hull i CV-en, åpenhet om kostnader, miljøvennlige produkter", "Riktig! Ekte og konkret. Bygger merkevare på sosial profil.", correct=True),
                C("c", "Ingen CSR", "Helt feil."),
                C("d", "Kun på papir", "Stormberg er kjent for handlinger.")],
               "Verdibasert differensiering er vanskelig å kopiere. Konkurrenter kan matche pris/kvalitet, ikke autentiske verdier på et øyeblikk.")]),
        ph("🏆", "Omdømme", "Kapitalen vi ikke eier.",
           "Omdømme er kapitalen vi ikke eier, men forvalter. Bygges over år gjennom konsistent oppførsel — kan ødelegges på minutter ved skandale. Tillit er fundamentet. Reputation Institute måler bedrifters omdømme årlig. Sterkt omdømme: høyere prising-makt, lojal kundebase, lettere rekruttering, motstandskraft mot kriser.",
           [("YEARS TO BUILD", "Omdømme tar år å bygge, kan ødelegges på dager."),
            ("VERDI", "Sterkt omdømme = pricing-makt + lojalitet + rekrutterings-fortrinn.")],
           "Hvilke norske bedrifter har sterkt omdømme? Hvilke har dårlig?",
           [ex("Tidsperspektiv", "Hvor lang tid tar å bygge sterkt omdømme?",
               [C("a", "Måneder", "For kort."),
                C("b", "År — konsistent positiv oppførsel over tid", "Riktig! Omdømme er resultat av tusenvis av små handlinger over år.", correct=True),
                C("c", "Bare uker", "Helt urealistisk."),
                C("d", "Generasjoner", "Overdrevet."),],
               "Patagonias omdømme bygd over 50 år. Ferd med å være uovertruffent i klesbransjen."),
            ex("Tap", "Hvor raskt kan omdømme tapes?",
               [C("a", "Aldri tapt", "Tvert imot — kan tapes raskt."),
                C("b", "På dager — én skandale kan ødelegge årevis med arbeid", "Riktig! Volkswagen Dieselgate ødela årevis med merkebygging på uker.", correct=True),
                C("c", "Bare etter mange år", "For tregt — sosiale medier akselererer."),
                C("d", "Aldri raskt", "Helt feil.")],
               "Sosiale medier har dramatisk akselerert omdømme-tap. Krise-kommunikasjon er kritisk."),
            ex("Verdi", "Hva gir sterkt omdømme?",
               [C("a", "Bare bedre reklame", "For smalt."),
                C("b", "Pricing-makt, lojalitet, rekruttering, krise-motstand", "Riktig! Bredt strategisk verdi. Apple kan ta 30 % premium fordi merkevaren er sterk.", correct=True),
                C("c", "Lavere skatt", "Ikke direkte."),
                C("d", "Tilfeldig", "Strukturell verdi.")],
               "Reputation = future cashflow. Investorer betaler premium for sterke merkevarer.")]),
        ph("🌿", "Grønnvasking", "Lyver om miljøgevinst.",
           "Grønnvasking (greenwashing) er bruk av vage eller udokumenterte miljøpåstander for å virke mer bærekraftig enn man er. Forbrukertilsynet slår hardt ned. SAS, Statkraft, flyselskaper har fått pålegg om å fjerne 'klimanøytral'-påstander uten dokumentasjon. EUs Green Claims-direktiv (2024) skjerper kravene. Spesifikke, dokumenterte påstander er kravet.",
           [("FORBUDT", "Markedsføringsloven § 7. Forbrukertilsynet håndhever aktivt."),
            ("BLI SPESIFIKK", "'25 % redusert utslipp 2019-2023, verifisert av PwC' > 'miljøvennlig'.")],
           "Hvilke 'grønne' reklamer ville du undersøkt nærmere som tilsynsperson?",
           [ex("Hva er det", "Hva er grønnvasking?",
               [C("a", "Vaske miljøvennlig", "Bokstavelig — feil tolkning."),
                C("b", "Lyve eller bruke vage påstander om miljøprofil", "Riktig! Villedning om miljøgevinster. Forbudt under markedsføringsloven.", correct=True),
                C("c", "Sertifisering som økologisk", "Reell merking, ikke grønnvasking."),
                C("d", "Reduksjon av energibruk", "Det er bra praksis."),],
               "Forbrukertilsynet har konkret saksbehandling. Sjekk forbrukertilsynet.no for eksempler."),
            ex("Akseptabel påstand", "Hvilken er akseptabel?",
               [C("a", "'Vi er en grønn bedrift'", "Vag — ingen dokumentasjon."),
                C("b", "'Vi reduserte CO2-utslipp 23 % fra 2019 til 2023, verifisert av PwC'", "Riktig! Spesifikk, målbar, tidsbestemt, uavhengig verifisert. Standard for akseptabelt.", correct=True),
                C("c", "'Klimanøytral' uten kontekst", "Forbrukertilsynet har slått ned på dette."),
                C("d", "'Bærekraftig'", "Tomt buzzword."),],
               "Generell regel: spesifikt, dokumentert, verifiserbart. Ellers er det grønnvasking."),
            ex("Sanksjon", "Hva kan grønnvasking koste?",
               [C("a", "Bare advarsel", "Mer alvorlig."),
                C("b", "Pålegg om endring + bot opp til 4 % av omsetning + omdømmetap", "Riktig! Både juridiske sanksjoner og markedsmessig skade. Forbrukere boikotter ofte.", correct=True),
                C("c", "Ingenting", "Helt feil."),
                C("d", "Fengsel for daglig leder", "Sjelden direkte."),],
               "Patagonia bruker autentisk bærekraft som konkurransefortrinn. Konkurrenter kan ikke kopiere ekte data.")]),
        ph("🔄", "Sirkulær økonomi", "Fra bruk-og-kast til gjenbruk.",
           "Sirkulær økonomi: designe produkter for gjenbruk, reparasjon og resirkulering. Motstykke til 'lineær' økonomi (kjøp-bruk-kast). Eksempler: Patagonia reparerer klær gratis. Apple resirkulerer iPhones. Vestre møbler designet for å vare 50+ år. Tomras pant-system. Strategisk fortrinn + miljøgevinst.",
           [("DESIGN FOR GJENBRUK", "Reparasjon, resirkulering, tilbakeleveringsordninger fra start."),
            ("FORRETNINGSMODELL", "Kan være kjerneforretning, ikke bare bærekraftstiltak.")],
           "Hvilke produkter rundt deg er designet sirkulært? Hvilke er åpenbart lineære?",
           [ex("Hva er det", "Hva kjennetegner sirkulær økonomi?",
               [C("a", "Bedrifter som vokser raskt", "Helt feil."),
                C("b", "Designe for gjenbruk, reparasjon, resirkulering", "Riktig! Motstykke til lineær 'kjøp-bruk-kast'. Krav til hele produktdesignet.", correct=True),
                C("c", "Bare resirkulering på slutten", "For sent — design er nøkkelen."),
                C("d", "Kun for klær", "Brukes i alle bransjer."),],
               "Tre prinsipper: designe ut avfall, holde produkter og materialer i bruk, regenerere naturlige systemer."),
            ex("Norsk eksempel", "Hvilket norsk selskap er ledende?",
               [C("a", "REMA 1000 — billig og raskt", "Lineær modell."),
                C("b", "Tomra — pant-systemer som holder materialer i bruk", "Riktig! Kjernevirksomhet er sirkulær økonomi. Globalt ledende.", correct=True),
                C("c", "Statkraft — bare strøm", "Energi, ikke direkte sirkulær."),
                C("d", "Bare utenlandske selskaper", "Helt feil — Norge er sterkt."),],
               "Tomra er et av verdens mest verdifulle bærekraftsselskaper på Oslo Børs."),
            ex("Strategi", "Er sirkulær kun bærekraft, eller også business?",
               [C("a", "Kun bærekraft, koster penger", "For begrenset syn."),
                C("b", "Begge — kan være kjerneforretning som gir konkurransefortrinn", "Riktig! Patagonia, Tomra og IKEA bruker sirkularitet som strategi, ikke bare etikk.", correct=True),
                C("c", "Kun reklame", "For smalt."),
                C("d", "Bare for store", "Brukes i alle størrelser."),],
               "Patagonia 'Worn Wear' (brukt-handel) gir både inntekt og merkebygging. Sirkulær = strategi.")]),
        ph("🤝", "Etisk handel", "Ansvar for hele verdikjeden.",
           "Åpenhetsloven (2022) krever dokumentasjon av menneskerettigheter og arbeidsforhold i hele leverandørkjeden. Bedrifter med 50+ ansatte rammes. Forbrukere kan be om innsyn — bedriften svarer innen 3 uker. Skandaler i leverandørkjeden (H&M, Zara i Bangladesh) skaper omdømmeskade. Etisk handel er strategisk forsvar.",
           [("HELE KJEDEN", "Ikke bare egen bedrift — også underleverandører."),
            ("ÅPENHETSLOVEN", "Lovpålagt fra 2022 for bedrifter med 50+ ansatte.")],
           "Sjekk en favorittklesmerke — kan du finne hvor produkter er laget? Hva sier det om etisk handel?",
           [ex("Åpenhetsloven", "Hva krever Åpenhetsloven?",
               [C("a", "Bare regnskap", "For smalt."),
                C("b", "Dokumentasjon av menneskerettigheter og arbeidsforhold i leverandørkjeden", "Riktig! Aktsomhetsvurderinger i hele kjeden. Innsynsrett for forbrukere.", correct=True),
                C("c", "Antall ansatte", "Helt urelevant."),
                C("d", "Bare miljørapportering", "For smalt — også sosiale forhold."),],
               "Norge var blant første land med slik lov. EU følger etter med Corporate Sustainability Due Diligence Directive."),
            ex("Hvem omfattes", "Hvilke bedrifter må følge Åpenhetsloven?",
               [C("a", "Alle bedrifter", "For bredt."),
                C("b", "Bedrifter med 50+ ansatte (eller omsetning > 70 mill, balansesum > 35 mill)", "Riktig! Mellomstore og store. Små unntatt.", correct=True),
                C("c", "Bare børsnoterte", "Bredere."),
                C("d", "Bare statlige", "Privat sektor primært."),],
               "Sjekk om din arbeidsplass er omfattet. Aktsomhetsvurderinger er omfattende prosess."),
            ex("Innsyn", "Hva må bedriften gjøre når forbruker krever innsyn?",
               [C("a", "Ignorere", "Klart feil."),
                C("b", "Svare innen 3 uker med relevant info", "Riktig! Lovfestet rett. Du må ha dokumentasjon klar.", correct=True),
                C("c", "Saksøke forbrukeren", "Helt feil."),
                C("d", "Bare hvis avis spør", "Loven gjelder alle borgere."),],
               "Lag standardprosess for innsynskrav. Du har 3 uker, ikke vent til kravet kommer.")]),
        ph("📊", "ESG-rapportering", "Environmental, Social, Governance.",
           "ESG (Environmental, Social, Governance) er investorenes vurderingskriterier. ESG-fond har vokst til over 30 trillion USD globalt. Bedrifter med dårlig ESG-score får dyrere finansiering. CSRD-direktivet i EU gjør ESG-rapportering lovpålagt. Tre dimensjoner: Miljø (klima, ressursbruk), Sosialt (ansatte, leverandører, samfunn), Styring (etikk, ledelse, transparens).",
           [("ESG = INVESTOR-KRAV", "Strenge investorer ser kun på ESG-kompatible selskaper."),
            ("CSRD-LOVKRAV", "EU-direktiv gjør ESG-rapportering obligatorisk for store bedrifter.")],
           "Sjekk en bedrifts årsrapport — hvor mye fokus på ESG vs ren økonomi? Endring over år?",
           [ex("Hva er ESG", "Hva betyr ESG?",
               [C("a", "European Securities Group", "Helt feil."),
                C("b", "Environmental, Social, Governance — investorers vurderingskriterier", "Riktig! Tre dimensjoner. Brukes for å vurdere bedrifters ansvarlighet.", correct=True),
                C("c", "Earnings, Salary, Growth", "Helt feil."),
                C("d", "Type regnskap", "ESG er bredere."),],
               "ESG-fondene har vokst eksplosivt. Bedrifter som ikke skårer godt får dyrere finansiering."),
            ex("Effekt", "Hva skjer med dårlige ESG-bedrifter?",
               [C("a", "Ingenting", "Tvert imot — strukturelle effekter."),
                C("b", "Dyrere finansiering, kapitalflukt, lavere børsverdi", "Riktig! ESG-fond ekskluderer dem. Bankene priser inn risiko. Markedet straffer.", correct=True),
                C("c", "Lavere skatt", "Tvert imot — ofte høyere skatt."),
                C("d", "Bedre omdømme", "Helt feil — dårligere."),],
               "BlackRock og andre store kapitaleier truer å trekke kapital fra ESG-svake selskaper. Reell konsekvens."),
            ex("Norge", "Hvordan står Norge med ESG?",
               [C("a", "Bak resten av Europa", "Tvert imot."),
                C("b", "I front — Oljefondet ekskluderer selskaper, sterke ESG-krav", "Riktig! Oljefondet (verdens største) har egne ESG-krav. Også norske finansinstitusjoner.", correct=True),
                C("c", "Likegyldig", "Norge er ledende."),
                C("d", "Ingen rolle", "Helt feil."),],
               "Oljefondets ekskluderingsliste sender sjokkbølger globalt. Når Norge ekskluderer, følger andre.")]),
        ph("🏆", "Strategisk bærekraft", "Konkurransefortrinn, ikke kostnad.",
           "Bærekraft er ikke lenger 'kostnad' eller 'risikohåndtering' — det er strategisk konkurransefortrinn. Bedrifter som integrerer bærekraft i kjerneforretningen vinner: lavere kapitalkostnad, sterkere merkevare, bedre rekruttering, høyere kundepriser. Eksempler: Patagonia, Tomra, IKEA, Equinor (i overgangen).",
           [("KONKURRANSEFORTRINN", "Ikke bare etikk — strategisk fordel."),
            ("INTEGRERT", "Må være del av kjerneforretningen, ikke et tilleggsprosjekt.")],
           "Hvordan kan din bedrift gjøre bærekraft til konkurransefortrinn? Hva er allerede integrert?",
           [ex("Hva endret", "Hvordan ser man på bærekraft nå vs før?",
               [C("a", "Bare kostnad", "Gammel tenkning."),
                C("b", "Strategisk konkurransefortrinn — gir lavere kapitalkostnad, sterkere merkevare, bedre rekruttering", "Riktig! Modern tenkning. Investorer, kunder, ansatte krever det.", correct=True),
                C("c", "Bare risikohåndtering", "For smalt."),
                C("d", "Bare for offentlige", "Privat sektor like rammet."),],
               "Den som ikke ser bærekraft som strategi, taper kapital, talenter og kunder. Strukturelt skifte."),
            ex("Patagonia", "Hva er Patagonias strategiske bærekraft?",
               [C("a", "Bare donasjoner", "De gjør mye mer."),
                C("b", "Hele forretningsmodellen er bygget på reparasjon, gjenbruk, ærlighet", "Riktig! 'Don't buy this jacket'-kampanjen. Sirkulær økonomi som forretningsmodell.", correct=True),
                C("c", "Bare reklame", "Ekte handlinger."),
                C("d", "Ingen strategi", "Helt feil."),],
               "Yvon Chouinard ga bort hele Patagonia (3 mrd USD) til miljøstiftelse i 2022. 'Earth is now our only shareholder.'"),
            ex("Måling", "Hvordan måler man strategisk bærekraft?",
               [C("a", "Kun gjennom hyggelige ord", "Fluffy."),
                C("b", "ESG-score + finansielle resultater + merkevareverdi over tid", "Riktig! Multi-dimensjonal måling. Trippel bunnlinje i praksis.", correct=True),
                C("c", "Ikke målbart", "Mye er målbart."),
                C("d", "Kun klimagassutslipp", "For smalt."),],
               "Triple Bottom Line-rapporter blir mer sofistikerte hver år. CSRD krever standardiserte målinger.")]),
    ],
    ["Du forstår Triple Bottom Line og at lovpålagt rapportering kommer via CSRD",
     "Du kan gjennomføre interessentanalyse og prioritere på makt × interesse",
     "Du kjenner FNs 17 bærekraftsmål og hvorfor bedrifter velger 2-4 strategiske mål",
     "Du forstår grønnvasking og strenge norske krav til miljøpåstander",
     "Du ser bærekraft som konkurransefortrinn — ikke kostnad — drevet av ESG-investorer"])


import sys
g.write_modules([VISJON, BRANSJE, LEDER, SAMFUNN], "BATCH B — ML2 (4 moduler)")
