#!/usr/bin/env python3
"""ML2-11 Kommunikasjonsstrategier."""
import importlib.util
from pathlib import Path
spec = importlib.util.spec_from_file_location("g", Path(__file__).parent / ".gen-shared.py")
g = importlib.util.module_from_spec(spec); spec.loader.exec_module(g)
C, ph, ex, M = g.C, g.ph, g.ex, g.M


KOMM = M("Kommunikasjonsstrategier", "ml2", "ML2-11", "Kommunikasjonsstrategier", "📣",
    "kommunikasjonsstrategier", "ml2",
    "Integrert markedskommunikasjon (IMC) — én stemme utad gjennom alle kanaler. Strategisk kommunikasjon binder sammen reklame, PR, salg, sosiale medier og innhold til ett konsistent budskap som bygger merkevare over tid.",
    "Telenor har holdt julekampanje-stilen konsistent i over 10 år. Forbrukerne forventer kampanjen — det er en kulturell hendelse. Konsistens over tid bygger 'mental hylleplassering'.",
    "Kommunikasjon uten strategi er bare støy. Strategisk kommunikasjon koordinerer alle kanaler mot felles mål — bygger merkevare som tåler kriser.",
    [
        ph("📣", "IMC — Integrert markedskommunikasjon",
           "Én stemme utad gjennom alle kanaler.",
           "IMC betyr at alle kommunikasjonskanaler — reklame, PR, salg, sosiale medier, kundeservice, intern kommunikasjon — leverer samme kjernebudskap. Konsistens bygger merkevare; sprik forvirrer kunden. Krever sentral merkestyring og klar visuell identitet.",
           [("KONSISTENS", "Samme budskap, tone og visuell identitet uansett kanal."),
            ("KOORDINERING", "Sentralt brand-team koordinerer på tvers av avdelinger.")],
           "Velg en bedrift du kjenner. Er kommunikasjonen konsistent på tvers av Instagram, nettside, butikk, kundeservice?",
           [ex("Definisjon", "Hva betyr IMC?",
               [C("a", "International Marketing Council", "Helt feil."),
                C("b", "Integrated Marketing Communications — én stemme utad", "Riktig! Strategisk koordinering på tvers av kanaler.", correct=True),
                C("c", "Internet Marketing Channel", "Helt feil."),
                C("d", "Internal Management Committee", "Helt feil.")],
               "IMC ble populært på 1990-tallet da kanaler eksploderte. Krevde nytt rammeverk for å holde sammen."),
            ex("Hvorfor", "Hvorfor er konsistens viktig?",
               [C("a", "Spare penger", "Sekundært."),
                C("b", "Bygger gjenkjennelse over tid og tillit hos kunden", "Riktig! Sprik svekker merkevare. Konsistens bygger.", correct=True),
                C("c", "Lovkrav", "Helt urelevant."),
                C("d", "Bare estetikk", "Strategisk verdi.")],
               "Apple har holdt samme visuell identitet i 20+ år. Det bygger umiddelbar gjenkjennelse globalt."),
            ex("Norsk eksempel", "Hvilken norsk bedrift er sterk på IMC?",
               [C("a", "Tilfeldig", "Strategisk."),
                C("b", "Telenor — konsistent julekampanje, samme tone på alle kanaler i 10+ år", "Riktig! Telenor er klassisk eksempel på langsiktig IMC.", correct=True),
                C("c", "Helt feil", "Faktisk veldig sterk."),
                C("d", "Bare DnB", "DnB er også sterk, men Telenor er enda mer konsistent.")],
               "Test: når du tenker 'jul + telekom' i Norge, hva ser du? Telenor-julekampanjen — det er IMC i praksis.")]),
        ph("🎯", "Kommunikasjonsmål", "Fra kjennskap til handling.",
           "Kommunikasjonsmål struktureres typisk i hierarki: kjennskap (vet de at vi finnes?), kunnskap (forstår de hva vi gjør?), holdning (liker de oss?), preferanse (foretrekker de oss?), handling (kjøper de?). Hvert mål krever ulik strategi og budskap. AIDA-modellen er beslektet.",
           [("HIERARKI", "Kunden må gjennom flere stadier før kjøp."),
            ("ULIKE TILTAK", "Kjennskap krever bred reklame; handling krever konkret call-to-action.")],
           "Hvilket kommunikasjonsstadium er du selv i for et merke du vurderer å kjøpe?",
           [ex("Stadier", "Hva er typisk hierarki?",
               [C("a", "Bare pris", "For smalt."),
                C("b", "Kjennskap → kunnskap → holdning → preferanse → handling", "Riktig! Klassisk kommunikasjonshierarki.", correct=True),
                C("c", "Tilfeldig", "Strukturert modell."),
                C("d", "Bare reklame → kjøp", "For forenklet.")],
               "Modellen kalles også 'effekthierarkiet'. Kunden må gjennom hvert steg før kjøp."),
            ex("Strategisk valg", "Hvor er målgruppen din?",
               [C("a", "Spiller ingen rolle", "Avgjørende for strategi."),
                C("b", "Avgjør hvilken type budskap som passer — kjennskap krever bredt, handling krever spesifikt", "Riktig! Match budskap til hvor kunden er.", correct=True),
                C("c", "Bare salg", "For smalt."),
                C("d", "Alltid samme", "Tilpasset stadium.")],
               "Lansering = bygge kjennskap (TV, store kampanjer). Etablert merke = drive handling (Google Ads, retargeting)."),
            ex("AIDA", "Hva er AIDA?",
               [C("a", "Et merke", "Helt feil."),
                C("b", "Attention, Interest, Desire, Action — klassisk reklamemodell", "Riktig! Beslektet med kommunikasjonshierarkiet.", correct=True),
                C("c", "African International Development Agency", "Helt urelevant."),
                C("d", "Tilfeldig", "Strukturert modell.")],
               "AIDA er fra 1898. Fortsatt relevant — alle steg må fungere for at reklame skal virke.")]),
        ph("🎚️", "Påvirkningsmiksen", "5 hovedverktøy.",
           "Påvirkningsmiksen består av 5 verktøy: reklame (massekjennskap), PR (troverdighet), salgsfremming (kortsiktig boost), personlig salg (B2B og høyverdig B2C), direkte markedsføring (lojalitet). Strategisk vekting basert på mål og målgruppe. Få bedrifter bruker bare én.",
           [("5 VERKTØY", "Reklame, PR, salgsfremming, personlig salg, DM."),
            ("STRATEGISK VEKTING", "Velg miks basert på mål, ikke vane.")],
           "Hvilken påvirkningsmiks bruker bedrifter du kjenner? Hvilke er overrepresentert?",
           [ex("5 verktøy", "Hva er de 5 verktøyene?",
               [C("a", "Pris, produkt, plass, promo", "Det er markedsmiksen."),
                C("b", "Reklame, PR, salgsfremming, personlig salg, direkte markedsføring", "Riktig! Klassisk inndeling av kommunikasjonsverktøy.", correct=True),
                C("c", "Bare reklame", "For smalt."),
                C("d", "Tilfeldig", "Strukturert modell.")],
               "Hver har egne styrker. Reklame = bredde. Personlig salg = dybde. Riktig miks varierer."),
            ex("PR styrke", "Hva er PRs unike styrke?",
               [C("a", "Lavest pris", "Ofte dyrt."),
                C("b", "Troverdighet — tredjepart sier det, ikke bedriften selv", "Riktig! Omtale i media oppfattes mer pålitelig enn reklame.", correct=True),
                C("c", "Bare for store", "Brukes alle størrelser."),
                C("d", "Lovkrav", "Helt urelevant.")],
               "1 god avisartikkel kan være verdt 10 sider med reklame. Troverdigheten er kritisk forskjell."),
            ex("Salgsfremming", "Hva er salgsfremming best til?",
               [C("a", "Langsiktig merkebygging", "Tvert imot — kortsiktig."),
                C("b", "Kortsiktig boost — kampanjer, rabatter, konkurranser", "Riktig! Effekt umiddelbar, men varig effekt liten.", correct=True),
                C("c", "Bygge merkevare", "Sjelden — kan til og med skade premium-merker."),
                C("d", "Tilfeldig bruk", "Strukturert verktøy.")],
               "Black Friday = klassisk salgsfremming. Boost i salgsperiode, men kunder venter på neste rabatt.")]),
        ph("🛤️", "Den digitale kundereisen",
           "Oppdage → vurdere → konvertere → beholde.",
           "Tradisjonell trakt er ikke lineær lenger — kundene hopper inn og ut, sammenligner, leser anmeldelser, sjekker sosiale medier. Markedsføringen må være tilstede i alle ledd. Customer Journey Mapping er strategisk verktøy for å forstå alle berøringspunkter.",
           [("IKKE LINEÆR", "Moderne kunder hopper mellom kanaler og stadier."),
            ("MULTI-TOUCHPOINT", "5-20 berøringspunkter typisk før kjøp.")],
           "Husk siste større kjøp — hvor mange touchpoints hadde du før kjøp? Hva avgjorde?",
           [ex("4 stadier", "Hva er den digitale kundereisens 4 stadier?",
               [C("a", "Tilfeldige", "Strukturert modell."),
                C("b", "Oppdage, vurdere, konvertere, beholde", "Riktig! Standard rammeverk for digital markedsføring.", correct=True),
                C("c", "Pris, produkt, plass, promo", "Det er markedsmiksen."),
                C("d", "Bare kjøp", "For forenklet.")],
               "Hvert stadium krever ulike kanaler og budskap. Oppdage = sosiale medier. Konvertere = nettside CTA."),
            ex("Touchpoints", "Hvor mange touchpoints typisk?",
               [C("a", "1-2", "Underestimert."),
                C("b", "5-20 i komplekse kjøp, 7+ i typiske B2C", "Riktig! Multi-touch er regelen, ikke unntaket.", correct=True),
                C("c", "Bare 1", "For lavt."),
                C("d", "100+", "Overdrevet.")],
               "Selv om kunden kjøper på nettstedet, har hun typisk vært innom Google, Instagram, anmeldelser, venner først."),
            ex("Mapping", "Hva er Customer Journey Mapping?",
               [C("a", "Bare GPS", "Helt feil tolkning."),
                C("b", "Strukturert oversikt over alle touchpoints kunden har med bedriften", "Riktig! Strategisk verktøy for å avdekke smutthull og forbedringspunkter.", correct=True),
                C("c", "Markedsanalyse", "Beslektet, men spesifikt på reisen."),
                C("d", "Tilfeldig", "Strukturert metode.")],
               "Tegn ut hver touchpoint: Google-søk → klikk på annonse → nettside → produktside → handlevogn → bekreftelse → e-post. Avdekker friksjon.")]),
        ph("📝", "Innholdsstrategi",
           "Content marketing — hjelp, ikke selg.",
           "Content marketing bygger autoritet og tillit gjennom verdifullt innhold. DnBs Magma-blogg, Hubspots guider, Patagonias miljøreportasjer. Strategien er langsiktig — bli den foretrukne eksperten, så kjøper folk fra deg når de er klare. Krever konsistens (minst ukentlig) og faktisk verdi.",
           [("VERDI FØRST", "Hjelp, ikke selg. Bygger tillit som blir til salg."),
            ("KONSISTENS", "Minst ukentlig publisering. Sporadisk mister momentum.")],
           "Hvilken bedrift bruker innhold som strategi? Stoler du mer på dem som leverandør?",
           [ex("Prinsipp", "Hva er kjernen i 'hjelp, ikke selg'?",
               [C("a", "Aldri selg noe", "Du selger til slutt — bare ikke i hver artikkel."),
                C("b", "Skap verdi for leseren først; salg kommer som naturlig konsekvens", "Riktig! Bygger tillit over tid.", correct=True),
                C("c", "Kun bruk innhold til å selge produktet direkte", "Da er det salgstekst, ikke content marketing."),
                C("d", "Ignorer salgsmål", "Mål skal være der, men nås gjennom verdi.")],
               "Hubspot bygde milliardselskap på å gi bort markedsføring-guider gratis. Gull-standard."),
            ex("Konsistens", "Minimum publiseringsfrekvens?",
               [C("a", "Én gang i året", "For lavt."),
                C("b", "Minst ukentlig", "Riktig! Konsistens er nøkkelen til både SEO og målgruppe-vekst.", correct=True),
                C("c", "Bare når man har tid", "Sporadisk innhold mister momentum."),
                C("d", "Daglig", "Bra, men ikke realistisk for de fleste.")],
               "Velg én kanal og publiser konsistent der, fremfor mange kanaler sporadisk."),
            ex("Norsk eksempel", "Hvilken norsk bedrift har sterk innholdsmarkedsføring?",
               [C("a", "REMA 1000", "Reklame-fokusert."),
                C("b", "DnB med Magma-bloggen om personlig økonomi", "Riktig! Magma er DnBs innholdshub. Bygger DnB som ekspert.", correct=True),
                C("c", "Coop med katalog", "Reklame, ikke innhold."),
                C("d", "Telia med fakturaen", "Faktura er ikke marketing.")],
               "Andre eksempler: Equinor sin Energi-podkast, Schibsted sine bransjeguider, Nordnet sin investorblogg.")]),
        ph("📱", "Sosiale medier og dialog",
           "Fra monolog til samspill.",
           "Sosiale medier endret reklamen fundamentalt: kunden kan svare, kritisere, dele og kjøpe direkte i samme kanal. Hver plattform har egen dynamikk: Facebook 30+, Instagram 20-40, TikTok 15-25, LinkedIn B2B. Krever responstid (timer, ikke dager) og evne til å håndtere ros og ris åpent.",
           [("DIALOG", "Forskjell fra TV: kunden svarer."),
            ("PLATTFORMTILPASNING", "Samme video til alle plattformer feiler.")],
           "Hvilken bedrift gjør best på sosiale medier? Hva gjør de annerledes?",
           [ex("Plattformforskjell", "Hva er typisk forskjell Facebook vs TikTok?",
               [C("a", "De er like", "Helt forskjellige."),
                C("b", "Facebook har eldre brukere (30+), TikTok dominerer 15-25-segmentet", "Riktig! Aldersprofilen er svært ulik.", correct=True),
                C("c", "Facebook er kun B2B", "Begge er primært B2C."),
                C("d", "TikTok forbudt i Norge", "Helt feil.")],
               "Distribusjonsregel: opprett innhold for hver plattform, ikke kopier."),
            ex("Krise", "Kunde klager høyt på Facebook. Hva gjør du?",
               [C("a", "Slett kommentaren", "Sjelden lurt — andre vil se."),
                C("b", "Svar offentlig, profesjonelt, tilby å ta saken til DM", "Riktig! Åpenhet og rask respons viser at du tar kunder på alvor.", correct=True),
                C("c", "Ignorer", "Verste alternativ."),
                C("d", "Saksøk kunden", "Helt overdrevet.")],
               "United Airlines tapte over 1 mrd USD i markedsverdi på et viralt klipp. Krise-kommunikasjon er kritisk."),
            ex("Norsk eksempel", "Hvilken norsk bedrift er sterk på sosial?",
               [C("a", "Statkraft", "Solid bedrift, mindre sosial-fokus."),
                C("b", "Vipps med viralt innhold på TikTok og Instagram", "Riktig! Vipps har vært ekstremt aktive — humor på TikTok.", correct=True),
                C("c", "Bolig.no", "Mindre fokus."),
                C("d", "Hydro", "Mest B2B og pressekontakt.")],
               "Vipps' strategi: humoristisk, lokal, rask respons. Bygger merkevare som 'norsk og folkelig'.")]),
        ph("💰", "Budsjettering",
           "Mål- og oppgavemetoden.",
           "Tre vanlige metoder: prosent av omsetning (enkelt, men reaktivt), konkurranse-metoden (følg de andre), mål- og oppgavemetoden (regn ut hva som kreves for målene). Den siste er strategisk, men krever disiplin. Mange bedrifter underbudsjetterer kommunikasjon — særlig i nedgangstider.",
           [("MÅL- OG OPPGAVE", "Strategisk: definer mål, beregn ressursbehov."),
            ("PROSENT", "Enkelt: x % av omsetning. Men reaktivt og lite strategisk.")],
           "Hvor mye bør en lansering koste i kommunikasjon? Hvordan beregne?",
           [ex("Beste metode", "Hvilken er mest strategisk?",
               [C("a", "Prosent av omsetning", "Enkelt, men ikke strategisk."),
                C("b", "Mål- og oppgavemetoden — definer mål, beregn behov", "Riktig! Krever mer arbeid, men gir riktig allokering.", correct=True),
                C("c", "Følg konkurrentene", "Reaktivt."),
                C("d", "Bruk samme som i fjor", "Ingen strategi.")],
               "Mål- og oppgavemetoden tvinger frem realisme — ofte avslører at mål er urealistiske med eksisterende budsjett."),
            ex("Risiko", "Hva er risiko ved prosent-metoden?",
               [C("a", "For komplisert", "Tvert imot — for enkel."),
                C("b", "Blir reaktivt — kutter budsjett når salg faller, men da trenger man mer marketing", "Riktig! Klassisk feil. Mister momentum.", correct=True),
                C("c", "For dyrt", "Er metoden — ikke nivået."),
                C("d", "Lovstridig", "Lovlig metode.")],
               "Investorer studerer dette: bedrifter som økt marketing i krise (Amazon 2009) har gjort det bedre enn de som kuttet."),
            ex("Underbudsjettering", "Hva er klassisk feil?",
               [C("a", "Bruke for mye", "Ofte motsatt problem."),
                C("b", "Underbudsjettere kommunikasjon — særlig for nye produkter", "Riktig! Lansering uten kommunikasjons-budsjett = produktet dør.", correct=True),
                C("c", "Bruke alt på reklame", "Mangler mix-balanse."),
                C("d", "Tilfeldig", "Strukturert problem.")],
               "Tommelfingerregel: lansering trenger 20-50 % av forventet første-års-omsetning i kommunikasjon.")]),
        ph("📊", "Effektmåling (KPI)",
           "Hvordan vet vi at det virker?",
           "Kommunikasjon må måles. Digitale kanaler: presise tall (klikk, konvertering, ROAS). Tradisjonelle: estimater (TNS Gallup, Kantar målgruppeundersøkelser). Brand tracking måler kjennskap, preferanse over tid. Velg KPI etter mål — ikke 'vanity metrics' som likes uten kobling til konvertering.",
           [("DIGITAL = PRESIST", "Hver visning, klikk og konvertering kan spores."),
            ("VANITY METRICS", "Likes uten kobling til salg er ofte vanity.")],
           "Hvilke KPI-er måler bedriften du jobber for / kjenner? Er det vanity eller verdi?",
           [ex("Vanity metric", "Hva er en vanity metric?",
               [C("a", "Salg", "Faktisk verdi."),
                C("b", "Antall likes uten kobling til konvertering", "Riktig! Måler synlighet, ikke verdi.", correct=True),
                C("c", "ROAS", "Direkte verdi-mål."),
                C("d", "Customer Lifetime Value", "Strategisk verdi-mål.")],
               "Steve Jobs sa: 'I don't care what people say about me. I care what they buy.' Effekt > eksponering."),
            ex("ROAS", "Hva betyr ROAS?",
               [C("a", "Rate of Annual Sales", "Helt feil."),
                C("b", "Return on Ad Spend — inntekt per annonsekrone", "Riktig! Standard performance metric.", correct=True),
                C("c", "Average Sales", "Helt feil."),
                C("d", "Risk Assessment", "Helt feil.")],
               "ROAS 4 = hver krone i annonser ga 4 kroner i salg. Over 3 regnes generelt som lønnsomt."),
            ex("Brand tracking", "Hva måles?",
               [C("a", "Bare salget", "For smalt."),
                C("b", "Kjennskap, preferanse, oppfattet kvalitet over tid", "Riktig! Strategiske indikatorer på merkets helse.", correct=True),
                C("c", "Antall ansatte", "Helt urelevant."),
                C("d", "Konkurrenters salg", "Sekundært.")],
               "Norske store bedrifter gjør kvartalsvis brand tracking. Tidlig signal hvis merket begynner å falme.")]),
        ph("🎬", "Kreativ utforming",
           "Idéen slår produksjonsbudsjettet.",
           "Lavbudsjett-kampanjer med god idé slår dyrt produserte uten idé. Apple sin '1984' og Coca-Colas julekampanjer er begge bevis. På sosiale medier avgjør de første 3 sekundene. Norske eksempler: Telenor-julekampanjen, Spotify Wrapped, IKEA-katalogen. Kreativitet er strategi.",
           [("IDÉ > BUDSJETT", "God idé med lavt budsjett slår dårlig idé med stort budsjett."),
            ("FØRSTE 3 SEK", "På sosiale medier avgjør hookene umiddelbart.")],
           "Hvilken reklame husker du best siste år? Hva gjorde den minneverdig?",
           [ex("Hva avgjør", "Hva er viktigst for at reklame skal virke?",
               [C("a", "Stort produksjonsbudsjett", "Hjelper, men sekundært."),
                C("b", "En klar, sterk kreativ idé", "Riktig! Lavbudsjett med god idé slår dyrt uten idé.", correct=True),
                C("c", "Mange budskap samtidig", "Tvert imot — fokus slår spredning."),
                C("d", "Lengde — minst 60 sekunder", "Korte er ofte mer effektive på sosiale medier.")],
               "Apple-eksempel: '1984'-reklamen kostet lite i produksjon, ekstremt sterk idé. Endret bransjen."),
            ex("Sosial medier-attention", "Hvor viktige er første sekunder?",
               [C("a", "Lite — folk ser uansett ferdig", "Helt feil — folk scroller."),
                C("b", "Avgjørende — du har 3 sekunder før de scroller videre", "Riktig! Algoritmen + adferd betyr at hookene må være på plass i sekund 1-3.", correct=True),
                C("c", "Slutten viktigst", "CTA er viktig, men hvis ingen ser frem til slutten..."),
                C("d", "Bare lengde", "Innhold > lengde.")],
               "TikTok-skapere bruker 80 % av tiden på de første 3 sekundene. Viktig kunnskap."),
            ex("Klassiske grep", "Hvilket er IKKE et klassisk kreativt grep?",
               [C("a", "Humor", "Klassisk grep."),
                C("b", "Historiefortelling", "En av de mest effektive."),
                C("c", "Bare prislister og spesifikasjoner", "Riktig! Rene fakta-lister er informasjon, ikke kreativ reklame. De huskes ikke.", correct=True),
                C("d", "Provokasjon", "Risikabelt grep — Benetton brukte det.")],
               "Faktabasert reklame har sin plass (B2B), men trenger fortsatt en historie for å feste seg.")]),
        ph("🎯", "Strategisk synergi",
           "Når 1+1 blir 3.",
           "God strategisk kommunikasjon utnytter synergi mellom kanaler. TV-reklame skaper kjennskap som forsterkes av Google-søk og handles på nettsiden. Influencer-anbefaling skaper interesse som drives til konvertering via retargeting. Strategien tenker helhet, ikke siloer per kanal.",
           [("SYNERGI", "Kanaler forsterker hverandre når koordinert."),
            ("HELHET", "Strategi må tenke kanal-overskridende, ikke per silo.")],
           "Hvilken kampanje du har sett brukte flere kanaler effektivt sammen?",
           [ex("Synergi", "Hva er synergi-effekt?",
               [C("a", "Kostnadskutt", "Kan være, men ikke kjernen."),
                C("b", "Når kanaler forsterker hverandre — total effekt > sum av deler", "Riktig! 1+1=3-prinsippet.", correct=True),
                C("c", "Bare for store", "Brukes alle størrelser."),
                C("d", "Lovkrav", "Helt urelevant.")],
               "TV-reklame + retargeting på Facebook + e-post = mye sterkere enn én kanal alene."),
            ex("Helhet", "Hvorfor må strategi tenke helhet?",
               [C("a", "Spare penger", "Sekundært."),
                C("b", "Kunden opplever merket som ett — ikke som separate kanaler", "Riktig! Sprik mellom kanaler skader merket.", correct=True),
                C("c", "Tilfeldig", "Strukturelt."),
                C("d", "Lovkrav", "Helt urelevant.")],
               "Kunden bryr seg ikke om hvilken avdeling som driver kanalen. Hun ser bare merket — eller mangelen på konsistens."),
            ex("Hva er strategisk komm.", "Hva kjennetegner strategisk kommunikasjon?",
               [C("a", "Mest mulig støy", "For overflatisk."),
                C("b", "Bygger langsiktige verdier — ikke bare kortsiktig støy", "Riktig! Modern tenkning. Konsistens over tid bygger merkekapital.", correct=True),
                C("c", "Bare reklame", "For smalt."),
                C("d", "Tilfeldig", "Strategisk valg.")],
               "Kommunikasjon er bygging av langsiktige verdier — ikke et serie av engangshendelser.")]),
    ],
    ["Du forstår IMC som strategisk koordinering på tvers av alle kommunikasjonskanaler",
     "Du kan strukturere kommunikasjonsmål i hierarki fra kjennskap til handling",
     "Du behersker påvirkningsmiksens 5 verktøy og strategisk vekting",
     "Du kjenner den digitale kundereisen og multi-touchpoint-realiteten",
     "Du kan velge mellom budsjettmetoder og måle effekt med riktige KPI-er"])


g.write_modules([KOMM], "ML2-11 Kommunikasjonsstrategier")
