#!/usr/bin/env python3
"""ML2-12 Markedsmiks og effektmåling."""
import importlib.util
from pathlib import Path
spec = importlib.util.spec_from_file_location("g", Path(__file__).parent / ".gen-shared.py")
g = importlib.util.module_from_spec(spec); spec.loader.exec_module(g)
C, ph, ex, M = g.C, g.ph, g.ex, g.M


MIKS = M("MarkedsmiksOgEffektmaling", "ml2", "ML2-12", "Markedsmiks og effektmåling", "📊",
    "markedsmiks-og-effektmaling", "ml2",
    "Markedsmiksen er sammensetningen av strategiske valg innen produkt, pris, plass og påvirkning. Effektmåling forteller om miksen virker. KPI, ROI, ROAS og analytics gjør markedsføringen målbar — fra magi til disiplin.",
    "Bedrifter som måler markedsføringen sin systematisk har 30 % høyere avkastning enn de som ikke gjør det. Måling tvinger frem disiplin og læring.",
    "Halvparten av reklamebudsjettet er bortkastet — du vet bare ikke hvilken halvpart. Effektmåling reduserer det til kanskje en fjerdedel.",
    [
        ph("📊", "Markedsmiksen — 4 P-er", "Strategiske valg som hører sammen.",
           "Markedsmiksen består av 4 P-er: Produkt (hva tilbyr vi), Pris (hva koster det), Plass (hvor selges det), Påvirkning (hvordan kommuniserer vi). Hver P er en variabel — sammen utgjør de bedriftens totale tilbud til markedet. Endrer du én, må de andre vurderes på nytt.",
           [("4 P-ER", "Produkt, Pris, Plass, Påvirkning."),
            ("INTEGRERT", "Endre én = vurder de tre andre.")],
           "Velg en bedrift. Beskriv markedsmiksen — alle 4 P-er. Henger de sammen?",
           [ex("4 P-er", "Hva er de 4 P-ene?",
               [C("a", "Penger, posisjon, prestige, prosess", "Helt feil."),
                C("b", "Produkt, Pris, Plass, Påvirkning", "Riktig! Klassisk markedsmiks.", correct=True),
                C("c", "Plan, prosess, prestasjon, profitt", "Helt feil."),
                C("d", "Bare 3", "For få.")],
               "McCarthy formulerte 4 P-er i 1960. Fortsatt grunnleggende rammeverk."),
            ex("Tjenester", "Hva med tjenester?",
               [C("a", "Bare 4 P-er", "Tjenester får ofte 7 P-er."),
                C("b", "Tjenester får 7 P-er — pluss People, Process, Physical evidence", "Riktig! Tjenester er mer komplekse pga menneskelig leveranse.", correct=True),
                C("c", "Bare 2", "For få."),
                C("d", "Tilfeldig", "Strukturert utvidelse.")],
               "7 P-ene utviklet for tjenester på 1980-tallet. People (ansatte), Process (leveranse), Physical evidence (fysiske spor)."),
            ex("Integrasjon", "Hvorfor må P-ene henge sammen?",
               [C("a", "Tilfeldig", "Strategisk."),
                C("b", "Premium-produkt + lavpris = inkonsistent. Hver P signaliserer posisjonering", "Riktig! Sprik forvirrer kunden og svekker merket.", correct=True),
                C("c", "Lovkrav", "Helt urelevant."),
                C("d", "Bare estetikk", "Strategisk verdi.")],
               "Rolex selges ikke i REMA. Premium-pris krever premium-distribusjon og premium-kommunikasjon. Konsistens.")]),
        ph("🎯", "Synergieffekter", "1+1=3.",
           "God markedsmiks har synergi — P-ene forsterker hverandre. Apple: premium-produkt + premium-pris + premium-distribusjon (egne butikker) + premium-kommunikasjon. Hver P bygger merket. Dårlig miks: motstridende signaler. Bil med luksus-design men solgt i lavpris-kanaler — taper begge segmenter.",
           [("FORSTERKING", "P-ene skal forsterke samme posisjonering."),
            ("MOTSTRIDENDE = TAP", "Sprikende P-er svekker hverandre.")],
           "Hvilken bedrift har best synergi mellom 4 P-er? Hvilken har sprik?",
           [ex("Synergi", "Hva betyr synergi i markedsmiks?",
               [C("a", "Tilfeldig", "Strategisk."),
                C("b", "P-ene forsterker hverandres budskap", "Riktig! Total effekt > sum av deler.", correct=True),
                C("c", "Bare for tjenester", "Gjelder produkter også."),
                C("d", "Lovkrav", "Helt urelevant.")],
               "Apple-eksempel: design + pris + butikker + reklame — alt forsterker 'premium og innovativ'."),
            ex("Sprik-eksempel", "Eksempel på dårlig synergi?",
               [C("a", "Konsistent merkevare", "Tvert imot."),
                C("b", "Luksus-bil solgt på REMA — produkt og distribusjon er motstridende", "Riktig! Tilfeldig eksempel — men prinsippet stemmer.", correct=True),
                C("c", "Ingen problem", "Stort problem."),
                C("d", "Lovstridig", "Helt urelevant.")],
               "Sprik kan ramme alt: produkt, pris, kanal, kommunikasjon. Sjekk konsistensen."),
            ex("Test", "Hvordan teste synergi?",
               [C("a", "Magefølelse", "Subjektiv."),
                C("b", "Spør: signaliserer hver P samme posisjonering?", "Riktig! Strukturert sjekk på konsistens.", correct=True),
                C("c", "Bare salg", "For sent — bør sjekkes før."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Hvert tiltak bør 'passe' merkets posisjonering. Hvis ikke, kutt eller juster.")]),
        ph("📋", "Markedsplanen som styringsverktøy",
           "Det dokumentet som binder alt sammen.",
           "Markedsplanen samler analyse, mål, strategi, tiltak og budsjett i ett dokument. For en mellomstor bedrift typisk 30-80 sider. Brukes som styringsverktøy gjennom året. Kortere er ofte bedre — én side som folk handler på er mer verdifull enn 200 sider som ingen leser.",
           [("STYRINGSVERKTØY", "Brukes som referanse gjennom året."),
            ("HANDLING > LENGDE", "Kort plan som handles på > lang plan som arkiveres.")],
           "Har bedriften du jobber for / kjenner en markedsplan? Brukes den faktisk?",
           [ex("Lengde", "Hva er typisk for en god markedsplan?",
               [C("a", "Minst 200 sider", "For lang."),
                C("b", "30-80 sider for mellomstore bedrifter, men kortere er ofte bedre", "Riktig! Lengde alene gir ikke verdi.", correct=True),
                C("c", "Bare 1 setning", "For kort."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Test: kan du forklare planen på 5 minutter? Hvis nei, er den for kompleks."),
            ex("Funksjon", "Hva er markedsplanens funksjon?",
               [C("a", "Pynt", "Praktisk verktøy."),
                C("b", "Styringsverktøy gjennom året — refereres til i beslutninger", "Riktig! Brukt riktig: kompass.", correct=True),
                C("c", "Bare for ledelsen", "Bredere bruk."),
                C("d", "Lovkrav", "Helt urelevant.")],
               "Hvis planen ligger i skuffen etter januar, er den ikke et styringsverktøy."),
            ex("Hvor mislykkes", "Hva er klassisk feil?",
               [C("a", "For ambisiøs", "Sjelden problem."),
                C("b", "Skrives én gang, refereres aldri til, glemmes", "Riktig! 'Strategi-arkivet'-feilen.", correct=True),
                C("c", "For mange møter", "Symptom."),
                C("d", "For dyrt", "Sjelden hovedårsak.")],
               "Lag månedlige planmøter. Sjekk: er vi på sporet? Avvik = juster.")]),
        ph("📈", "Hvorfor måle?",
           "Læring, kontroll, bevis.",
           "Effektmåling tjener tre formål: 1) Læring (hva virker, hva virker ikke?), 2) Kontroll (er vi på sporet mot målene?), 3) Bevis (legitimerer markedsføringsbudsjettet for ledelsen). Uten måling er markedsføring magi. Med måling er det forretningsdisiplin.",
           [("3 FORMÅL", "Læring, kontroll, bevis."),
            ("DISIPLIN", "Måling tvinger frem strukturert tenkning.")],
           "Hva ville du målt for å vite om markedsføring i bedriften du kjenner virker?",
           [ex("3 grunner", "Hvorfor måle effekt?",
               [C("a", "Bare lovkrav", "Strategisk verdi."),
                C("b", "Læring + kontroll + bevis for ledelsen", "Riktig! Tre uavhengige verdier.", correct=True),
                C("c", "Pynt", "Praktisk verktøy."),
                C("d", "Bare for konsulenter", "For ledelsen først.")],
               "Måling er hvordan markedsføring blir tatt på alvor i ledelsen. Uten data er det 'kreativt arbeid'."),
            ex("Læring", "Hvordan brukes læring?",
               [C("a", "Bare arkivere", "Verdiløst."),
                C("b", "Justere neste kampanje basert på hva som virket", "Riktig! Iterativ forbedring over tid.", correct=True),
                C("c", "Bare for store", "Gjelder alle."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Best in class: A/B-tester hver kampanje. Læring akkumulerer over år."),
            ex("Bevis", "Hvorfor er bevis viktig?",
               [C("a", "Bare ego", "Strategisk verdi."),
                C("b", "Når økonomi-direktør spør 'hva fikk vi for pengene?' kreves dokumentasjon", "Riktig! Marketing-budsjett er ofte først ut i kostnadskutt.", correct=True),
                C("c", "Lovkrav", "Helt urelevant."),
                C("d", "Bare i krise", "Daglig behov.")],
               "Marketing-direktører som kan vise ROI behold budsjett. De som ikke kan, taper det.")]),
        ph("🧠", "Kommunikasjonseffekt",
           "Ble vi husket? Endret vi holdninger?",
           "Kommunikasjonseffekt måles i kjennskap (kjenner kundene oss?), recall (husker de reklamen?), preferanse (foretrekker de oss?). Måles via brand tracking-undersøkelser. Tar tid å se utslag — men er strategiske indikatorer på merkevarens helse.",
           [("KJENNSKAP", "Andel av målgruppen som kjenner merket."),
            ("RECALL", "Andel som spontant husker reklamen og budskapet.")],
           "Hvilke merker har du sterk uhjulpen kjennskap til (kommer på dem uten påminnelse)?",
           [ex("Uhjulpen", "Hva er uhjulpen kjennskap?",
               [C("a", "Med påminnelse", "Det er hjulpen."),
                C("b", "Spontan kjennskap — kunden nevner merket uten påminnelse", "Riktig! Sterkeste indikator på topp-of-mind.", correct=True),
                C("c", "Bare i USA", "Måling brukes overalt."),
                C("d", "Lovkrav", "Helt urelevant.")],
               "Test: 'Nevn 3 mobiloperatører'. Spontane svar = uhjulpen kjennskap. Sterke merker scorer høyt."),
            ex("Ad recall", "Hva betyr ad recall?",
               [C("a", "Tilbakekalling av reklame", "Bokstavelig — feil tolkning."),
                C("b", "Andel av målgruppen som husker en spesifikk reklame", "Riktig! Måles etter kampanje for å vurdere effekt.", correct=True),
                C("c", "Bare for produktproblemer", "Helt feil."),
                C("d", "Tilfeldig", "Strukturert måling.")],
               "Bra ad recall: 30-50 %. Verdensklasse: 60+ %. Avhenger av kampanje-type og kategori."),
            ex("Brand tracking", "Hvor ofte måles?",
               [C("a", "Aldri", "For lite."),
                C("b", "Kvartalsvis eller halvårlig — ser endring over tid", "Riktig! Frekvens nok til å fange utvikling, ikke for ofte.", correct=True),
                C("c", "Daglig", "For ofte og dyrt."),
                C("d", "Bare ved krise", "For sjelden — bør være proaktivt.")],
               "Norske store bedrifter (DnB, Telenor, Equinor) gjør kvartalsvis brand tracking. Standard.")]),
        ph("💰", "Salgseffekt",
           "Hvor mye økte salget?",
           "Salgseffekt: hvor mye økte omsetningen direkte av kampanjen? ROAS (Return on Ad Spend) er nøkkeltallet for digitale kampanjer — inntekt / annonsekostnad. ROAS 3 = hver krone i annonser ga 3 kroner i salg. Over 3 regnes generelt som lønnsomt for e-handel.",
           [("ROAS = SALGSEFFEKT", "Inntekt / annonsekostnad."),
            ("ROAS 3+", "Generelt lønnsomt for e-handel.")],
           "Hvilken ROAS ville vært akseptabel for en bedrift du kjenner? Hva avhenger det av?",
           [ex("ROAS", "Hva betyr ROAS?",
               [C("a", "Rate of Annual Sales", "Helt feil."),
                C("b", "Return on Ad Spend — inntekt per annonsekrone", "Riktig! Standard performance metric.", correct=True),
                C("c", "Average Sales", "Helt feil."),
                C("d", "Risk Assessment", "Helt feil.")],
               "ROAS 4 = 4× tilbakebetaling. ROAS over 3 er generelt lønnsomt."),
            ex("Margin-effekt", "Hvorfor avhenger 'lønnsom ROAS' av margin?",
               [C("a", "Tilfeldig", "Matematisk."),
                C("b", "Lav margin krever høyere ROAS for å være lønnsom", "Riktig! Hvis margin er 20 %, krever ROAS 5+ for å være lønnsom etter alle kostnader.", correct=True),
                C("c", "Lovkrav", "Helt urelevant."),
                C("d", "Bare estetikk", "Praktisk regel.")],
               "Lavpris-bransjer (mat) krever høyere ROAS. Premium-bransjer (luksus) kan klare seg med lavere."),
            ex("Multi-touch", "Hva er problemet med last-click attribution?",
               [C("a", "For komplisert", "Tvert imot — for enkelt."),
                C("b", "Gir all kreditt til siste touchpoint, ignorerer tidlige merkebyggende kanaler", "Riktig! Favoriserer typisk Google Ads, undervurderer TV/sosiale medier.", correct=True),
                C("c", "Lovstridig", "Lovlig.")],
               "Multi-touch attribution gir mer presist bilde — men er vanskeligere å sette opp.")]),
        ph("📐", "ROI i markedsføring",
           "Avkastning på investert markedskapital.",
           "ROI = (gevinst - kostnad) / kostnad × 100. Inkluderer alle kostnader, ikke bare annonser (også internt arbeid). Hvis ROI er 30 %, er hver krone investert verdt 1,30 kr. Vanskelig å beregne presist for merkebygging — men kritisk for å rettferdiggjøre marketing-budsjett.",
           [("HELHETLIG ROI", "Inkluder alle kostnader — internt arbeid, byråer, teknologi."),
            ("KORT vs LANG SIKT", "Direktesalg er lett; merkebygging er vanskelig å attribuere.")],
           "Hvordan ville du beregnet ROI for en merkekampanje uten direkte salg?",
           [ex("Definisjon", "Hva er ROI?",
               [C("a", "Bare omsetning", "For smalt."),
                C("b", "(Gevinst - kostnad) / kostnad × 100", "Riktig! Standard formel for avkastning.", correct=True),
                C("c", "Bare kostnad", "For smalt."),
                C("d", "Tilfeldig", "Strukturert.")],
               "ROI 30 % = 1.30 kr tilbake per krone investert. Standard finansielt mål."),
            ex("Inkluder", "Hva må inkluderes i markedskostnad?",
               [C("a", "Bare annonser", "For smalt."),
                C("b", "Annonser + internt arbeid + byråer + teknologi", "Riktig! Helhetlig kostnadsbilde.", correct=True),
                C("c", "Bare lønninger", "For smalt."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Mange undervurderer marketing-kostnad ved å glemme internt arbeid. Gir feilaktig høy ROI."),
            ex("Vanskelig", "Hvorfor er merkebygging vanskelig å attribuere?",
               [C("a", "Tilfeldig", "Strukturelle årsaker."),
                C("b", "Effekt skjer over år, mange faktorer påvirker, ikke direkte salg-link", "Riktig! Strukturell utfordring i ROI-beregning.", correct=True),
                C("c", "Bare for B2B", "Gjelder alle."),
                C("d", "Lovstridig", "Helt urelevant.")],
               "Coca-Cola kan ikke beregne nøyaktig ROI for julekampanjen. Men de vet at kjennskap og preferanse holdes høyt — strategisk verdi.")]),
        ph("🔍", "Digital sporing — Analytics",
           "Følg kunden fra første klikk til ferdig kjøp.",
           "Google Analytics, Hubspot, Mixpanel sporer hver bruker gjennom konverteringstrakten. Kan se: hvor de kom fra, hva de gjorde, hvor de falt fra, hva som ble kjøp. GDPR setter grenser for personlig sporing. Cookie-løse løsninger blir viktigere fra 2024.",
           [("ANALYTICS", "Standard verktøy: Google Analytics, Hubspot."),
            ("GDPR-EFFEKT", "Reduserer presisjon, men målinger er fortsatt mulige.")],
           "Bruker bedriften du kjenner Google Analytics? Hva sporer de?",
           [ex("Funksjon", "Hva gjør analytics-verktøy?",
               [C("a", "Bare antall besøk", "For smalt."),
                C("b", "Sporer hele brukerreisen — kilde, atferd, konvertering", "Riktig! Helhetlig analyse av digital atferd.", correct=True),
                C("c", "Bare reklame", "For smalt."),
                C("d", "Lovstridig", "Lovlig med samtykke.")],
               "Google Analytics 4 er gratis og brukes av millioner av nettsider globalt."),
            ex("Konverteringstrakt", "Hva er en konverteringstrakt?",
               [C("a", "Fysisk trakt", "Bokstavelig — feil tolkning."),
                C("b", "Strukturert vei fra første kontakt til kjøp — typisk smalere ved hvert steg", "Riktig! Visualisering av kundereisen.", correct=True),
                C("c", "Bare for små", "Brukes alle størrelser."),
                C("d", "Tilfeldig", "Strukturert modell.")],
               "100 besøk → 30 produktvisninger → 5 handlevogn → 1 kjøp. Trakt blir smalere — analyse identifiserer hvor folk faller fra."),
            ex("GDPR-effekt", "Hva har GDPR endret?",
               [C("a", "Ingenting", "Stor effekt."),
                C("b", "Strengere samtykkekrav — målretting basert på personlige data er vanskeligere", "Riktig! Strukturell endring i bransjen.", correct=True),
                C("c", "Bare i USA", "EU/EØS-direktiv."),
                C("d", "Bare for Facebook", "Hele bransjen rammet.")],
               "Apples ATT (App Tracking Transparency) i 2021 reduserte effektiviteten av målrettet annonsering ytterligere.")]),
        ph("⚠️", "Feilkilder ved måling",
           "Sesong, konkurrenter, eksterne sjokk.",
           "Måling er ikke perfekt. Sesong (julehandel ≠ januarsalg), konkurrenter (deres kampanjer påvirker dine resultater), eksterne sjokk (pandemi, krig, valuta). Tolking krever fagforståelse, ikke bare tallene. Korrelasjon er ikke kausalitet — pass på å trekke for raske konklusjoner.",
           [("KORRELASJON ≠ KAUSALITET", "Salg økte etter kampanjen — men var det kampanjen eller noe annet?"),
            ("KONTEKST", "Tall må tolkes i lys av sesong, konkurranse, makro.")],
           "Salget steg 20 % etter kampanjen. Men: solskinnsdag, konkurrent stengt, jul. Hva avgjorde egentlig?",
           [ex("Korrelasjon", "Hva er forskjellen på korrelasjon og kausalitet?",
               [C("a", "De er det samme", "Helt feil."),
                C("b", "Korrelasjon = ting endrer seg sammen; kausalitet = én forårsaker den andre", "Riktig! Kritisk skille i analyse.", correct=True),
                C("c", "Bare statistikk-jargong", "Praktisk viktig."),
                C("d", "Tilfeldig", "Strukturert skille.")],
               "Klassisk eksempel: iskremsalg og drukninger korrelerer — men begge skyldes sommer, ikke at iskrem forårsaker drukninger."),
            ex("Sesong", "Hvordan håndtere sesong?",
               [C("a", "Ignorere", "Gir feilaktige konklusjoner."),
                C("b", "Sammenligne med samme periode året før", "Riktig! Year-on-year-sammenligning fjerner sesongeffekt.", correct=True),
                C("c", "Bare se på totale tall", "Sesong skjuler virkelig effekt."),
                C("d", "Tilfeldig", "Strukturert metode.")],
               "Detaljhandel-bransjen lever av YoY-sammenligning. Standard analytisk teknikk."),
            ex("A/B-test", "Hvorfor bruke A/B-test?",
               [C("a", "Pynt", "Kraftfull metode."),
                C("b", "Eliminerer eksterne faktorer — sammenligner to varianter samtidig", "Riktig! Best-praksis for å isolere kausalitet.", correct=True),
                C("c", "Bare for store", "Brukes alle størrelser."),
                C("d", "Lovstridig", "Lovlig.")],
               "Send 50 % trafikk til variant A, 50 % til B. Mål forskjellen. Kontrollert eksperiment.")]),
        ph("🎯", "Kontrollfasen — start på neste runde",
           "Lukk loopen.",
           "Kontrollfasen er starten på neste planleggingsperiode. Læring fra forrige runde bygges inn i neste års strategi. Det er hvordan markedsføring vokser fra håndverk til vitenskap. Mange bedrifter glemmer dette — gjør samme feil år etter år. Disiplinert review er konkurransefortrinn.",
           [("LÆRING ER PRODUKT", "Hver kampanje gir innsikt for neste."),
            ("CYKLISK", "Plan → utfør → mål → lær → ny plan.")],
           "Hva har du lært av siste prosjekt du var med på? Hvordan brukes læringen videre?",
           [ex("Prosess", "Hvordan ser læringssyklusen ut?",
               [C("a", "Plan → utfør → ferdig", "Mangler læring og iterasjon."),
                C("b", "Plan → utfør → mål → lær → ny plan", "Riktig! Cyklisk læring.", correct=True),
                C("c", "Bare planlegging", "For smalt."),
                C("d", "Tilfeldig", "Strukturert."),],
               "PDCA-syklus (Plan-Do-Check-Act) er klassisk modell. Brukt i kvalitetsledelse i 80+ år."),
            ex("Hva mister man", "Hva mister bedrifter som ikke gjør review?",
               [C("a", "Ingenting", "Mye."),
                C("b", "Læring som kunne forbedret neste kampanje — gjentar samme feil", "Riktig! Klassisk feil i mange bedrifter.", correct=True),
                C("c", "Bare tid", "Strategisk verdi."),
                C("d", "Lovkrav", "Helt urelevant."),],
               "Bedrifter som dokumenterer læring konsistent har 3-5x bedre marketing-effekt over år. Forskning støtter dette."),
            ex("Disiplin", "Hva er kritisk for kontrollfasen?",
               [C("a", "Tilfeldig", "Strukturert."),
                C("b", "Disiplinert review-prosess — ikke bare arkivering", "Riktig! Faste reviews i kalenderen, dokumenterte læringspoeng.", correct=True),
                C("c", "Bare ledelse", "Bredt teamarbeid."),
                C("d", "Bare i krise", "Konstant prosess."),],
               "Best praksis: månedlige reviews + årlig retrospektiv. Læring akkumulerer.")]),
    ],
    ["Du forstår markedsmiksen som integrert sett av strategiske valg",
     "Du kan vurdere synergi mellom de 4 P-ene og avdekke sprik",
     "Du kan måle kommunikasjonseffekt med kjennskap, recall og preferanse",
     "Du behersker ROAS, ROI og analytics som verktøy for performance-måling",
     "Du forstår feilkilder ved måling og forskjellen på korrelasjon og kausalitet"])


g.write_modules([MIKS], "ML2-12 Markedsmiks og effektmåling")
