#!/usr/bin/env python3
"""ENT1 kap 8-10."""
import importlib.util
from pathlib import Path
spec = importlib.util.spec_from_file_location("g", Path(__file__).parent / ".gen-shared.py")
g = importlib.util.module_from_spec(spec); spec.loader.exec_module(g)
C, ph, ex, M = g.C, g.ph, g.ex, g.M


MFSALG = M("MarkedsforingSalgNystartede", "ent1", "ENT1-08", "Markedsføring og salg for nystartede", "📢",
    "markedsforing-salg-nystartede", "ent1",
    "Nå ut til de første kundene når merkevaren er ukjent og budsjettet lite. Guerilla marketing, sosiale medier, personlig salg og referanser er gull for nystartede.",
    "I starten er eierne de viktigste markedsførerne og selgerne. Ingen kjenner produktet bedre, ingen har sterkere insentiv. Outsourcing kommer senere.",
    "Lavbudsjett-kreativitet slår dyrt og kjedelig. Som ny gründer har du tiden, hjernen og motivasjonen — bruk dem.",
    [
        ph("🎨", "Guerilla Marketing",
           "Kreativ markedsføring med lavt budsjett.",
           "Skape oppmerksomhet uten dyre annonser. Stunts, gateteater, viral video, uvanlige plasseringer. Kahoot ble kjent ved å gi det gratis til lærere — som så solgte det videre til skolene sine. Kreativitet over budsjett.",
           [("KREATIVITET", "Slår budsjett ofte i tidlig fase."),
            ("VIRAL POTENSIAL", "Gode ideer sprer seg gratis.")],
           "Hvilke kreative markedsføringsstunt du har sett? Hvorfor virket de?",
           [ex("Hva", "Hva er guerilla marketing?",
               [C("a", "Bare aggressiv reklame", "Kreativ tilnærming."),
                C("b", "Kreativ, lavbudsjett — skape oppmerksomhet uten dyre annonser", "Riktig! Strategisk valg.", correct=True),
                C("c", "Krigsmetafor", "Helt feil tolkning."),
                C("d", "Bare militære kanaler", "Helt feil.")],
               "Begrepet kommer fra geriljakrig — bruke kreativitet og overraskelse mot overlegne motstandere."),
            ex("Eksempel", "Kahoot-eksempel?",
               [C("a", "Bare betalt reklame", "Tvert imot."),
                C("b", "Gratis til lærere — som spredte det viralt til skolene sine", "Riktig! Klassisk eksempel.", correct=True),
                C("c", "Tilfeldig", "Strukturert."),
                C("d", "Bare i USA", "Norsk eksempel.")],
               "Kahoot ble milliardselskap dels gjennom denne lavbudsjett-strategien. Validering + viral spredning."),
            ex("Når", "Når passer guerilla?",
               [C("a", "Bare for store", "Tvert imot — for små."),
                C("b", "Tidlig fase med lite kapital og mye tid", "Riktig! Match til situasjon.", correct=True),
                C("c", "Aldri", "Brukes mye."),
                C("d", "Tilfeldig", "Strategisk valg.")],
               "Når du har $0 marketing-budsjett men tid og kreativitet, er guerilla overlegen.")]),
        ph("📱", "Sosiale medier for gründere",
           "Bygge fellesskap og dialog.",
           "Bygge fellesskap og dialog med kundene gjennom TikTok, Instagram, LinkedIn. Velg én eller to plattformer der målgruppen er, ikke prøv å være overalt. Konsistens er viktigere enn frekvens. Vipps har vokst eksplosivt på TikTok.",
           [("VELG ÉN", "Bedre å være sterk på én plattform enn svak på alle."),
            ("KONSISTENS", "Regelmessig poster slår sporadiske bursts.")],
           "Hvilken plattform passer ideen din best? Hvorfor?",
           [ex("Strategi", "Hva er beste strategi?",
               [C("a", "Være på alle", "For mye for én person."),
                C("b", "Velge én eller to plattformer der målgruppen er", "Riktig! Fokus over spredning.", correct=True),
                C("c", "Bare på Facebook", "For smalt."),
                C("d", "Tilfeldig", "Strukturert valg.")],
               "Bedre å være sterk på TikTok enn middels på 5 plattformer. Fokus."),
            ex("Plattformer", "Hvilken målgruppe?",
               [C("a", "TikTok bare gamle", "Tvert imot."),
                C("b", "TikTok 15-25, Instagram 20-40, Facebook 30+, LinkedIn B2B", "Riktig! Match til målgruppe.", correct=True),
                C("c", "Tilfeldig", "Strukturert."),
                C("d", "Bare i USA", "Globalt.")],
               "Sjekk hvor målgruppen din er. Ikke gå dit fordi det er trendy — gå dit fordi de er der."),
            ex("Vipps", "Hva gjorde Vipps?",
               [C("a", "Bare TV-reklame", "Mer enn det."),
                C("b", "Viral innhold på TikTok og Instagram — humoristisk, lokal", "Riktig! Vipps er case-studie.", correct=True),
                C("c", "Tilfeldig", "Strategisk."),
                C("d", "Aldri sosiale medier", "Helt feil.")],
               "Vipps' sosial-strategi: humor, norsk, rask respons. Bygde merkevare som 'norsk og folkelig'.")]),
        ph("📚", "Innholdsmarkedsføring",
           "Del kunnskap som er nyttig.",
           "Del kunnskap som er nyttig for kunden for å bygge tillit. Gründer-blogger, video-tutorials, gratis e-bøker. 'Hjelp, ikke selg' — over tid blir du den foretrukne eksperten. DnB sin Magma er klassisk eksempel — gir bort kunnskap, vinner kunder.",
           [("VERDI FØRST", "Gi gratis verdi før du ber om noe."),
            ("AUTORITET", "Bli ekspert i nisjen — kunder følger.")],
           "Hva er du ekspert på? Hvordan kunne du delt kunnskap?",
           [ex("Prinsipp", "Hva er kjernen?",
               [C("a", "Bare selge", "Tvert imot."),
                C("b", "Hjelp først, salg kommer naturlig", "Riktig! Tillitsbygging.", correct=True),
                C("c", "Tilfeldig", "Strukturert."),
                C("d", "Lovkrav", "Strategisk valg.")],
               "Hubspot bygde milliardselskap på å gi bort markedsføring-guider gratis. Standard nå."),
            ex("Frekvens", "Hvor ofte publisere?",
               [C("a", "Aldri", "For lite."),
                C("b", "Minst ukentlig — konsistens er nøkkelen", "Riktig! Bygger momentum.", correct=True),
                C("c", "Bare en gang", "For lite."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Sporadisk innhold mister momentum. Velg én kanal og publiser konsistent der."),
            ex("Norsk eksempel", "Hvilken norsk?",
               [C("a", "REMA 1000", "Reklame-fokusert."),
                C("b", "DnB Magma — bygger DnB som ekspert via verdifullt innhold", "Riktig! Klassisk eksempel.", correct=True),
                C("c", "Tilfeldig", "Strukturert."),
                C("d", "Bare amerikanske", "Norske gjør det også.")],
               "Andre: Equinor sin Energi-podkast, Schibsted sine guider, Nordnet sin investorblogg.")]),
        ph("🤝", "Personlig salg",
           "Banking on doors.",
           "Den viktigste kanalen for nystartede. 'Banking on doors' — direkte kontakt med potensielle kunder. Hver salgssamtale gir læring om hva som virker. Outsource ikke salget — som gründer må DU selge selv først. Klarna brukte 3 år på direkte salg før de skalerte.",
           [("BANKING ON DOORS", "Direkte kontakt slår alle kanaler tidlig."),
            ("LÆRING", "Hver samtale lærer om kunden.")],
           "Hvor mange potensielle kunder har du snakket direkte med om ideen din?",
           [ex("Hvorfor", "Hvorfor må gründer selge selv?",
               [C("a", "Spare penger", "Sekundært."),
                C("b", "Lærer mest om markedet — ingen andre kan i tidlig fase", "Riktig! Kunnskap er kritisk.", correct=True),
                C("c", "Lovkrav", "Helt urelevant."),
                C("d", "Bare i USA", "Universal sannhet.")],
               "Steve Blank: 'Get out of the building.' Gründer må snakke med kunder direkte."),
            ex("Klarna", "Hva gjorde Klarna?",
               [C("a", "Bare reklame", "Tvert imot."),
                C("b", "3 år direkte salg til nettbutikker før skalering", "Riktig! Disiplinert oppstart.", correct=True),
                C("c", "Tilfeldig", "Strukturert."),
                C("d", "Bare via venner", "Profesjonelt salg.")],
               "Klarna er nå milliardselskap. Tidlig disiplinert salg bygde fundamentet."),
            ex("Antall", "Hvor mange samtaler?",
               [C("a", "1-2", "For få."),
                C("b", "Mange — sett mål av samtaler/uke", "Riktig! Strukturert tilnærming.", correct=True),
                C("c", "Tilfeldig", "Strukturert."),
                C("d", "Bare hvis billig", "Investering verdt det.")],
               "Beste gründere: 5+ kundesamtaler per uke i tidlig fase. Bygger forståelse og pipeline.")]),
        ph("👥", "Referansemarkedsføring",
           "Bruke fornøyde kunder.",
           "Bruk fornøyde kunder for å skaffe nye (Word of Mouth). Anbefalingen fra en venn er kraftigere enn alle annonser sammen. Be aktivt om henvisninger — de fleste fornøyde kunder anbefaler ikke uten å bli spurt. Klassisk undervurdert kanal.",
           [("WOM", "Sterkeste markedsføringsform — gratis."),
            ("AKTIV BE", "Spør — folk anbefaler ikke uten oppfordring.")],
           "Hvordan ville du oppfordret kunder til å henvise andre?",
           [ex("Verdi", "Hvor verdifull er WOM?",
               [C("a", "Lite", "Tvert imot."),
                C("b", "Sterkeste markedsføringsform — anbefaling fra venn slår all reklame", "Riktig! Forskningsbasert.", correct=True),
                C("c", "Tilfeldig", "Strukturert effekt."),
                C("d", "Lovkrav", "Helt urelevant.")],
               "Nielsen-forskning: 92 % stoler på anbefaling fra venner. 33 % på reklame. Stor forskjell."),
            ex("Be aktivt", "Hvorfor be om henvisninger?",
               [C("a", "Tilfeldig", "Strukturelt."),
                C("b", "De fleste fornøyde kunder anbefaler ikke uten å bli spurt", "Riktig! Aktivt steg.", correct=True),
                C("c", "Lovkrav", "Helt urelevant."),
                C("d", "Bare for store", "Gjelder alle."),],
               "Test: ble du spurt om å anbefale sist du var fornøyd? Sjelden — det er taps-mulighet."),
            ex("Insentiver", "Bør man gi insentiver?",
               [C("a", "Aldri", "Kan virke."),
                C("b", "Av og til — Dropbox vokste eksplosivt med 'gi 500 MB, få 500 MB'", "Riktig! Klassisk vekst-trick.", correct=True),
                C("c", "Tilfeldig", "Strukturert."),
                C("d", "Lovstridig", "Lovlig."),],
               "Refer-a-friend programmer kan akselerere vekst dramatisk. Krever produkt verd å anbefale.")]),
        ph("🌐", "Nettverksbygging",
           "Bruke eksisterende kontakter.",
           "Bruk eksisterende kontakter og delta på gründer-treff (StartupLab, MESH, Innovasjon Norge events). Mange forretningsmuligheter starter ved en samtale ved kaffemaskinen — ikke en LinkedIn-melding. Bygg nettverk før du trenger det.",
           [("EKSISTERENDE KONTAKTER", "Begynn der du allerede er kjent."),
            ("FYSISK SLÅR DIGITAL", "Ekte møter bygger sterkere relasjoner.")],
           "Hvilke nettverk har du allerede? Hvem kunne hjulpet deg?",
           [ex("Hvor starte", "Hvor starte nettverksbygging?",
               [C("a", "Tilfeldig", "Strukturert."),
                C("b", "Eksisterende kontakter først — venner, kolleger, alumni", "Riktig! Lavest barriere.", correct=True),
                C("c", "Bare LinkedIn", "For smalt."),
                C("d", "Bare gjennom annonser", "For passivt.")],
               "De fleste forretningsmuligheter kommer fra 'andre-grads' kontakter — venners venner."),
            ex("Norske miljøer", "Hvor møte gründere?",
               [C("a", "Bare på nett", "Fysisk er bedre."),
                C("b", "StartupLab Oslo, MESH, Innovasjon Norge events, lokale meetups", "Riktig! Aktivt miljø.", correct=True),
                C("c", "Bare i utlandet", "Norge har sterke miljøer."),
                C("d", "Tilfeldig", "Strukturert.")],
               "StartupLab er Norges største startup-hub. Mange suksesser har kommet derfra."),
            ex("Timing", "Når bygge nettverk?",
               [C("a", "Bare når man trenger", "For sent."),
                C("b", "Bygg nettverk før du trenger det — relasjoner tar tid", "Riktig! Proaktiv.", correct=True),
                C("c", "Tilfeldig", "Strukturert."),
                C("d", "Bare etter suksess", "For sent."),],
               "Karateka: 'Plant trees before you need shade.' Nettverk er trærne.")]),
        ph("🔍", "Digital synlighet (SEO)",
           "Bli funnet på Google.",
           "Sørge for at folk finner deg når de søker etter problemet du løser. Google Søkekonsoll, Google Analytics — gratis verktøy som forteller hva folk faktisk søker etter. Skriv innhold som svarer på de spørsmålene. SEO tar 6-12 måneder å virke, men holder lenge.",
           [("INTENSJON", "SEO fanger folk som faktisk søker etter løsning."),
            ("LANG SIKT", "Tar tid, men holder lenge.")],
           "Hva ville folk søkt på Google for å finne din bedrift?",
           [ex("SEO-tid", "Hvor lang tid tar SEO?",
               [C("a", "1 dag", "For kort."),
                C("b", "6-12 måneder for å se reell trafikk", "Riktig! Lang sikt.", correct=True),
                C("c", "10 år", "For langt."),
                C("d", "Tilfeldig", "Strukturert."),],
               "SEO er investering, ikke kortsiktig. Men holder lenge når du er etablert."),
            ex("Verktøy", "Gratis verktøy?",
               [C("a", "Ingen", "Mange finnes."),
                C("b", "Google Search Console, Google Analytics, Google Trends", "Riktig! Alle gratis.", correct=True),
                C("c", "Bare betalte", "Helt feil."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Google gir bort enorm verdi gratis. Bruk verktøyene aktivt."),
            ex("Strategi", "Hva er beste startstrategi?",
               [C("a", "Tilfeldig", "Strukturert."),
                C("b", "Skriv innhold som svarer på spørsmål målgruppen din søker etter", "Riktig! Match intensjon.", correct=True),
                C("c", "Bare logo-design", "Helt feil."),
                C("d", "Lovkrav", "Strategisk valg.")],
               "Sjekk søkevolum med Google Keyword Planner. Skriv innhold for de spørsmålene.")]),
        ph("🎯", "Salgstrakt",
           "Oppmerksomhet → interesse → vurdering → kjøp.",
           "Kundereise gjennom 4 stadier. Mål antall personer i hver fase. Hvis 1000 ser annonsen, 100 klikker, 10 ber om demo, 1 kjøper — er konvertering 0,1 %. Tall som dette gjør markedsføringen styrbar. Fokus optimalisering på flaskehalser.",
           [("4 STADIER", "Oppmerksomhet, interesse, vurdering, kjøp."),
            ("FLASKEHALS", "Optimaliser der folk faller fra.")],
           "Tegn salgstrakten for en bedrift du kjenner. Hvor er flaskehalsene?",
           [ex("Stadier", "4 stadier?",
               [C("a", "Tilfeldig", "Strukturert."),
                C("b", "Oppmerksomhet, interesse, vurdering, kjøp (AIDA-lignende)", "Riktig! Klassisk modell.", correct=True),
                C("c", "Bare kjøp", "For smalt."),
                C("d", "Bare reklame", "For smalt.")],
               "Trakt-metaforen: bredt på toppen, smalt på bunnen. Mange begynner, få kjøper."),
            ex("Måle", "Hvorfor måle hver fase?",
               [C("a", "Tilfeldig", "Strategisk."),
                C("b", "Identifisere flaskehalser — hvor folk faller fra", "Riktig! Optimaliseringspoeng.", correct=True),
                C("c", "Lovkrav", "Helt urelevant."),
                C("d", "Bare estetikk", "Strategisk verdi."),],
               "Hvis 90 % faller fra mellom interesse og vurdering, vet du hvor du må fikse."),
            ex("Konvertering", "1000 → 100 → 10 → 1. Hva er konvertering?",
               [C("a", "10 %", "Helt feil."),
                C("b", "0,1 % fra topp til bunn", "Riktig! 1/1000.", correct=True),
                C("c", "1 %", "Feil.")],
               "Lav konvertering er normalt på topp av trakt. Optimaliser hvert stadium for å øke total.")]),
        ph("👤", "Eierne som markedsførere",
           "Beste salgsteam i starten.",
           "I starten er eierne de viktigste markedsførerne og selgerne. Ingen kjenner produktet bedre, ingen har sterkere insentiv. Outsourcing kommer senere — først må gründerne lære markedet selv. Brian Chesky (Airbnb) sov hos kunder for å lære.",
           [("KUNNSKAP", "Gründer kjenner produktet best."),
            ("INSENTIV", "Gründer har sterkest motivasjon for suksess.")],
           "Når kan gründer overlate marketing til andre?",
           [ex("Hvorfor", "Hvorfor må gründer markedsføre selv?",
               [C("a", "Spare penger", "Sekundært."),
                C("b", "Beste produktkunnskap + sterkest insentiv + lærer markedet", "Riktig! Multi-fordel.", correct=True),
                C("c", "Lovkrav", "Helt urelevant."),
                C("d", "Bare i krise", "Konstant tidlig.")],
               "Gründer-til-kunde-kontakt er undervurdert. Bygger forståelse og relasjoner."),
            ex("Outsource", "Når outsource?",
               [C("a", "Aldri", "Senere er det riktig."),
                C("b", "Når du har systematisert prosessen og kan trene andre", "Riktig! Systemer først.", correct=True),
                C("c", "Bare når dyrt", "Strategisk vurdering."),
                C("d", "Tilfeldig", "Strukturert."),],
               "Du kan ikke outsource det du ikke selv mestrer. Lær først, deleger så."),
            ex("Brian Chesky", "Hva gjorde Airbnb-grunnlegger?",
               [C("a", "Bare reklame", "Mer dramatisk."),
                C("b", "Sov hos kunder, fotograferte leiligheter selv — for å lære", "Riktig! Klassisk eksempel.", correct=True),
                C("c", "Bare nettsted", "For smalt."),
                C("d", "Tilfeldig", "Strukturert."),],
               "Y Combinators 'Do things that don't scale'. Manuelt arbeid i tidlig fase bygger fundament.")]),
        ph("🚀", "Startups marketing-prinsipper",
           "Lavbudsjett-kreativitet vinner.",
           "Lavbudsjett-kreativitet slår dyrt og kjedelig. Som ny gründer har du tiden, hjernen og motivasjonen — bruk dem. Test mye, lær raskt, dobbel ned på det som virker. Glem reklamebyråer i tidlig fase. Du er den beste markedsføreren bedriften har.",
           [("KREATIVITET > BUDSJETT", "Tid og hjerne er gratis ressurser."),
            ("TEST + LÆR", "Iterativ tilnærming til markedsføring.")],
           "Hva er den viktigste lærdommen om marketing for nystartede?",
           [ex("Prinsipp", "Hovedprinsipp?",
               [C("a", "Bare betalt reklame", "For smalt."),
                C("b", "Kreativitet + iterasjon + læring slår budsjett", "Riktig! Strategisk fokus.", correct=True),
                C("c", "Tilfeldig", "Strukturert."),
                C("d", "Bare ide", "For smalt.")],
               "Best gründere kombinerer kreativitet med disiplinert måling. Lærer raskt hva som virker."),
            ex("Reklamebyrå", "Når trenge byrå?",
               [C("a", "Fra dag 1", "For tidlig."),
                C("b", "Når du har systematisert hva som virker — byråer skalerer, ikke oppdager", "Riktig! Riktig fase.", correct=True),
                C("c", "Aldri", "Senere er det riktig."),
                C("d", "Tilfeldig", "Strukturert valg.")],
               "Byråer er gode til å skalere kjente formater. Mindre gode til å oppdage hva som virker for ditt nye produkt."),
            ex("Lærdom", "Beste lærdommen?",
               [C("a", "Bare bruk penger", "For smalt."),
                C("b", "Du er den beste marketer-bedriften har — i tidlig fase", "Riktig! Selv-tro.", correct=True),
                C("c", "Tilfeldig", "Strukturert."),
                C("d", "Lovkrav", "Strategisk valg."),],
               "Mange gründere undervurderer egen marketing-evne. Test selv, lær selv, vinn selv.")]),
    ],
    ["Du forstår at lavbudsjett-kreativitet slår dyrt og kjedelig i tidlig fase",
     "Du behersker guerilla marketing, sosiale medier og innholdsmarkedsføring",
     "Du ser personlig salg som beste kanal for nystartede — banking on doors",
     "Du kan måle salgstrakten og identifisere flaskehalser",
     "Du forstår at gründer må markedsføre selv først — outsourcing kommer senere"])


LOV = M("LovverkAvtalerHms", "ent1", "ENT1-09", "Lovverk, avtaler og HMS", "⚖️",
    "lovverk-avtaler-hms", "ent1",
    "Sikkerhet og juridisk trygghet — rammene som beskytter bedriften og gjør vekst mulig. Dårlig juridisk arbeid kan ta livet av selv den beste ide.",
    "Norske gründere ignorerer ofte juridiske detaljer i tidlig fase. Det kommer tilbake som store problemer når bedriften vokser. Gjør det rett fra start.",
    "Orden i sysakene gir troverdighet og trygghet for vekst. Investorer, banker og store kunder forventer dokumentert HMS, GDPR-compliance og rene avtaler.",
    [
        ph("📚", "Relevante lover",
           "Hvilke lover påvirker?",
           "Avtaleloven (når er en avtale bindende?), kjøpsloven (B2B-handel), forbrukerkjøpsloven (B2C-handel), markedsføringsloven (reklamens grenser), arbeidsmiljøloven (ansattes rettigheter), regnskapsloven, skatteloven. En gründer trenger ikke være jurist, men må kjenne grunnleggende regler.",
           [("FLERE LOVER", "Multi-lov rammeverk for bedrifter."),
            ("GRUNNLEGGENDE", "Kjenne hovedreglene i hver.")],
           "Hvilke lover er mest aktuelle for ideen din?",
           [ex("Hvilke", "Hvilke er sentrale?",
               [C("a", "Bare en", "For smalt."),
                C("b", "Avtaleloven, kjøpsloven, forbrukerkjøpsloven, markedsføringsloven, arbeidsmiljøloven", "Riktig! Multi-lov.", correct=True),
                C("c", "Bare i USA", "Norske lover."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Hver lov dekker et område. Bedriften må forholde seg til flere samtidig."),
            ex("Avtaleloven", "Hva sier den?",
               [C("a", "Bare for store", "Gjelder alle."),
                C("b", "Når er en avtale bindende — tilbud, aksept, vilkår", "Riktig! Grunnleggende kontraktsrett.", correct=True),
                C("c", "Bare for B2C", "Begge.")],
               "Muntlig avtale er like bindende som skriftlig — bare vanskeligere å bevise. Skriv ned!"),
            ex("Forbrukerkjøps", "Forbrukerkjøpsloven gjelder?",
               [C("a", "Alle salg", "For bredt."),
                C("b", "Bare salg til forbrukere — ikke B2B", "Riktig! Strukturell forskjell.", correct=True),
                C("c", "Bare B2B", "Tvert imot."),
                C("d", "Tilfeldig", "Strukturert."),],
               "Forbrukerkjøpsloven gir kunder sterkere vern enn kjøpsloven. Husk skillet.")]),
        ph("📝", "Kontrakter",
           "Skriftlige avtaler er gull.",
           "Viktigheten av skriftlige avtaler med kunder, leverandører og ansatte. 'Avtaler er bindende' selv om de er muntlige — men bevisbyrden er enorm. En enkel skriftlig kontrakt sparer deg for konflikter senere. Bruk maler — ikke finn opp hjulet.",
           [("SKRIFTLIG", "Bevis ved tvist."),
            ("MALER", "Bruk standardavtaler — ikke finn opp.")],
           "Hvilke avtaler ville du sikret skriftlig fra dag 1?",
           [ex("Hvorfor", "Hvorfor skriftlig?",
               [C("a", "Lovkrav", "Ofte ikke."),
                C("b", "Bevis ved konflikt — muntlig er bindende men umulig å bevise", "Riktig! Praktisk verdi.", correct=True),
                C("c", "Tilfeldig", "Strukturert."),
                C("d", "Bare for store", "Gjelder alle."),],
               "Test: kan du bevise hva som ble avtalt? Hvis bare 'min hukommelse', taper du i retten."),
            ex("Med kunder", "Hva sikre skriftlig?",
               [C("a", "Tilfeldig", "Strukturert."),
                C("b", "Pris, leveringsbetingelser, garantier, ansvarsbegrensning", "Riktig! Kjernevilkår.", correct=True),
                C("c", "Bare pris", "For smalt."),
                C("d", "Lovkrav", "Strategisk valg.")],
               "Standardvilkår på faktura er minimum. For større avtaler: egen kontrakt."),
            ex("Maler", "Hvor finne maler?",
               [C("a", "Måtte alltid lage selv", "Helt feil."),
                C("b", "Standardavtaler fra advokat-firmaer, bransjeorganer", "Riktig! Mange tilgjengelige.", correct=True),
                C("c", "Tilfeldig", "Strukturert."),
                C("d", "Lovkrav", "Frivillig.")],
               "NHO, Virke, advokatkontorer publiserer maler. Tilpas til din situasjon, ikke kopier blindt.")]),
        ph("🦺", "HMS — Helse, miljø og sikkerhet",
           "Internkontrollforskriften.",
           "Internkontrollforskriften krever at alle bedrifter har systematisk HMS-arbeid. Selv en énmannsbedrift må ha skrevne prosedyrer for risikovurdering, opplæring og oppfølging. Arbeidstilsynet kan kontrollere uanmeldt. Bøter ved brudd kan være store.",
           [("ALLE BEDRIFTER", "Selv små må ha HMS-system."),
            ("DOKUMENTERT", "Skriftlig HMS-arbeid er lovkravet.")],
           "Hvilke HMS-risikoer ville du dokumentert for en lokal kafé?",
           [ex("Hvem omfattes", "Hvem må ha HMS?",
               [C("a", "Bare store", "Alle bedrifter."),
                C("b", "Alle bedrifter — selv énmannsbedrift", "Riktig! Lovkrav for alle.", correct=True),
                C("c", "Bare offentlige", "Privat sektor også."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Internkontrollforskriften har ingen størrelses-grense. Skala på kravene varierer."),
            ex("Arbeidstilsynet", "Kan de kontrollere?",
               [C("a", "Aldri", "Konstant kontroll."),
                C("b", "Ja — uanmeldt — og kan stenge drift ved brudd", "Riktig! Sterke beføyelser.", correct=True),
                C("c", "Bare etter klage", "Også proaktivt."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Arbeidstilsynet er aktivt. Bedrifter rammes regelmessig av kontroller."),
            ex("Konsekvens", "Konsekvenser av brudd?",
               [C("a", "Bare advarsel", "Mer alvorlig."),
                C("b", "Bøter, pålegg, stengning av drift", "Riktig! Reelle sanksjoner.", correct=True),
                C("c", "Lovstridig å straffe", "Helt feil."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Bøter for HMS-brudd kan være over 1 mill kr for små bedrifter. Krever proaktiv håndtering.")]),
        ph("🔍", "Risikovurdering",
           "Identifisere farer.",
           "Identifisere farer og iverksette tiltak for å forebygge ulykker eller sykdom. Fysiske farer (brann, fall), psykososiale (stress, mobbing), kjemiske (allergi). Skriv det ned — udokumentert HMS er som ingen HMS. Standard ROS-analyse: vurder sannsynlighet × konsekvens.",
           [("ROS-ANALYSE", "Risiko + Sårbarhet = struktur."),
            ("DOKUMENTERT", "Skrevne prosedyrer = bevis ved kontroll.")],
           "Lag en enkel ROS for en lokal kafé — 3 risikoer.",
           [ex("ROS", "Hva er ROS?",
               [C("a", "Tilfeldig", "Strukturert akronym."),
                C("b", "Risiko og sårbarhet — analyse av hva som kan gå galt", "Riktig! Standard verktøy.", correct=True),
                C("c", "Bare for offshore", "Brukes overalt."),
                C("d", "Tilfeldig", "Strukturert.")],
               "ROS-analyser brukes både i HMS, IT-sikkerhet, beredskapsplanlegging."),
            ex("Type risikoer", "Hvilke typer?",
               [C("a", "Bare fysisk", "For smalt."),
                C("b", "Fysiske, psykososiale, kjemiske, biologiske", "Riktig! Multi-dimensjonal.", correct=True),
                C("c", "Bare brann", "For smalt."),
                C("d", "Tilfeldig", "Strukturert."),],
               "Psykososiale risikoer (stress, mobbing) er ofte oversett — men reelle og lovregulerte."),
            ex("Skrive ned", "Hvorfor skrive?",
               [C("a", "Pynt", "Lovkrav."),
                C("b", "Lovkrav + bevis ved kontroll + grunnlag for tiltak", "Riktig! Multi-formål.", correct=True),
                C("c", "Tilfeldig", "Strukturert."),
                C("d", "Bare for revisor", "Bredere."),],
               "Udokumentert HMS = ingen HMS i Arbeidstilsynets øyne. Sett av tid til skriftlig arbeid.")]),
        ph("🔒", "Personvern (GDPR)",
           "Strenge regler.",
           "Regler for hvordan bedriften skal håndtere kunde- og ansattopplysninger. Krev samtykke før innsamling, dokumenter formål, slett data når formålet er oppfylt. Brudd kan gi 4 % av global omsetning i bot — også for små bedrifter. Datatilsynet håndhever.",
           [("SAMTYKKE", "Krev aktivt samtykke for behandling."),
            ("4 % OMSETNING", "Maks bot — selv små bedrifter rammes.")],
           "Hvilke personopplysninger samler bedriften du jobber for / kjenner?",
           [ex("Maks bot", "Hvor høy kan boten være?",
               [C("a", "10 000 kr", "For lavt."),
                C("b", "4 % av global omsetning eller 20 mill euro", "Riktig! Strenge sanksjoner.", correct=True),
                C("c", "100 000 kr", "For lavt for store brudd."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Meta er bøtelagt over 1 mrd euro under GDPR. Selv små norske bedrifter har fått bøter på flere hundre tusen."),
            ex("Datainnbrudd", "Hvor raskt melde?",
               [C("a", "Aldri", "Lovkrav."),
                C("b", "Innen 72 timer etter oppdagelse", "Riktig! Standard frist.", correct=True),
                C("c", "30 dager", "For sent."),
                C("d", "Bare hvis stort", "Generelt krav.")],
               "Frist starter når du oppdager — ikke når du har løst. Ha rutiner klar."),
            ex("Rettigheter", "Brukerens rettigheter?",
               [C("a", "Bare innsyn", "Mer enn det."),
                C("b", "Innsyn, retting, sletting, dataportabilitet", "Riktig! Fire kjerne-rettigheter.", correct=True),
                C("c", "Ingen", "Helt feil."),
                C("d", "Tilfeldig", "Strukturert."),],
               "Sett opp prosess for å håndtere innsynsbegjæringer. 30 dager til å svare.")]),
        ph("🛡️", "Immaterielle rettigheter (IPR)",
           "Patent, design, varemerke.",
           "Beskyttelse av oppfinnelser (patent), design (designregistrering) og navn/logo (varemerke). Patent koster 50 000-500 000 kr og varer 20 år. Varemerke er billigere og varer evig så lenge det fornyes. Patentstyret håndterer alt i Norge. Internasjonalt via WIPO.",
           [("3 TYPER", "Patent (oppfinnelser), design, varemerke (navn/logo)."),
            ("PATENTSTYRET", "Norsk myndighet for IPR.")],
           "Hva ville du beskyttet av immaterielle verdier i ideen din?",
           [ex("3 typer", "Hvilke typer IPR finnes?",
               [C("a", "Bare patent", "For smalt."),
                C("b", "Patent (oppfinnelser), design, varemerke (navn/logo)", "Riktig! Tre hovedtyper.", correct=True),
                C("c", "Bare logo", "For smalt."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Hver type har egne søknadsprosess. Patent er dyrest og tregest, varemerke billigst og raskest."),
            ex("Patent kostnad", "Hva koster patent?",
               [C("a", "Gratis", "Krever penger."),
                C("b", "50 000-500 000 kr per land", "Riktig! Dyrt internasjonalt.", correct=True),
                C("c", "1000 kr", "For lavt."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Patenter koster mye fordi de gir 20 års monopol. Vurder om verdien rettferdiggjør kostnaden."),
            ex("Varemerke", "Hva varer evig?",
               [C("a", "Patent", "Bare 20 år."),
                C("b", "Varemerke — så lenge det fornyes", "Riktig! Coca-Cola fra 1893 fortsatt beskyttet.", correct=True),
                C("c", "Design", "Begrenset tid."),
                C("d", "Tilfeldig", "Strukturert."),],
               "Varemerker fornyes hvert 10. år. Coca-Cola-merket er over 130 år gammelt — fortsatt beskyttet.")]),
        ph("👔", "Arbeidsgiveransvar",
           "Plikter med ansatte.",
           "Plikter når man ansetter første medarbeider: skriftlig kontrakt, lønnsavregning, skattetrekk, arbeidsgiveravgift, OTP-pensjon, yrkesskadeforsikring, oppsigelsesvern. Bruk gjerne lønnssystem som Tripletex eller Conta. Komplekst — bruk regnskapsfører.",
           [("MANGE PLIKTER", "Multi-dimensjonalt arbeidsgiveransvar."),
            ("LØNNSSYSTEM", "Bruk verktøy — ikke regn manuelt.")],
           "Hva må være på plass før du ansetter første medarbeider?",
           [ex("Hva må være på plass", "Hva trengs?",
               [C("a", "Bare lønn", "For smalt."),
                C("b", "Skriftlig kontrakt, OTP, yrkesskadeforsikring, lønnsavregning", "Riktig! Multi-element.", correct=True),
                C("c", "Bare e-post", "For smalt."),
                C("d", "Tilfeldig", "Strukturert."),],
               "Sjekkliste fra Altinn eller Skatteetaten. Komplisert å huske alt selv."),
            ex("OTP", "Hva er OTP?",
               [C("a", "Tilfeldig", "Akronym."),
                C("b", "Obligatorisk tjenestepensjon — fra 1 ansatt med 20 %+ stilling", "Riktig! Lovkrav.", correct=True),
                C("c", "Bare for store", "For alle."),
                C("d", "Frivillig", "Lovkrav.")],
               "Manglende OTP gir bøter. Velg pensjonsleverandør (DnB, Storebrand, KLP)."),
            ex("Verktøy", "Hvilke verktøy?",
               [C("a", "Bare Excel", "For komplisert."),
                C("b", "Tripletex, Conta, Power Office Go — lønns- og regnskapssystemer", "Riktig! Norske systemer.", correct=True),
                C("c", "Bare papir", "Foreldet."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Lønnsystem koster 200-500 kr/mnd per ansatt. Verdt det — automatiserer skattetrekk, AGA, OTP.")]),
        ph("⚖️", "Etikk i entreprenørskap",
           "Korrupsjon og rettferdig konkurranse.",
           "Å gjøre det rette, selv når ingen ser på. Korrupsjon, misvisende reklame, urettferdig konkurranse — alt dette kan være lønnsomt på kort sikt, men ødelegger merkevaren og kan gi straffeforfølgelse på lang sikt. Norske lover gjelder norske bedrifter globalt.",
           [("LANGSIKT > KORTSIKT", "Etisk drift bygger merkevare."),
            ("GLOBAL JURISDIKSJON", "Norske lover følger norske bedrifter ut.")],
           "Hva ville du gjort hvis sjefen din ba deg betale bestikkelse for kontrakt?",
           [ex("Korrupsjon", "Hva sier norsk lov?",
               [C("a", "Lovlig hvis utlandet", "Helt feil."),
                C("b", "Forbudt under norsk lov — også i utlandet", "Riktig! Ekstraterritoriell jurisdiksjon.", correct=True),
                C("c", "Bare i Norge", "Helt feil."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Statoil-saken (Iran 2003): bot på 80 mill USD. Norske bedrifter holdes ansvarlige globalt."),
            ex("Hovedlærdom", "Hva er etisk hovedlærdom?",
               [C("a", "Tilfeldig", "Strukturelt."),
                C("b", "Etisk drift bygger merkevare; uetisk drift ødelegger den", "Riktig! Strategisk verdi.", correct=True),
                C("c", "Lovkrav", "Strategisk verdi."),
                C("d", "Bare for store", "Gjelder alle."),],
               "Patagonia, Stormberg, Tomra — bygget på etisk drift. Konkurransefortrinn."),
            ex("Test", "Etisk test?",
               [C("a", "Tilfeldig", "Strukturert."),
                C("b", "Aviskolonne-test: ville jeg vært stolt om handlingen sto på forsiden", "Riktig! Praktisk test.", correct=True),
                C("c", "Bare lov", "Etikk er bredere."),
                C("d", "Tilfeldig", "Strukturert."),],
               "Hvis du ikke vil at moren din ser handlingen i avisen — ikke gjør det.")]),
        ph("📊", "Dokumentasjon for vekst",
           "Investorer krever orden.",
           "Investorer, banker og store kunder forventer dokumentert HMS, GDPR-compliance, rene avtaler. Mange gründere mister investorer pga rotete dokumentasjon — selv med god ide. Orden i sysakene gir troverdighet og trygghet for vekst.",
           [("DUE DILIGENCE", "Investorer går gjennom alt."),
            ("PROAKTIV", "Bygg dokumentasjon fra start.")],
           "Hva ville investorer sett på i 'due diligence'?",
           [ex("Due diligence", "Hva er det?",
               [C("a", "Tilfeldig", "Strukturert."),
                C("b", "Investors gjennomgang av bedriftens dokumentasjon før investering", "Riktig! Standard prosess.", correct=True),
                C("c", "Bare regnskap", "For smalt."),
                C("d", "Lovkrav", "Frivillig prosess."),],
               "DD inkluderer juridisk, økonomisk, kommersiell, teknisk vurdering. Tar uker."),
            ex("Hva sjekkes", "Hva sjekker investorer?",
               [C("a", "Bare ide", "For smalt."),
                C("b", "Avtaler, IPR, regnskap, HMS, GDPR, ansatt-kontrakter", "Riktig! Helhetlig.", correct=True),
                C("c", "Bare team", "For smalt."),
                C("d", "Tilfeldig", "Strukturert."),],
               "Hvis dokumentasjon er rotete, krever investorene rabatt — eller dropper investeringen."),
            ex("Proaktiv", "Hvorfor bygge tidlig?",
               [C("a", "Tilfeldig", "Strategisk."),
                C("b", "Vanskelig å rydde opp senere — bedre å gjøre rett fra start", "Riktig! Forebygging.", correct=True),
                C("c", "Lovkrav", "Strategisk valg."),
                C("d", "Bare for tek", "Gjelder alle."),],
               "Standard advokat-tariff for å rydde opp i etablert bedrift: 500 000+. Bedre å betale 50 000 i starten.")]),
        ph("🎯", "Hovedlærdom — orden gir vekst",
           "Profesjonalitet fra dag 1.",
           "Orden i sysakene gir troverdighet og trygghet for vekst. Investorer, banker og store kunder forventer dokumentert HMS, GDPR-compliance, rene avtaler. Uten det stoppes mange dører — uansett hvor god ideen er.",
           [("PROFESJONELL", "Behandle bedriften som profesjonell organisasjon."),
            ("STRATEGISK", "Juridisk arbeid er strategisk forsvar.")],
           "Hva er den viktigste lærdommen om juss og etikk for entreprenører?",
           [ex("Hovedlærdom", "Hva er den viktigste?",
               [C("a", "Bare ide teller", "For smalt."),
                C("b", "Orden i sysakene = grunnlag for vekst og investering", "Riktig! Multi-stakeholder-krav.", correct=True),
                C("c", "Tilfeldig", "Strukturert."),
                C("d", "Lovkrav", "Strategisk valg.")],
               "Mange suksess-startups har juridiske problemer som hindrer vekst. Forebygg fra start."),
            ex("Investering", "Hvor mye investere i juss?",
               [C("a", "Aldri", "For lite."),
                C("b", "5-10 % av tidlig kapital — verdt forebyggingen", "Riktig! Akseptabel investering.", correct=True),
                C("c", "100 %", "For mye."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Rådene fra advokat før etablering kan spare millioner senere. Betal nå eller mer senere."),
            ex("Hovedfeil", "Klassisk feil?",
               [C("a", "For mye juss", "Sjelden problem."),
                C("b", "Ignorere juss til problemer oppstår — for sent", "Riktig! Reaktiv tilnærming.", correct=True),
                C("c", "Tilfeldig", "Strukturelt."),
                C("d", "Lovkrav", "Helt urelevant.")],
               "'Penny wise, pound foolish' — spare på advokat = miste investering eller kunde.")]),
    ],
    ["Du forstår grunnleggende lover som påvirker bedrifter (avtaleloven, kjøpsloven, mfl.)",
     "Du kjenner viktigheten av skriftlige avtaler og hvorfor maler er smarte",
     "Du behersker HMS-kravene og kan gjøre enkel ROS-analyse",
     "Du forstår GDPR-kravene og 4 % omsetning som maks bot",
     "Du ser at orden i juridisk arbeid er strategisk forsvar — ikke kostnad"])


SAMARB = M("SamarbeidTeambygging", "ent1", "ENT1-10", "Samarbeid og teambygging", "🤝",
    "samarbeid-teambygging", "ent1",
    "Sammen er vi sterkere — utfyllende kompetanse og god dynamikk er ofte viktigere enn ideen. Investorer satser på team — ofte mer enn på produkt.",
    "En middels idé med fantastisk team vinner over en fantastisk idé med middels team. Investorer satser ofte mer på team enn på produkt.",
    "Mange gründerteam kollapser pga konflikt om eierskap — ikke pga produkt. Skriv aksjonæravtale TIDLIG.",
    [
        ph("👥", "Hvorfor team?",
           "Utfyllende kompetanse.",
           "Klassisk modell: 'Hacker' (teknisk), 'Hustler' (forretning) og 'Hipster' (design). De fleste vellykkede oppstartsbedrifter har minst to gründere — én alene har sjelden alle ferdighetene som trengs. Komplementære evner > like kopier.",
           [("HACKER + HUSTLER + HIPSTER", "Klassisk komplementær triade."),
            ("MULTI-FERDIGHET", "Få har alt selv.")],
           "Hva er din 'rolle' (hacker, hustler eller hipster)? Hvem trenger du på teamet?",
           [ex("3 typer", "Hva er klassisk gründertriaden?",
               [C("a", "Tilfeldig", "Strukturert."),
                C("b", "Hacker (teknisk), Hustler (forretning), Hipster (design)", "Riktig! Komplementære roller.", correct=True),
                C("c", "Bare en type", "For smalt."),
                C("d", "Lovkrav", "Strategisk valg.")],
               "Begrepet kommer fra Y Combinator-miljøet. Tre komplementære perspektiver."),
            ex("Solo", "Hvorfor solo-gründer ofte taper?",
               [C("a", "Tilfeldig", "Strukturelt."),
                C("b", "Få har alle nødvendige ferdigheter selv", "Riktig! Multi-ferdighet kreves.", correct=True),
                C("c", "Lovkrav", "Helt urelevant."),
                C("d", "Bare for tek", "Gjelder alle.")],
               "Solo-gründere kan lykkes (Mailchimp, Basecamp), men er statistisk sjeldent."),
            ex("Komplementær", "Hva betyr komplementær?",
               [C("a", "Like kopier", "Tvert imot."),
                C("b", "Utfyllende ferdigheter — ikke konkurrerende", "Riktig! Strukturell forskjell.", correct=True),
                C("c", "Bare venner", "For smalt."),
                C("d", "Tilfeldig", "Strukturert."),],
               "To ingeniører er ikke komplementært — bare dobbelt så mye av samme. Trenger forretning + design.")]),
        ph("🌊", "Team-modning (Tuckman)",
           "Forming, storming, norming, performing.",
           "Bruce Tuckmans fire faser: forming (oppstart, høflig), storming (konflikter, posisjoneringer), norming (regler etableres), performing (full effektivitet). Mange team gir opp i storming-fasen — det er normalt og må gjennomleves.",
           [("4 FASER", "Forming → storming → norming → performing."),
            ("STORMING NORMALT", "Konflikter er sunne — bygger team.")],
           "Hvilken fase er et team du har vært del av? Storming?",
           [ex("Faser", "Hva er Tuckmans 4 faser?",
               [C("a", "Tilfeldig", "Strukturert."),
                C("b", "Forming, storming, norming, performing", "Riktig! Klassisk modell.", correct=True),
                C("c", "Bare oppstart", "For smalt."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Tuckman publiserte i 1965. Lagt til 'adjourning' senere for team-avslutning."),
            ex("Storming", "Hva er storming?",
               [C("a", "Bare ros", "Tvert imot."),
                C("b", "Konflikter, posisjoneringer, definere roller", "Riktig! Sunn fase.", correct=True),
                C("c", "Slutten", "Det er adjourning."),
                C("d", "Tilfeldig", "Strukturert."),],
               "Storming er ikke svikt — det er bygging. Team som unngår storming når sjelden performing."),
            ex("Lærdom", "Hva er lærdommen?",
               [C("a", "Unngå konflikt", "Tvert imot."),
                C("b", "Konflikt er sunt — gjennomgå det med struktur", "Riktig! Strategisk håndtering.", correct=True),
                C("c", "Tilfeldig", "Strukturelt."),
                C("d", "Lovkrav", "Strategisk valg.")],
               "Mange team gir opp i storming. De som klarer det får full effektivitet i performing.")]),
        ph("🎭", "Belbins teamroller",
           "9 roller i et team.",
           "Meredith Belbin identifiserte 9 team-roller: idéskaperen, iverksetteren, koordinatoren, analytikeren m.fl. Alle roller er nødvendige; team som mangler én rolle kompenserer dårlig. Belbin-test kan brukes for å analysere ditt team.",
           [("9 ROLLER", "Multi-rolle-team."),
            ("BALANSE", "Manglende roller skaper svakhet.")],
           "Hvilken Belbin-rolle tror du er din naturlige?",
           [ex("Antall", "Hvor mange roller?",
               [C("a", "3", "For få."),
                C("b", "9", "Riktig! Belbins komplette modell.", correct=True),
                C("c", "20", "For mange."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Hver rolle har styrker og 'tillatte svakheter'. Sammen utfyller de hverandre."),
            ex("Idéskaper", "Hva gjør idéskaperen?",
               [C("a", "Tilfeldig", "Strukturert."),
                C("b", "Genererer kreative ideer og løsninger", "Riktig! Kreativ rolle.", correct=True),
                C("c", "Bare lytte", "Det er overvåkeren."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Hver rolle er beskrevet i Belbin-modellen. Idéskaper er en av de mest synlige."),
            ex("Test", "Hva er Belbin-testen?",
               [C("a", "Personlighetstest", "Spesifikk team-test."),
                C("b", "Spørreskjema som identifiserer dine teamroller", "Riktig! Praktisk verktøy.", correct=True),
                C("c", "IQ-test", "Helt feil."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Belbin-test er kommersiell tjeneste. Mange bedrifter bruker det for team-utvikling.")]),
        ph("💬", "Kommunikasjon i teamet",
           "Åpenhet og lytting.",
           "Åpenhet, aktiv lytting og konstruktiv tilbakemelding. Slack, Teams, Notion gjør den daglige kommunikasjonen lett — men ingen verktøy erstatter ærlige samtaler. Etablér rutiner for både formell og uformell kontakt. Sett av tid til 1:1.",
           [("ÅPENHET", "Si fra før det blir konflikt."),
            ("RUTINER", "Faste samtaler bygger sikkerhet.")],
           "Hvilke kommunikasjons-vaner ville du etablert i et nytt team?",
           [ex("Verktøy vs samtaler", "Hva er viktigst?",
               [C("a", "Slack alene", "For overflatisk."),
                C("b", "Verktøy + ekte samtaler — begge nødvendig", "Riktig! Komplementært.", correct=True),
                C("c", "Bare e-post", "For tregt."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Verktøy er tidssparere, ikke relasjon-byggere. Trenger fysisk/video-tid for tillit."),
            ex("1:1", "Hva er 1:1?",
               [C("a", "Tilfeldig", "Strukturert."),
                C("b", "Faste 1-mot-1 samtaler mellom leder og ansatt", "Riktig! Standard ledelsesverktøy.", correct=True),
                C("c", "Bare i krise", "Konstant praksis."),
                C("d", "Tilfeldig", "Strukturert."),],
               "Beste team har faste 1:1 ukentlig eller annenhver uke. Bygger tillit og fanger problemer tidlig."),
            ex("Aktivt lytte", "Hva betyr aktivt lytte?",
               [C("a", "Bare være stille", "For passivt."),
                C("b", "Forstå før du svarer — gjenta tilbake, still oppfølgingsspørsmål", "Riktig! Strukturert teknikk.", correct=True),
                C("c", "Tilfeldig", "Strukturert."),
                C("d", "Bare høre", "For passivt.")],
               "Stephen Covey: 'Forstå først, så bli forstått.' Klassisk innsikt om kommunikasjon.")]),
        ph("🤜", "Konflikthåndtering",
           "Løse uenigheter konstruktivt.",
           "Hvordan løse uenigheter før de ødelegger bedriften. Lytt aktivt, fokuser på problemet (ikke personen), søk felles interesser, kompromiss eller mekling. Aksjonæravtalen er førstelinjeforsvar mot eskalering. Eksterne meklere kan hjelpe.",
           [("PROBLEM > PERSON", "Skill mellom person og problem."),
            ("AKSJONÆRAVTALE", "Forebygging er bedre enn løsning.")],
           "Hvordan ville du håndtert konflikt med medgründer om strategi?",
           [ex("Problem vs person", "Hovedprinsippet?",
               [C("a", "Angripe personen", "For destruktivt."),
                C("b", "Skille person og problem — angripe problemet, ikke personen", "Riktig! Klassisk teknikk.", correct=True),
                C("c", "Ignorere", "Eskalerer."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Harvard Negotiation Project: 'Hard on the problem, soft on the people.' Effektiv tilnærming."),
            ex("Mekling", "Når mekling?",
               [C("a", "Aldri", "Effektivt verktøy."),
                C("b", "Når intern løsning ikke virker — ekstern part hjelper", "Riktig! Profesjonell hjelp.", correct=True),
                C("c", "Bare i retten", "Mekling unngår retten."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Mekling koster langt mindre enn rettsak. Mange tvister løses raskt med god mekler."),
            ex("Forebygging", "Beste forebygging?",
               [C("a", "Tilfeldig", "Strukturert."),
                C("b", "Aksjonæravtale + faste team-møter + åpenhet", "Riktig! Multi-tiltak.", correct=True),
                C("c", "Bare avtale", "For smalt."),
                C("d", "Lovkrav", "Strategisk valg.")],
               "Forebygging er overlegen håndtering. Avtaler + kultur er nøkkelen.")]),
        ph("🔥", "Motivasjon",
           "Indre vs ytre.",
           "Indre motivasjon (mestring, mening) vs ytre motivasjon (lønn, bonus). Daniel Pinks bok 'Drive' viser at autonomi, mestring og formål driver høy ytelse mer enn pengebelønning. Lønn er nødvendig men ikke tilstrekkelig.",
           [("INDRE > YTRE", "Indre motivasjon varer lenger."),
            ("DRIVE", "Autonomi + mestring + formål.")],
           "Hva motiverer deg mest — penger eller mening?",
           [ex("Pinks 3", "Hva er Daniel Pinks 3 drivere?",
               [C("a", "Tilfeldig", "Strukturert."),
                C("b", "Autonomi, mestring, formål", "Riktig! 'Drive'-modell.", correct=True),
                C("c", "Bare penger", "For smalt."),
                C("d", "Lovkrav", "Helt urelevant.")],
               "Pinks 'Drive' (2009) endret motivasjons-tenkning. Forskningsbasert."),
            ex("Lønn", "Hvor langt rekker lønn?",
               [C("a", "Uendelig", "Tvert imot."),
                C("b", "Nødvendig, men ikke tilstrekkelig — folk venner seg til lønn", "Riktig! Pengelykke flater ut.", correct=True),
                C("c", "Bare for unge", "Aldersnøytralt."),
                C("d", "Tilfeldig", "Strukturert."),],
               "Forskning: pengelykke flate ut etter ~75 000 USD i USA. Mer penger ≠ mer motivasjon."),
            ex("Formål", "Hvorfor formål?",
               [C("a", "Tilfeldig", "Strukturelt."),
                C("b", "Folk vil føle at arbeidet betyr noe — særlig yngre", "Riktig! Generasjons-skifte.", correct=True),
                C("c", "Bare i frivillig sektor", "Gjelder alle."),
                C("d", "Lovkrav", "Strategisk verdi."),],
               "Yngre prioriterer formål høyere enn forrige generasjoner. Strategisk tilpasning kreves.")]),
        ph("💻", "Virtuelle team",
           "Samarbeid via digitale verktøy.",
           "Samarbeid via digitale verktøy (Slack, Teams, Trello, Notion). Pandemien viste at det funker — men krever klarere prosesser, regelmessige videosamtaler, og bevisst innsats for å bygge team-følelsen som kommer naturlig på kontoret.",
           [("VERKTØY", "Slack, Teams, Notion, Trello er standard."),
            ("BEVISST INNSATS", "Team-følelse må bygges aktivt online.)")],
           "Hva er forskjellen på fysisk og virtuelt teamarbeid?",
           [ex("Verktøy", "Hvilke standard verktøy?",
               [C("a", "Bare e-post", "For begrenset."),
                C("b", "Slack/Teams (chat), Notion (dokumenter), Trello (oppgaver), Zoom (video)", "Riktig! Verktøystakk.", correct=True),
                C("c", "Bare telefon", "For begrenset."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Hver kategori har egne ledende verktøy. Velg hva som passer team-størrelse og kultur."),
            ex("Utfordring", "Hva er hovedutfordringen?",
               [C("a", "Tilfeldig", "Strukturelt."),
                C("b", "Bygge team-følelse og tillit uten fysisk kontakt", "Riktig! Strukturell utfordring.", correct=True),
                C("c", "Bare teknologi", "Sekundært."),
                C("d", "Lovkrav", "Helt urelevant.")],
               "Pandemien viste utfordringen: tillit bygges saktere virtuelt. Krever bevisst arbeid."),
            ex("Hybrid", "Beste tilnærming?",
               [C("a", "Bare virtuelt", "Mister noe."),
                C("b", "Hybrid — fysiske møter regelmessig + virtuell daglig kommunikasjon", "Riktig! Beste av begge.", correct=True),
                C("c", "Bare fysisk", "Mister fleksibilitet."),
                C("d", "Tilfeldig", "Strukturert valg.")],
               "Mange selskaper finner hybrid optimalt — fast i samme rom kvartalsvis, virtuell daglig.")]),
        ph("👤", "Lederrollen i oppstarten",
           "Fra 'doer' til 'enabler'.",
           "Gründerens rolle endrer seg. I starten er du 'doer' (gjør alt selv). Etter hvert 'enabler' (lar andre gjøre). Mange gründere klarer ikke overgangen — og blir flaskehalsen som hindrer veksten. Krever bevisst skifte i mindset.",
           [("DOER → ENABLER", "Skifte i fokus etter hvert som teamet vokser."),
            ("FLASKEHALS-RISIKO", "Gründer kan bli vekstbremmer.")],
           "Hva ville du synes vanskelig med å delegere oppgaver?",
           [ex("Skifte", "Hva må gründer skifte?",
               [C("a", "Tilfeldig", "Strukturert."),
                C("b", "Fra å gjøre alt selv til å la andre gjøre — lede vs utføre", "Riktig! Strukturell endring.", correct=True),
                C("c", "Bare lønn", "For smalt."),
                C("d", "Lovkrav", "Helt urelevant.")],
               "Mange gründere identifiserer seg med å gjøre. Skifte til ledelse er emosjonelt vanskelig."),
            ex("Flaskehals", "Hvorfor blir gründer flaskehals?",
               [C("a", "Tilfeldig", "Strukturelt."),
                C("b", "Tar alle beslutninger selv — teamet kan ikke handle uten gründer", "Riktig! Sentralisering.", correct=True),
                C("c", "Lovkrav", "Helt urelevant."),
                C("d", "Bare lønn", "For smalt."),],
               "Klassisk vekst-problem. Bedrift kan ikke vokse forbi gründerens daglige kapasitet."),
            ex("Løsning", "Hvordan unngå?",
               [C("a", "Tilfeldig", "Strukturert."),
                C("b", "Aktivt delegere + bygge systemer + ansette ledere", "Riktig! Strukturelt arbeid.", correct=True),
                C("c", "Bare gjøre mer selv", "Tvert imot."),
                C("d", "Lovkrav", "Strategisk valg.")],
               "Microsoft Bill Gates, Amazon Jeff Bezos — alle delegerte aktivt for å skalere. Modellen er klar.")]),
        ph("⚠️", "Snapchat-stiftelsen",
           "Hva som skjer uten avtale.",
           "Snapchat ble stiftet av Evan Spiegel, Bobby Murphy og Reggie Brown. Brown ble skviset ut i tidlig fase — over 150 millioner dollar i rettssak senere. Konflikt om eierskap er en hovedårsak til at gründerteam kollapser. Skriv aksjonæravtale TIDLIG.",
           [("KLASSISK FEIL", "Stiftelses-konflikt er svært vanlig."),
            ("AKSJONÆRAVTALE TIDLIG", "Forebygg når dere er enige.")],
           "Hva ville vært i din aksjonæravtale med medgründer?",
           [ex("Hva skjedde", "Hva med Reggie Brown?",
               [C("a", "Forblev grunnlegger", "Tvert imot."),
                C("b", "Skviset ut, saksøkte, fikk over 150 mill USD", "Riktig! Klassisk eksempel.", correct=True),
                C("c", "Tilfeldig", "Strukturelt."),
                C("d", "Helt fiktivt", "Reell sak.")],
               "Snapchat-saken er studie-objekt. Lærdom: aksjonæravtale tidlig."),
            ex("Frekvens", "Hvor vanlige er gründer-konflikter?",
               [C("a", "Sjelden", "Vanlig."),
                C("b", "Veldig vanlige — 65 % av startup-kollaps har komponent", "Riktig! Strukturelt mønster.", correct=True),
                C("c", "Bare i USA", "Globalt."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Forskning konsistent: konflikt er hovedårsak til startup-kollaps. Forebygg!"),
            ex("Når avtale", "Når skrive avtale?",
               [C("a", "Når konflikt", "For sent."),
                C("b", "Før dere starter sammen — alltid før konflikt", "Riktig! Proaktiv.", correct=True),
                C("c", "Aldri", "Stor risiko."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Når dere er i forelskede gründer-fasen er det enklest å bli enige. Konflikt-fase er for sent.")]),
        ph("🏆", "Team slår idé",
           "Investorer satser på folk.",
           "En middels idé med fantastisk team vinner over en fantastisk idé med middels team. Investorer satser ofte mer på team enn på produkt — fordi en sterkt team kan endre produkt, men et svakt team kan ikke endre seg selv. Bygg team først, idé andre.",
           [("TEAM > IDÉ", "Sterkt team adapterer; svakt team kollapser."),
            ("INVESTORER VET", "Satser på folk over produkt.")],
           "Hva er den viktigste lærdommen om team for entreprenører?",
           [ex("Hva slår", "Hva slår alt annet?",
               [C("a", "Bare ide", "Tvert imot."),
                C("b", "Middels idé + fantastisk team > fantastisk idé + middels team", "Riktig! Investor-prinsipp.", correct=True),
                C("c", "Tilfeldig", "Strukturert mønster."),
                C("d", "Bare penger", "For smalt."),],
               "Y Combinator, Sequoia, andre topp-investorer satser på team. Klassisk innsikt."),
            ex("Hvorfor", "Hvorfor team viktigst?",
               [C("a", "Tilfeldig", "Strukturelt."),
                C("b", "Sterkt team kan endre produkt; svakt team kan ikke endre seg selv", "Riktig! Adaptivitet.", correct=True),
                C("c", "Lovkrav", "Helt urelevant."),
                C("d", "Bare for tek", "Gjelder alle."),],
               "Pivot er normalt. Team som klarer pivot vinner. Svakt team feiler ved første utfordring."),
            ex("Lærdom", "Hovedlærdom?",
               [C("a", "Tilfeldig", "Strukturelt."),
                C("b", "Bygg team før du investerer i produkt", "Riktig! Strategisk prioritering.", correct=True),
                C("c", "Bare ide", "For smalt."),
                C("d", "Lovkrav", "Strategisk valg.")],
               "Steve Jobs: 'Hire smart people and let them tell you what to do.' Klassisk innsikt.")]),
    ],
    ["Du forstår at komplementære team (hacker, hustler, hipster) slår solo-gründere",
     "Du kjenner Tuckmans 4 faser og at storming er normal og sunn",
     "Du behersker kommunikasjons-strategier for både fysiske og virtuelle team",
     "Du forstår at konflikt er hovedårsak til startup-kollaps — aksjonæravtale forebygger",
     "Du ser at team slår idé — investorer satser på folk fordi sterkt team adapterer"])


g.write_modules([MFSALG, LOV, SAMARB], "ENT1 8-10")
