#!/usr/bin/env python3
"""ENT1 kap 4-7."""
import importlib.util
from pathlib import Path
spec = importlib.util.spec_from_file_location("g", Path(__file__).parent / ".gen-shared.py")
g = importlib.util.module_from_spec(spec); spec.loader.exec_module(g)
C, ph, ex, M = g.C, g.ph, g.ex, g.M


BMC = M("ForretningsmodellBmc", "ent1", "ENT1-04", "Forretningsmodellen (BMC)", "🗺️",
    "forretningsmodell-bmc", "ent1",
    "Business Model Canvas — verktøyet som kondenserer en forretningsidé til ni byggeklosser. Visualiserer hele forretningsmodellen på én side. Brukt globalt av startups og store bedrifter.",
    "Strategyzer (Alex Osterwalder) sin BMC har blitt brukt av over 5 millioner brukere globalt. Standard verktøy i moderne strategi.",
    "BMC er ikke svaret — det er rammeverket som tvinger frem riktige spørsmål. Bruk det som dialog-verktøy, ikke fasit.",
    [
        ph("🗺️", "Hva er en forretningsmodell?",
           "Hvordan bedriften skaper, leverer og kaprer verdi.",
           "Forretningsmodell beskriver hvordan bedriften skaper verdi (for kunden), leverer den (gjennom kanaler), og kaprer den (gjennom inntekter). Forklarer logikken bak hvordan bedriften tjener penger — uavhengig av selve produktet.",
           [("3 KOMPONENTER", "Skape + levere + kapre verdi."),
            ("LOGIKK", "Beskriver hvordan bedriften tjener penger.")],
           "Beskriv en bedrifts forretningsmodell: hvordan skaper, leverer og kaprer de verdi?",
           [ex("3 deler", "Hva er kjerneelementene?",
               [C("a", "Bare salg", "For smalt."),
                C("b", "Skape, levere, kapre verdi", "Riktig! Tre dimensjoner.", correct=True),
                C("c", "Kun produkt", "For smalt."),
                C("d", "Tilfeldig", "Strukturert."),],
               "Forskjell fra produkt-fokus: forretningsmodellen handler om HVORDAN, ikke HVA."),
            ex("Forskjell", "Forskjell på produkt og forretningsmodell?",
               [C("a", "De er det samme", "Helt feil."),
                C("b", "Produkt = hva. Forretningsmodell = hvordan tjene penger på det", "Riktig! Strukturell forskjell.", correct=True),
                C("c", "Bare for store", "Gjelder alle."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Samme produkt kan ha ulike forretningsmodeller: kjøp, leie, abonnement, freemium."),
            ex("Eksempel", "Spotify — beskriv modellen.",
               [C("a", "Bare salg", "For smalt."),
                C("b", "Skape (musikkbibliotek) + levere (app) + kapre (abonnement + reklame)", "Riktig! Komplett forretningsmodell.", correct=True),
                C("c", "Bare reklame", "Mer enn det."),
                C("d", "Tilfeldig", "Strukturert."),],
               "Spotify-modellen er hybrid: gratis (med reklame) + premium (abonnement). Fanger ulike segmenter.")]),
        ph("👥", "Kundesegmenter og verdiløfte",
           "Hjertet i BMC.",
           "BMCs kjerne: hvem hjelper vi (kundesegmenter), og med hva (verdiløfte)? Disse to byggestenene må passe perfekt sammen — ellers kollapser hele modellen. Verdiløftet må løse et reelt problem for et reelt segment.",
           [("HVEM + HVA", "Kundesegment + verdiløfte = match eller mismatch."),
            ("KJERNE", "Andre 7 byggesteiner støtter disse to.")],
           "Kan du beskrive 'hvem' og 'hva' for en bedrift du kjenner?",
           [ex("Kjerne", "Hva er kjernen i BMC?",
               [C("a", "Bare inntekt", "For smalt."),
                C("b", "Match mellom kundesegment og verdiløfte", "Riktig! Hovedtest.", correct=True),
                C("c", "Bare logo", "For smalt."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Strategyzer har eget Value Proposition Canvas — utdyper denne matchen."),
            ex("Mismatch", "Hva skjer ved mismatch?",
               [C("a", "Tilfeldig", "Strukturelt."),
                C("b", "Modellen kollapser — produktet treffer ikke kunden", "Riktig! Klassisk feil.", correct=True),
                C("c", "Pynt", "Strategisk svikt."),
                C("d", "Lovkrav", "Helt urelevant.")],
               "Google Glass var teknologisk imponerende, men matchet ikke noe reelt kundesegment. Mislyktes."),
            ex("Test", "Hvordan teste match?",
               [C("a", "Bare spørre seg selv", "Subjektivt."),
                C("b", "Snakke med kundesegmentet — bekrefter de problemet og løsningen?", "Riktig! Validering.", correct=True),
                C("c", "Tilfeldig", "Strukturert.")],
               "Hvis 10/10 kunder bekrefter problemet, er du på sporet. Hvis 2/10, er det galt segment.")]),
        ph("📞", "Kanaler og kunderelasjoner",
           "Hvordan nå og beholde kunder.",
           "Kanaler: hvordan vi når kunden (nettbutikk, butikk, partnere). Kunderelasjoner: hvordan vi beholder kontakten (selvbetjening, personlig hjelp, abonnement). Sammen styrer de kundeopplevelsen. Velg basert på segment og verdiløfte.",
           [("KANALER", "Hvordan nå kunden — direkte, indirekte, digitale."),
            ("RELASJONER", "Hvordan beholde kunden — automatisert eller personlig.")],
           "Hvilke kanaler bruker bedriften du jobber for / kjenner? Hvilken relasjon har de?",
           [ex("Kanaler", "Hva er kanalvalget?",
               [C("a", "Bare nettbutikk", "For smalt."),
                C("b", "Hvordan vi når kunden — direkte, indirekte, digitale, fysiske", "Riktig! Strategisk valg.", correct=True),
                C("c", "Bare reklame", "Helt feil."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Multi-kanal er normalt. Apple bruker både egne butikker og forhandlere."),
            ex("Relasjoner", "Hvilke typer kunderelasjoner finnes?",
               [C("a", "Bare personlig hjelp", "For smalt."),
                C("b", "Selvbetjening, personlig, automatisert, abonnement, communities", "Riktig! Mange typer.", correct=True),
                C("c", "Bare via telefon", "For smalt."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Spotify: selvbetjent app + community (delte spillelister). Hybrid-relasjon."),
            ex("Match", "Hva må matche?",
               [C("a", "Tilfeldig", "Strukturert."),
                C("b", "Kanal + relasjon må matche kundesegmentets forventning og verdiløftet", "Riktig! Helhet.", correct=True),
                C("c", "Bare lavest pris", "For smalt."),
                C("d", "Lovkrav", "Strategisk valg."),],
               "Premium-segment forventer personlig service. Lavpris-segment aksepterer selvbetjening. Match.")]),
        ph("💰", "Inntektsstrømmer",
           "Hvordan få betalt.",
           "Inntektsstrømmer: hvordan skal vi faktisk få betalt? Salg, abonnement, leie, reklame, lisensiering, transaksjonsgebyr. De fleste vellykkede bedrifter har flere inntektsstrømmer for å spre risiko. Spotify: gratis + premium. Apple: produkt + tjeneste + App Store.",
           [("FLERE", "Diversifiserte inntektsstrømmer reduserer risiko."),
            ("MODELLER", "Salg, abonnement, leie, reklame, lisens — mange muligheter.")],
           "Hvilke inntektsstrømmer har bedriften du jobber for? Bare én eller flere?",
           [ex("Hvor mange", "Bør bedrifter ha flere inntektsstrømmer?",
               [C("a", "Aldri", "Strategisk fordel."),
                C("b", "Ja — diversifisering reduserer risiko ved markedsendringer", "Riktig! Standard finansprinsipp.", correct=True),
                C("c", "Bare for store", "Gjelder alle."),
                C("d", "Lovkrav", "Strategisk valg."),],
               "Apple Service-segmentet vokser raskere enn iPhone — diversifisering har bygget motstand."),
            ex("Modeller", "Hvilke modeller finnes?",
               [C("a", "Bare salg", "For smalt."),
                C("b", "Salg, abonnement, leie, reklame, lisens, freemium, transaksjonsgebyr", "Riktig! Mange muligheter.", correct=True),
                C("c", "Bare en type", "For smalt."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Microsoft pivoterte fra produktsalg (Office) til abonnement (Microsoft 365). Strategisk skifte."),
            ex("Eksempel", "Spotify — hvilke inntektsstrømmer?",
               [C("a", "Bare abonnement", "Hybrid."),
                C("b", "Premium-abonnement + reklame fra free-tier + bedriftsavtaler", "Riktig! Multi-stream.", correct=True),
                C("c", "Bare reklame", "Mer enn det."),
                C("d", "Tilfeldig", "Strukturert."),],
               "Hybrid-modell gjør det mulig å fange flere kundesegmenter samtidig.")]),
        ph("🔧", "Nøkkelressurser og nøkkelaktiviteter",
           "Hva må vi ha og gjøre.",
           "Nøkkelressurser: hva vi MÅ ha (mennesker, fysiske midler, immaterielle rettigheter, kapital). Nøkkelaktiviteter: hva vi MÅ gjøre hver dag (produksjon, salg, service, plattform-vedlikehold). Definerer kjerne-virksomheten.",
           [("RESSURSER", "Hva må være på plass for å levere."),
            ("AKTIVITETER", "Hva må gjøres daglig.")],
           "Hva er nøkkelressursene og -aktivitetene for en lokal kafé?",
           [ex("Forskjell", "Forskjell på ressurser og aktiviteter?",
               [C("a", "De er det samme", "Helt feil."),
                C("b", "Ressurser = hva du har. Aktiviteter = hva du gjør", "Riktig! Statisk vs dynamisk.", correct=True),
                C("c", "Bare for store", "Gjelder alle."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Eksempel: Kafé. Ressurs = espressomaskin + lokale. Aktivitet = brygge kaffe + kundeservice."),
            ex("Apple-ressurs", "Hva er Apples viktigste ressurs?",
               [C("a", "Bare bygninger", "For smalt."),
                C("b", "Merkevare, ansatte (designere, ingeniører), immaterielle rettigheter, økosystem", "Riktig! Multi-dimensjonal.", correct=True),
                C("c", "Bare penger", "For smalt."),
                C("d", "Tilfeldig", "Strukturert."),],
               "Apples merkevare alene er verdsatt over 500 mrd USD. Største ressurs."),
            ex("Test", "Hvordan identifisere nøkkelressurser?",
               [C("a", "Tilfeldig", "Strukturert."),
                C("b", "Spør: hva ville bedriften kollapset uten?", "Riktig! Kritikalitets-test.", correct=True),
                C("c", "Bare økonomi", "For smalt."),
                C("d", "Lovkrav", "Strategisk valg."),],
               "Test: hvis vi mistet X, ville vi kunnet operere? Hvis nei = nøkkelressurs.")]),
        ph("🤝", "Nøkkelpartnere",
           "Hvem må vi samarbeide med.",
           "Nøkkelpartnere: hvem må vi samarbeide med for å lykkes? Leverandører, allianser, teknologi-partnere, distribusjonspartnere. Sterke partnerskap kan være forskjellen på å klare alt selv (dyrt og sakte) eller skalere raskt. Apple og TSMC (chip-produsent) er klassisk eksempel.",
           [("STRATEGISK", "Riktige partnere kan gi konkurransefortrinn."),
            ("FOKUS", "Outsource det som ikke er kjernen.")],
           "Hvilke partnere er viktige for bedrifter du kjenner? Hva ville skjedd uten dem?",
           [ex("Hvorfor", "Hvorfor partnere?",
               [C("a", "Bare spare penger", "For smalt."),
                C("b", "Få tilgang til ressurser/kompetanse vi ikke har — fokus på kjerne", "Riktig! Strategisk valg.", correct=True),
                C("c", "Lovkrav", "Helt urelevant."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Apple lager ikke chips selv — TSMC produserer. Apple fokuserer på design + økosystem."),
            ex("Type", "Hvilke type partnerskap?",
               [C("a", "Bare leverandører", "For smalt."),
                C("b", "Leverandører, allianser, joint ventures, distribusjon, teknologi", "Riktig! Mange typer.", correct=True),
                C("c", "Bare bank", "For smalt."),
                C("d", "Tilfeldig", "Strukturert."),],
               "Allianse: Spotify + Tesla (forhåndsinstallert). Distribusjon: Coca-Cola + McDonald's. Multi-typer."),
            ex("Test", "Når partner med noen?",
               [C("a", "Tilfeldig", "Strategisk."),
                C("b", "Når de har noe vi trenger og vi har noe de trenger — gjensidig verdi", "Riktig! Win-win.", correct=True),
                C("c", "Bare når billig", "For smalt."),
                C("d", "Lovkrav", "Strategisk valg."),],
               "Tesla og Panasonic: Tesla trengte batterier, Panasonic trengte stor kunde. Strategisk partnerskap.")]),
        ph("💸", "Kostnadsstruktur",
           "Hva er de største utgiftene.",
           "Kostnadsstruktur: hva er de største utgiftene våre? Faste kostnader (uavhengige av salg — leie, lønn) vs variable (følger salget — råvarer, frakt). Forstå strukturen — det avgjør hvor sårbar du er ved svingninger i salget. Cost-driven vs value-driven modeller.",
           [("FASTE vs VARIABLE", "Kjenn fordelingen — påvirker risiko."),
            ("STRATEGI", "Cost-driven (lavpris) vs value-driven (premium).")],
           "Hva er de største kostnadspostene for en bedrift du kjenner? Faste eller variable?",
           [ex("Forskjell", "Faste vs variable?",
               [C("a", "De er det samme", "Helt feil."),
                C("b", "Faste = uavhengige av salg. Variable = følger salget", "Riktig! Strukturell forskjell.", correct=True),
                C("c", "Bare beløp", "For smalt."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Husleie = fast (samme uansett salg). Råvarer = variable (mer salg = mer råvarer)."),
            ex("Cost-driven", "Hva er cost-driven modell?",
               [C("a", "Bare premium", "Tvert imot."),
                C("b", "Lavest mulig kostnader = lavest mulig pris (IKEA, Ryanair)", "Riktig! Strategisk valg.", correct=True),
                C("c", "Tilfeldig", "Strategisk."),
                C("d", "Lovkrav", "Strategisk valg.")],
               "IKEA optimaliserer hver kostnadspost. Lave priser er resultat av strukturell strategi."),
            ex("Risiko", "Hva betyr høye faste kostnader?",
               [C("a", "Bare positivt", "Tveegget sverd."),
                C("b", "Sårbar ved salgsfall — kostnader påløper uansett", "Riktig! Strukturell risiko.", correct=True),
                C("c", "Lovkrav", "Helt urelevant."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Restauranter med høy husleie er sårbare. Bare lavt salg over uker kan velte dem.")]),
        ph("🔄", "Lean Startup og pivot",
           "BMC som testverktøy.",
           "Lean Startup: bruk BMC til å teste hypoteser. Hver byggesten er en antakelse — test den med ekte kunder. Hvis antakelsen feiler, må du 'pivotere' (endre retning). Snapchat startet som geo-tagged bilder før de pivoterte til selvslettende meldinger. Klassisk eksempel.",
           [("HYPOTESER", "Hver byggesten er antakelse — test."),
            ("PIVOT", "Endre retning når antakelse feiler.")],
           "Hvilken antakelse i din ide kunne du testet i morgen?",
           [ex("Hva", "Hva er Lean Startup-tilnærmingen?",
               [C("a", "Tilfeldig", "Strukturert."),
                C("b", "Test antakelser med ekte kunder før stor investering", "Riktig! Forskningsbasert.", correct=True),
                C("c", "Bare planlegging", "For smalt."),
                C("d", "Bare for tek", "Bredt anvendelig.")],
               "Eric Ries populariserte Lean Startup. Modell brukt globalt nå."),
            ex("Pivot", "Hva er pivot?",
               [C("a", "Tilfeldig", "Strategisk valg."),
                C("b", "Endre retning når antakelse viser seg feil", "Riktig! Adaptasjon.", correct=True),
                C("c", "Avslutte", "For dramatisk."),
                C("d", "Lovkrav", "Helt urelevant.")],
               "Snapchat pivoterte fra geo-tagged bilder til selvslettende meldinger. Snapchat ble milliardselskap."),
            ex("Hvorfor", "Hvorfor pivotere?",
               [C("a", "Tilfeldig", "Strukturelt."),
                C("b", "Marked er ukjent terreng — antakelser viser seg ofte feil", "Riktig! Realisme om usikkerhet.", correct=True),
                C("c", "Lovkrav", "Helt urelevant."),
                C("d", "Bare for unge", "Gjelder alle."),],
               "Mange suksess-startups pivoterte tidlig. Twitter startet som podcasting-plattform. YouTube som datingside.")]),
        ph("📋", "BMC i praksis",
           "Hvordan bruke verktøyet.",
           "BMC er ikke svaret — det er rammeverket som tvinger frem riktige spørsmål. Bruk det som dialog-verktøy, ikke fasit. Tegn ut canvas på vegg, fyll inn med post-its, diskuter med team. Iterer ofte. Bedre enn 100-side forretningsplan ingen leser.",
           [("DIALOG", "Verktøy for samtale, ikke endelig fasit."),
            ("VISUELL", "Tegn ut, bruk post-its, gjør synlig.")],
           "Tegn et BMC for en bedrifts-ide du har. Begynn med kundesegment + verdiløfte.",
           [ex("Bruk", "Hvordan bruke BMC?",
               [C("a", "Som svar", "Som rammeverk."),
                C("b", "Som dialog-verktøy som tvinger frem riktige spørsmål", "Riktig! Praktisk verktøy.", correct=True),
                C("c", "Bare for konsulenter", "For ledelsen først."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Best praksis: BMC på storformat-papir, post-its for hver byggesten. Enkelt å iterere."),
            ex("Verdi", "Hva gir BMC?",
               [C("a", "Bare struktur", "For smalt."),
                C("b", "Helhetsbilde + tvinger frem spørsmål + felles språk i teamet", "Riktig! Multi-verdi.", correct=True),
                C("c", "Bare reklame", "For smalt."),
                C("d", "Lovkrav", "Strategisk valg.")],
               "Felles språk er undervurdert. BMC gjør det enkelt å diskutere strategi på tvers av roller."),
            ex("vs lang plan", "Hvorfor BMC fremfor lang forretningsplan?",
               [C("a", "Bare estetikk", "Strategisk."),
                C("b", "Lett å lese, lett å iterere, faktisk brukt av folk", "Riktig! Praktisk overlegen.", correct=True),
                C("c", "Lovkrav", "Helt urelevant."),
                C("d", "Tilfeldig", "Strukturert valg."),],
               "200-side forretningsplan = 90 % sjanse at ingen leser. 1-side BMC = brukt jevnlig.")]),
        ph("🚀", "Spotify sin BMC",
           "Klassisk eksempel.",
           "Spotify: Kundesegment = musikkfans. Verdiløfte = ubegrenset musikk billig. Kanaler = app, web. Inntekter = abonnement + reklame. Ressurser = musikkrettigheter + teknologi. Aktiviteter = utvikling + lisensiering. Partnere = plateselskaper. Kostnader = royalties + drift. BMC visualiserer hele modellen på én side.",
           [("HELHET", "Alle 9 byggesteiner samlet."),
            ("KOMPLEKS MODELL", "BMC gjør komplekse modeller forståelige.")],
           "Tegn BMC for Netflix. Hva er forskjellig fra Spotify?",
           [ex("Spotify-segment", "Hva er Spotifys kundesegment?",
               [C("a", "Bare musikere", "For smalt."),
                C("b", "Musikkfans — globalt", "Riktig! Bredt målmarked.", correct=True),
                C("c", "Bare bedrifter", "For smalt."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Spotify har 600+ mill brukere globalt. Massmarkedsmodell."),
            ex("Spotify-inntekt", "Hva er Spotifys inntektsmodell?",
               [C("a", "Bare salg", "Tvert imot."),
                C("b", "Abonnement + reklame fra free-tier", "Riktig! Hybrid-modell.", correct=True),
                C("c", "Bare reklame", "For smalt."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Hybrid-modell tillater å fange ulike kundesegmenter — gratis for budsjett-bevisste, premium for de som vil ha mer."),
            ex("Spotify-partner", "Hvem er Spotifys nøkkelpartnere?",
               [C("a", "Bare brukere", "Ikke partnere."),
                C("b", "Plateselskaper og artister — uten musikkrettigheter, ingen tjeneste", "Riktig! Kritiske partnere.", correct=True),
                C("c", "Bare Apple", "For smalt."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Spotify betaler 70+ % av inntektene til musikkrettigheter. Kritisk partnerskap.")]),
        ph("📐", "BMC — levende dokument",
           "Utvikler seg med bedriften.",
           "BMC er et levende dokument som utvikler seg med bedriften. Når marked endrer seg, må modellen oppdateres. Periodisk review (kvartalsvis) for vekstbedrifter. Spotify har endret BMC mange ganger — fra ren musikk til podcaster, lydbøker, livestreaming. Strategisk fleksibilitet.",
           [("LEVENDE", "Oppdateres når marked endrer seg."),
            ("REVIEW", "Kvartalsvis for vekstbedrifter.")],
           "Hvilke bedrifter har endret forretningsmodellen sin de siste 5 årene?",
           [ex("Statisk?", "Er BMC statisk?",
               [C("a", "Ja, bestemmes én gang", "Tvert imot."),
                C("b", "Nei — utvikler seg med bedriften og marked", "Riktig! Levende dokument.", correct=True),
                C("c", "Bare hvert 10. år", "For sjelden."),
                C("d", "Tilfeldig", "Strukturert review."),],
               "Spotify la til podcaster i 2018, lydbøker i 2022. Strategisk evolusjon."),
            ex("Microsoft", "Hva endret Microsoft?",
               [C("a", "Ingenting", "Stor endring."),
                C("b", "Pivoterte fra produktsalg (Office) til abonnement (Microsoft 365)", "Riktig! Forretningsmodell-innovasjon.", correct=True),
                C("c", "Bare logo", "For smalt."),
                C("d", "Tilfeldig", "Strukturert."),],
               "Microsoft 365: predikerbar inntekt, lavere terskel for kunder. Strategisk transformation."),
            ex("Lærdom", "Hva er strategisk lærdom?",
               [C("a", "Modeller er statiske", "Tvert imot."),
                C("b", "Strategisk fleksibilitet — vær villig til å endre modellen", "Riktig! Dynamisk strategi.", correct=True),
                C("c", "Tilfeldig", "Strukturert."),
                C("d", "Lovkrav", "Strategisk valg."),],
               "Bedrifter som klamrer seg til gammel modell taper. Bedrifter som tør å pivotere vinner.")]),
    ],
    ["Du forstår BMC som verktøy for å visualisere hele forretningsmodellen på én side",
     "Du kan beskrive de 9 byggestenene og hvordan de henger sammen",
     "Du behersker Lean Startup-tilnærmingen — test antakelser, pivoter ved feil",
     "Du forstår forskjellen på faste og variable kostnader og deres strategiske betydning",
     "Du ser BMC som levende dokument som utvikler seg med bedriften"])


ETABL = M("EtableringSelskapsformer", "ent1", "ENT1-05", "Etablering og selskapsformer", "🏛️",
    "etablering-selskapsformer", "ent1",
    "Fra idé til juridisk enhet — selskapsformer, registrering og første praktiske steg. Riktig form gir nødvendig trygghet og rom for vekst.",
    "I Norge registreres rundt 60 000 nye foretak hvert år. ENK er vanligst for soloprenører, AS er standard for bedrifter med vekstambisjoner.",
    "Mange gründere overinvesterer i AS for tidlig. ENK er ofte rett start — kan bytte til AS senere når omsetningen vokser.",
    [
        ph("🏛️", "Valg av selskapsform",
           "ENK eller AS — eller noe annet.",
           "Hovedvalget i Norge: Enkeltpersonforetak (ENK) vs Aksjeselskap (AS). ENK er enkelt og billig, men gir personlig ansvar. AS gir begrenset ansvar, men krever 30 000 kr i aksjekapital og mer formalitet. Andre former: ANS, DA, NUF — sjeldnere brukt.",
           [("ENK = ENKELT", "Lav terskel, men personlig ansvar."),
            ("AS = TRYGT", "Begrenset ansvar, men mer formalitet og kapitalkrav.")],
           "Hva ville du valgt for et lite sideprosjekt — ENK eller AS?",
           [ex("Hovedvalg", "Hva er hovedvalget i Norge?",
               [C("a", "ENK eller AS", "Riktig! De vanligste formene.", correct=True),
                C("b", "Bare AS", "For smalt."),
                C("c", "Bare ENK", "For smalt."),
                C("d", "Tilfeldig", "Strukturert valg.")],
               "Over 90 % av norske bedrifter er enten ENK eller AS. De andre formene er nisje."),
            ex("Forskjell", "Hovedforskjell ENK vs AS?",
               [C("a", "De er det samme", "Helt feil."),
                C("b", "ENK = personlig ansvar. AS = begrenset ansvar (kun aksjekapital risikeres)", "Riktig! Strukturell forskjell.", correct=True),
                C("c", "Bare for store", "Begge brukes alle størrelser."),
                C("d", "Tilfeldig", "Strukturert."),],
               "ENK: bedriften = du. AS: bedriften er egen juridisk enhet adskilt fra eier."),
            ex("Når ENK", "Når passer ENK?",
               [C("a", "Aldri", "Brukes mye."),
                C("b", "Soloprenører, lavrisiko, lite kapital, sideprosjekt", "Riktig! Lav-terskel-løsning.", correct=True),
                C("c", "Bare for store", "Tvert imot."),
                C("d", "Lovkrav", "Strategisk valg.")],
               "Mange frilansere og konsulenter starter ENK. Kan bytte til AS når omsetningen vokser.")]),
        ph("📜", "Aksjeselskap (AS)",
           "Begrenset ansvar.",
           "AS krever minimum 30 000 kr i aksjekapital. Begrenset ansvar — eierne risikerer kun aksjekapitalen, ikke privat formue. Du kan jobbe som ansatt i ditt eget AS. Krever revisor over visse grenser. Standard for bedrifter med vekstambisjoner og ekstern finansiering.",
           [("30 000 KR", "Minimum aksjekapital."),
            ("BEGRENSET ANSVAR", "Eierne risikerer kun aksjekapitalen.")],
           "Hva er minste aksjekapital for AS i Norge?",
           [ex("Aksjekapital", "Minimum aksjekapital?",
               [C("a", "10 000 kr", "For lavt."),
                C("b", "30 000 kr", "Riktig! Senket fra 100 000 i 2012.", correct=True),
                C("c", "100 000 kr", "Gammel grense, ikke gjeldende."),
                C("d", "1 mill kr", "For høyt.")],
               "Kravet ble senket fra 100 000 til 30 000 i 2012 for å gjøre AS-etablering enklere."),
            ex("Ansvar", "Hvor stort er eiers ansvar?",
               [C("a", "Ubegrenset", "Tvert imot."),
                C("b", "Begrenset til aksjekapitalen — privat formue er beskyttet", "Riktig! Hovedfordel ved AS.", correct=True),
                C("c", "Bare lønn", "Helt feil."),
                C("d", "Tilfeldig", "Strukturert."),],
               "Hvis AS-et går konkurs, taper eierne kun aksjekapitalen. Privat formue er beskyttet."),
            ex("Krav", "Hvilke andre krav har AS?",
               [C("a", "Ingen", "Mange krav."),
                C("b", "Styre, revisor (over visse grenser), årsregnskap, generalforsamling", "Riktig! Formelle krav.", correct=True),
                C("c", "Bare aksjekapital", "Mer enn det."),
                C("d", "Tilfeldig", "Strukturert.")],
               "AS krever mer formalitet enn ENK. Pris for begrenset ansvar.")]),
        ph("👤", "Enkeltpersonforetak (ENK)",
           "Lav terskel, personlig ansvar.",
           "ENK: lav etableringsterskel — kun registrering i Brønnøysund (gratis i Foretaksregisteret, gebyr i Enhetsregisteret). Men: fullt personlig ansvar for gjeld og forpliktelser. Bedriften = du. Banken kan ta huset hvis det går galt. Vanlig for soloprenører og bi-virksomheter.",
           [("LAV TERSKEL", "Enkel og billig å starte."),
            ("PERSONLIG ANSVAR", "Bedriften = du. Privat formue er ikke beskyttet.")],
           "Hva er risikoen ved ENK hvis bedriften går konkurs?",
           [ex("Etablering", "Hvordan etablere ENK?",
               [C("a", "Bare via advokat", "Ikke nødvendig."),
                C("b", "Registrere i Brønnøysund — kan gjøres på nett, raskt", "Riktig! Lav terskel.", correct=True),
                C("c", "Bare via bank", "Helt feil."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Altinn-portalen tar deg gjennom prosessen. Tar typisk 1-2 dager å bli registrert."),
            ex("Ansvar", "Hva er ENK-ansvar?",
               [C("a", "Begrenset", "Tvert imot."),
                C("b", "Fullt personlig ansvar — privat formue er ikke beskyttet", "Riktig! Hovedrisikoen.", correct=True),
                C("c", "Bare lønn", "Helt feil."),
                C("d", "Tilfeldig", "Strukturert."),],
               "Kreditorer kan kreve betaling fra privat formue, hus, sparepenger. Stor personlig risiko."),
            ex("Når", "Når passer ENK?",
               [C("a", "Aldri", "Brukes mye."),
                C("b", "Soloprenør, lavrisiko-virksomhet, sideprosjekt, lite kapital", "Riktig! Lav-terskel-løsning.", correct=True),
                C("c", "Bare for store", "Tvert imot."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Mange konsulenter, frilansere starter ENK. Bytter ofte til AS når omsetningen passerer 500 000-1 mill.")]),
        ph("📝", "Registreringsprosessen",
           "Brønnøysund og Altinn.",
           "Samordnet registermelding via Altinn — én utfylling registrerer deg i alle relevante registre (Foretaksregisteret, Enhetsregisteret, MVA hvis omsetning > 50 000). Får organisasjonsnummer på dagen ofte. Helt gratis for ENK i Enhetsregisteret, gebyr for AS-registrering.",
           [("ALTINN", "Digital plattform — én søknad."),
            ("ORG.NR.", "Får organisasjonsnummer raskt — ofte samme dag.")],
           "Hva er fordelen med digital registrering via Altinn?",
           [ex("Hvor", "Hvor registreres bedrifter?",
               [C("a", "Skattetaten", "Skattetaten er for skatt."),
                C("b", "Brønnøysundregistrene via Altinn", "Riktig! Sentral registrering.", correct=True),
                C("c", "Bare hos kommunen", "Helt feil."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Brønnøysundregistrene er sentralt foretaksregister. Altinn er den digitale grensesnittet."),
            ex("Mva", "Når kreves mva-registrering?",
               [C("a", "Aldri", "Lovkrav over visse grenser."),
                C("b", "Når omsetningen passerer 50 000 kr per år", "Riktig! Lovgrense.", correct=True),
                C("c", "Bare for B2B", "Gjelder all mva-pliktig omsetning."),
                C("d", "Tilfeldig", "Strukturert."),],
               "Frem til 50 000 kr i omsetning er du fritatt for mva. Over: må registreres og kreve inn mva."),
            ex("Tidsbruk", "Hvor lang tid?",
               [C("a", "Bare måneder", "For tregt."),
                C("b", "ENK: timer-dager. AS: dager-uker", "Riktig! Norske rammer er effektive.", correct=True),
                C("c", "Bare år", "Helt feil."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Norge er rangert høyt internasjonalt for hvor lett det er å starte bedrift.")]),
        ph("🛡️", "Skatter og avgifter",
           "MVA, skattetrekk, arbeidsgiveravgift.",
           "MVA: 25 % standard, 15 % på mat, 12 % på persontransport, 0 % på enkelte tjenester. Skattetrekk: 15 % forskuddsskatt for ENK. AS-eiere får utbytte med 35,2 % skatt. Arbeidsgiveravgift: 14,1 % i sone 1, lavere i andre soner. Komplekst — bruk regnskapsfører.",
           [("MVA", "25 % standard, lavere på mat, transport."),
            ("ENK vs AS", "Ulike skatteregler for ulike former.")],
           "Hva er standard mva-sats i Norge?",
           [ex("Mva", "Hva er standard mva i Norge?",
               [C("a", "12 %", "Det er på persontransport."),
                C("b", "25 %", "Riktig! Standardsatsen.", correct=True),
                C("c", "15 %", "Det er på mat."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Mat: 15 %. Persontransport: 12 %. Standard: 25 %. Helse, undervisning, finans: 0 %."),
            ex("ENK-skatt", "Hvordan skatter ENK?",
               [C("a", "Bare som ansatt", "Helt feil."),
                C("b", "Personlig næringsinntekt — beskattes med personlig inntektsskatt", "Riktig! Som personlig inntekt.", correct=True),
                C("c", "Aldri skatt", "Helt feil."),
                C("d", "Tilfeldig", "Strukturert."),],
               "ENK-overskudd er personlig inntekt. Trygdeavgift, trinnskatt, kommunal skatt — opp til ~50 %."),
            ex("Bruk regnskapsfører", "Når bruke regnskapsfører?",
               [C("a", "Aldri", "Anbefales i de fleste tilfeller."),
                C("b", "Fra dag 1 — komplekst regelverk gir lett feil med store konsekvenser", "Riktig! Spar tid og unngå feil.", correct=True),
                C("c", "Bare for store", "Selv små bør ha hjelp."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Regnskapsfører koster 1500-3000 kr/mnd for små bedrifter. Verdien er typisk høyere — unngår feil og frigjør tid.")]),
        ph("📄", "Forsikringer",
           "Yrkesskade, ansvarsforsikring, OTP.",
           "Yrkesskadeforsikring er lovpålagt for alle ansatte (også deg selv hvis du er ansatt i eget AS). Ansvarsforsikring beskytter bedriften mot erstatningskrav fra kunder. OTP (obligatorisk tjenestepensjon) er pålagt fra 1 ansatt med over 20 % stilling. Vurder også: avbruddsforsikring, cyber-forsikring.",
           [("YRKESSKADE", "Lovpålagt for alle ansatte."),
            ("ANSVARSFORSIKRING", "Beskytter mot kundekrav.")],
           "Hvilke forsikringer ville du tegnet for en ny bedrift?",
           [ex("Lovpålagt", "Hvilke forsikringer er lovpålagt?",
               [C("a", "Ingen", "Helt feil."),
                C("b", "Yrkesskadeforsikring + OTP fra 1 ansatt med 20 %+ stilling", "Riktig! Minimumskrav.", correct=True),
                C("c", "Bare brann", "For smalt."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Manglende lovpålagt forsikring kan gi store bøter og personlig erstatningsansvar."),
            ex("Ansvarsforsikring", "Hva dekker den?",
               [C("a", "Bare brann", "Helt feil."),
                C("b", "Erstatningskrav fra tredjepart (kunder, leverandører)", "Riktig! Stor risiko-reduksjon.", correct=True),
                C("c", "Bare lønn", "Helt feil."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Klassisk eksempel: kunde skader seg på dine premisser. Ansvarsforsikring dekker erstatningen."),
            ex("Pris", "Cirka pris for grunnleggende forsikrings-pakke?",
               [C("a", "Gratis", "Koster penger."),
                C("b", "5 000-15 000 kr/år for liten bedrift", "Riktig! Akseptabel kostnad mot risiko.", correct=True),
                C("c", "100 000 kr/år", "Vanligvis lavere for små."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Sammenlign tilbud fra If, Gjensidige, Tryg. Selvbetjent online-portaler gjør det enkelt.")]),
        ph("🏷️", "Navn og merkevare",
           "Foretaksnavn og varemerke.",
           "Foretaksnavnet må være unikt i Norge — sjekk på Brønnøysund. Vil du beskytte logo og merke, må du registrere varemerke hos Patentstyret (2 700 kr for første klasse, 1 350 for tilleggsklasser). Internasjonalt kan beskyttelsen utvides via WIPO Madrid-protokollen.",
           [("UNIKT NAVN", "Sjekk Brønnøysund før du velger."),
            ("PATENTSTYRET", "Varemerke-beskyttelse for logo og navn.")],
           "Hvordan ville du valgt navn til en ny bedrift?",
           [ex("Foretaksnavn", "Hvor sjekkes navn?",
               [C("a", "Tilfeldig", "Strukturert."),
                C("b", "Brønnøysund — må være unikt", "Riktig! Lovkrav om unikhet.", correct=True),
                C("c", "Bare i butikk", "Helt feil."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Foretaksnavn-database er åpen på brreg.no. Sjekk før du velger og registrerer."),
            ex("Varemerke", "Hvem registrerer varemerker?",
               [C("a", "Bare Brønnøysund", "Det er foretaksnavn."),
                C("b", "Patentstyret", "Riktig! Egen myndighet.", correct=True),
                C("c", "Skattetaten", "Helt feil."),
                C("d", "Kommunen", "Helt feil.")],
               "Patentstyret håndterer varemerker, design og patenter. Egne søknadsprosesser per type."),
            ex("Pris", "Hvor mye koster varemerke i Norge?",
               [C("a", "Gratis", "Koster penger."),
                C("b", "Ca 2 700 kr for første klasse", "Riktig! Akseptabel kostnad for beskyttelse.", correct=True),
                C("c", "100 000 kr", "For høyt."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Varemerke gjelder i 10 år, fornybart. Krever aktiv registrering — ikke automatisk.")]),
        ph("🤝", "Avtaler mellom gründere",
           "Aksjonæravtale er gull verdt.",
           "Aksjonæravtale: hvem som bestemmer hva, hvordan utbytter fordeles, hva som skjer hvis en gründer slutter eller dør. Mange gründere venter til konflikten oppstår — for sent. Klassisk eksempel: To venner uten avtale, konflikt etter 2 år, rettssak i 3 år, bedriften gikk konkurs.",
           [("PROAKTIV", "Skriv avtalen før konflikten."),
            ("DEKK ALT", "Beslutninger, utbytte, exit, dødsfall.")],
           "Hvilke punkter ville du sikret i aksjonæravtale med medgründer?",
           [ex("Når", "Når skrive aksjonæravtale?",
               [C("a", "Når konflikten oppstår", "For sent."),
                C("b", "Før dere starter sammen — alltid før konflikt", "Riktig! Proaktiv.", correct=True),
                C("c", "Aldri", "Stor risiko."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Når dere er i forelskede gründer-fasen er det enklest å bli enige. Konflikt-fase er for sent."),
            ex("Innhold", "Hva skal aksjonæravtale dekke?",
               [C("a", "Bare lønn", "For smalt."),
                C("b", "Beslutninger, utbytte, eksit, dødsfall, vetorett, kjøpsrett", "Riktig! Helhetlig.", correct=True),
                C("c", "Tilfeldig", "Strukturert."),
                C("d", "Lovkrav", "Strategisk valg."),],
               "Standard mal finnes — bruk advokat for å tilpasse til deres situasjon."),
            ex("Kostnad", "Hva koster aksjonæravtale?",
               [C("a", "Gratis", "Koster typisk penger."),
                C("b", "5 000-30 000 kr for advokat-utforming", "Riktig! Verdt det.", correct=True),
                C("c", "100 000+", "Sjelden så høyt."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Spar penger på dette og du kan tape millioner senere. Klassisk klok investering.")]),
        ph("⚠️", "Snapchat-rettssaken",
           "Hva som skjer uten avtale.",
           "Snapchat ble stiftet av Evan Spiegel, Bobby Murphy og Reggie Brown. Brown ble skviset ut i tidlig fase — over 150 millioner dollar i rettssak senere. Konflikt om eierskap er en hovedårsak til at gründerteam kollapser. Skriv aksjonæravtale TIDLIG.",
           [("KONFLIKT-RISIKO", "Tidlig konflikt om eierskap er vanlig."),
            ("DYRT", "Rettssaker kan koste mer enn aksjonæravtale 1000x.")],
           "Hva ville du gjort annerledes hvis du var Snapchat-grunnlegger?",
           [ex("Hva skjedde", "Hva skjedde med Reggie Brown?",
               [C("a", "Forblev grunnlegger", "Tvert imot."),
                C("b", "Ble skviset ut, saksøkte og fikk over 150 mill USD", "Riktig! Klassisk eksempel.", correct=True),
                C("c", "Tilfeldig", "Strukturelt."),
                C("d", "Helt fiktivt", "Reell sak.")],
               "Snapchat-saken er studie-objekt på business schools globalt. Lærdom om aksjonæravtale."),
            ex("Lærdom", "Hva er lærdommen?",
               [C("a", "Aldri samarbeid", "For dramatisk."),
                C("b", "Skriv aksjonæravtale TIDLIG — før konflikt", "Riktig! Proaktiv beskyttelse.", correct=True),
                C("c", "Bare ha én grunnlegger", "Sjelden mulig."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Mange gründerteam kollapser pga konflikt. Avtalen er forsikring mot dette."),
            ex("Frekvens", "Hvor vanlig er gründerkonflikter?",
               [C("a", "Sjelden", "Mye vanligere."),
                C("b", "Veldig vanlige — ofte hovedårsak til startup-kollaps", "Riktig! Vanlig problem.", correct=True),
                C("c", "Bare i USA", "Globalt fenomen."),
                C("d", "Tilfeldig", "Strukturelt mønster.")],
               "Forskning: 65 % av startup-kollaps har en gründer-konflikt-komponent.")]),
        ph("🎯", "Velge riktig form",
           "Match til ambisjon og risiko.",
           "Velg form som gir nødvendig trygghet og rom for vekst. Ikke overinvester i AS hvis du tester en sideforretning — ENK er ofte rett start. Vurder å bytte til AS når omsetningen vokser, du tar inn investorer, eller risikoen øker. Mange suksess-bedrifter startet ENK.",
           [("MATCH", "Form skal matche ambisjon og risiko."),
            ("BYTTE", "Du kan starte ENK og bytte til AS senere.")],
           "Hva ville du valgt for: a) konsulent-bivirksomhet, b) tek-startup med vekstambisjoner?",
           [ex("Soloprenør", "Hva passer en konsulent som starter alene?",
               [C("a", "AS umiddelbart", "Ofte overinvestering."),
                C("b", "ENK først — kan bytte til AS hvis omsetningen vokser", "Riktig! Lavterskel-tilnærming.", correct=True),
                C("c", "ANS", "Krever to personer."),
                C("d", "Tilfeldig", "Strukturert valg.")],
               "Mange frilanskonsulenter forblir ENK hele karrieren. Fungerer godt hvis omsetning er begrenset."),
            ex("Vekst-startup", "Hva passer tek-startup med ambisjoner?",
               [C("a", "ENK", "For begrensende."),
                C("b", "AS — kreves for å ta inn investorer", "Riktig! Investor-vennlig.", correct=True),
                C("c", "ANS", "Sjelden brukt for tek."),
                C("d", "Tilfeldig", "Strukturert valg.")],
               "Investorer kjøper aksjer i AS. ENK kan ikke ta inn ekstern kapital på samme måte."),
            ex("Bytte", "Kan man bytte form senere?",
               [C("a", "Aldri", "Tvert imot."),
                C("b", "Ja — kan bytte ENK til AS, ofte naturlig vei", "Riktig! Strategisk fleksibilitet.", correct=True),
                C("c", "Bare en gang i livet", "Helt feil."),
                C("d", "Tilfeldig", "Strukturert."),],
               "Skattetaten har egne regler for konvertering. Bruk regnskapsfører/advokat ved bytte.")]),
    ],
    ["Du forstår forskjellen på ENK og AS — særlig ansvar og kapitalkrav",
     "Du kjenner registreringsprosessen via Brønnøysund og Altinn",
     "Du behersker grunnleggende skatteregler (mva, skattetrekk, AGA)",
     "Du forstår viktigheten av aksjonæravtale før konflikten oppstår",
     "Du kan velge selskapsform basert på risiko, ambisjon og kapitalbehov"])


FINANS = M("FinansieringTilskudd", "ent1", "ENT1-06", "Finansiering og tilskudd", "💵",
    "finansiering-tilskudd", "ent1",
    "Kapital til oppstarten — fra egne sparepenger til engleinvestorer. Riktig finansiering gir bedriften nødvendig 'runway' til å ta av.",
    "Innovasjon Norge ga ut over 5 milliarder kroner i tilskudd og lån i 2023. Norske gründere har mange støtteordninger — de fleste vet ikke om dem.",
    "For lite penger gir desperate beslutninger; for mye gir slappe vaner. Riktig mengde kapital er strategisk viktig.",
    [
        ph("💵", "Kapitalbehov",
           "Hvor mye trenger vi?",
           "Kapitalbehov: hvor mye penger trenger vi før vi begynner å tjene penger? Beregn likviditetsbehovet måned for måned: lønn, husleie, utstyr, markedsføring, mva. Mange undervurderer behovet og må hente nye penger i en svak posisjon.",
           [("LIKVIDITETSBEHOV", "Måned-for-måned-beregning av cash-behov."),
            ("MARGIN", "Legg til 30-50 % buffer — uventede kostnader kommer alltid.")],
           "Hva ville en lokal kafé trenge i kapital før den begynte å tjene penger?",
           [ex("Hva", "Hva er kapitalbehov?",
               [C("a", "Tilfeldig", "Strukturert."),
                C("b", "Penger som trengs før bedriften går i pluss", "Riktig! 'Runway' til lønnsomhet.", correct=True),
                C("c", "Bare oppstart", "Bredere."),
                C("d", "Lovkrav", "Strategisk."),],
               "'Runway' i startup-språk: hvor lang tid bedriften kan operere uten ny kapital."),
            ex("Beregning", "Hvordan beregne?",
               [C("a", "Magefølelse", "For unøyaktig."),
                C("b", "Måned for måned: alle utgifter minus forventede inntekter", "Riktig! Strukturert beregning.", correct=True),
                C("c", "Bare en sum", "For overflatisk."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Likviditetsbudsjett er standard verktøy. Excel-template tilgjengelig fra Innovasjon Norge."),
            ex("Buffer", "Hvor mye buffer?",
               [C("a", "Ingen", "For risikabelt."),
                C("b", "30-50 % over beregnet behov — uventede kostnader kommer alltid", "Riktig! Realistisk margin.", correct=True),
                C("c", "100 %", "Ofte for mye."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Murphys lov i forretning: alt tar lengre tid og koster mer enn planlagt. Buffer er nødvendig.")]),
        ph("🏠", "Egenkapital",
           "Sparepenger og 'love money'.",
           "Egenkapital: penger gründerne selv spytter inn eller henter fra venner og familie ('love money'). Risiko deles ofte med personlige relasjoner — sørg for klare avtaler selv med mor og far. Egenkapital signaliserer commitment til andre investorer.",
           [("EGNE PENGER", "Personlig investering signaliserer tro."),
            ("LOVE MONEY", "Familie/venner — krever klare avtaler.")],
           "Hva er fordeler og ulemper ved å låne av familie?",
           [ex("Hva", "Hva er egenkapital?",
               [C("a", "Bare lån", "Tvert imot."),
                C("b", "Penger eierne selv legger inn — ikke lån, men eierandel", "Riktig! Strukturell forskjell.", correct=True),
                C("c", "Bare fra venner", "For smalt."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Egenkapital er buffer mot tap. Større egenkapital = lavere risiko for bedriften."),
            ex("Love money", "Hva er love money?",
               [C("a", "Romantiske partnere", "Bokstavelig — feil tolkning."),
                C("b", "Investeringer fra venner og familie", "Riktig! Folk som investerer i deg pga relasjon.", correct=True),
                C("c", "Bare gaver", "Investering, ikke gaver."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Mange suksess-startups startet med love money. Klare avtaler er kritiske for å bevare relasjoner."),
            ex("Risiko", "Hva er risiko ved love money?",
               [C("a", "Ingen", "Stor risiko."),
                C("b", "Tap av relasjoner hvis det går galt", "Riktig! Personlig risiko.", correct=True),
                C("c", "Lovkrav", "Helt urelevant."),
                C("d", "Bare økonomisk", "Større risiko enn økonomisk."),],
               "Klart definerte vilkår skriftlig: er det lån, gave eller eierandel? Forebygg konflikt.")]),
        ph("🏦", "Lån og kreditt",
           "Banklån og leverandørkreditt.",
           "Banklån: krever sikkerhet og personlig garanti for små bedrifter. Banker er konservative — de vil sjelden finansiere ren oppstartsrisiko. Kassekreditt: fleksibilitet på løpende konto. Leverandørkreditt: utsatt betaling fra leverandører — gratis finansiering hvis man bruker den riktig.",
           [("BANKLÅN", "Krever sikkerhet — vanskelig for oppstart."),
            ("LEVERANDØRKREDITT", "Utsatt betaling = gratis finansiering.")],
           "Hvilke kredittformer ville du brukt for å finansiere en ny bedrift?",
           [ex("Banklån", "Hva krever banker?",
               [C("a", "Ingenting", "Strenge krav."),
                C("b", "Sikkerhet (pant), personlig garanti, dokumentasjon", "Riktig! Konservative.", correct=True),
                C("c", "Bare god ide", "For lite."),
                C("d", "Tilfeldig", "Strukturert."),],
               "Banker tjener på rente, ikke risiko. Vil ha sikkerhet for å begrense tap ved konkurs."),
            ex("Leverandørkreditt", "Hva er leverandørkreditt?",
               [C("a", "Lån fra bank", "Annet."),
                C("b", "Utsatt betaling fra leverandører — typisk 30-60 dager", "Riktig! Innebygget finansiering.", correct=True),
                C("c", "Bare for store", "Brukes alle størrelser."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Klassisk finansiering: kjøp i dag, betal om 60 dager. Selg varene først, betal leverandøren etterpå."),
            ex("Personlig garanti", "Hva er personlig garanti?",
               [C("a", "Aksjekapital", "Annet."),
                C("b", "Du står personlig ansvarlig for lånet selv om bedriften er AS", "Riktig! Bryter ned AS-skjermen.", correct=True),
                C("c", "Bare for store", "Krever ofte for små."),
                C("d", "Tilfeldig", "Strukturert."),],
               "Mange små AS-eiere må gi personlig garanti for banklån. Bryter den begrensede ansvar-fordelen.")]),
        ph("🇳🇴", "Innovasjon Norge",
           "Statlige tilskudd og lån.",
           "Innovasjon Norge tilbyr markedsavklaringstilskudd (opp til 100 000 kr), kommersialiseringstilskudd og lån. Forskningsrådet finansierer FoU. Søknadsprosessen er omfattende — men gratis penger er verdt arbeidet. Stort statlig støtteapparat for norske gründere.",
           [("FLERE ORDNINGER", "Tilskudd, lån, mentor, internasjonalisering."),
            ("OMFATTENDE SØKNAD", "Tar tid — men ofte verdt det.")],
           "Hva ville du søkt om hos Innovasjon Norge for en startup-ide?",
           [ex("Hva", "Hva er Innovasjon Norge?",
               [C("a", "Privat bank", "Helt feil."),
                C("b", "Statlig institusjon for å støtte næringsutvikling", "Riktig! Statlig hjelpe-organisasjon.", correct=True),
                C("c", "Bare for store", "For oppstart også."),
                C("d", "Tilfeldig", "Strukturert."),],
               "Innovasjon Norge har 30 kontorer i Norge + flere internasjonalt. Bredt mandat."),
            ex("Markedsavklaringstilskudd", "Hva er det?",
               [C("a", "Bare reklame", "For smalt."),
                C("b", "Tilskudd opp til 100 000 kr for å undersøke om idé har marked", "Riktig! Tidlig fase-støtte.", correct=True),
                C("c", "Bare lån", "Tilskudd, ikke lån."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Brukes for kundeintervjuer, markedsundersøkelser, validering. Lav-risiko statlig støtte."),
            ex("Søknad", "Hva kreves i søknad?",
               [C("a", "Bare ide", "Mer enn det."),
                C("b", "Forretningsplan, markedsanalyse, team-presentasjon, milepæler", "Riktig! Strukturert dokumentasjon.", correct=True),
                C("c", "Bare økonomi", "For smalt."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Innovasjon Norge har egne maler. Bruk veiledere — ofte gratis støtte til søknads-skriving.")]),
        ph("🌐", "Crowdfunding",
           "Folkefinansiering.",
           "Crowdfunding: hente små beløp fra mange mennesker via plattformer som Kickstarter, Indiegogo eller norske Folkeinvest. Gir både penger og første kundebase samtidig — perfekt validering av produktidé. Mange suksesser har startet her.",
           [("VALIDATION + PENGER", "Markedsbevisning gjennom forhåndsbestillinger."),
            ("PLATTFORMER", "Kickstarter (intl), Folkeinvest (norsk).")],
           "Hvilke produkter du kjenner har startet via crowdfunding?",
           [ex("Hva", "Hva er crowdfunding?",
               [C("a", "Lån fra bank", "Helt feil."),
                C("b", "Hente små beløp fra mange via digitale plattformer", "Riktig! Folkefinansiering.", correct=True),
                C("c", "Bare for vekselgjeld", "For smalt."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Pebble Watch hentet 10+ mill USD i 2012 via Kickstarter. Klassisk eksempel på crowdfunding-suksess."),
            ex("Norsk plattform", "Hvilken norsk plattform?",
               [C("a", "Bare amerikanske", "Norske finnes."),
                C("b", "Folkeinvest (aksje-basert), Bidra.no (donasjon)", "Riktig! Norske alternativer.", correct=True),
                C("c", "Tilfeldig", "Strukturert."),
                C("d", "Lovkrav", "Strategisk valg.")],
               "Folkeinvest er regulert av Finanstilsynet. Aksje-crowdfunding lovregulert i Norge."),
            ex("Fordel", "Hva er hovedfordelen?",
               [C("a", "Bare penger", "Mer enn det."),
                C("b", "Validering — hvis folk forhåndsbestiller, har du marked", "Riktig! Beste markedsundersøkelse.", correct=True),
                C("c", "Lavere skatt", "Helt urelevant."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Forhåndsbestilling er strengeste markedstest. Folk som faktisk legger ut penger.")]),
        ph("👼", "Business Angels",
           "Engleinvestorer.",
           "Business Angels (engleinvestorer): private investorer som bidrar med både kapital (typisk 500 000 — 5 millioner) og kompetanse. De forventer ofte 10-30 % eierandel og aktiv styreplass. Bra for bedrifter som trenger mer enn penger. Norske angels: SmartEnergi, Norway Angel Network.",
           [("PENGER + KOMPETANSE", "Mer enn kapital — mentorskap og nettverk."),
            ("EIERANDEL", "10-30 % typisk for tidlig fase.")],
           "Hva ville du verdsatt mest fra en engleinvestor — penger eller kompetanse?",
           [ex("Hva", "Hva tilbyr engleinvestorer?",
               [C("a", "Bare penger", "Mer enn det."),
                C("b", "Kapital + kompetanse + nettverk + mentorskap", "Riktig! Multi-pakke.", correct=True),
                C("c", "Bare lån", "Eierandel, ikke lån."),
                C("d", "Tilfeldig", "Strukturert.")],
               "'Smart money' — penger med ekspertise. Verdifullt for unge gründere."),
            ex("Eierandel", "Hva forventer de?",
               [C("a", "0 %", "Sjelden."),
                C("b", "10-30 % eierandel + ofte styreplass", "Riktig! Aktivt eierskap.", correct=True),
                C("c", "100 %", "Helt urealistisk."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Engleinvestorer satser på vekst — kompenserer høy risiko med stor eierandel ved suksess."),
            ex("Norske", "Norske angels-nettverk?",
               [C("a", "Ingen", "Helt feil."),
                C("b", "Norway Angel Network, SmartEnergi, lokale grupper", "Riktig! Aktiv miljø.", correct=True),
                C("c", "Bare en", "Flere finnes."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Norge har voksende engle-miljø. Mange tidligere gründere reinvesterer profitt i nye startups.")]),
        ph("🎒", "Bootstrapping",
           "Drive for egne midler.",
           "Bootstrapping: drive for egne midler uten ekstern kapital. Fokus på lav kostnad og rask inntjening. Mange suksesser startet bootstrapped (Mailchimp, GitHub, Basecamp) — gir full kontroll, men begrenser veksttakten. Norsk eksempel: Visma startet bootstrapped.",
           [("FULL KONTROLL", "Ingen investorer = ingen krav på styret."),
            ("BEGRENSER VEKST", "Kapitalmangel kan hindre rask skalering.")],
           "Hva er fordeler og ulemper ved bootstrapping?",
           [ex("Hva", "Hva er bootstrapping?",
               [C("a", "Crowdfunding", "Annet."),
                C("b", "Drive for egne midler uten ekstern kapital", "Riktig! Egenfinansiert vekst.", correct=True),
                C("c", "Tilfeldig", "Strukturert."),
                C("d", "Bare for store", "For oppstart især."),],
               "Mailchimp ble bootstrapped fra startup til 12 mrd USD-salg. Klassisk eksempel."),
            ex("Fordel", "Hva er hovedfordelen?",
               [C("a", "Tilfeldig", "Strukturert."),
                C("b", "Full kontroll + ingen press fra investorer", "Riktig! Strategisk frihet.", correct=True),
                C("c", "Mest penger", "Tvert imot — mindre."),
                C("d", "Lovkrav", "Helt urelevant.")],
               "Mailchimp-grunnleggerne solgte for 12 mrd USD — beholdt full kontroll hele veien."),
            ex("Ulempe", "Hva er hovedulempen?",
               [C("a", "Tilfeldig", "Strukturelt."),
                C("b", "Begrenset vekstkapital — vanskelig å skalere raskt", "Riktig! Strategisk trade-off.", correct=True),
                C("c", "Lovkrav", "Helt urelevant."),
                C("d", "Bare for små", "Gjelder alle.")],
               "Konkurrenter med mye kapital kan kjøpe markedsandel. Bootstrapping krever forsiktig vekst.")]),
        ph("🎤", "Pitching for kapital",
           "Overbevis investorer på 3 minutter.",
           "Hvordan presentere idéen for å overbevise investorer på 3 minutter. Standard pitch er 3-10 minutter: problem, løsning, marked, forretningsmodell, team, traksjon, behov. Øv mange ganger — du får bare ett møte per investor. Gode pitch-kurs gjennom Innovasjon Norge.",
           [("STRUKTUR", "Problem → løsning → marked → modell → team → behov."),
            ("ØVELSE", "Pitch må sitte — du får én sjanse.")],
           "Hva ville du inkludert i en 3-minutters pitch for ideen din?",
           [ex("Struktur", "Hva er typisk pitch-struktur?",
               [C("a", "Tilfeldig", "Strukturert."),
                C("b", "Problem → løsning → marked → modell → team → traksjon → behov", "Riktig! Standard mal.", correct=True),
                C("c", "Bare produktet", "For smalt."),
                C("d", "Bare økonomi", "For smalt.")],
               "Y Combinator har egen pitch-mal. Brukt globalt nå."),
            ex("Tid", "Hvor lang er typisk pitch?",
               [C("a", "1 time", "For lang."),
                C("b", "3-10 minutter", "Riktig! Kort og presis.", correct=True),
                C("c", "30 sekunder", "For kort for full pitch."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Elevator pitch: 30-60 sek. Full investor-pitch: 5-10 min. VC-møte: 30-60 min."),
            ex("Øvelse", "Hvor mange ganger øve?",
               [C("a", "1 gang", "For lite."),
                C("b", "Mange — du får én sjanse per investor", "Riktig! Pitch må være polert.", correct=True),
                C("c", "Aldri", "Helt feil."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Beste gründere øver 50+ ganger før viktig pitch. Ord, tempo, kroppsspråk — alt må sitte.")]),
        ph("🚀", "No Isolation sin reise",
           "Klassisk kapitaltrappestige.",
           "No Isolation lager teknologi mot ensomhet (AV1-roboten for kronisk syke barn). Startet med crowdfunding (validering + penger), så Innovasjon Norge (utvikling), deretter venture capital (skalering). Klassisk kapitaltrappestige fra idé til vekst.",
           [("TRAPPESTIGE", "Crowdfunding → tilskudd → angels → VC."),
            ("MATCH FASE", "Hver finansieringskilde passer en fase.")],
           "Tegn kapitaltrappestige fra ide til IPO. Hvilke kilder finnes på hvert nivå?",
           [ex("Trappestige", "Hva er kapitaltrappestige?",
               [C("a", "Tilfeldig", "Strukturert."),
                C("b", "Sekvens av finansieringskilder fra ide til vekst", "Riktig! Strategisk progresjon.", correct=True),
                C("c", "Bare ett trinn", "Helt feil."),
                C("d", "Lovkrav", "Strategisk valg.")],
               "Standard sekvens: love money → tilskudd → crowdfunding → angels → VC → IPO. Hver fase har sin kilde."),
            ex("No Isolation", "Hva gjorde No Isolation?",
               [C("a", "Bare bank", "Mer komplekst."),
                C("b", "Crowdfunding først, så Innovasjon Norge, så VC", "Riktig! Klassisk progresjon.", correct=True),
                C("c", "Tilfeldig", "Strukturert."),
                C("d", "Bare egenkapital", "For begrenset.")],
               "AV1-roboten validerte først via crowdfunding. Bevis på etterspørsel ga lettere tilgang til neste runde."),
            ex("Lærdom", "Hva er strategisk lærdom?",
               [C("a", "Tilfeldig", "Strukturelt mønster."),
                C("b", "Match finansieringskilde til vekstfase — ikke hopp over trinn", "Riktig! Strukturert tilnærming.", correct=True),
                C("c", "Bare VC fra start", "For tidlig."),
                C("d", "Lovkrav", "Strategisk valg."),],
               "VC-er investerer ikke i tidlig idé. Begynn med love money og crowdfunding for validering.")]),
        ph("🎯", "Riktig finansiering = runway",
           "Tid til å bevise modellen.",
           "Riktig finansiering gir bedriften nødvendig 'runway' til å ta av — tid til å bevise modellen før pengene tar slutt. For lite penger gir desperate beslutninger; for mye gir slappe vaner. Mål: 18-24 mnd runway etter hver finansieringsrunde.",
           [("RUNWAY", "Hvor lenge bedriften kan operere uten ny kapital."),
            ("18-24 MND", "Standard mål etter finansieringsrunde.")],
           "Hva er ditt 'runway' for et personlig prosjekt? Hvor lang tid kan du holde på?",
           [ex("Runway", "Hva er runway?",
               [C("a", "Flyplass", "Bokstavelig — feil tolkning."),
                C("b", "Hvor lenge bedriften kan operere uten ny kapital", "Riktig! Kritisk metric.", correct=True),
                C("c", "Bare overskudd", "For smalt."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Klassisk startup-metric. Beregnes som: kontanter / månedlig forbruk."),
            ex("Mål", "Hva er målet etter finansieringsrunde?",
               [C("a", "3 mnd", "For kort."),
                C("b", "18-24 mnd", "Riktig! Standard mål.", correct=True),
                C("c", "10 år", "For langt."),
                C("d", "Tilfeldig", "Strukturert.")],
               "18-24 mnd gir tid til å bevise milepæler før neste finansieringsrunde."),
            ex("For mye penger", "Hva er problemet med for mye?",
               [C("a", "Ingenting", "Stor risiko."),
                C("b", "Slappe vaner — bruker for mye, mister disiplinen", "Riktig! Strukturell risiko.", correct=True),
                C("c", "Lovkrav", "Helt urelevant."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Mange unicorn-startups som hentet for mye kapital har gått konkurs. Disiplin er strategisk fortrinn.")]),
    ],
    ["Du forstår kapitalbehov og hvordan beregne 'runway'",
     "Du kjenner forskjellen på egenkapital, lån, tilskudd og crowdfunding",
     "Du behersker norske støtteordninger via Innovasjon Norge og Forskningsrådet",
     "Du kan strukturere en investor-pitch på standardmal",
     "Du forstår kapitaltrappestigen og match mellom finansieringskilde og vekstfase"])


OKO_PLAN = M("OkonomiskPlanleggingBudsjett", "ent1", "ENT1-07", "Økonomisk planlegging og budsjett", "📊",
    "okonomisk-planlegging-budsjett", "ent1",
    "Kontroll på kronene — budsjett, dekningsbidrag og likviditet for nye gründere. God økonomistyring er forskjellen på suksess og konkurs.",
    "Norske startups som mangler god økonomistyring har 3-5x høyere konkurs-rate enn de med disiplinert budsjettering. Tall slår magefølelse.",
    "Mange gründere er flinke med produkt og dårlige med tall. De som mestrer begge vinner.",
    [
        ph("📋", "Hvorfor budsjettere?",
           "Forutse, styre, dokumentere.",
           "Tre hovedformål: 1) Forutse fremtiden — hva trenger vi når? 2) Styre driften — på sporet eller ikke? 3) Dokumentere behov for kapital — banker og investorer krever budsjett. Et godt budsjett gir deg svar før spørsmålene oppstår.",
           [("3 FORMÅL", "Forutse, styre, dokumentere."),
            ("STRATEGI I TALL", "Budsjett er strategi uttrykt i kroner.")],
           "Har du erfart prosjekt uten budsjett? Hvilke problemer oppstod?",
           [ex("Hovedformål", "Hva er hovedformålene?",
               [C("a", "Tilfeldig", "Strukturert."),
                C("b", "Forutse fremtiden, styre driften, dokumentere kapitalbehov", "Riktig! Tre formål.", correct=True),
                C("c", "Bare regnskap", "For smalt."),
                C("d", "Bare kontroll", "For smalt.")],
               "Budsjett er ikke prediksjon — det er styringsverktøy. Forskjell."),
            ex("Strategi", "Hva er forholdet til strategi?",
               [C("a", "Ingenting", "Sterk kobling."),
                C("b", "Budsjett er strategi uttrykt i kroner", "Riktig! Operasjonalisering.", correct=True),
                C("c", "Bare økonomi", "For smalt."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Vil du vekste? Vis det i budsjettet. Vil du kutte? Vis det i budsjettet. Strategi → tall."),
            ex("Investorer", "Hvorfor krever investorer budsjett?",
               [C("a", "Tilfeldig", "Strukturelt."),
                C("b", "Måle om bedriften vil gi avkastning på investeringen", "Riktig! Risikovurdering.", correct=True),
                C("c", "Lovkrav", "Strategisk krav."),
                C("d", "Tilfeldig", "Strukturert."),],
               "Ingen investor gir penger uten å se forventet kontantstrøm og lønnsomhet over tid.")]),
        ph("📈", "Resultatbudsjett",
           "Lønnsomhet over perioden.",
           "Resultatbudsjett: planlagt inntekt minus planlagte kostnader over en periode (typisk ett år). Viser om bedriften vil gå med overskudd. Kunst: ikke være for optimistisk — pessimistiske scenarier gir mer realistisk planlegging. Bygg gjerne 'best case', 'worst case', 'most likely'.",
           [("LØNNSOMHET", "Inntekter minus kostnader over perioden."),
            ("FLERE SCENARIER", "Best, worst, most likely — bedre risikovurdering.")],
           "Lag et enkelt resultatbudsjett for et personlig prosjekt — inntekter og utgifter over 6 mnd.",
           [ex("Hva", "Hva viser resultatbudsjett?",
               [C("a", "Bare inntekter", "For smalt."),
                C("b", "Inntekter minus kostnader = forventet resultat", "Riktig! Lønnsomhet.", correct=True),
                C("c", "Bare kostnader", "For smalt."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Resultatbudsjett er det viktigste budsjettet for å vurdere lønnsomhet."),
            ex("Periode", "Typisk periode?",
               [C("a", "1 år", "Riktig! Standard.", correct=True),
                C("b", "1 dag", "For kort."),
                C("c", "100 år", "For langt."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Årlig budsjett, brutt ned til måneder for oppfølging. Standard struktur."),
            ex("Optimisme", "Hva er klassisk feil?",
               [C("a", "For pessimistisk", "Sjelden problem."),
                C("b", "For optimistisk — overestimere inntekter, underestimere kostnader", "Riktig! Vanligste feil.", correct=True),
                C("c", "Tilfeldig", "Strukturelt mønster."),
                C("d", "Lovkrav", "Helt urelevant.")],
               "Hofstadters lov: 'It always takes longer than you expect, even when you take into account Hofstadter's Law.'")]),
        ph("💧", "Likviditetsbudsjett",
           "Kontanter måned for måned.",
           "Likviditetsbudsjett: oversikt over innbetalinger og utbetalinger måned for måned. Har vi penger i kassa til å betale regninger? Mange lønnsomme bedrifter går konkurs av likviditetskrise — du kan ikke betale lønn med fakturaer.",
           [("KASSEFLYT", "Faktiske penger inn og ut, ikke regnskapsmessig overskudd."),
            ("CASH IS KING", "Lønnsomhet på papiret er lite verdt uten kontanter.")],
           "Hva er forskjellen på lønnsomhet og likviditet for en bedrift?",
           [ex("Hva", "Hva viser likviditetsbudsjett?",
               [C("a", "Bare overskudd", "Det er resultat."),
                C("b", "Faktiske innbetalinger og utbetalinger måned for måned", "Riktig! Cash flow.", correct=True),
                C("c", "Bare lønninger", "For smalt."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Salg på faktura skaper inntekt på papiret, men ikke kontant — kunden betaler senere."),
            ex("Hvorfor", "Hvorfor er det kritisk?",
               [C("a", "Tilfeldig", "Strukturelt."),
                C("b", "Bedriften kan være lønnsom på papiret, men likevel gå konkurs av kontantmangel", "Riktig! Klassisk eksempel.", correct=True),
                C("c", "Lovkrav", "Helt urelevant."),
                C("d", "Bare for store", "Gjelder alle."),],
               "Norwegian rapporterte rekordtall 2019. Konkurs 2020 — likviditetskrise. Klassisk feil."),
            ex("Norske eksempler", "Når er likviditet kritisk?",
               [C("a", "Tilfeldig", "Strukturelt."),
                C("b", "Vekstfaser, sesong-bedrifter, ny investering — alle krever cash buffer", "Riktig! Multi-faser.", correct=True),
                C("c", "Bare i krise", "Konstant viktig."),
                C("d", "Lovkrav", "Helt urelevant."),],
               "Sesong-bedrifter (turisme, jul-handel) har spesielt stor likviditetsutfordring. Krever planlegging.")]),
        ph("🔒", "Faste og variable kostnader",
           "Strukturell forskjell.",
           "Faste kostnader: uavhengige av salg (husleie, fastlønn, forsikring). Variable kostnader: følger salget (råvarer, provisjon, frakt). Forstå skillet — det er nøkkelen til alle videre lønnsomhetsberegninger. Høye faste kostnader = sårbar ved salgsfall.",
           [("FASTE", "Uavhengige av salg — alltid der."),
            ("VARIABLE", "Følger salget — øker når salget øker.")],
           "List kostnader for en lokal kafé — hvilke er faste, hvilke variable?",
           [ex("Faste", "Eksempler på faste kostnader?",
               [C("a", "Råvarer", "Variable."),
                C("b", "Husleie, fastlønn, forsikring, lisenser", "Riktig! Uavhengige av salg.", correct=True),
                C("c", "Frakt", "Variable."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Disse må betales selv om bedriften ikke selger noe. Konstant utgift."),
            ex("Variable", "Eksempler på variable?",
               [C("a", "Husleie", "Fast."),
                C("b", "Råvarer, provisjon, frakt, emballasje", "Riktig! Følger salget.", correct=True),
                C("c", "Forsikring", "Fast."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Mer salg = mer råvarer = mer variable kostnader. Skala lineært."),
            ex("Strategi", "Hvorfor er fordelingen viktig?",
               [C("a", "Tilfeldig", "Strukturelt."),
                C("b", "Høye faste kostnader = sårbar ved salgsfall — break-even må analyseres", "Riktig! Strategisk risiko.", correct=True),
                C("c", "Lovkrav", "Helt urelevant."),
                C("d", "Bare for store", "Gjelder alle."),],
               "Restauranter med høy husleie er sårbare. Pandemi rammet dem hardt — kostnader påløper uten salg.")]),
        ph("🎯", "Nullpunktanalyse",
           "Break-even-punkt.",
           "Nullpunktanalyse (break-even): hvor mye må vi selge for å gå i null? Faste kostnader / dekningsbidrag per enhet. Eksempel: 200 000 kr i faste kostnader / 100 kr DB = 2 000 enheter. Hvis du tror du selger 1 500, er det røde lys. Kritisk verktøy for prising og lansering.",
           [("FORMEL", "Break-even = faste kostnader / DB per enhet."),
            ("BESLUTNING", "Sammenligne med realistisk salgsestimat.")],
           "Faste kostnader 100 000. DB per enhet 50 kr. Hva er break-even?",
           [ex("Hva", "Hva er nullpunkt?",
               [C("a", "Når man går konkurs", "Tvert imot."),
                C("b", "Når inntekter dekker totale kostnader — verken tap eller fortjeneste", "Riktig! Kritisk milestone.", correct=True),
                C("c", "Når lager er tomt", "Helt feil."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Break-even forteller minimumsvolum for lønnsomhet. Under = tap, over = profitt."),
            ex("Beregning", "Faste 100 000. DB 50 kr. Break-even?",
               [C("a", "1 000 enheter", "Feil regning."),
                C("b", "2 000 enheter (100 000 / 50)", "Riktig! Klassisk beregning.", correct=True),
                C("c", "5 000 enheter", "Feil regning."),
                C("d", "10 000 enheter", "Helt feil.")],
               "Sjekk: kan vi realistisk selge 2000+ enheter? Hvis ikke, ikke lansér."),
            ex("Bruk", "Når brukes break-even?",
               [C("a", "Aldri", "Brukes mye."),
                C("b", "Lansering, prising, kapasitetsplanlegging", "Riktig! Strategisk verktøy.", correct=True),
                C("c", "Bare etter lansering", "Bør være før."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Beregn break-even FØR lansering. Avdekker urealistiske planer.")]),
        ph("📊", "Dekningsbidrag",
           "Hva sitter vi igjen med per enhet?",
           "Dekningsbidrag = Salgspris - Variable kostnader. Hva sitter vi igjen med per solgt enhet til å dekke faste kostnader og fortjeneste? Selger du for 200 og det koster 80 i råvarer, er DB 120 — det er pengene du har å jobbe med. Dekningsgrad = DB i prosent av salgspris.",
           [("FORMEL", "DB = Pris - Variable kostnader."),
            ("DEKNINGSGRAD", "DB i prosent av salgspris.")],
           "Pris 200 kr. Variable kostnader 80 kr. Hva er DB og DG?",
           [ex("Definisjon", "Hva er DB?",
               [C("a", "Total inntekt", "Bruttoinntekt."),
                C("b", "Salgspris minus variable kostnader", "Riktig! Det som er igjen.", correct=True),
                C("c", "Bare overskudd", "DB inkluderer faste kostnader."),
                C("d", "Tilfeldig", "Strukturert.")],
               "DB = 200 - 80 = 120 kr. Disse 120 kr skal dekke faste kostnader og fortjeneste."),
            ex("DG", "Pris 200, DB 120. DG?",
               [C("a", "20 %", "Feil regning."),
                C("b", "60 % (120/200)", "Riktig! DB i prosent av salgspris.", correct=True),
                C("c", "40 %", "Det er VK-andel."),
                C("d", "100 %", "Helt feil.")],
               "DG er nyttig for sammenligning på tvers av produkter med ulik pris."),
            ex("Avanse vs DG", "Forskjell?",
               [C("a", "De er det samme", "Helt feil."),
                C("b", "Avanse = av innkjøpspris. DG = av salgspris", "Riktig! Klassisk feil i butikkdrift.", correct=True),
                C("c", "Bare for B2B", "Begge brukes overalt."),
                C("d", "Tilfeldig", "Strukturert."),],
               "50 % avanse = 33 % DG. Mange nye butikkeiere blander disse — kan gå konkurs.")]),
        ph("💰", "Prissetting i oppstarten",
           "Selvkost vs markedsbasert.",
           "To hovedtilnærminger: Selvkost (alle kostnader + påslag — sikrer lønnsomhet) vs markedsbasert (hva er kunden villig til å betale — riktigere, men krever testing). Beste tilnærming er ofte hybrid: bruk markedsbasert for å sette pris, sjekk mot selvkost for å sikre lønnsomhet.",
           [("SELVKOST", "Sikrer at hver enhet er lønnsom."),
            ("MARKEDSBASERT", "Maximerer pris kunden vil betale.")],
           "Hvilken tilnærming ville du brukt for et nytt produkt?",
           [ex("Selvkost", "Hva er selvkost-prising?",
               [C("a", "Kunden bestemmer", "Det er markedsbasert."),
                C("b", "Alle kostnader + påslag for fortjeneste = pris", "Riktig! Sikrer lønnsomhet.", correct=True),
                C("c", "Tilfeldig", "Strukturert."),
                C("d", "Lovkrav", "Strategisk valg.")],
               "Garanterer at hver enhet er lønnsom. Men kan undervurdere hva markedet vil betale."),
            ex("Marked", "Markedsbasert?",
               [C("a", "Tilfeldig", "Strukturert."),
                C("b", "Hva kunden er villig til å betale — testing avgjør", "Riktig! Maksimerer pris.", correct=True),
                C("c", "Bare lavest pris", "For smalt."),
                C("d", "Lovkrav", "Strategisk."),],
               "Apple bruker markedsbasert prising. Kunder betaler premium fordi de vil — ikke fordi det er kostnaden + påslag."),
            ex("Hybrid", "Beste tilnærming?",
               [C("a", "Bare en", "For smalt."),
                C("b", "Hybrid — markedsbasert som hovedregel, sjekk mot selvkost for lønnsomhet", "Riktig! Beste av begge.", correct=True),
                C("c", "Tilfeldig", "Strukturert."),
                C("d", "Lovkrav", "Strategisk."),],
               "Markedsbasert maksimerer inntekt. Selvkost-sjekk sikrer at vi ikke selger med tap.")]),
        ph("🔍", "Økonomisk kontroll",
           "Sammenlign budsjett mot faktiske tall.",
           "Sammenlign budsjett mot faktiske tall hver måned. Avvik gir signal: revider budsjettet, eller endre driften. Mange gründere lager budsjett én gang og ignorerer det — det er sløsing av tid. Disiplinert månedlig review er kritisk.",
           [("MÅNEDLIG", "Sammenlign minst månedlig."),
            ("AVVIK = LÆRING", "Forstå hvorfor og juster.")],
           "Hvor ofte ville du sammenlignet budsjett mot virkelighet?",
           [ex("Frekvens", "Hvor ofte review?",
               [C("a", "Aldri", "For lite."),
                C("b", "Månedlig minimum", "Riktig! Standard frekvens.", correct=True),
                C("c", "Hver dag", "For ofte."),
                C("d", "Årlig", "For sjelden.")],
               "Månedlig regnskap kommer typisk uansett. Bruk det aktivt — ikke bare for skattemyndighetene."),
            ex("Avvik", "Hva gjøre med avvik?",
               [C("a", "Ignorere", "Tap av læring."),
                C("b", "Forstå hvorfor — juster budsjett eller drift", "Riktig! Læringsprosess.", correct=True),
                C("c", "Tilfeldig", "Strukturert."),
                C("d", "Lovkrav", "Strategisk valg.")],
               "Stort positivt avvik kan være like alarmerende som negativt — kan tyde på dårlig planlegging."),
            ex("Verdi", "Hva er verdien av kontroll?",
               [C("a", "Pynt", "Strategisk verdi."),
                C("b", "Lærer kontinuerlig — bedre planlegging neste runde", "Riktig! Iterativ forbedring.", correct=True),
                C("c", "Bare for revisor", "For ledelse først."),
                C("d", "Tilfeldig", "Strukturert."),],
               "Bedrifter som måler systematisk forbedrer seg konsistent. Disiplin er konkurransefortrinn.")]),
        ph("💼", "Kahoots tidlige budsjett",
           "Stram likviditetsstyring.",
           "Kahoot startet med begrenset kapital. Stram likviditetsstyring (cash burn) ble fulgt månedlig — én forsinket investering kunne tatt livet av selskapet i tidlig fase. God økonomistyring var like viktig som produktet. Klassisk eksempel på disiplinert oppstart.",
           [("CASH BURN", "Hvor raskt bedriften bruker kontanter."),
            ("MÅNEDLIG", "Daglig oversikt i kritiske faser.")],
           "Hva ville du fulgt opp daglig hvis du var startup-CEO?",
           [ex("Cash burn", "Hva er cash burn?",
               [C("a", "Branner", "Bokstavelig — feil."),
                C("b", "Hvor raskt bedriften bruker kontanter", "Riktig! Standard startup-metric.", correct=True),
                C("c", "Bare lønninger", "For smalt."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Beregnes som: (kontanter ved start - kontanter nå) / antall måneder. Standard startup-mål."),
            ex("Hvorfor", "Hvorfor følge så tett?",
               [C("a", "Tilfeldig", "Strukturelt."),
                C("b", "I tidlig fase kan én feil ta livet av selskapet — kontroll = overlevelse", "Riktig! Eksistensielt.", correct=True),
                C("c", "Lovkrav", "Helt urelevant."),
                C("d", "Bare estetikk", "Strategisk verdi."),],
               "Mange startups har stengt fordi de oppdaget likviditetskrise for sent. Ukentlig sjekk er minimum."),
            ex("Lærdom", "Strategisk lærdom?",
               [C("a", "Bare ide teller", "For smalt."),
                C("b", "Økonomistyring er like kritisk som produktet — særlig i tidlig fase", "Riktig! Helhetlig syn.", correct=True),
                C("c", "Bare reklame", "For smalt."),
                C("d", "Tilfeldig", "Strukturert."),],
               "Kahoot bygde milliardselskap pga både produkt OG økonomistyring. Ingen kan stå alene.")]),
        ph("🎯", "Forskjellen suksess vs konkurs",
           "Disiplin slår geni.",
           "God økonomistyring er forskjellen på suksess og konkurs. Bedriften kan ha en fantastisk idé, godt team og lojale kunder — men hvis pengene tar slutt, er alt over. Mange genier har sett bedriften sin gå konkurs av dårlig økonomistyring. Disiplin slår geni.",
           [("DISIPLIN > GENI", "Beste idé dør uten økonomistyring."),
            ("OVERLEVELSE FØRST", "Kan ikke vokse uten å overleve.")],
           "Hva ville du prioritert: bedre produkt eller bedre økonomistyring?",
           [ex("Forskjell", "Hva skiller suksess fra konkurs?",
               [C("a", "Bare flaks", "Strukturelle drivere."),
                C("b", "Disiplinert økonomistyring sammen med godt produkt", "Riktig! Begge må være på plass.", correct=True),
                C("c", "Bare ide", "For smalt."),
                C("d", "Tilfeldig", "Strukturelt mønster.")],
               "Forskning: 65 % av startups som mislykkes nevner økonomistyring som hovedårsak."),
            ex("Geni vs disiplin", "Hva slår hva?",
               [C("a", "Geni alltid", "Tvert imot."),
                C("b", "Disiplin slår geni — særlig i økonomi", "Riktig! Strukturelt mønster.", correct=True),
                C("c", "Tilfeldig", "Strukturert."),
                C("d", "Lovkrav", "Helt urelevant.")],
               "Mange genier har sett gode bedrifter gå konkurs. Disiplin er undervurdert ferdighet."),
            ex("Hovedlærdom", "Hovedlærdommen?",
               [C("a", "Bare salg", "For smalt."),
                C("b", "Bygg disiplinerte økonomistyring fra dag 1 — ikke vent", "Riktig! Proaktivt.", correct=True),
                C("c", "Tilfeldig", "Strukturert."),
                C("d", "Lovkrav", "Strategisk valg."),],
               "Sett opp regnskaps-systemer fra start. Bruk regnskapsfører. Ikke vent til problemene oppstår.")]),
    ],
    ["Du forstår de 3 hovedformålene med budsjettering: forutse, styre, dokumentere",
     "Du kjenner forskjellen på resultatbudsjett (lønnsomhet) og likviditetsbudsjett (cash flow)",
     "Du kan beregne dekningsbidrag, dekningsgrad og break-even punkt",
     "Du forstår skillet på faste og variable kostnader og strategisk betydning",
     "Du ser at god økonomistyring er forskjellen på suksess og konkurs"])


g.write_modules([BMC, ETABL, FINANS, OKO_PLAN], "ENT1 4-7")
