#!/usr/bin/env python3
"""ML2-13 Organisering og ledelse strategisk + ML2-14 HRM."""
import importlib.util
from pathlib import Path
spec = importlib.util.spec_from_file_location("g", Path(__file__).parent / ".gen-shared.py")
g = importlib.util.module_from_spec(spec); spec.loader.exec_module(g)
C, ph, ex, M = g.C, g.ph, g.ex, g.M


ORG = M("OrganiseringOgLedelseStrategisk", "ml2", "ML2-13", "Organisering og ledelse (strategisk nivå)", "🏢",
    "organisering-og-ledelse-strategisk", "ml2",
    "Strategisk organisasjonsdesign — hvordan bygge organisasjon som gjennomfører strategien. Kultur, struktur, endringsledelse, agil organisering. 'Culture eats strategy for breakfast' — Drucker.",
    "Hurtigruten endret seg fra ferge-leverandør til premium-cruise. Krevde fundamental kulturendring fra 'vi er ferje' til 'vi er opplevelse'. Tok år.",
    "Strategien dør uten en organisasjon som er rigget for å gjennomføre den. Kultur er den usynlige kraften som avgjør om strategien blir til handling.",
    [
        ph("🏗️", "Organisasjonsstruktur", "Strukturen følger strategien.",
           "Funksjonell, produktbasert, markedsbasert, matrise. Velg basert på strategi: ett produkt + ett marked = funksjonell. Mange produkter = produktbasert. Globale markeder = matrise. Endrer du strategi, må strukturen vurderes på nytt.",
           [("FØLGER STRATEGI", "Endre strategi = vurder struktur."),
            ("FLERE TYPER", "Funksjonell, produkt, marked, matrise.")],
           "Hvilken struktur passer en lokal kafé vs en global teknologi-bedrift?",
           [ex("Strukturer", "Hvilke hovedtyper finnes?",
               [C("a", "Bare hierarkisk", "For begrenset."),
                C("b", "Funksjonell, produktbasert, markedsbasert, matrise", "Riktig! De viktigste organisasjonsformene.", correct=True),
                C("c", "Bare flat", "For begrenset."),
                C("d", "Tilfeldig", "Strukturerte valg.")],
               "Alfred Chandler: 'Structure follows strategy'. Klassisk innsikt fra 1962."),
            ex("Matrise", "Når brukes matriseorganisasjon?",
               [C("a", "Aldri", "Brukes mye."),
                C("b", "Når man trenger både funksjonell ekspertise og produkt/markedsfokus", "Riktig! Brukes i komplekse globale selskaper.", correct=True),
                C("c", "Bare for små", "Tvert imot — for store."),
                C("d", "Lovkrav", "Helt urelevant.")],
               "P&G, Microsoft bruker matrise. Komplisert, men gir balanse mellom dimensjoner."),
            ex("Test", "Hvordan velge struktur?",
               [C("a", "Magefølelse", "Strategisk valg."),
                C("b", "Basert på strategi — hvilken struktur støtter målene best?", "Riktig! Strukturen følger strategien.", correct=True),
                C("c", "Bare etter størrelse", "Strategi viktigere."),
                C("d", "Tilfeldig", "Strukturert."),],
               "Endre strategi → vurder struktur. Behold gammel struktur med ny strategi = friksjon.")]),
        ph("🎭", "Bedriftskultur",
           "De usynlige reglene.",
           "Kultur = 'slik gjør vi det her' uten at noen sier det. Sterk kultur kan være konkurransefortrinn (Apple, Patagonia). Eller bremsekloss for endring. Kultur dannes av: ledelsens eksempel, hva som premieres, hva som tolereres. Tar år å bygge, kan brytes på dager.",
           [("USYNLIG", "Kultur uttrykkes i handlinger, ikke verdiplakater."),
            ("LEDELSENS EKSEMPEL", "Hva ledere gjør betyr mer enn hva de sier.")],
           "Hva er de usynlige reglene på arbeidsplass du kjenner? Hvordan påvirker de hverdagen?",
           [ex("Hva", "Hva er bedriftskultur?",
               [C("a", "Verdiplakater", "Plakater er ord — kultur er handling."),
                C("b", "De usynlige reglene som styrer hvordan ansatte oppfører seg", "Riktig! 'Slik gjør vi det her'-uten at noen sier det.", correct=True),
                C("c", "Antall ansatte", "Helt urelevant."),
                C("d", "Bedriftens logo", "Visuelt uttrykk, ikke kultur."),],
               "Test: Hva ville ny ansatt sett etter en uke som hun ville fortalt vennen sin? Det er kultur."),
            ex("Drucker-sitatet", "Hva betyr 'Culture eats strategy for breakfast'?",
               [C("a", "Strategi viktigere", "Tvert imot — kultur sterkere."),
                C("b", "Kultur slår strategi — uten støttende kultur kan ikke strategi gjennomføres", "Riktig! Klassisk innsikt.", correct=True),
                C("c", "Frokost viktigst", "Helt feil tolkning."),
                C("d", "Kun for store", "Gjelder alle."),],
               "Den beste strategien dør hvis kulturen motsetter seg den. Kultur er fundamentet."),
            ex("Lederens rolle", "Hva former kultur mest?",
               [C("a", "HR-policyer", "Policyer alene endrer ikke kultur."),
                C("b", "Ledelsens daglige eksempel", "Riktig! 'Walk the talk'. Folk kopierer ledere.", correct=True),
                C("c", "Plakater", "Pynt."),
                C("d", "Lønn", "Sekundært.")],
               "Steve Jobs: 'kultur er det som skjer når lederen ikke er i rommet'. Riktig observasjon.")]),
        ph("🔄", "Endringsledelse",
           "Lede gjennom endring.",
           "John Kotters 8-stegs-modell er klassikeren: 1) Skap nødfølelse, 2) Bygg ledende koalisjon, 3) Visjon, 4) Kommuniser, 5) Fjern hindringer, 6) Feire seire, 7) Forankre, 8) Befest i kultur. 70 % av endringsprogrammer mislykkes — typisk pga svak kommunikasjon.",
           [("8 STEG", "Strukturert tilnærming. Hopper du steg, mislykkes."),
            ("70 % MISLYKKES", "Kommunikasjon er typisk svakeste punkt.")],
           "Hvilken endring du har vært del av lyktes? Hva avgjorde?",
           [ex("Antall steg", "Hvor mange steg har Kotter?",
               [C("a", "3", "For få."),
                C("b", "8", "Riktig! Klassisk modell.", correct=True),
                C("c", "12", "For mange."),
                C("d", "Bare 1", "For lite.")],
               "Modellen utviklet etter studier av 100+ endringsprogrammer. Fortsatt dominerende."),
            ex("Første steg", "Hva er første steg?",
               [C("a", "Ny teknologi", "Senere steg."),
                C("b", "Skape nødfølelse — vise hvorfor endring er nødvendig", "Riktig! Uten følt behov motsetter folk endring.", correct=True),
                C("c", "Strategi", "Senere."),
                C("d", "Strukturendring", "Senere.")],
               "Mange ledere starter med strukturendring. Møtes med motstand fordi folk ikke forstår hvorfor."),
            ex("Hovedfeil", "Hvor svikter endring oftest?",
               [C("a", "For dyrt", "Sjelden hovedårsak."),
                C("b", "Dårlig kommunikasjon — strategien når aldri ut", "Riktig! Mest vanlige feil.", correct=True),
                C("c", "For mange møter", "Symptom."),
                C("d", "Endring lykkes alltid", "Helt feil — 70 % mislykkes.")],
               "Bruk minst halvparten av endringsbudsjettet på kommunikasjon, opplæring og motivasjon.")]),
        ph("🎚️", "Lederstiler på strategisk nivå",
           "Inspirerende vs kontrollbasert.",
           "Inspirerende ledelse (Jobs, Musk) skaper engasjement og innovasjon. Kontrollbasert (mange tradisjonelle CEO-er) gir presis utførelse. Begge har sin plass. Krise = mer kontroll. Vekst = mer inspirasjon. Beste ledere veksler basert på situasjon.",
           [("INSPIRERENDE", "Skaper engasjement og innovasjon — passer vekst."),
            ("KONTROLLBASERT", "Gir presis utførelse — passer krise og rutine.")],
           "Hvilken lederstil har vært mest effektiv i din erfaring?",
           [ex("Inspirerende", "Hva kjennetegner inspirerende ledelse?",
               [C("a", "Mikromanagement", "Tvert imot."),
                C("b", "Visjonsdrevet, motiverende, gir autonomi", "Riktig! Skaper engasjement og innovasjon.", correct=True),
                C("c", "Bare regler", "Det er kontrollbasert."),
                C("d", "Tilfeldig", "Strukturert tilnærming.")],
               "Steve Jobs er klassisk eksempel. Inspirerte Apple til innovasjon, men også kjent for å være krevende."),
            ex("Kontrollbasert", "Når passer kontrollbasert?",
               [C("a", "Aldri", "Brukes mye."),
                C("b", "Krise, rutinepreget arbeid, høyrisikobransjer", "Riktig! Sikkerhet og presisjon krever kontroll.", correct=True),
                C("c", "Bare for unge", "Aldersnøytralt."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Flybransjen, kjernekraft, militær — strukturert kontroll er passende. Innovasjon-bransjer trenger annet."),
            ex("Veksle", "Bør ledere veksle?",
               [C("a", "Aldri — én stil for hele karrieren", "For rigid."),
                C("b", "Ja — basert på situasjon, oppgave, team-modenhet", "Riktig! Situasjonsbestemt ledelse.", correct=True),
                C("c", "Bare i krise", "For begrenset."),
                C("d", "Tilfeldig", "Strukturert valg.")],
               "Beste ledere har repertoar av stiler og bytter bevisst. Mindre fleksible blir mindre effektive.")]),
        ph("📢", "Internmarkedsføring",
           "Selg strategien til de ansatte.",
           "Internmarkedsføring: selge strategien til de ansatte før den selges til kunden. Hvis ikke ansatte tror på merkevaren, klarer de heller ikke formidle den. SAS, Hurtigruten, IKEA bruker betydelige ressurser på ansatt-engasjement. Eksterne kampanjer dør hvis interne ikke er med.",
           [("ANSATTE FØRST", "Selg internt før eksternt."),
            ("AMBASSADØRER", "Engasjerte ansatte er beste merkeambassadører.")],
           "Hvordan kommuniserer bedriften du jobber for / kjenner med ansatte om strategi?",
           [ex("Hva", "Hva er internmarkedsføring?",
               [C("a", "Reklame plassert internt", "Helt feil tolkning."),
                C("b", "Selge strategien til ansatte før den selges til kunden", "Riktig! Bygger interne ambassadører.", correct=True),
                C("c", "Bare ansatte-rabatt", "For smalt."),
                C("d", "Internasjonal markedsføring", "Helt feil.")],
               "Engasjerte ansatte selger merkevaren autentisk — bedre enn noen reklame."),
            ex("Hvorfor", "Hvorfor er det viktig?",
               [C("a", "Spare penger", "Sekundært."),
                C("b", "Hvis ansatte ikke tror på merket, klarer de ikke formidle det til kundene", "Riktig! Autentisitet kommer innenfra.", correct=True),
                C("c", "Bare for store", "Gjelder alle."),
                C("d", "Lovkrav", "Helt urelevant.")],
               "Sjekk: kan dine ansatte forklare merkets verdier på 30 sekunder? Hvis ikke, mangler internmarkedsføring."),
            ex("Norsk eksempel", "Hvilken norsk bedrift er sterk på dette?",
               [C("a", "Tilfeldig", "Strategisk valg."),
                C("b", "Hurtigruten — investerer mye i ansatt-engasjement og opplæring", "Riktig! Reise-opplevelse leveres av ansatte. Kritisk å ha dem ombord.", correct=True),
                C("c", "Bare statlige", "Privat sektor like aktivt."),
                C("d", "Bare i USA", "Norge er aktivt."),],
               "Hurtigrutens reise fra ferje til opplevelse krevde massiv intern-merkebygging.")]),
        ph("🎓", "Kompetansestrategi",
           "Sikre fremtidens kompetanse.",
           "Sikre at bedriften har hodene som trengs for fremtiden. Krever aktivt arbeid: kompetansekartlegging, læring og utvikling, rekruttering på lang sikt. Tek-bedrifter bruker mer på rekruttering enn på reklame. Kompetanse er strategisk ressurs i kunnskapsøkonomien.",
           [("FREMTIDSKOMPETANSE", "Hva trengs om 3-5 år, ikke bare nå."),
            ("AKTIVT ARBEID", "Kompetansestrategi krever bevisst innsats over år.")],
           "Hvilken kompetanse vil bedriften du jobber for / kjenner trenge om 5 år?",
           [ex("Hva", "Hva er kompetansestrategi?",
               [C("a", "Tilfeldig rekruttering", "Strategisk planlegging."),
                C("b", "Planlegging av fremtidig kompetansebehov", "Riktig! Hvilke ferdigheter trenger vi om 3-5 år?", correct=True),
                C("c", "Bare opplæring", "Bredere."),
                C("d", "Bare lønn", "Helt urelevant."),],
               "Spør: hvilke jobber finnes om 5 år som ikke finnes nå? AI, dataanalyse, bærekraft — alle krever ny kompetanse."),
            ex("Tek-bransjen", "Hva er typisk for tek-bedrifter?",
               [C("a", "Lavt rekrutteringsbudsjett", "Tvert imot."),
                C("b", "Bruker mer på rekruttering enn reklame — talent er knapphetsressurs", "Riktig! Kunnskapsøkonomien har snudd prioriteringene.", correct=True),
                C("c", "Bare egne ansatte", "For smalt."),
                C("d", "Tilfeldig", "Strukturert prioritering."),],
               "Google bruker over 1 mrd USD årlig på rekruttering. Talent er viktigere enn reklame for dem."),
            ex("Bygging", "Hvordan bygge kompetanse?",
               [C("a", "Bare ansette", "For smalt."),
                C("b", "Kombinasjon: rekruttere + utvikle eksisterende + lære av eksterne", "Riktig! Multi-strategi.", correct=True),
                C("c", "Bare ekstern opplæring", "Bredere."),
                C("d", "Tilfeldig", "Strukturert."),],
               "70-20-10-modell: 70 % læring fra arbeid, 20 % fra andre, 10 % fra formelle kurs.")]),
        ph("⚡", "Agil organisering",
           "Snu seg raskt i digitalt marked.",
           "Spotifys squad/tribe-modell, Amazons 'two pizza teams' — små autonome enheter som kan beslutte og utføre raskt. Motsatt av tradisjonell hierarkisk struktur. Krever moden organisasjon — ellers blir det kaos. Norske: DnB Marketing, Telenor Digital, Schibsted.",
           [("SQUADS", "Små selvgående team, 5-10 personer."),
            ("AUTONOMI", "Beslutninger nær kunden, raskere respons.")],
           "Hvilke fordeler og utfordringer ser du med agil organisering?",
           [ex("Spotify-modell", "Hva kjennetegner Spotify-modellen?",
               [C("a", "Stor sentralisering", "Tvert imot."),
                C("b", "Små autonome team (squads) organisert rundt produkter", "Riktig! Squads med klart mandat og produktfokus.", correct=True),
                C("c", "Bare for IT", "Brukes nå mange bransjer."),
                C("d", "Ingen ledere", "Det er ledere — bare flatere.")],
               "DnB Marketing implementerte squad-modell rundt 2018-2020. Resultatet var raskere respons og mer innovasjon."),
            ex("Krav", "Hva må være på plass?",
               [C("a", "Mange ansatte", "Størrelse er ikke avgjørende."),
                C("b", "Klare mål, sterk kultur, modne team som tåler autonomi", "Riktig! Agil krever moden organisasjon. Uten kultur blir det kaos.", correct=True),
                C("c", "Kun digitale produkter", "Brukes nå bredt."),
                C("d", "Ingen ledelse", "Krever sterk ledelse, bare annerledes.")],
               "Slipp først ut autonomi når teamene har bevist seg. For tidlig autonomi gir fragmentering."),
            ex("Risiko", "Hva kan gå galt?",
               [C("a", "Folk blir for spesialisert", "Tvert imot."),
                C("b", "Ingen koordinasjon — alle løper i hver sin retning", "Riktig! Uten klare overordnede mål blir autonomi til kaos.", correct=True),
                C("c", "For mye sentralisering", "Helt feil retning."),
                C("d", "For mange møter", "Agil reduserer typisk møter."),],
               "'Aligned autonomy': Klar overordnet retning, autonomi i hvordan målet nås.")]),
        ph("🔗", "Samarbeid og team",
           "Bryte ned siloer.",
           "Bryte ned siloer mellom avdelinger. Cross-funksjonelle team, felles KPI-er, samlokalisering. Sikre at marked, IT, salg og produkt jobber mot samme mål, ikke konkurrerer internt. Siloer er klassisk problem i funksjonelle organisasjoner.",
           [("CROSS-FUNKSJONELL", "Team på tvers av avdelinger."),
            ("FELLES KPI", "Samme mål gir samme retning.")],
           "Ser du siloer i bedriften du jobber for / kjenner? Hvordan kunne de brytes?",
           [ex("Siloer", "Hva er siloer?",
               [C("a", "Bygninger", "Bokstavelig — feil tolkning."),
                C("b", "Avdelinger som jobber isolert og ikke koordinerer godt", "Riktig! Klassisk problem i funksjonelle organisasjoner.", correct=True),
                C("c", "Bare for offentlig", "Gjelder alle organisasjoner."),
                C("d", "Tilfeldig", "Strukturelt fenomen.")],
               "Siloer skaper friksjon, dobbeltarbeid, motstridende prioriteringer. Avgjørende å motvirke."),
            ex("Bryte ned", "Hvordan bryte siloer?",
               [C("a", "Aksepter dem", "Strategi-feil."),
                C("b", "Cross-funksjonelle team, felles KPI-er, samlokalisering", "Riktig! Multi-tiltak nødvendig.", correct=True),
                C("c", "Bare flere møter", "Symptom-behandling."),
                C("d", "Mer hierarki", "Forverrer ofte problemet.")],
               "Spotifys tribes er konkret tiltak: medlemmer fra ulike fag samles rundt produkt-tema."),
            ex("Cross-funksjonelt", "Hva betyr cross-funksjonelt team?",
               [C("a", "Samme avdeling", "Det er funksjonelt."),
                C("b", "Medlemmer fra ulike fag (marked, IT, salg, produkt) jobber sammen", "Riktig! Bryter siloer ved struktur.", correct=True),
                C("c", "Bare for IT", "Bredere bruk."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Klassisk eksempel: produktlanseringsteam med marketing, salg, produktdesign, IT — alle sammen for ett mål.")]),
        ph("🌍", "Hurtigrutens kulturreise",
           "Fra ferje til opplevelse.",
           "Hurtigruten omformet seg fra lokal ferje-leverandør til globalt premium-cruiseselskap. Krevde fundamental kulturendring — fra 'vi er ferje' til 'vi er opplevelse'. Ny rekruttering, betydelig opplæring, lederendringer. Strategi mislyktes flere ganger før kulturen kom på plass. Klassisk eksempel.",
           [("KULTUR FØLGER STRATEGI", "Strategiendring krevde kulturendring."),
            ("TAR ÅR", "Reell kulturendring kan ta 5-10 år.")],
           "Hvilke andre norske bedrifter har gjort store kulturendringer?",
           [ex("Hva", "Hva endret Hurtigruten?",
               [C("a", "Bare logo", "Mye dypere."),
                C("b", "Fra ferje-leverandør til premium-cruise — kulturendring fra 'transport' til 'opplevelse'", "Riktig! Fundamental endring i identitet.", correct=True),
                C("c", "Bare priser", "Bredere endring."),
                C("d", "Tilfeldig", "Strategisk valg."),],
               "Hurtigruten er nå internasjonal premium-merkevare. Reisen er ikke 'å komme dit', men 'å oppleve underveis'."),
            ex("Tid", "Hvor lang tid tok det?",
               [C("a", "Måneder", "For kort."),
                C("b", "År — flere mislykkede forsøk før kulturen kom på plass", "Riktig! Kulturendring tar tid og tålmodighet.", correct=True),
                C("c", "Uker", "Helt urealistisk."),
                C("d", "Generasjoner", "Overdrevet, men ofte år."),],
               "Realistisk regne 5-10 år for fundamental kulturendring i etablert organisasjon."),
            ex("Lærdom", "Hva er strategisk lærdom?",
               [C("a", "Kultur er rask å endre", "Tvert imot."),
                C("b", "Strategiendring krever kulturendring — tar tid og krever bevisst innsats", "Riktig! Mange undervurderer dette.", correct=True),
                C("c", "Tilfeldig", "Strukturelt mønster."),
                C("d", "Lovkrav", "Helt urelevant.")],
               "Equinor (tidligere Statoil) er pågående eksempel — fra olje til energi. Pågår fortsatt.")]),
        ph("🚀", "Strategi-implementering",
           "Bro mellom strategi og resultat.",
           "Strategien dør uten organisasjon som er rigget for å gjennomføre den. Implementering krever: tydelige KPI-er, månedlig oppfølging, ledelse-engasjement, tilstrekkelige ressurser, kommunikasjon på alle nivåer. 70 % av strategier mislykkes på implementering — typisk pga svak kultur eller kommunikasjon.",
           [("HELHET", "Strategi + struktur + kultur = implementering."),
            ("70 % MISLYKKES", "Implementering er hardere enn planlegging.")],
           "Hva har du sett som har skilt vellykkede fra mislykkede implementeringer?",
           [ex("Nøkkelen", "Hva er broen mellom strategi og resultat?",
               [C("a", "Bare planlegging", "For smalt."),
                C("b", "Organisasjonen — kultur, struktur, prosesser som støtter strategien", "Riktig! Implementering er organisasjonens oppgave.", correct=True),
                C("c", "Bare penger", "For smalt."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Beste strategi blir verdiløs uten organisasjon som kan utføre den. Realitet."),
            ex("Hva trengs", "Hva trengs for vellykket implementering?",
               [C("a", "Bare god plan", "Plan uten utførelse er ingenting."),
                C("b", "KPI-er + oppfølging + ledelse-engasjement + ressurser + kommunikasjon", "Riktig! Helhetlig systemarbeid.", correct=True),
                C("c", "Bare penger", "Penger uten retning er bortkastet."),
                C("d", "Bare beste folk", "Folk uten retning får ikke gjort noe.")],
               "Implementering er disiplin. Følg opp månedlig, juster basert på data, kommuniser konstant."),
            ex("Suksessrate", "Hvor mange strategier lykkes?",
               [C("a", "90 %", "Helt feil — mye lavere."),
                C("b", "30 % — 70 % mislykkes", "Riktig! McKinsey-data konsistent over år.", correct=True),
                C("c", "Alle", "Helt feil."),
                C("d", "10 %", "Lavere enn realiteten.")],
               "Statistikken er stabil — ikke fordi strategi er svak, men fordi implementering er undervurdert.")]),
    ],
    ["Du forstår at strukturen følger strategien — endre strategi, vurder struktur",
     "Du kan diagnostisere bedriftskultur og dens effekt på strategi-implementering",
     "Du kjenner Kotters 8-stegs endringsmodell og hvorfor 70 % mislykkes",
     "Du forstår agil organisering som svar på rask digital endring",
     "Du ser internmarkedsføring og kompetansestrategi som kritiske implementeringsverktøy"])


HRM = M("PersonaladministrasjonHRM", "ml2", "ML2-14", "Personaladministrasjon og HRM", "👥",
    "personaladministrasjon-hrm", "ml2",
    "Human Resource Management — strategisk arbeid med mennesker. Rekruttering, motivasjon, kompetanseutvikling, belønning. Folk er bedriftens eneste ressurs som kan tenke selv.",
    "Feil ansettelse er dyrt — opp til 6 ganger årslønnen i tap (rekruttering, opplæring, mistet produksjon). HR-strategi er økonomisk strategi.",
    "Menneskene driver alle resultater. HR-strategi er ofte undervurdert sammenlignet med markeds- eller produktstrategi — men kan være det viktigste konkurransefortrinn.",
    [
        ph("👥", "Hva er HRM?",
           "Strategisk arbeid med mennesker.",
           "HRM = Human Resource Management. Mer enn lønnsutbetaling — strategisk planlegging, anskaffelse og utvikling av bedriftens mennesker. Bygger fremtidens organisasjon. I kunnskapsøkonomien er talent strategisk ressurs.",
           [("STRATEGISK", "Mer enn admin — strategisk arbeid."),
            ("FREMTIDSORIENTERT", "Bygger kompetansen organisasjonen trenger om 3-5 år.")],
           "Hva tror du HR gjør i bedriften du jobber for / kjenner? Mer enn lønn?",
           [ex("HRM", "Hva er HRM?",
               [C("a", "Bare lønn", "For smalt."),
                C("b", "Strategisk planlegging, anskaffelse og utvikling av mennesker", "Riktig! Bredt og strategisk.", correct=True),
                C("c", "Bare oppsigelser", "For smalt."),
                C("d", "Bare jus", "Helt feil.")],
               "Moderne HR jobber med strategi, kultur, talent — ikke bare administrasjon."),
            ex("Strategisk", "Hvorfor er HR strategisk?",
               [C("a", "Ikke det", "Stor strategisk verdi."),
                C("b", "Folk er kritisk konkurransefortrinn — særlig i kunnskapsøkonomien", "Riktig! Talent er strategisk ressurs.", correct=True),
                C("c", "Lovkrav", "Strategisk verdi."),
                C("d", "Bare for tek", "Gjelder alle bransjer.")],
               "Google bruker mer på rekruttering enn reklame. HR er deres strategiske fortrinn."),
            ex("Verdi", "Hva er HRs viktigste oppgave?",
               [C("a", "Lønnsutbetaling", "For smalt."),
                C("b", "Sikre at bedriften har riktige mennesker til riktige oppgaver", "Riktig! Right people, right roles.", correct=True),
                C("c", "Bare opplæring", "Bredere."),
                C("d", "Tilfeldig", "Strukturert."),],
               "Jim Collins: 'First who, then what'. Folk først, deretter strategi.")]),
        ph("📋", "Rekrutteringsprosessen",
           "4 steg fra behov til ansettelse.",
           "Rekruttering: jobbanalyse (hva skal personen gjøre?), utlysning (hvem vil vi nå?), seleksjon (intervjuer, tester, referanser), ansettelse (kontrakt, onboarding). Feil ansettelse er dyrt — opp til 6× årslønn i tap. Strukturert prosess gir bedre treff.",
           [("4 STEG", "Jobbanalyse, utlysning, seleksjon, ansettelse."),
            ("DYRT MED FEIL", "6× årslønn i tap ved feil ansettelse.")],
           "Har du vært gjennom en god rekrutteringsprosess? Hva gjorde den god?",
           [ex("Steg", "Hva er de 4 stegene?",
               [C("a", "Bare intervju", "For smalt."),
                C("b", "Jobbanalyse, utlysning, seleksjon, ansettelse", "Riktig! Strukturert prosess.", correct=True),
                C("c", "Bare lønnsforhandling", "For smalt."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Hopper du over jobbanalyse, ender du ofte med å ansette feil person fordi behovet ikke var klart definert."),
            ex("Kostnad", "Hva koster feil ansettelse?",
               [C("a", "Bare rekrutteringsgebyr", "Mye mer."),
                C("b", "Opp til 6× årslønn — rekruttering + opplæring + mistet produksjon + ny prosess", "Riktig! Stort økonomisk tap.", correct=True),
                C("c", "Lite", "Tvert imot."),
                C("d", "Tilfeldig", "Strukturert beregning."),],
               "Derfor lønner det seg å investere i grundig rekrutteringsprosess. Spar timer på rekruttering, taper måneder på utskifting."),
            ex("Beste praksis", "Hva er beste praksis for seleksjon?",
               [C("a", "Bare 1 intervju", "For overflatisk."),
                C("b", "Strukturerte intervjuer, ferdighetsesting, referansesjekk", "Riktig! Multi-metode reduserer bias og gir bedre treff.", correct=True),
                C("c", "Magefølelse", "Bias-utsatt."),
                C("d", "Tilfeldig", "Strukturert."),],
               "Forskning viser strukturerte intervjuer dobler prediksjons-presisjon vs ustrukturerte.")]),
        ph("🎯", "Motivasjonsteori",
           "Herzberg: hygiene vs motivasjon.",
           "Herzbergs to-faktor-teori: Hygienefaktorer (lønn, arbeidsmiljø, sjefen) må være på plass — men gir ikke motivasjon. Motivasjonsfaktorer (mestring, anerkjennelse, ansvar, vekst) skaper engasjement. Lønn forhindrer misnøye, men skaper ikke motivasjon over tid.",
           [("HYGIENE = MIN.", "Lønn osv må være på plass — ellers misnøye."),
            ("MOTIVASJON = +", "Mestring, anerkjennelse skaper engasjement.")],
           "Hva motiverer deg på jobb / skole? Lønn alene? Eller mer?",
           [ex("Hygiene", "Hva er hygienefaktorer?",
               [C("a", "Toaletter", "Bokstavelig — feil tolkning."),
                C("b", "Lønn, arbeidsmiljø, sjefen, jobbsikkerhet — må være på plass", "Riktig! Forebygger misnøye, men skaper ikke motivasjon.", correct=True),
                C("c", "Bare bonus", "For smalt."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Lav lønn skaper misnøye. Men høy lønn alene gir ikke varig motivasjon — andre faktorer trengs."),
            ex("Motivasjon", "Hva er motivasjonsfaktorer?",
               [C("a", "Bare bonus", "For smalt."),
                C("b", "Mestring, anerkjennelse, ansvar, vekstmuligheter", "Riktig! Skaper varig engasjement.", correct=True),
                C("c", "Bare ferie", "Sekundært."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Daniel Pinks 'Drive': autonomi, mestring, formål driver høy ytelse mer enn pengebelønning."),
            ex("Lønn", "Hvorfor motiverer ikke høy lønn alene?",
               [C("a", "Tilfeldig", "Strukturelt."),
                C("b", "Folk venner seg til lønn — den slutter å motivere etter en stund", "Riktig! Adapsjons-teori. Pengelykke flate ut.", correct=True),
                C("c", "Lønn er irrelevant", "Det er hygiene."),
                C("d", "Lovkrav", "Helt urelevant."),],
               "Forskning: pengelykke flater ut etter ~75 000 USD i USA. Mer penger = ikke nødvendigvis mer lykke.")]),
        ph("📚", "Kompetanseutvikling",
           "70-20-10-modellen.",
           "Læring skjer på 3 nivåer: 70 % fra arbeidet selv (gjennomføring av oppgaver), 20 % fra andre (mentor, kolleger, feedback), 10 % fra formelle kurs. Kurs alene er ikke nok — læring må være integrert i hverdagen.",
           [("70-20-10", "Arbeid > andre > formell læring."),
            ("KURS ALENE = LITE", "Hovedlæringen skjer i jobben.")],
           "Hva har du lært mest av siste år? Kurs, jobben eller folk rundt deg?",
           [ex("70-20-10", "Hva betyr 70-20-10?",
               [C("a", "Pris-strategi", "Helt feil ramme."),
                C("b", "70 % fra arbeid, 20 % fra andre, 10 % fra kurs", "Riktig! Klassisk lærings-fordeling.", correct=True),
                C("c", "Tilfeldig", "Strukturert modell."),
                C("d", "Bare for ledere", "Gjelder alle.")],
               "Sentral innsikt: kurs alene er ikke nok. Læring må integreres i arbeidet."),
            ex("Praktisk", "Hvordan utvikle kompetanse?",
               [C("a", "Bare flere kurs", "For smalt."),
                C("b", "Utfordrende oppgaver + mentor + målrettet kurs", "Riktig! Kombinasjon av alle tre nivåer.", correct=True),
                C("c", "Bare lese", "For passivt."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Best in class: stretch-oppgaver med støtte, ikke 'kast inn i dypvannet'."),
            ex("Mentor", "Hvorfor mentor?",
               [C("a", "Tilfeldig", "Strategisk verdi."),
                C("b", "Erfaringsoverføring, perspektiv, nettverk — alt vanskelig å få fra kurs", "Riktig! Mentorskap er undervurdert utviklings-ressurs.", correct=True),
                C("c", "Bare for unge", "Gjelder alle aldre."),
                C("d", "Lovkrav", "Helt urelevant."),],
               "Microsoft, Google har formelle mentor-programmer. Norske bedrifter er mer ad hoc — kan forbedres.")]),
        ph("⚖️", "Arbeidsmiljøloven",
           "Norske rammer for arbeidslivet.",
           "Arbeidsmiljøloven setter de juridiske rammene for arbeidslivet i Norge: arbeidstid, ferie, oppsigelse, varsling, diskriminering, HMS. Bryter du den, kan Arbeidstilsynet stenge driften — i tillegg til erstatningsansvar. HR må kjenne hovedpunktene.",
           [("RAMMER", "Arbeidstid, ferie, oppsigelse, varsling, HMS."),
            ("HÅNDHEVING", "Arbeidstilsynet kan stenge drift ved brudd.")],
           "Hvilke rettigheter har norske arbeidstakere som du synes er viktige?",
           [ex("Hva", "Hva regulerer Arbeidsmiljøloven?",
               [C("a", "Bare lønn", "For smalt."),
                C("b", "Arbeidstid, ferie, oppsigelse, varsling, HMS, diskriminering", "Riktig! Helhetlig rammeverk for arbeidslivet.", correct=True),
                C("c", "Bare ferie", "For smalt."),
                C("d", "Bare oppsigelse", "For smalt.")],
               "Norge har en av Europas sterkeste arbeidstakervern. Strengere enn EU-minimum."),
            ex("Oppsigelse", "Hva kreves for lovlig oppsigelse?",
               [C("a", "Ingenting", "Strenge krav."),
                C("b", "Saklig grunn, drøftingsmøte, dokumentasjon, klagerett", "Riktig! Lovkrav om hele prosessen.", correct=True),
                C("c", "Bare ledelsens beslutning", "Krever mye mer."),
                C("d", "Bare økonomi", "Sekundært."),],
               "Bryter du oppsigelses-prosessen, kan retten opprettholde stillingen — selv etter oppsigelse."),
            ex("Sanksjoner", "Hva kan Arbeidstilsynet gjøre?",
               [C("a", "Ingenting", "Sterke beføyelser."),
                C("b", "Stenge drift, gi pålegg, ilegge gebyr", "Riktig! Tilsynsmyndighet med reelle sanksjoner.", correct=True),
                C("c", "Bare advarsel", "For begrenset."),
                C("d", "Saksøke ansatte", "Helt feil — beskytter ansatte.")],
               "Arbeidstilsynet inspiserer regelmessig. Brudd kan koste mye — både økonomisk og omdømme.")]),
        ph("💰", "Belønningssystemer",
           "Mer enn lønn.",
           "Belønning: lønn, bonus, opsjoner, frynsegoder, anerkjennelse. Ekstreme bonusordninger kan gi vridde insentiver (banksektoren før 2008). Best er ofte balansert grunnlønn pluss beskjeden, predikerbar bonus. Anerkjennelse er gratis og undervurdert.",
           [("BALANSERT", "Grunnlønn + beskjeden bonus + andre goder."),
            ("ANERKJENNELSE", "Gratis, undervurdert, ofte mest verdifullt.")],
           "Hva har vært den mest meningsfulle 'belønningen' du har fått på jobb / skole?",
           [ex("Forskjellige", "Hva inkluderer moderne belønning?",
               [C("a", "Bare lønn", "For smalt."),
                C("b", "Lønn + bonus + opsjoner + frynsegoder + anerkjennelse", "Riktig! Multi-dimensjonal.", correct=True),
                C("c", "Bare bonus", "For smalt."),
                C("d", "Tilfeldig", "Strukturert."),],
               "Tek-bedrifter bruker opsjoner mye — gir ansatte del i selskapets vekst."),
            ex("Vridde insentiver", "Hva er vridde insentiver?",
               [C("a", "Tilfeldig", "Strukturelt problem."),
                C("b", "Belønning som motiverer feil adferd — bankere belønnet for risiko, ikke ansvar", "Riktig! Klassisk eksempel fra finansbransjen.", correct=True),
                C("c", "Bare i USA", "Globalt fenomen."),
                C("d", "Aldri problem", "Stort problem.")],
               "Wells Fargo: 5000+ ansatte opprettet falske kontoer pga press på salgstall. Vridde insentiver."),
            ex("Anerkjennelse", "Hvorfor er anerkjennelse undervurdert?",
               [C("a", "Tilfeldig", "Strukturelt."),
                C("b", "Gratis, men kraftig motiverende — folk vil føle seg sett og verdsatt", "Riktig! Mange ledere undervurderer dette.", correct=True),
                C("c", "Lovkrav", "Frivillig praksis."),
                C("d", "Bare for unge", "Alle aldre.")],
               "Daglig anerkjennelse fra leder er sterkt motiverende. Koster ingenting, gir mye.")]),
        ph("📅", "Medarbeidersamtalen",
           "Strukturert dialog.",
           "Medarbeidersamtalen: strukturert dialog om trivsel, prestasjon og mål. Skjer minst en gang i året, helst kvartalsvis. Brukt riktig: utvikling og engasjement. Brukt feil: tidssløsing og frustrasjon. Forberedelse fra begge sider er nøkkelen.",
           [("STRUKTURERT", "Forberedt agenda, dokumentert, med oppfølging."),
            ("TILBAKEMELDING", "Begge veier — leder gir, ansatt gir tilbake.")],
           "Har du opplevd god vs dårlig medarbeidersamtale? Hva skilte dem?",
           [ex("Frekvens", "Hvor ofte bør samtalen skje?",
               [C("a", "Aldri", "For lite."),
                C("b", "Minst årlig, helst kvartalsvis", "Riktig! Hyppigere gir bedre dialog.", correct=True),
                C("c", "Hver dag", "For ofte."),
                C("d", "Kun ved problemer", "For reaktivt.")],
               "Moderne praksis: kortere men hyppigere samtaler. Årlig samtale er for sjelden."),
            ex("Best praksis", "Hva kjennetegner god samtale?",
               [C("a", "Bare lederen snakker", "Skal være dialog."),
                C("b", "Forberedt, dokumentert, dialogbasert, med konkrete tiltak", "Riktig! Strukturert prosess.", correct=True),
                C("c", "Tilfeldig prat", "For lite verdi."),
                C("d", "Bare lønnsdiskusjon", "For smalt.")],
               "Send agenda 1 uke før. Ansatt forbereder også. Skriv ned tiltak med deadline."),
            ex("Vanlig feil", "Hva er klassisk feil?",
               [C("a", "Forberedelse", "Det er bra."),
                C("b", "Skje sjelden, uforberedt, uten oppfølging — ren ritualistisk øvelse", "Riktig! Mister verdien.", correct=True),
                C("c", "For ofte", "Sjelden problem."),
                C("d", "For mye dokumentasjon", "Lite problem."),],
               "Test: skjer det noe konkret etter samtalen? Hvis ikke, er den ritualistisk.")]),
        ph("🚪", "Personalavvikling",
           "Oppsigelse på en lovlig måte.",
           "Oppsigelse og avskjed på en ryddig og lovlig måte. Krav til saklig grunn, drøftingsmøte, rett til advokat. Slurv her gir både rettssaker og dårlig omdømme. Statoils 8000-personers nedbemanning 2014-2016 er klassisk eksempel på god håndtering — åpenhet, sluttpakker, omplassering.",
           [("LOVKRAV", "Saklig grunn, drøftingsmøte, dokumentasjon."),
            ("OMDØMME", "Hvordan avvikles påvirker bedriftens omdømme.")],
           "Hva ville vært viktig hvis du måtte si opp en kollega?",
           [ex("Saklig grunn", "Hva kreves?",
               [C("a", "Ingenting", "Strenge krav."),
                C("b", "Saklig grunn (mangelfull arbeidsutførelse, nedbemanning, mislighold)", "Riktig! Loven krever klar grunn.", correct=True),
                C("c", "Bare lederens magefølelse", "Helt urealistisk."),
                C("d", "Bare økonomisk argument", "For smalt.")],
               "Saklig grunn må kunne dokumenteres. Vagt 'pasret ikke kulturen' er sjelden nok."),
            ex("Drøftingsmøte", "Hva er drøftingsmøte?",
               [C("a", "Ferieplanlegging", "Helt feil."),
                C("b", "Lovpålagt møte før oppsigelse — gir ansatt mulighet til å bli hørt", "Riktig! Prosesskrav.", correct=True),
                C("c", "Bare for ledere", "Gjelder alle ansatte."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Brudd på drøftings-prosess kan være selvstendig grunn for å sette oppsigelse til side."),
            ex("Statoil", "Hva gjorde Statoil bra i 2014-16?",
               [C("a", "Ingen nedbemanning", "Faktisk 8000+ stillinger."),
                C("b", "Åpen prosess, sluttpakker, omplasseringskurs — bevarte omdømme", "Riktig! Klassisk eksempel på ryddig nedbemanning.", correct=True),
                C("c", "Tilfeldig", "Strukturert prosess."),
                C("d", "Hemmelig", "Tvert imot — åpen.")],
               "Resultat: lave rettssaker, bevart omdømme, mange kom tilbake da markedet snudde.")]),
        ph("🌟", "Employer branding",
           "Bli en attraktiv arbeidsgiver.",
           "Employer Branding: hvordan bedriften fremstår som arbeidsgiver. Konkurranse om talent er like hard som konkurranse om kunder. Equinor, DnB, Telenor bruker millioner på å fremstå som førstevalg. Innebærer kultur, lønn, utviklingsmuligheter, omdømme — alt som gjør at folk vil jobbe der.",
           [("TALENT-KONKURRANSE", "Som hard som kunde-konkurranse."),
            ("HELHETLIG", "Kultur + lønn + utvikling + omdømme — alt teller.")],
           "Hvilke bedrifter ville du jobbet for? Hvorfor? Hva gjør dem attraktive?",
           [ex("Hva", "Hva er employer branding?",
               [C("a", "Bedriftens logo", "Bredere konsept."),
                C("b", "Hvordan bli attraktiv arbeidsgiver i konkurransen om talent", "Riktig! Strategisk merkebygging mot ansatte og potensielle ansatte.", correct=True),
                C("c", "Bare lønn", "For smalt."),
                C("d", "Bare reklame mot ansatte", "For smalt.")],
               "Employer branding-rangeringer (Universum) påvirker hvor folk søker. Strategisk verdi."),
            ex("Talent-konkurranse", "Hvorfor så viktig?",
               [C("a", "Tilfeldig", "Strukturell endring."),
                C("b", "Talent er strategisk ressurs — best folk gir best resultater", "Riktig! Særlig i kunnskapsøkonomien.", correct=True),
                C("c", "Bare for tek", "Gjelder alle bransjer."),
                C("d", "Lovkrav", "Helt urelevant."),],
               "Google, Apple bruker mer på rekruttering enn reklame. Talent er deres viktigste innsatsfaktor."),
            ex("Norsk eksempel", "Hvilken norsk bedrift har sterk employer brand?",
               [C("a", "Tilfeldig", "Strategisk valg."),
                C("b", "Equinor — drømmearbeidsgiver for norske ingeniørstudenter", "Riktig! Konsistent toppplassering i Universum-undersøkelser.", correct=True),
                C("c", "Bare offentlige", "Privat sektor like sterk."),
                C("d", "Bare i Oslo", "Nasjonalt fenomen.")],
               "Equinor får tilgang til de beste kandidatene — strategisk fortrinn i innovasjon.")]),
        ph("📊", "HR-strategi",
           "Folk er strategisk ressurs.",
           "HR-strategi: planlegging av fremtidig kompetanseebehov. Hvilke ferdigheter trenger vi om 3 år? Hvor henter vi dem? Hvordan beholder vi nøkkeltalentene? Strategiske spørsmål som ikke kan løses akutt — krever 2-5 års horisont. I kunnskapsøkonomien er HR ofte den viktigste strategiske disiplinen.",
           [("LANGSIKTIG", "2-5 års horisont — ikke akutte beslutninger."),
            ("STRATEGISK", "I kunnskapsøkonomien ofte viktigste strategi.")],
           "Hva tror du er bedriften du jobber for / kjenner sin viktigste fremtidige kompetanse?",
           [ex("Tidshorisont", "Hvor langt frem ser HR-strategi?",
               [C("a", "Neste uke", "For kort."),
                C("b", "2-5 år frem", "Riktig! Kompetansebygging tar tid.", correct=True),
                C("c", "Bare neste år", "For kort."),
                C("d", "100 år", "Overdrevet."),],
               "Du kan ikke 'rekruttere ekspertgruppe i AI' over natten. Krever flere år å bygge."),
            ex("Spørsmål", "Hva er kjernespørsmålene?",
               [C("a", "Bare lønn", "For smalt."),
                C("b", "Hva trenger vi? Hvor finner vi det? Hvordan beholder vi dem?", "Riktig! Strategiske spørsmål.", correct=True),
                C("c", "Bare oppsigelse", "For smalt."),
                C("d", "Tilfeldig", "Strukturert."),],
               "HR-strategi knytter folk til forretningsstrategi. Uten kobling blir det administrasjon."),
            ex("Hvorfor strategisk", "Hvorfor er folk strategisk ressurs?",
               [C("a", "Lovkrav", "Strategisk verdi."),
                C("b", "Folk er bedriftens eneste ressurs som kan tenke selv og innovere", "Riktig! Maskiner gjør det de programmeres til. Mennesker tilpasser seg og skaper.", correct=True),
                C("c", "Bare i USA", "Globalt."),
                C("d", "Tilfeldig", "Strukturelt sant.")],
               "Drucker: 'In the knowledge economy, the most valuable assets walk out the door every evening.' Kritisk innsikt.")]),
    ],
    ["Du forstår HRM som strategisk arbeid med mennesker — ikke bare administrasjon",
     "Du kjenner Herzbergs to-faktor-teori og 70-20-10-læringsmodellen",
     "Du behersker rekrutteringsprosessen og kostnaden ved feil ansettelse",
     "Du forstår norsk arbeidsmiljølov og krav til oppsigelser",
     "Du ser employer branding og HR-strategi som kritiske strategiske disipliner"])


g.write_modules([ORG, HRM], "ML2-13 + ML2-14")
