#!/usr/bin/env python3
"""ENT2 kap 11-13: Strategisk planlegging, Forretningsutvikling, Markedsanalyse."""
import importlib.util
from pathlib import Path
spec = importlib.util.spec_from_file_location("g", Path(__file__).parent / ".gen-shared.py")
g = importlib.util.module_from_spec(spec); spec.loader.exec_module(g)
C, ph, ex, M = g.C, g.ph, g.ex, g.M


STRAT = M("StrategiskPlanleggingVekst", "ent2", "ENT2-11", "Strategisk planlegging for vekst", "🎯",
    "strategisk-planlegging-vekst", "ent2",
    "Strategi er valgene du tar for å vinne — hva du gjør, hva du IKKE gjør, og hvor du satser. Vekstbedrifter trenger systematisk strategisk arbeid.",
    "Norske selskaper som Equinor, Telenor og DNB har egne strategi-avdelinger. Mindre vekstbedrifter må gjøre samme tenkning, bare i mindre skala.",
    "Strategi handler om prioritering. Du kan ikke gjøre alt — så hva velger du å satse på, og hva sier du nei til?",
    [
        ph("🎯", "Hva er strategi?",
           "Strategi er valg av posisjon og retning.",
           "Strategi handler om hvordan bedriften skaper og leverer unik verdi over tid. Det er sammenhengende valg om hvor man konkurrerer, hvordan man vinner, og hvilke ressurser man bruker. Michael Porter skiller mellom operasjonell effektivitet (gjøre samme bedre) og strategi (gjøre noe annet). Equinor flyttet fra olje mot havvind — strategisk valg.",
           [("VALG", "Strategi er hva du gjør OG ikke gjør."),
            ("RETNING", "Lang sikt, ikke daglige beslutninger.")],
           "Hva er din bedrifts strategiske valg de neste tre årene?",
           [ex("Definisjon", "Hva er strategi?",
               [C("a", "Bare daglige beslutninger", "Det er operasjonelt."),
                C("b", "Sammenhengende valg om posisjon og retning på lang sikt", "Riktig! Porters definisjon.", correct=True),
                C("c", "Bare budsjett", "Strategi gir budsjettet retning."),
                C("d", "Tilfeldige valg", "Strategi er strukturert.")],
               "Porter: Strategi er å velge en unik posisjon i markedet."),
            ex("Porter", "Hva skiller strategi fra operasjonell effektivitet?",
               [C("a", "Strategi = gjøre noe annet, OE = gjøre samme bedre", "Riktig! Klar Porter-distinksjon.", correct=True),
                C("b", "Ingen forskjell", "Stor forskjell."),
                C("c", "Bare størrelse", "Begrepsmessig forskjell."),
                C("d", "Tilfeldig", "Strukturelt skille.")],
               "OE er nødvendig men ikke nok — uten unik posisjon konkurrerer alle på pris."),
            ex("Equinor", "Hvorfor er Equinors satsning på havvind strategisk?",
               [C("a", "Bare trend", "Strukturelt valg."),
                C("b", "Strategisk omposisjonering — bygger fremtidsbedrift på eksisterende kompetanse", "Riktig! Klassisk strategisk valg.", correct=True),
                C("c", "Tilfeldig", "Bevisst valg."),
                C("d", "Bare PR", "Massive investeringer.")],
               "Bruker offshore-kompetansen til å bygge ny vekstmotor — strategi er å se trender og posisjonere seg.")]),
        ph("🌍", "PESTEL-analyse",
           "Forstå makro-omgivelsene.",
           "PESTEL kartlegger Politiske, Økonomiske, Sosiokulturelle, Teknologiske, Miljømessige og Lovmessige faktorer som påvirker bedriften. Politiske vedtak om elbiler påvirker Tesla og bilbransjen. Demografi (aldring) påvirker helse-startups. Teknologi (AI) endrer alle bransjer. Klimakrav påvirker Equinor. Bruk PESTEL før strategiske valg.",
           [("MAKRO", "Faktorer du ikke kontrollerer."),
            ("BREDT", "Tving deg til å se utenfor egen bransje.")],
           "Hvilken PESTEL-faktor påvirker din bedrift mest?",
           [ex("Hva", "Hva er PESTEL?",
               [C("a", "Bare politisk", "Seks faktorer."),
                C("b", "Politisk, Økonomisk, Sosiokulturelt, Teknologisk, Miljø, Lovmessig", "Riktig! Bredt rammeverk.", correct=True),
                C("c", "Bare lov", "Mer enn det."),
                C("d", "Konkurrenter", "Det er Porter 5.")],
               "PESTEL = makroanalyse. Porter 5 = bransjeanalyse. SWOT = bedriftsanalyse."),
            ex("Eksempel", "Hvordan påvirket teknologi-faktoren Kodak?",
               [C("a", "Ikke i det hele tatt", "Knuste dem."),
                C("b", "Digitalisering ødela film-forretningen — Kodak så det men handlet ikke", "Riktig! Klassisk strategi-feil.", correct=True),
                C("c", "Hjalp dem", "Tvert imot."),
                C("d", "Bare litt", "Eksistensielt.")],
               "Kodak oppfant digital fotografering men beholdt fokus på film. Teknologi-trend de ikke responderte på."),
            ex("Bruk", "Når bruker du PESTEL?",
               [C("a", "Aldri", "Standard verktøy."),
                C("b", "Ved strategi-utvikling og store investeringer", "Riktig! Strategisk planlegging.", correct=True),
                C("c", "Bare daglig", "Makro-perspektiv."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Brukes typisk hvert 1-3 år ved strategi-revisjon, eller ved store omstillinger.")]),
        ph("🏰", "Porters 5 Forces (avansert)",
           "Bransjestruktur og lønnsomhet.",
           "Porter 5: Konkurrenter (rivalitet), nye aktører (inntreden), substitutter, leverandørmakt, kundemakt. Sammen avgjør de bransjens lønnsomhet. Norsk dagligvare har sterk leverandørmakt (få kjeder), lav inntreden (regulering), men sterk konkurranse. Streaming endrer Hollywood — substitutter forandrer alt. Bruk Porter 5 før du går inn i en bransje.",
           [("BRANSJE", "Forklarer hvorfor noen bransjer er lønnsomme."),
            ("VALG", "Sterke krefter = lav lønnsomhet, svake = høy.")],
           "Hvilken av de 5 kreftene er sterkest i din bransje?",
           [ex("Modell", "Porter 5 sine fem krefter?",
               [C("a", "Bare konkurrenter", "Fem faktorer."),
                C("b", "Rivalitet, inntreden, substitutter, leverandørmakt, kundemakt", "Riktig! Klassiker.", correct=True),
                C("c", "Bare pris", "Mer komplekst."),
                C("d", "PESTEL", "Det er noe annet.")],
               "Lærte 1979, fortsatt grunnstein i strategi-undervisning."),
            ex("Bruk", "Hva forteller Porter 5?",
               [C("a", "Bedrifts-strategi", "Det er én anvendelse."),
                C("b", "Bransjens strukturelle attraktivitet og lønnsomhet", "Riktig! Bransje-nivå.", correct=True),
                C("c", "Bare lov", "Strukturelt."),
                C("d", "Tilfeldig", "Strukturert analyse.")],
               "Sterk leverandørmakt + stor kundemakt = vanskelig bransje uavhengig av strategi."),
            ex("Eksempel", "Hvorfor er flyselskaper ulønnsomme?",
               [C("a", "Tilfeldig", "Strukturelt."),
                C("b", "Sterke krefter — leverandører (fly), kunder (pris), konkurranse, substitutter", "Riktig! Klassisk Porter-eksempel.", correct=True),
                C("c", "Bare flaks", "Strukturelt."),
                C("d", "Bare lov", "Bransjestrukturelt.")],
               "Warren Buffett: 'Hvis Wright-brødrene visste hvor lite penger flyselskaper ville tjene, hadde de skutt seg selv ned.'")]),
        ph("📊", "BCG-matrisen",
           "Portefølje-strategi for produkter.",
           "BCG-matrisen plasserer produkter etter markedsandel og markedsvekst: Stjerner (høy/høy — invester), Kontantkyr (høy/lav — melk), Spørsmålstegn (lav/høy — vurder) og Hunder (lav/lav — selg/avvikl). Telenor Mobil er kontantku, satellittsatsninger var stjerner/spørsmålstegn. Brukes ved strategiske ressursvalg.",
           [("PORTEFØLJE", "Tenk på flere produkter samtidig."),
            ("RESSURSER", "Hvor skal vi investere, melke, avvikle?")],
           "Hvilke produkter har bedriften din i hver kategori?",
           [ex("Modell", "BCG sine fire kategorier?",
               [C("a", "Bare produkt", "Fire kategorier."),
                C("b", "Stjerner, Kontantkyr, Spørsmålstegn, Hunder", "Riktig! Klassisk matrise.", correct=True),
                C("c", "Bare 2", "Fire kvadranter."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Boston Consulting Group, 1970. Akse 1: relativ markedsandel. Akse 2: markedsvekst."),
            ex("Strategi", "Hva gjør du med en kontantku?",
               [C("a", "Avvikl", "Generer kontanter."),
                C("b", "Melk for å finansiere stjerner og spørsmålstegn", "Riktig! Klassisk strategi.", correct=True),
                C("c", "Bare invester", "Begrenset vekst."),
                C("d", "Tilfeldig", "Strategisk valg.")],
               "Kontantkyr betaler for fremtiden. Stjerner blir morgendagens kontantkyr."),
            ex("Eksempel", "Hva er Microsoft Office?",
               [C("a", "Stjerne", "Lavt vekst nå."),
                C("b", "Kontantku — høy markedsandel, lav vekst, generer enorm cash", "Riktig! Klassisk eksempel.", correct=True),
                C("c", "Hund", "Tvert imot."),
                C("d", "Spørsmålstegn", "Etablert.")],
               "Office finansierer Azure (stjerne) og AI-satsninger (spørsmålstegn). Klassisk portefølje-tenkning.")]),
        ph("🚀", "Ansoff-matrisen",
           "Vekststrategier i 2x2.",
           "Ansoff-matrisen viser fire vekststrategier: Markedspenetrasjon (eksisterende produkt + marked, mest sikkert), Produktutvikling (nytt produkt + eksisterende marked), Markedsutvikling (eksisterende produkt + nytt marked), Diversifisering (nytt + nytt, mest risiko). Tomra penetrerer eksisterende panteautomat-marked, utviklet sortering (produkt-utvikling), gikk til USA (markedsutvikling). Diversifisering er sjelden — Virgin er unntaket.",
           [("RISIKO", "Diversifisering = høyest risiko."),
            ("VALG", "Velg én eller to retninger, ikke alle.")],
           "Hvilken Ansoff-strategi følger din bedrift nå?",
           [ex("Modell", "Ansoff sine fire vekststrategier?",
               [C("a", "Bare en", "Fire."),
                C("b", "Penetrasjon, produktutvikling, markedsutvikling, diversifisering", "Riktig! Klassisk modell.", correct=True),
                C("c", "Bare BCG", "Annet rammeverk."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Igor Ansoff, 1957. Akse 1: produkt (eksisterende/nytt). Akse 2: marked (eksisterende/nytt)."),
            ex("Risiko", "Hvilken er mest risikabel?",
               [C("a", "Penetrasjon", "Sikrest."),
                C("b", "Diversifisering — nytt produkt + nytt marked = ukjent på alt", "Riktig! Høyest risiko, høyest gevinst.", correct=True),
                C("c", "Produktutvikling", "Du kjenner markedet."),
                C("d", "Tilfeldig", "Risikograd er målt.")],
               "Diversifisering = bygge ny bedrift fra null. Mange feiler her."),
            ex("Eksempel", "Hva gjorde Tomra med USA-ekspansjon?",
               [C("a", "Penetrasjon", "Nytt marked."),
                C("b", "Markedsutvikling — eksisterende produkt i nytt geografisk marked", "Riktig! Klassisk eksempel.", correct=True),
                C("c", "Diversifisering", "Samme produkt."),
                C("d", "Tilfeldig", "Strategisk valg.")],
               "Tomra eksporterer norsk panteautomat-teknologi globalt. Markedsutvikling.")]),
        ph("⚔️", "Konkurransefortrinn",
           "Hva gjør deg unik?",
           "Porter: To grunntyper konkurransefortrinn — kostnadslederskap (være billigst) eller differensiering (være best/unik). I tillegg fokuseringstrategi (smal nisje). Rema 1000 er kostnadsleder. Stormberg differensierer på etikk og produktkvalitet. Apple differensierer på design og økosystem. Du må velge — å prøve begge gir 'stuck in the middle'.",
           [("VELG", "Differensiering eller kostnad — sjelden begge."),
            ("VARIG", "Konkurransefortrinn må forsvares mot kopi.")],
           "Hva er bedriften din sitt primære konkurransefortrinn?",
           [ex("Typer", "Porters generiske strategier?",
               [C("a", "Bare pris", "To pluss fokus."),
                C("b", "Kostnadslederskap, differensiering og fokuseringstrategi", "Riktig! Tre grunntyper.", correct=True),
                C("c", "Bare reklame", "Strategisk valg."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Stuck in the middle = verken billigst eller best — taper."),
            ex("Differensiering", "Hva må du gjøre for å differensiere?",
               [C("a", "Senke pris", "Det er kostnadsstrategi."),
                C("b", "Skape unik verdi kunden er villig til å betale ekstra for", "Riktig! Premium-posisjon.", correct=True),
                C("c", "Tilfeldig", "Strategisk valg."),
                C("d", "Kopi", "Tvert imot.")],
               "Apple, Mercedes, Stormberg — kunder betaler premium for opplevd merverdi."),
            ex("Eksempel", "Hvordan differensierer Stormberg?",
               [C("a", "Lavest pris", "Mellompris."),
                C("b", "Etikk (fair trade, miljø) og kvalitet — etisk premium-merke", "Riktig! Klart valg.", correct=True),
                C("c", "Tilfeldig", "Strategisk valg."),
                C("d", "Bare lov", "Strategisk valg.")],
               "Stormberg ansetter folk med hull i CV — etisk profil = differensiering. Bevisst strategi.")]),
        ph("🎯", "Visjon, misjon og verdier",
           "Hvor skal vi, hvorfor finnes vi?",
           "Visjon = drømmen om fremtiden ('hva ønsker vi å bli'). Misjon = nåværende oppgave ('hvorfor finnes vi'). Verdier = hvordan vi oppfører oss. Equinors visjon er 'energi for et bedre liv'. NSB → Vy endret visjon fra 'jernbane' til 'mobilitet'. Verdier styrer beslutninger når regler ikke rekker. Bra V/M/V = beslutningskompass.",
           [("VISJON", "Inspirerer ansatte og rekruttering."),
            ("VERDIER", "Test: vil du fyre for brudd, ikke bare belønne for etterlevelse?")],
           "Hva er din bedrifts visjon? Misjon? Verdier?",
           [ex("Forskjell", "Visjon vs misjon?",
               [C("a", "Det samme", "Forskjell."),
                C("b", "Visjon = fremtidig drøm, misjon = nåværende oppgave", "Riktig! Tidshorisont skiller.", correct=True),
                C("c", "Bare lov", "Strategisk verktøy."),
                C("d", "Tilfeldig", "Strukturelt.")],
               "Visjon: 'En verden uten kreft.' Misjon: 'Vi forsker på kreftbehandling.'"),
            ex("Verdier", "Når er verdier ekte?",
               [C("a", "På veggen", "Lett å skrive."),
                C("b", "Når du sier opp folk eller mister kunder for å forsvare dem", "Riktig! Tester verdier.", correct=True),
                C("c", "I markedsføring", "Lett å påberope."),
                C("d", "Tilfeldig", "Tester gjennom handling.")],
               "Patagonia tapte kunder ved å ta miljøstandpunkt. Det viser ekte verdier."),
            ex("Equinor", "Hvorfor endret Statoil til Equinor?",
               [C("a", "Tilfeldig", "Strategisk."),
                C("b", "Visjon-skift fra olje til energi — 'energi for et bedre liv'", "Riktig! Strategisk omposisjonering.", correct=True),
                C("c", "Bare design", "Strategisk valg."),
                C("d", "Bare lov", "Strategisk valg.")],
               "Equinor signaliserer langsiktig strategi mot havvind, hydrogen, CO2-lagring.")]),
        ph("📐", "OKR og KPI",
           "Måling og oppfølging av strategi.",
           "OKR (Objectives & Key Results) brukt av Google, Spotify og mange norske scaleups. Tre nivåer: Objective (kvalitativt mål, inspirerende), Key Results (3-5 målbare resultater per objective). KPI = løpende drifts-måling. OKR settes hver kvartal, KPI måles løpende. Skille: KPI for 'business as usual', OKR for 'noe vi skal endre/vekse'.",
           [("MÅLBARE", "Det som måles, blir gjort."),
            ("OFTE", "Kvartalsvis revurdering — ikke årlig planlegging.")],
           "Hva er din bedrifts viktigste OKR for kvartalet?",
           [ex("Hva", "Hva er OKR?",
               [C("a", "Bare KPI", "Forskjellig formål."),
                C("b", "Objectives & Key Results — kvartalsvise endrings-mål", "Riktig! Google-modellen.", correct=True),
                C("c", "Bare visjon", "Konkrete mål."),
                C("d", "Tilfeldig", "Strukturert.")],
               "John Doerr brakte OKR fra Intel til Google. Boken 'Measure What Matters'."),
            ex("Forskjell", "OKR vs KPI?",
               [C("a", "Det samme", "Forskjellige."),
                C("b", "OKR = endringsmål kvartalsvis, KPI = løpende drift", "Riktig! Skiller seg.", correct=True),
                C("c", "Bare lov", "Strukturelt."),
                C("d", "Tilfeldig", "Strategisk skille.")],
               "KPI: månedlig omsetning. OKR: lansere produkt X innen Q2."),
            ex("Eksempel", "Eksempel på god OKR?",
               [C("a", "'Bli bedre'", "For vagt."),
                C("b", "O: Bli den foretrukne SaaS-leverandøren. KR: Vokse fra 100 til 200 kunder, 95% retention, NPS 50", "Riktig! Strukturert.", correct=True),
                C("c", "Bare omsetning", "Bare ett tall."),
                C("d", "Tilfeldig", "Strukturert format.")],
               "OKR skal være ambisiøs — 70% oppnåelse er ofte målet, ikke 100%.")]),
        ph("⚠️", "Misforståelser om strategi",
           "Vanlige feil i strategi-arbeid.",
           "Vanlige feil: 1) Strategi er bare planlegging — nei, det er valg om hva man IKKE gjør. 2) Strategi er for store bedrifter — nei, små trenger fokus mer. 3) Strategi er ledelsens jobb alene — nei, må forankres i hele organisasjonen. 4) Visjon er strategi — nei, visjonen er inspirasjon, strategi er handlingsplan. 5) Strategi er statisk — må revideres kvartalsvis.",
           [("VALG", "Strategi krever sterke nei-er."),
            ("LEVENDE", "Strategi som ikke endres er død strategi.")],
           "Hvilken misforståelse har du selv hatt om strategi?",
           [ex("Mest vanlig", "Hva er den største misforståelsen?",
               [C("a", "Strategi = bare ledelsens jobb", "En av flere."),
                C("b", "Strategi = mer av alt — egentlig handler det om å velge bort", "Riktig! Sentral Porter-innsikt.", correct=True),
                C("c", "Bare for store", "Liten misforståelse."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Porter: 'The essence of strategy is choosing what NOT to do.' Sterke nei-er."),
            ex("Statisk", "Er strategi statisk?",
               [C("a", "Ja, fast", "Endrer seg."),
                C("b", "Nei — må revideres jevnlig (kvartalsvis) når omgivelsene endres", "Riktig! Levende dokument.", correct=True),
                C("c", "Tilfeldig", "Strukturert revisjon."),
                C("d", "Bare lov", "Strategisk valg.")],
               "Kodak hadde strategi men endret den ikke. Blockbuster også. Konsekvenser."),
            ex("Liten", "Trenger små bedrifter strategi?",
               [C("a", "Nei", "Tvert imot."),
                C("b", "Ja — faktisk mer enn store; har færre ressurser å sløse på feil retning", "Riktig! Fokus mer kritisk.", correct=True),
                C("c", "Bare for å imponere", "Strategisk verdi."),
                C("d", "Tilfeldig", "Strategisk verktøy.")],
               "Stor bedrift kan tolerere strategi-feil. Liten gründer går konkurs.")]),
        ph("⚖️", "Lovverk og strategiske rammer",
           "Eksterne rammer for strategi.",
           "Strategiske valg påvirkes av: konkurranselovgivning (forbud mot prissamarbeid), GDPR (databegrensninger), klimakrav og taksonomi (EU-regler), åpenhetsloven (rapporteringskrav), arbeidsmiljøloven og arbeidsrett (HR-rammer), EUs Digital Services Act (DSA). Equinor må følge taksonomi for å hente kapital. Strategi må være lovlig OG attraktiv for investorer.",
           [("RAMMER", "Lov gir både hindringer og muligheter."),
            ("ESG", "Strategi må svare på bærekraftskrav.")],
           "Hvilke lovverk påvirker din bedrift sin strategi?",
           [ex("Konkurranse", "Hva forbyr konkurranseloven?",
               [C("a", "All konkurranse", "Tvert imot."),
                C("b", "Prissamarbeid og misbruk av dominerende stilling", "Riktig! Sentrale forbud.", correct=True),
                C("c", "Bare reklame", "Strukturelle forbud."),
                C("d", "Tilfeldig", "Strukturert lov.")],
               "Konkurransetilsynet håndhever. Bøter kan være 10% av global omsetning."),
            ex("ESG", "Hva er EU-taksonomien?",
               [C("a", "Bare skatt", "Bærekrafts-rammeverk."),
                C("b", "Klassifisering av hva som er bærekraftige økonomiske aktiviteter", "Riktig! Påvirker kapital-tilgang.", correct=True),
                C("c", "Bare en list", "Strukturelt rammeverk."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Investorer krever taksonomi-rapportering. Påvirker hva bedrifter kan gjøre og finansiere."),
            ex("Strategi", "Hvordan påvirker dette strategi?",
               [C("a", "Ikke", "Helt sentralt."),
                C("b", "Strategiske valg må være både lovlige og bærekrafts-rapporterbare", "Riktig! Doble krav.", correct=True),
                C("c", "Bare for store", "Gjelder alle."),
                C("d", "Tilfeldig", "Strukturelt krav.")],
               "Investor-attraktivitet krever ESG-strategi. Lovkrav setter rammen.")]),
    ],
    ["Du forstår at strategi er valg om hva man IKKE gjør, ikke bare hva man gjør",
     "Du behersker PESTEL, Porter 5 Forces, BCG og Ansoff som strategiske analyseverktøy",
     "Du kjenner Porter generiske strategier: kostnad, differensiering, fokusering",
     "Du forstår V/M/V, OKR og KPI som styringsverktøy",
     "Du ser at strategi må forholde seg til lov, ESG og taksonomi"])


FORRSKAL = M("ForretningsutviklingSkalering", "ent2", "ENT2-12", "Forretningsutvikling og skalering", "📈",
    "forretningsutvikling-skalering", "ent2",
    "Skalering er kunsten å vokse uten å miste kvalitet eller kultur. Mange startups dør i overgangen fra 10 til 100 ansatte.",
    "Norske scaleups som Kahoot, Cognite og Oda har skalert raskt internasjonalt — alle har egne 'scaling playbooks'.",
    "Skalering = repetisjon av suksess. Ikke vokse før du har funnet noe som fungerer — men når du har, vokse raskt.",
    [
        ph("🌱", "Hva er skalering?",
           "Vokse uten å miste det som virker.",
           "Skalering = vokse omsetning og volum uten tilsvarende økning i kostnader. Forretningsmodellen må være repeterbar — produktet må kunne selges til mange likes kunder uten omfattende tilpasning. SaaS skalerer bra (samme kode, mange kunder). Konsulentbyrå skalerer dårlig (lineær mellom omsetning og ansatte). Skala krever forretningsmodell som er bygget for det.",
           [("REPETISJON", "Skalerbar modell = produkt selger til mange like kunder."),
            ("MODELL", "Konsulent vs SaaS — radikalt forskjellig skalerbarhet.")],
           "Er din forretningsmodell skalerbar? Hvorfor/hvorfor ikke?",
           [ex("Definisjon", "Hva er skalering?",
               [C("a", "Bare vokse", "Mer presist."),
                C("b", "Vokse omsetning uten tilsvarende kostnadsøkning", "Riktig! Definisjon.", correct=True),
                C("c", "Bare ansette", "Konsekvens, ikke definisjon."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Marginal kostnad per ny kunde må være lav. Det er kjernen i skalering."),
            ex("Modell", "SaaS vs konsulent?",
               [C("a", "Det samme", "Stor forskjell."),
                C("b", "SaaS skalerer (samme kode, mange kunder); konsulent er lineært timer/kr", "Riktig! Forretningsmodell-forskjell.", correct=True),
                C("c", "Bare lov", "Modell-forskjell."),
                C("d", "Tilfeldig", "Strukturelt.")],
               "Konsulent kan skalere via spesialisering eller produkter — men starten er lineær."),
            ex("Eksempel", "Hvorfor skalerer Kahoot?",
               [C("a", "Tilfeldig", "Strukturelt."),
                C("b", "Software brukt av millioner — marginalkostnad per bruker nær null", "Riktig! Klassisk software-skalering.", correct=True),
                C("c", "Bare reklame", "Modellen er kjernen."),
                C("d", "Bare ansatte", "Skala kommer fra modell.")],
               "Kahoot har 20% av norsk arbeidsstyrke som brukere — samme kode for alle.")]),
        ph("🔄", "Product-market fit",
           "Når produktet finner markedet.",
           "PMF = produktet løser problemet markedet faktisk har. Marc Andreessen: 'Du kjenner det når du har det — kunden kjøper raskere enn du klarer å levere.' Før PMF: ikke skaler, du vil bare gjøre feil raskere. Etter PMF: skaler aggressivt. Mange startups feiler ved å skalere før de har PMF. Slack hadde PMF før de gikk i markedsmodus.",
           [("FØR", "Ikke skaler før PMF — du repeterer feil."),
            ("ETTER", "Etter PMF skaler raskt før konkurrenter kommer.")],
           "Har din bedrift product-market fit? Hvordan vet du?",
           [ex("Definisjon", "Hva er PMF?",
               [C("a", "Bare salg", "Mer presist."),
                C("b", "Produktet løser kundens problem så godt at etterspørselen er sterk", "Riktig! PMF-definisjon.", correct=True),
                C("c", "Bare lov", "Markedsfaktor."),
                C("d", "Tilfeldig", "Strukturelt.")],
               "Andreessen: 'Customers are buying as fast as you can make it.'"),
            ex("Tegn", "Tegn på PMF?",
               [C("a", "Bare gode tilbakemeldinger", "Sterkere tegn."),
                C("b", "Organisk vekst, lav churn, kunder anbefaler andre, du sliter med å levere", "Riktig! Sterke signaler.", correct=True),
                C("c", "Bare et salg", "Trenger mønster."),
                C("d", "Tilfeldig", "Strukturerte signaler.")],
               "Sean Ellis test: spør kunder hvor skuffet de blir hvis de mister produktet. >40% 'veldig skuffet' = PMF."),
            ex("Før vs etter", "Hva endres ved PMF?",
               [C("a", "Tilfeldig", "Strategisk skift."),
                C("b", "Før PMF = optimaliser produkt; etter PMF = skaler salg/markedsføring", "Riktig! To ulike faser.", correct=True),
                C("c", "Bare lov", "Strategisk skift."),
                C("d", "Bare ansette", "Strategisk fokusskift.")],
               "Skalering før PMF = brenner kapital på feil retning. Etter PMF = optimaliser distribusjon.")]),
        ph("📊", "Skalere salg og markedsføring",
           "Bygge salgsmaskin som vokser.",
           "Skalering av salg krever: 1) Repeterbar salgsprosess (alle kan selge samme måten), 2) Salgsmateriell og playbooks, 3) CRM-system (HubSpot, Salesforce), 4) Klare KPI-er (CAC, LTV, conversion). Outbound vs inbound: outbound skaler ved å ansette flere selgere, inbound ved å investere i innhold/SEO. Hubspot vokste ved inbound. Oracle ved outbound.",
           [("PROSESS", "Du skaler ikke selgere, du skaler prosess."),
            ("MÅLBARE", "CAC, LTV, churn — sjekkpunkter du må beherske.")],
           "Hvordan skalerer din bedrift salget?",
           [ex("Krav", "Hva skal til for å skalere salg?",
               [C("a", "Bare flere selgere", "Trenger system."),
                C("b", "Repeterbar prosess, playbooks, CRM, KPI-er", "Riktig! Systemiske krav.", correct=True),
                C("c", "Bare reklame", "Bredere system."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Uten prosess gjør hver selger sin egen variant — uskalerbar."),
            ex("Inbound", "Hva er inbound salg?",
               [C("a", "Selger ringer ut", "Det er outbound."),
                C("b", "Kunder kommer til deg via innhold, SEO, anbefaling", "Riktig! Pull-modell.", correct=True),
                C("c", "Bare reklame", "Spesifikk modell."),
                C("d", "Tilfeldig", "Strukturert tilnærming.")],
               "Inbound: kunde-magnet (innhold, SEO). Outbound: cold calling, e-post."),
            ex("KPI", "Viktigste salgs-KPI ved skalering?",
               [C("a", "Bare omsetning", "Grovt."),
                C("b", "CAC og LTV — kostnad per kunde og kundens livstidsverdi", "Riktig! Lønnsomhet.", correct=True),
                C("c", "Bare lov", "Forretningsfaktor."),
                C("d", "Tilfeldig", "Konkret KPI.")],
               "LTV/CAC > 3 = sunn bedrift. < 1 = brenner penger.")]),
        ph("👥", "Skalere team og ansette",
           "Hvordan vokse fra 10 til 100.",
           "Hver fordobling av ansatte krever ny struktur. 10 ansatte: alle vet alt. 25: avdelinger oppstår. 50: ledelseslag. 100: politikker. 250: byråkrati uten kjent kultur. Reed Hoffmans 'Blitzscaling': prioriter hastighet over effektivitet i vekstfase. Men: feil ansettelse er dyrere enn ingen ansettelse. Stripe har egne 'first 100 engineers'-playbook.",
           [("FASER", "10/25/50/100 — ulike utfordringer."),
            ("FEIL", "Bedre å vente enn ansette feil person.")],
           "Hvor mange ansatte er din bedrift? Hva er neste utfordring?",
           [ex("Faser", "Hva skjer ved 50 ansatte?",
               [C("a", "Tilfeldig", "Strukturelt."),
                C("b", "Ledelseslag oppstår — ledere som leder ledere, ikke bare bidragsytere", "Riktig! Klassisk overgang.", correct=True),
                C("c", "Ingenting", "Stort skille."),
                C("d", "Bare lov", "Organisatorisk."),],
               "10-50: alle bidragsytere. 50+: ledelse blir egen disiplin."),
            ex("Feilansettelse", "Hvor mye koster feilansettelse?",
               [C("a", "Lite", "Mye."),
                C("b", "Estimat: 2-3 ganger årslønn pluss forsinkelser", "Riktig! Stort tap.", correct=True),
                C("c", "Tilfeldig", "Strukturert estimat."),
                C("d", "Bare lov", "Forretningstap.")],
               "Tap inkluderer: lønn, opplæring, sluttpakke, tapt momentum, lederens tid."),
            ex("Blitzscaling", "Hva er Reid Hoffmans blitzscaling?",
               [C("a", "Bare ansette", "Mer strategisk."),
                C("b", "Prioriter hastighet over effektivitet i vekstfase for å vinne marked", "Riktig! Konsept fra LinkedIn-grunnlegger.", correct=True),
                C("c", "Tilfeldig", "Strukturert tilnærming."),
                C("d", "Bare lov", "Strategisk valg.")],
               "Brukt av Facebook, Airbnb, Uber. Risiko: brenner kapital, bygger gjeld.")]),
        ph("⚙️", "Skalere systemer og prosesser",
           "Automatisering og infrastruktur.",
           "Det som virker manuelt for 10 kunder dør ved 1000. Skalering krever: 1) Automatisering av repetitive oppgaver, 2) Selvbetjening for kundene, 3) Robust IT-infrastruktur (cloud), 4) Dokumentasjon og prosessbeskrivelser. Stripe vokste ved å gjøre betaling 7 linjer kode. Shopify gjør e-handel selv-betjent. Manuelle workarounds som virker tidlig blir flaskehalser senere.",
           [("AUTOMATISER", "Det som gjøres ofte må automatiseres."),
            ("SELVBETJENING", "Kunden gjør jobben — du skalerer bedre.")],
           "Hva er din bedrifts største flaskehals i prosesser?",
           [ex("Hva", "Hva må skaleres i prosesser?",
               [C("a", "Bare ansette flere", "Bedre å automatisere."),
                C("b", "Automatisering, selvbetjening, IT, dokumentasjon", "Riktig! Helhetlig.", correct=True),
                C("c", "Bare lov", "Strukturelt."),
                C("d", "Tilfeldig", "Strukturert.")],
               "10 kunder kan håndteres med Excel. 1000 trenger system."),
            ex("Eksempel", "Hva gjorde Stripe?",
               [C("a", "Bare reklame", "Produktet var nøkkelen."),
                C("b", "Gjorde betaling til 7 linjer kode — selvbetjent integrasjon", "Riktig! Skalerings-mester.", correct=True),
                C("c", "Tilfeldig", "Bevisst design."),
                C("d", "Bare ansatte", "Produkt-design.")],
               "Stripe vant fordi de gjorde det enkelt for utviklere. Selvbetjening = skala."),
            ex("Manuelt", "Hvorfor kollapser manuelle prosesser?",
               [C("a", "Tilfeldig", "Strukturelt."),
                C("b", "Lineær arbeidsmengde med kunde-vekst — flere kunder = flere timer", "Riktig! Skala-blokkering.", correct=True),
                C("c", "Lov", "Operasjonelt."),
                C("d", "Bare PR", "Operasjonell svikt.")],
               "Manuelt gjør det at du må ansette én ny per X kunder. Bryter skalering.")]),
        ph("🌐", "Internasjonalisering",
           "Vokse ut av Norge.",
           "Norge er for lite for store ambisjoner. Norske scaleups går tidlig ut. Strategi: 1) Norden først (likhet i marked), 2) Engelsk-talende (UK/USA), 3) Lokaliser produkt + språk + betaling. Kahoot har 80% inntekter utenfor Norge. Cognite valgte USA før Asia. Risiko: språk, kultur, regulering. Mest vellykkede: nordisk hjemmebane → engelsk-talende → resten.",
           [("TIDLIG", "Norge er for lite. Tenk globalt fra start."),
            ("FOKUS", "Velg ett nytt marked, ikke fem.")],
           "Hvilke markeder bør din bedrift inn i? I hvilken rekkefølge?",
           [ex("Hvorfor", "Hvorfor må norske bedrifter ut?",
               [C("a", "Tilfeldig", "Strukturelt."),
                C("b", "Norge er for lite — kun 5,5M innbyggere", "Riktig! Markedstørrelse.", correct=True),
                C("c", "Bare lov", "Markedsfaktor."),
                C("d", "Bare PR", "Strategisk valg.")],
               "Sammenlignet: USA 330M, EU 450M, Kina 1,4B. Norsk bedrift bygd for hjemme = liten."),
            ex("Strategi", "Hva er beste rekkefølge?",
               [C("a", "Tilfeldig", "Strukturert."),
                C("b", "Norden → engelsktalende → resten — kultur-likhet først", "Riktig! Risiko-trapp.", correct=True),
                C("c", "Kina først", "Stort kultur-gap."),
                C("d", "Bare lov", "Strategisk valg.")],
               "Sverige er lik Norge. UK gir engelsk + tilgang til USA. Asia kommer sist."),
            ex("Eksempel", "Hva gjorde Kahoot?",
               [C("a", "Norge bare", "Tidlig ut."),
                C("b", "Tidlig USA-fokus — der er skole-markedet stort", "Riktig! Strategisk valg.", correct=True),
                C("c", "Tilfeldig", "Bevisst.")  ,
                C("d", "Bare lov", "Strategisk.")],
               "Kahoots stiftere flyttet til USA. Marked var der lærerne var. 80% inntekter utenlands.")]),
        ph("💰", "Skalere finansiering",
           "Vokse kapital med vekst.",
           "Skalerings-rundene: Seed (1-5M) → Series A (10-30M) → Series B (50-150M) → Series C (>150M). Hver runde har klare milepæler: A = PMF + tidlig skala, B = repeterbar vekst, C = markedslederskap. Norske scaleups som Cognite har vært gjennom alle. Equity vs gjeld vs venture: tidlig fase = equity (mest fleksibelt), sen fase kan også gjeld. Værvarsel: brenner mer enn 18 måneder cash = problem.",
           [("MILEPÆLER", "Hver runde krever spesifikk fremgang."),
            ("RUNWAY", "Alltid 18 måneders cash i banken.")],
           "Hvor mange måneder runway har din bedrift?",
           [ex("Runder", "Hva er Series A?",
               [C("a", "Første runde", "Det er seed."),
                C("b", "Større runde etter PMF — typisk 10-30M for å skalere", "Riktig! Vekstrunde.", correct=True),
                C("c", "Bare lov", "Finansieringsrunde."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Seed → A → B → C. Beløp og krav øker hver runde."),
            ex("Milepæl", "Hva forventer Series A-investor?",
               [C("a", "Bare ide", "Senere fase."),
                C("b", "Product-market fit, repeterbar inntekt, klar skaleringsplan", "Riktig! Bevis på modell.", correct=True),
                C("c", "Tilfeldig", "Strukturerte krav."),
                C("d", "Bare lov", "Forretningskrav.")],
               "Series A er ikke for ide — det er for å akselerere modell som virker."),
            ex("Runway", "Hva er runway?",
               [C("a", "Bare flytur", "Forretningsbegrep."),
                C("b", "Måneder med driftskapital før pengene tar slutt", "Riktig! Survival-måling.", correct=True),
                C("c", "Bare lov", "Finansiell måling."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Runway = (cash i banken) / (månedlig burn). Under 6 måneder = krise.")]),
        ph("🏆", "Bygge markedsposisjon",
           "Fra utfordrer til markedsleder.",
           "Markedsposisjon: 1) Niche-leder (best i smal nisje), 2) Utfordrer (nr 2-3, kjemper opp), 3) Markedsleder (nr 1, definerer marked), 4) Følger (kopierer leder). Strategi varierer: utfordrer differensierer, leder forsvarer. Tomra er global markedsleder i panteautomater. Vipps er nasjonal leder. Strategi for å beholde posisjon: kontinuerlig innovasjon + brand-bygging + lojalitet.",
           [("NISJE", "Bedre å være leder i nisje enn nr 5 i breddt marked."),
            ("FORSVARE", "Markedsleder bruker mer på forsvar enn angrep.")],
           "Hva er din bedrifts markedsposisjon?",
           [ex("Posisjoner", "Fire grunntyper markedsposisjoner?",
               [C("a", "Bare leder", "Fire roller."),
                C("b", "Niche-leder, utfordrer, markedsleder, følger", "Riktig! Strategiske roller.", correct=True),
                C("c", "Bare 2", "Fire kategorier."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Hver rolle har egen optimalstrategi. Følger-strategi = lavpris kopi."),
            ex("Nisje", "Hvorfor velge nisje?",
               [C("a", "Tilfeldig", "Strategisk."),
                C("b", "Mindre konkurranse, lettere å bli leder, høyere marginer", "Riktig! Strategi for små.", correct=True),
                C("c", "Bare PR", "Strategisk valg."),
                C("d", "Bare lov", "Strategisk valg.")],
               "Better at one thing > medium at many. Tomra er nesten alene globalt på pante."),
            ex("Eksempel", "Hvordan forsvarer Vipps posisjonen?",
               [C("a", "Bare reklame", "Mer omfattende."),
                C("b", "Brand, integrasjoner, brukervennlighet, økosystem, banktilknytning", "Riktig! Helhetlig forsvar.", correct=True),
                C("c", "Tilfeldig", "Strukturert.")  ,
                C("d", "Bare lov", "Strategisk forsvar.")],
               "Vipps forsvarer mot internasjonale (Apple Pay, Google Pay) ved nettverkseffekt og lokal tilpasning.")]),
        ph("⚠️", "Misforståelser om skalering",
           "Vanlige feil ved vekst.",
           "Vanlige feil: 1) Skalere før PMF — repeterer feil raskere. 2) Ansette for raskt — bygger feil kultur. 3) Ignorere kostnader — 'vi skal vokse oss til lønnsomhet' fungerer sjelden. 4) Glemme kunden — ny ansatte er ikke kundefokuserte. 5) Holde på alle små kunder — drenerer ressurser. WeWork eksemplifiserer flere — skalerte uten lønnsomhet.",
           [("SEKVENS", "PMF før skala. Lønnsomhet før vekst (vanligvis)."),
            ("KUNDEKULTUR", "Skala kan tørke ut kundefokus.")],
           "Hvilken misforståelse om skalering kjenner du igjen?",
           [ex("Feil", "Største vanlige skaleringsfeil?",
               [C("a", "Bare ansette", "Konsekvens."),
                C("b", "Skalere før product-market fit", "Riktig! Sentral feil.", correct=True),
                C("c", "Bare lov", "Strategi-feil."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Skalere uten PMF = brenne kapital på feil retning. Klassisk dødsårsak."),
            ex("Lønnsom", "Vokse seg til lønnsomhet?",
               [C("a", "Alltid riktig", "Sjelden."),
                C("b", "Risikabelt — fungerer for noen plattformer, ofte ikke", "Riktig! Avhenger av modell.", correct=True),
                C("c", "Tilfeldig", "Strategisk valg."),
                C("d", "Aldri", "Noen ganger virker det.")],
               "Amazon brukte 14 år på lønnsomhet — og hadde plan. WeWork hadde ikke."),
            ex("Kunder", "Hva er problemet med å holde alle små kunder?",
               [C("a", "Ingen", "Stort problem."),
                C("b", "Drenerer ressurser — bedre å fokusere på lønnsomme kundesegmenter", "Riktig! Pareto-prinsippet.", correct=True),
                C("c", "Tilfeldig", "Strukturelt.")  ,
                C("d", "Bare lov", "Strategisk valg.")],
               "20% av kunder gir 80% av omsetning. Skill mellom verdifulle og verdiløse.")]),
        ph("⚖️", "Lovverk ved skalering",
           "Compliance-utfordringer ved vekst.",
           "Skalering møter nye lovkrav: GDPR (datavolum øker), åpenhetsloven (>50 ansatte = krav), arbeidsmiljøloven (verneombud, AMU), regnskapsloven (revisjonsplikt), MVA-grenser (ulike land), produktansvarslov, skatte-EOR ved internasjonale ansatte. Mange scaleups blir overrasket av compliance-byrden. Bygg compliance-funksjon ved 25-50 ansatte.",
           [("TERSKLER", "Visse antall ansatte/omsetning utløser nye krav."),
            ("INTERNASJONALT", "Hvert land har egne regler.")],
           "Hvilke compliance-krav vil din bedrift møte ved vekst?",
           [ex("GDPR", "Hvorfor er GDPR utfordring ved skalering?",
               [C("a", "Tilfeldig", "Strukturelt."),
                C("b", "Mer data = mer ansvar, internasjonale krav, prosessdokumentasjon", "Riktig! Datavolum-effekt.", correct=True),
                C("c", "Bare lov", "Operasjonelle krav."),
                C("d", "Bare PR", "Compliance.")],
               "1000 kunder = 1000 datasubjekter med rettigheter (innsyn, sletting). Skala = byrde."),
            ex("Åpenhet", "Når trer åpenhetsloven inn?",
               [C("a", "Aldri", "Konkret terskel."),
                C("b", "Ved >50 ansatte ELLER ved store omsetnings-/balanse-grenser", "Riktig! Terskel-utløsende.", correct=True),
                C("c", "Tilfeldig", "Strukturelt."),
                C("d", "Bare for store", "Konkret terskel.")],
               "Åpenhetsloven krever aktsomhetsvurderinger og rapportering om menneskerettigheter."),
            ex("Internasjonalt", "Hva er EOR?",
               [C("a", "Bare lov", "Konkret tjeneste."),
                C("b", "Employer of Record — selskap som ansetter på dine vegne i andre land", "Riktig! Skala-verktøy.", correct=True),
                C("c", "Tilfeldig", "Strukturert."),
                C("d", "Bare PR", "Compliance-løsning.")],
               "EOR (Deel, Remote) lar deg ansette globalt uten å stifte selskap i hvert land.")]),
    ],
    ["Du forstår at skalering krever PMF, repeterbar prosess og automatisering",
     "Du behersker terminologien: PMF, CAC, LTV, runway, blitzscaling",
     "Du kjenner finansieringsrunder fra seed til Series C med tilhørende milepæler",
     "Du forstår strategiske valg ved internasjonalisering og markedsposisjon",
     "Du ser compliance-utfordringene som følger med vekst"])


MARKPOS = M("MarkedsanalysePosisjonering", "ent2", "ENT2-13", "Markedsanalyse og posisjonering", "🔍",
    "markedsanalyse-posisjonering", "ent2",
    "Markedsanalyse og posisjonering bestemmer om du blir oppfattet som premium, billig, ekspert eller generisk. Dette former alt — pris, salg, marketing.",
    "Tine, Stormberg, Vipps og Equinor har alle bevisste posisjoner. Du kan ikke være alt for alle. Posisjonering er valg.",
    "Posisjonering skjer i kundens hode, ikke i ditt produktdokument. Hva tenker kunden FØRST når de hører merkenavnet?",
    [
        ph("📊", "Hva er markedsanalyse?",
           "Strukturert forståelse av markedet.",
           "Markedsanalyse besvarer: Hvor stort er markedet? Hvem er kundene? Hvem er konkurrentene? Hva trender? Verktøy: PESTEL (makro), Porter 5 (bransje), STP (segmentering), TAM/SAM/SOM (markedstørrelse), kundeintervjuer, datakilder (SSB, Statista, Eurostat). Kahoot startet med data: skole-markedet er $200B globalt — verd å satse på. Markedsanalyse skiller informerte fra håpefulle valg.",
           [("DATA", "Beslutninger på data, ikke magefølelse."),
            ("KILDER", "SSB, bransjeforeninger, kundeintervjuer.")],
           "Hva er markedsstørrelsen i din bransje? Globalt og i Norge?",
           [ex("Hva", "Hva er markedsanalyse?",
               [C("a", "Bare reklame", "Strategisk grunnlag."),
                C("b", "Strukturert kartlegging av marked, kunder, konkurrenter, trender", "Riktig! Helhetsperspektiv.", correct=True),
                C("c", "Bare salg", "Bredere."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Grunnlag for strategiske valg om hvilke segmenter, hvilken pris, hvilke kanaler."),
            ex("TAM", "Hva er TAM?",
               [C("a", "Bare salg", "Markedsstørrelse."),
                C("b", "Total Addressable Market — globalt potensial om alle kjøper", "Riktig! Maksimalt marked.", correct=True),
                C("c", "Bare lov", "Forretningsbegrep."),
                C("d", "Tilfeldig", "Definert begrep.")],
               "TAM > SAM (servable) > SOM (du kan realistisk fange). Investorer krever alle tre."),
            ex("Kilder", "Hvor finner man markedsdata for Norge?",
               [C("a", "Bare gjette", "Det finnes data."),
                C("b", "SSB, bransjeforeninger, Innovasjon Norge, Statista, kundeintervjuer", "Riktig! Mange kilder.", correct=True),
                C("c", "Bare lov", "Strukturert."),
                C("d", "Tilfeldig", "Strukturerte kilder.")],
               "Sekundære data (SSB) er gratis. Primære (intervjuer) gir innsikt konkurrenter ikke har.")]),
        ph("🎯", "STP: Segmentering",
           "Dele marked i homogene grupper.",
           "Segmenteringsbaser: 1) Demografisk (alder, kjønn, inntekt), 2) Geografisk (land, by/bygd), 3) Psykografisk (verdier, livsstil), 4) Atferd (bruk, lojalitet, anledning). Tine segmenterer barneforeldre vs eldre. Stormberg på etisk-bevisste forbrukere. Segmentering må være: Målbar, Tilstrekkelig stor, Tilgjengelig, Differensierbar, Aksjonerbar.",
           [("BASER", "Demografi + psykografi + atferd."),
            ("KRAV", "MÅDA-modellen sikrer brukbar segmentering.")],
           "Hvilke segmenter er viktigst i din bransje?",
           [ex("Baser", "Fire vanlige segmenteringsbaser?",
               [C("a", "Bare alder", "Fire baser."),
                C("b", "Demografisk, geografisk, psykografisk, atferd", "Riktig! Standard.", correct=True),
                C("c", "Bare 2", "Fire baser."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Mest avansert er ofte psykografi + atferd — fanger 'hvorfor', ikke bare 'hvem'."),
            ex("Krav", "Hva må til for godt segment?",
               [C("a", "Bare stort", "Flere krav."),
                C("b", "Målbar, stor nok, tilgjengelig, differensierbar, aksjonerbar", "Riktig! Standard krav.", correct=True),
                C("c", "Tilfeldig", "Strukturert."),
                C("d", "Bare lov", "Forretningskrav.")],
               "Lite segment = ikke lønnsomt. Utilgjengelig segment = kan ikke nås. Begge feiler."),
            ex("Stormberg", "Hva er Stormbergs segment?",
               [C("a", "Bare alle", "Mer fokusert."),
                C("b", "Etisk-bevisste familier som verdsetter ansvarlig produksjon", "Riktig! Psykografisk.", correct=True),
                C("c", "Tilfeldig", "Strategisk valg."),
                C("d", "Bare lov", "Strategisk segment.")],
               "Stormberg konkurrerer ikke på pris — konkurrerer på etikk-verdier. Klart segment.")]),
        ph("🎪", "STP: Targeting",
           "Velge segmenter å satse på.",
           "Targeting-strategier: 1) Udifferensiert (én produkt for alle, sjelden), 2) Differensiert (ulike produkter for ulike segmenter — Tine har ulike melker), 3) Konsentrert/nisje (ett segment, dypt fokus — Stormberg etisk forbruker), 4) Mikromarkedsføring (lokalt eller individuelt — Spotify-spillelister). Valg avhenger av ressurser. Små bør ofte konsentrere.",
           [("FOKUS", "Småbedrifter: nisje. Storbedrifter: differensiert."),
            ("RESSURSER", "Du kan ikke betjene alle segmenter likt godt.")],
           "Hvilken targeting-strategi passer din bedrift?",
           [ex("Strategier", "Fire targeting-strategier?",
               [C("a", "Bare en", "Fire."),
                C("b", "Udifferensiert, differensiert, konsentrert, mikromarkedsføring", "Riktig! Klassisk.", correct=True),
                C("c", "Bare 2", "Fire alternativer."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Coca-Cola = differensiert (Coke, Diet, Zero, Coke Energy). Stormberg = konsentrert."),
            ex("Liten", "Hva passer småbedrifter?",
               [C("a", "Alle segmenter", "Ressurser ikke nok."),
                C("b", "Konsentrert/nisje — bli best i ett smalt segment", "Riktig! Fokus-strategi.", correct=True),
                C("c", "Tilfeldig", "Strategisk valg."),
                C("d", "Bare lov", "Strategi-valg.")],
               "Small fish in big pond drowns. Big fish in small pond winner."),
            ex("Tine", "Hvorfor differensiert hos Tine?",
               [C("a", "Tilfeldig", "Strategisk."),
                C("b", "Stort selskap, ulike kundebehov — barnemelk, skummet, laktosefri, premium", "Riktig! Bredde-strategi.", correct=True),
                C("c", "Bare lov", "Markeds-segmentering."),
                C("d", "Bare PR", "Strategisk valg.")],
               "Tine har ressurser til å betjene mange segmenter. Liten gründer kan ikke.")]),
        ph("📍", "STP: Posisjonering",
           "Plass i kundens hode.",
           "Posisjonering = hvordan kunden oppfatter merket sammenlignet med konkurrenter. Posisjoneringsmuligheter: pris (Rema), kvalitet (Stormberg), opprinnelse (Tine norsk), bruksanledning (Vipps daglige), målgruppe (Patagonia friluft), problem løst (Vipps enkel betaling). Posisjoneringskart: to akser (f.eks pris/kvalitet) — finn hull. Volvo = sikkerhet. Apple = enkelhet. Hva er du?",
           [("HODET", "Posisjonering skjer hos kunden, ikke i ditt brand-dokument."),
            ("HULL", "Finn ledig posisjon konkurrenter ikke eier.")],
           "Hvilken posisjon eier din bedrift i kundens hode?",
           [ex("Hva", "Hva er posisjonering?",
               [C("a", "Bare logo", "Mer enn det."),
                C("b", "Hvordan kunden oppfatter merket relativt til konkurrenter", "Riktig! Persepsjon.", correct=True),
                C("c", "Bare reklame", "Resultatet, ikke metoden."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Al Ries: 'Positioning is not what you do to a product. It's what you do to the mind of the prospect.'"),
            ex("Volvo", "Hva er Volvos posisjon?",
               [C("a", "Sport", "Ikke deres posisjon."),
                C("b", "Sikkerhet — eid posisjon i tiår", "Riktig! Klassisk eksempel.", correct=True),
                C("c", "Bare lov", "Markedsposisjon."),
                C("d", "Tilfeldig", "Bevisst valg.")],
               "Volvo investerte i sikkerhet (3-punkts belte gratis), kommuniserte konsistent. Eier mental posisjon."),
            ex("Hull", "Hvordan finne posisjon?",
               [C("a", "Tilfeldig", "Strukturert."),
                C("b", "Posisjoneringskart — to relevante akser, finn hull i markedet", "Riktig! Verktøy.", correct=True),
                C("c", "Bare lov", "Strukturert verktøy."),
                C("d", "Bare PR", "Strategisk verktøy.")],
               "F.eks pris (lav-høy) vs design (basic-premium). Hvor er ledige hull?")]),
        ph("🥇", "Differensiering",
           "Hva gjør deg unik og verdifull?",
           "Differensieringsdimensjoner: produkt (kvalitet, design, funksjoner), service (rask, personlig), kanal (eksklusiv distribusjon), folk (kompetanse, kultur), image (status, etikk). Ikea differensierer på 'flatpakke + lav pris + design'. Apple på 'design + økosystem'. Differensiering må være: 1) Verdifull for kunden, 2) Vanskelig å kopiere, 3) Kommunikerbar. Bare en av tre = ikke nok.",
           [("DIMENSJONER", "Du kan differensiere på flere ting."),
            ("KOPI", "Hvis konkurrenter kopierer raskt, mister du.")],
           "Hva er din primære differensieringsdimensjon?",
           [ex("Dim", "Differensieringsdimensjoner?",
               [C("a", "Bare pris", "Mange dimensjoner."),
                C("b", "Produkt, service, kanal, folk, image", "Riktig! Bredt spekter.", correct=True),
                C("c", "Bare lov", "Markedsføring."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Ikea: produkt + pris + image. Stormberg: image + folk. Apple: produkt + image."),
            ex("Krav", "Når virker differensiering?",
               [C("a", "Alltid", "Kun hvis kriterier oppfylles."),
                C("b", "Når den er verdifull, vanskelig å kopiere og kommuniserbar", "Riktig! Tre krav.", correct=True),
                C("c", "Tilfeldig", "Strukturert."),
                C("d", "Bare lov", "Konkrete krav.")],
               "Differensiering ingen bryr seg om = ingen verdi. Kopierbar = ingen vedvarende fordel."),
            ex("Apple", "Hvorfor er Apple svært differensiert?",
               [C("a", "Bare reklame", "Mer enn det."),
                C("b", "Design + økosystem + brand — flere dimensjoner sammen", "Riktig! Multidimensjonal.", correct=True),
                C("c", "Tilfeldig", "Bevisst.")  ,
                C("d", "Bare lov", "Strategisk valg.")],
               "Multi-dimensjonal differensiering er vanskeligst å kopiere. Konkurrenter må kopiere alt.")]),
        ph("🔍", "Konkurrentanalyse",
           "Forstå hvem du kjemper mot.",
           "Konkurrentanalyse-rammeverk: identifiser direkte og indirekte konkurrenter, kartlegg deres styrker/svakheter, pris, posisjon, markedsandel, strategi. Verktøy: SWOT per konkurrent, sammenligningsmatrise, mystery shopping, deres egne årsrapporter, ansatte du intervjuer. Vipps må følge med Apple Pay (direkte) og kontanter (indirekte). DnB følger med fintech-utfordrere. Konkurrenter endrer seg — kontinuerlig overvåking.",
           [("DIREKTE/INDIREKTE", "Glem ikke indirekte alternativer."),
            ("LEVENDE", "Konkurrentlandskapet endres raskt.")],
           "Hvem er din bedrifts største konkurrenter?",
           [ex("Typer", "Direkte vs indirekte konkurrent?",
               [C("a", "Det samme", "Forskjell."),
                C("b", "Direkte = samme produkt; indirekte = annet alternativ", "Riktig! Bredere syn.", correct=True),
                C("c", "Bare lov", "Markedsdefinisjon."),
                C("d", "Tilfeldig", "Strukturelt.")],
               "Vipps direkte: Apple Pay. Indirekte: kontanter, faktura. Begge er konkurrenter."),
            ex("Datakilder", "Hvor finner du konkurrent-data?",
               [C("a", "Tilfeldig", "Mange kilder."),
                C("b", "Årsrapporter, mystery shopping, intervjuer, sosiale medier, jobbutlysninger", "Riktig! Bredt spekter.", correct=True),
                C("c", "Bare lov", "Strukturert."),
                C("d", "Bare gjette", "Datakilder finnes.")],
               "Jobbutlysninger forteller hva konkurrenter satser på. Frontside-investerings-signal."),
            ex("Levende", "Hvorfor må analysen være levende?",
               [C("a", "Tilfeldig", "Strukturelt."),
                C("b", "Konkurrenter endrer strategi, nye aktører, ny teknologi", "Riktig! Dynamisk landskap.", correct=True),
                C("c", "Bare lov", "Operasjonelt."),
                C("d", "Bare PR", "Strukturelt.")],
               "Snapshot er foreldet på 6 måneder. Strukturer kontinuerlig overvåking.")]),
        ph("👤", "Persona-arbeid",
           "Konkretiser kunden i en person.",
           "En persona er en fiktiv person som representerer et segment. Inkluderer: demografi, jobb, mål, frustrasjoner, kjøps-prosess, kanaler. Stormberg sin persona er kanskje 'Kari, 38, lærer, 2 barn, opptatt av etikk og holdbarhet'. Personas hjelper team å snakke om 'Kari' i stedet for abstrakte segmenter. Bruk i produktutvikling, markedsføring, salg.",
           [("KONKRET", "Persona = navn, alder, foto, sitater."),
            ("FELLES SPRÅK", "Hele teamet snakker om samme kunde.")],
           "Lag en persona for din viktigste kunde — navn, alder, mål, problem.",
           [ex("Hva", "Hva er en persona?",
               [C("a", "Bare statistikk", "Konkret person."),
                C("b", "Fiktiv representativ kunde — navn, kontekst, mål, frustrasjoner", "Riktig! Empati-verktøy.", correct=True),
                C("c", "Bare lov", "Markedsverktøy."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Personas humaniserer segmentering. 'Hva ville Kari gjort?' er bedre enn segment-tall."),
            ex("Innhold", "Hva er med i god persona?",
               [C("a", "Bare alder", "Mer."),
                C("b", "Demografi, jobb, mål, frustrasjoner, kanaler, beslutningsprosess", "Riktig! Helhetlig.", correct=True),
                C("c", "Bare lov", "Innhold-krav."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Mål og frustrasjoner er viktigere enn demografi for produktutvikling."),
            ex("Bruk", "Hvor bruker du persona?",
               [C("a", "Aldri", "Bredt."),
                C("b", "Produktutvikling, markedsføring, salg, kundeservice", "Riktig! Tverrfaglig.", correct=True),
                C("c", "Bare lov", "Praktisk verktøy."),
                C("d", "Tilfeldig", "Brukes overalt.")],
               "Designer tegner for Kari. Markedsfører skriver til Kari. Selger snakker med Kari.")]),
        ph("🧪", "Markedstesting",
           "Validere før storskala lansering.",
           "Test før du investerer alt: 1) MVP-test (minimal produkt med ekte kunder), 2) A/B-test (to versjoner, mål forskjell), 3) Geografisk test (lanser i én by først), 4) Concierge-test (gjøre tjenesten manuelt for første kunder), 5) Smoke test (annonse for produkt som ikke finnes — mål interesse). Airbnb begynte som concierge-test, eierne kjørte service selv. Spotify A/B-tester alt.",
           [("BILLIG", "Test før du bygger ferdig."),
            ("ATFERD", "Hva folk gjør > hva de sier.")],
           "Hvordan kan du teste neste produktidé billig?",
           [ex("Metoder", "Markedstest-metoder?",
               [C("a", "Bare lansering", "Test billigere."),
                C("b", "MVP, A/B-test, geo-test, concierge, smoke test", "Riktig! Mange metoder.", correct=True),
                C("c", "Tilfeldig", "Strukturerte metoder."),
                C("d", "Bare lov", "Operasjonelle metoder.")],
               "Velg metode basert på hva du tester (etterspørsel, pris, kanal, brukervennlighet)."),
            ex("Smoke", "Hva er smoke test?",
               [C("a", "Brann-test", "Forretningsbegrep."),
                C("b", "Annonse for produkt som ikke finnes — mål klikk-rate", "Riktig! Etterspørselstest.", correct=True),
                C("c", "Bare lov", "Markedstest."),
                C("d", "Tilfeldig", "Strukturert metode.")],
               "Bygg landingsside med 'kjøp nå'. Hvis folk klikker = etterspørsel. Refundér de som betaler."),
            ex("Concierge", "Hvorfor concierge-test?",
               [C("a", "Tilfeldig", "Strukturelt."),
                C("b", "Test value-proposisjonen før du bygger automatisert produkt", "Riktig! Bygg riktig produkt.", correct=True),
                C("c", "Bare lov", "Strategisk test."),
                C("d", "Bare PR", "Operasjonell test.")],
               "Airbnb leverte tjenesten manuelt før de bygde plattform. Tester verdien.")]),
        ph("⚠️", "Misforståelser om posisjonering",
           "Vanlige feil i markedsføringsarbeid.",
           "Vanlige feil: 1) Posisjonere på flere ting samtidig (Volvo på sikkerhet OG sport = forvirring). 2) Posisjonere på det produktet er, ikke det kunden trenger. 3) Endre posisjonering for ofte — krever konsistens i 5+ år. 4) Posisjonere mot konkurrenten i stedet for kunden. 5) 'Premium kvalitet til lav pris' (alle sier det, betyr ingenting).",
           [("KONSISTENS", "Posisjon = mange års samme melding."),
            ("VALG", "Posisjonere = velge bort.")],
           "Hvilken misforståelse om posisjonering kjenner du igjen?",
           [ex("Feil", "Vanligste posisjonerings-feil?",
               [C("a", "Bare lov", "Strategisk feil."),
                C("b", "Prøve å posisjonere på flere dimensjoner samtidig — kunden blir forvirret", "Riktig! Klart problem.", correct=True),
                C("c", "Tilfeldig", "Strategisk valg."),
                C("d", "Bare PR", "Strukturelt.")],
               "Mind hates complexity. Velg én primær posisjon, kommuniser konsistent."),
            ex("Konsistens", "Hvor lenge må du holde posisjon?",
               [C("a", "1 år", "For kort."),
                C("b", "5+ år — det tar tid å bygge mental posisjon", "Riktig! Lang horisont.", correct=True),
                C("c", "Tilfeldig", "Strukturelt."),
                C("d", "Bare lov", "Strategisk.")],
               "Volvo har posisjonert seg på sikkerhet i 60+ år. Apple på enkelhet i 30+ år."),
            ex("Floskel", "Hvorfor virker ikke 'premium til lav pris'?",
               [C("a", "Tilfeldig", "Strukturelt."),
                C("b", "Alle sier det, ingen tror det, det er en motsigelse", "Riktig! Klassisk feil.", correct=True),
                C("c", "Bare lov", "Markedskommunikasjon."),
                C("d", "Bare PR", "Strategisk.")],
               "Hvis du ikke kan velge bort noe, har du ingen posisjon. Velg pris ELLER kvalitet.")]),
        ph("⚖️", "Lovverk i markedsanalyse",
           "Juridiske rammer for markedsforing og analyse.",
           "Markedsanalyse må følge: GDPR (samtykke ved kundeintervjuer, anonymisering av data), markedsføringsloven (sannferdig fremstilling), god markedsføringsskikk (forbruker-vern), konkurranseloven (forbud mot kartell-prising), forbrukerkjøpsloven (krav til produktopplysninger), distansavtaleloven (e-handel). Mystery shopping er lovlig men har grenser — du kan ikke utgi deg som myndighetsperson.",
           [("GDPR", "Kundeintervjuer = personopplysninger."),
            ("ETIKK", "Mystery shopping har grenser.")],
           "Hvilke lovkrav gjelder for din markedsanalyse?",
           [ex("GDPR", "Hva krever GDPR ved kundeintervjuer?",
               [C("a", "Ingenting", "Sterkt regulert."),
                C("b", "Samtykke, formål, anonymisering, sletting på forespørsel", "Riktig! Datasubjekt-rettigheter.", correct=True),
                C("c", "Bare lov", "Konkrete krav."),
                C("d", "Tilfeldig", "Strukturert.")],
               "Anonymisering er bedre enn pseudonymisering. Hvis du ikke trenger å vite hvem, slett."),
            ex("MfL", "Hva sier markedsføringsloven?",
               [C("a", "Bare reklame", "Bredere."),
                C("b", "Sannferdig fremstilling, forbud mot villedende reklame, balansert sammenligning", "Riktig! Grunnregler.", correct=True),
                C("c", "Bare lov", "Strukturelle krav."),
                C("d", "Tilfeldig", "Konkret lov.")],
               "Du kan sammenligne med konkurrent — men sammenligningen må være sannferdig og balansert."),
            ex("Mystery", "Er mystery shopping lovlig?",
               [C("a", "Aldri", "Lovlig med grenser."),
                C("b", "Ja, men du kan ikke utgi deg som myndighet eller bryte avtaler", "Riktig! Etiske grenser.", correct=True),
                C("c", "Tilfeldig", "Strukturelt."),
                C("d", "Bare PR", "Konkret regulering.")],
               "Vanlig markedsundersøkelse: lovlig. Bedrageri (utgir deg som inspektør): straffbart.")]),
    ],
    ["Du forstår markedsanalyse som strukturert datainnsamling om marked, kunder, konkurrenter",
     "Du behersker STP-modellen: Segmentering, Targeting, Posisjonering",
     "Du kjenner differensieringsdimensjoner og hvordan posisjonering skjer i kundens hode",
     "Du kan bygge personas og bruke dem på tvers av produktutvikling, salg og marketing",
     "Du forstår markedstesting (MVP, A/B, smoke, concierge) før storskala lansering"])


g.write_modules([STRAT, FORRSKAL, MARKPOS], "ENT2 11-13")
