import DrawerModule from '../shared/DrawerModule'
import type { DrawerPhase } from '../shared/DrawerModule'

export const PHASES: DrawerPhase[] = [
  {
    phaseNumber: 1,
    icon: '🎯',
    title: 'Hva er en klage?',
    quote: 'En klage er en gave — kunden gir deg sjansen til å rette opp',
    practical: 'Forskning viser at kun 4% av misfornøyde kunder klager — resten bare forsvinner. De som klager gir deg muligheten til å beholde dem.',
    exercises: [
      {
        id: 'klag-1-1',
        icon: '📊',
        title: 'Klagens verdi for bedriften',
        context: 'En butikksjef er frustrert over at de får mange klager en bestemt uke og sier: «Klager er bare bortkastet tid og energi.»',
        question: 'Hvorfor er dette synet på klager problematisk ifølge forskning på kundeservice?',
        choices: [
          { id: 'a', label: 'Fordi kunder alltid har rett og klagen aldri er urettferdig', isCorrect: false, feedback: 'Kunder har ikke alltid rett saksmessig, men klager gir verdifull informasjon uavhengig av om de er «riktige».' },
          { id: 'b', label: 'Fordi klager er gratis markedsundersøkelse som avslører reelle problemer du ellers ikke ville visst om', isCorrect: true, feedback: 'Riktig! Siden bare 4% av misfornøyde kunder klager, representerer én klage problemer som rammer mange flere. Klager er verdifull informasjon du ikke ville fått på annen måte.' },
          { id: 'c', label: 'Fordi kunder som klager alltid forteller det til venner og familien sin', isCorrect: false, feedback: 'Negativ omtale er en konsekvens av dårlig håndtering, ikke av selve klagen. Veldbehandlede klager kan faktisk snu dette til positiv omtale.' },
          { id: 'd', label: 'Fordi butikken er juridisk forpliktet til å ta imot klager', isCorrect: false, feedback: 'Det er riktig at det finnes juridiske forpliktelser, men det er ikke det viktigste argumentet mot butikksjefen. Verdien av klagen som informasjonskilde er mer grunnleggende.' },
        ],
        espenTip: 'En klage er en gave med dårlig innpakking. Åpne den — inni ligger informasjon du kan bruke til å bli bedre.',
      },
      {
        id: 'klag-1-2',
        icon: '🔍',
        title: 'De tause misfornøyde kundene',
        context: 'En restaurant merker at salget synker gradvis over tre måneder, men de mottar svært få klager. Eieren lurer på hva som kan gå galt.',
        question: 'Hva forteller den lave klagehyppigheten om situasjonen?',
        choices: [
          { id: 'a', label: 'At de fleste kunder er fornøyde og salgssvikten skyldes andre faktorer som konjunkturer', isCorrect: false, feedback: 'Lav klagehyppighet kan ikke tolkes som høy tilfredshet. Forskning viser konsekvent at svært få misfornøyde kunder faktisk klager — de forsvinner i stedet.' },
          { id: 'b', label: 'At kunder sannsynligvis er misfornøyde men ikke tar bryet med å klage — de bare slutter å komme', isCorrect: true, feedback: 'Riktig! Undersøkelser viser at bare 4% av misfornøyde kunder klager. De andre 96% forsvinner stille og forteller det heller til venner og bekjente.' },
          { id: 'c', label: 'At restauranten har så høy kvalitet at selv misfornøyde kunder ikke finner grunn til å klage', isCorrect: false, feedback: 'Salgssvikten over tre måneder tyder ikke på høy kvalitet. Fraværet av klager er et advarselstegn, ikke et kvalitetsbevis.' },
          { id: 'd', label: 'At kundene heller bruker anmeldelsessider på internett fremfor å klage direkte', isCorrect: false, feedback: 'Dette kan skje, men det forklarer ikke hele bildet. Uansett kommunikasjonskanal er den grunnleggende poenget at misfornøyde kunder sjelden klager direkte — de forsvinner.' },
        ],
        espenTip: 'Ingen klager = ingen kunder. Stilhet er ikke tilfredshet — det kan være at de allerede har gitt opp og sluttet å besøke deg.',
      },
      {
        id: 'klag-1-3',
        icon: '💡',
        title: 'Klagen som forbedringsmulighet',
        context: 'En dagligvarebutikk mottar gjentatte klager på at selvbetjeningskassene er forvirrende for eldre kunder. Butikksjefen velger å ignorere det fordi det er et mindretall av kundene.',
        question: 'Hva er den strategiske feilen i denne vurderingen?',
        choices: [
          { id: 'a', label: 'Eldre kunder har lovfestet rett til spesiell hjelp i butikker', isCorrect: false, feedback: 'Det finnes tilgjengelighetskrav, men det er ikke den primære strategiske feilen her. Den handler om forretningslogikk.' },
          { id: 'b', label: 'Et mindretall som klager representerer trolig et flertall som er misfornøyde men ikke klager', isCorrect: true, feedback: 'Riktig! Siden bare 4% klager, kan gjentatte klager fra eldre kunder bety at problemet rammer en stor gruppe. Å ignorere det er å ignorere en betydelig del av kundebasen.' },
          { id: 'c', label: 'Sosiale medier vil snart spre klagene og skade bedriftens omdømme', isCorrect: false, feedback: 'Omdømmeskade er en mulig konsekvens, men det er ikke den primære strategiske feilen. Representasjonsproblematikken — at klagerne representerer mange — er mer fundamental.' },
          { id: 'd', label: 'Eldre kunder har høyere lojalitet og bruker mer penger enn andre segmenter', isCorrect: false, feedback: 'Dette kan være sant som sekundærargument, men det er ikke den strategiske feilen i vurderingen. Klage-til-utilfredshet-ratioen er det sentrale poenget.' },
        ],
        espenTip: 'Gang antall klager med 25 — det er et grovt anslag på hvor mange kunder som faktisk er misfornøyde men ikke sier noe.',
      },
      {
        id: 'klag-1-4',
        icon: '🏆',
        title: 'Lojalitet etter vellykket klagebehandling',
        context: 'Forskning viser at en kunde hvis klage blir håndtert utmerket, kan bli mer lojal enn en kunde som aldri har hatt et problem.',
        question: 'Hva kalles dette fenomenet, og hva forklarer det?',
        choices: [
          { id: 'a', label: 'Kompensasjonseffekten — kunder vil ha erstatning og belønner det med lojalitet', isCorrect: false, feedback: 'Kompensasjon alene skaper ikke lojalitet. Det er selve opplevelsen av å bli hørt og tatt vare på som er driveren.' },
          { id: 'b', label: 'Service recovery paradokset — en god klageopplevelse viser bedriftens verdier og skaper sterkere emosjonell tilknytning', isCorrect: true, feedback: 'Riktig! Service recovery paradokset sier at en bedrift som håndterer en feil utmerket, demonstrerer sine verdier på en måte som en feilfri opplevelse ikke gjør. Det skaper sterkere tillit.' },
          { id: 'c', label: 'Bekreftelsesbias — kunden rettferdiggjør valget sitt om å bli ved å huske det positive', isCorrect: false, feedback: 'Bekreftelsesbias finnes, men er ikke forklaringen på service recovery paradokset. Det er den faktiske kvaliteten på håndteringen som skaper lojaliteten.' },
          { id: 'd', label: 'Gjensidighetsregelen — kunden føler seg forpliktet til å gi tilbake for god behandling', isCorrect: false, feedback: 'Gjensidighet kan spille en rolle, men er ikke kjerneforklaringen. Service recovery handler om tillit og opplevelse av å bli verdsatt som kunde.' },
        ],
        espenTip: 'En klage er en sjanse til å vise hvem dere virkelig er. Bruk den — det er gratis markedsføring til en kunde som allerede kjenner dere.',
      },
      {
        id: 'klag-1-5',
        icon: '🎁',
        title: 'Klage-begrepet i vid forstand',
        context: 'En kunde sier til en ansatt på vei ut: «Dere har aldri varene jeg leter etter inne» — ikke aggressivt, bare kommenterende.',
        question: 'Hvordan bør den ansatte tolke og reagere på denne kommentaren?',
        choices: [
          { id: 'a', label: 'Som uformell samtale uten videre konsekvens, siden kunden ikke formelt klaget', isCorrect: false, feedback: 'Uformelle tilbakemeldinger er like verdifulle som formelle klager — kanskje mer, fordi kunden velger å si noe selv om de ikke er forpliktet til det.' },
          { id: 'b', label: 'Som en skjult klage og verdifull tilbakemelding om sortimentet som bør registreres', isCorrect: true, feedback: 'Riktig! En kommentar som dette er en gave — kunden forteller deg noe viktig uten å kreve noe tilbake. Å notere dette og videreformidle til ledelsen er god servicekultur.' },
          { id: 'c', label: 'Som tegn på at kunden bør finne en annen butikk som passer dem bedre', isCorrect: false, feedback: 'Dette er en defensiv og kundefientlig tankegang. Kunden gir deg en mulighet til forbedring — ikke en oppfordring til å miste dem.' },
          { id: 'd', label: 'Med en forklaring om at sortimentet er leverandørstyrt og ikke noe butikken bestemmer', isCorrect: false, feedback: 'Dette kan være sant, men å gi en forklaring uten å registrere tilbakemeldingen løser ingenting og viser at du ikke ser verdien av informasjonen.' },
        ],
        espenTip: 'En klage er ikke bare formelle reklamasjoner — det er enhver tilbakemelding om at noe ikke møter forventningene. Hør etter signalene.',
      },
    ],
  },
  {
    phaseNumber: 2,
    icon: '⚖️',
    title: 'Reklamasjonsrett',
    quote: 'Forbrukerkjøpsloven er på kundens side — lær den',
    practical: '2 års reklamasjonsrett (5 år for varige varer). Butikken kan IKKE si "vi bytter ikke innkjøpte varer". Tre alternativer: reparasjon, ombytte eller prisavslag.',
    glossaryTerm: 'Reklamasjonsrett',
    exercises: [
      {
        id: 'klag-2-1',
        icon: '⚖️',
        title: 'Reklamasjonsrettens lengde',
        context: 'En kunde returnerer en støvsuger to år og tre måneder etter kjøp. Den ansatte sier: «Garantien er bare ett år, så vi kan dessverre ikke hjelpe deg.»',
        question: 'Hva er problemet med den ansattes svar?',
        choices: [
          { id: 'a', label: 'Den ansatte er korrekt — garantitiden bestemmer reklamasjonsretten', isCorrect: false, feedback: 'Garanti og reklamasjonsrett er ikke det samme. Garanti er frivillig og gitt av produsent/selger. Reklamasjonsrett er lovfestet og gjelder uavhengig av garantiperiodens lengde.' },
          { id: 'b', label: 'Forbrukerkjøpsloven gir reklamasjonsrett i minst 2 år (5 år for varige varer) — dette er en lovfestet rettighet uavhengig av garanti', isCorrect: true, feedback: 'Riktig! Reklamasjonsretten er lovfestet i Forbrukerkjøpsloven og gjelder i minst to år. For varige varer som støvsugere kan det være opp til fem år. Garanti og reklamasjonsrett er separate begreper.' },
          { id: 'c', label: 'Den ansatte bør spørre en overordnet fordi dette er en gråsone', isCorrect: false, feedback: 'Det er ikke en gråsone — loven er tydelig. Den ansatte bør kjenne sine plikter og rettigheter etter Forbrukerkjøpsloven.' },
          { id: 'd', label: 'Kunden bør henvende seg til produsenten, ikke butikken', isCorrect: false, feedback: 'Kunden har rett til å henvende seg til der de kjøpte varen. Butikken er ansvarlig overfor kunden og kan eventuelt henvende seg videre til produsent, men det er butikkens problem, ikke kundens.' },
        ],
        espenTip: 'Husk: garanti er det produsenten lover, reklamasjonsrett er det loven gir. Det er to helt forskjellige ting.',
      },
      {
        id: 'klag-2-2',
        icon: '🔧',
        title: 'Tre mulige løsninger ved reklamasjon',
        context: 'En kunde reklamerer på en jakke med defekt glidelås kjøpt for seks måneder siden. Den ansatte vet at loven gir tre alternative løsninger.',
        question: 'Hvilke tre alternativer har kunden krav på etter Forbrukerkjøpsloven?',
        choices: [
          { id: 'a', label: 'Pengene tilbake, ny vare, eller rabatt på neste kjøp', isCorrect: false, feedback: 'Rabatt på fremtidige kjøp er ikke en lovfestet rettighet. Loven beskytter mot den faktiske feilen, ikke fremtidige transaksjoner.' },
          { id: 'b', label: 'Reparasjon, ombytte eller prisavslag (ev. heving av kjøpet ved vesentlig mangel)', isCorrect: true, feedback: 'Riktig! Disse er de lovfestede alternativene etter Forbrukerkjøpsloven. Selger velger normalt mellom reparasjon og ombytte i første omgang. Heving er aktuelt ved vesentlig mangel.' },
          { id: 'c', label: 'Enten pengene tilbake eller en ny vare — kunden bestemmer', isCorrect: false, feedback: 'Kunden bestemmer ikke alene — selgeren har rett til å velge mellom reparasjon og ombytte i første omgang. Pengene tilbake er ikke alltid umiddelbart aktuelt.' },
          { id: 'd', label: 'Reparasjon, pengene tilbake eller erstatning for konsekvenstap', isCorrect: false, feedback: 'Erstatning for konsekvenstap er et eget krav som krever spesielle betingelser. Loven gir primært reparasjon, ombytte eller prisavslag som standard løsninger.' },
        ],
        espenTip: 'ROP = Reparasjon, Ombytte, Prisavslag. Lær disse tre bokstavene — de er din guide gjennom de fleste reklamasjonssituasjoner.',
      },
      {
        id: 'klag-2-3',
        icon: '🚫',
        title: 'Ulovlig avvisning av reklamasjon',
        context: 'En ansatt sier til en kunde som reklamerer: «Vi bytter ikke innkjøpte varer, det er vår policy. Du bør ha sjekket varen i butikken.»',
        question: 'Hva er problemet med dette svaret juridisk sett?',
        choices: [
          { id: 'a', label: 'Butikker kan ha egne policyer som overgår loven for å beskytte seg mot misbruk', isCorrect: false, feedback: 'Butikker kan IKKE ha policyer som er svakere enn lovens minimumsrettigheter. Forbrukerkjøpsloven gir kunden rettigheter som ikke kan avtalefestes bort.' },
          { id: 'b', label: 'Å avvise en reklamasjon med henvisning til butikkpolicy er ulovlig — loven gir kunden rettigheter som butikken ikke kan innskrenke', isCorrect: true, feedback: 'Riktig! Forbrukerkjøpsloven er preseptorisk til fordel for forbrukeren — det betyr at butikker ikke kan ha regler som gir kunden færre rettigheter enn loven gir.' },
          { id: 'c', label: 'Det er riktig — kunden skulle ha undersøkt varen før kjøp', isCorrect: false, feedback: 'Det er ikke kundens ansvar å oppdage skjulte feil i butikken. Reklamasjonsretten dekker feil som ikke var synlige ved kjøpstidspunktet.' },
          { id: 'd', label: 'Problemet er at den ansatte burde spurt om kvittering først', isCorrect: false, feedback: 'Kvittering er relevant for å bekrefte kjøpet, men det er ikke det juridiske kjerneproblemet her. Å avvise reklamasjonsretten med «policy» er det ulovlige.' },
        ],
        espenTip: '«Vi bytter ikke» er tre ord du aldri bør si til en kunde med en lovlig reklamasjon. Det er ulovlig og garantert eskalerer situasjonen.',
      },
      {
        id: 'klag-2-4',
        icon: '📋',
        title: 'Bevis for kjøp ved reklamasjon',
        context: 'En kunde vil reklamere på et produkt men har ikke kvittering. De husker omtrent når det ble kjøpt og hva de betalte.',
        question: 'Hva er kundens rettigheter i denne situasjonen?',
        choices: [
          { id: 'a', label: 'Uten kvittering har kunden ingen reklamasjonsrett', isCorrect: false, feedback: 'Kvittering er ikke det eneste gyldige beviset på kjøp. Kontoutskrift, bankkvittering, SMS-bekreftelse og vitner kan alle aksepteres som dokumentasjon.' },
          { id: 'b', label: 'Kunden kan bruke andre bevis som bankutskrift, e-postbekreftelse eller andre kjøpsbevis', isCorrect: true, feedback: 'Riktig! Loven krever ikke kvittering spesifikt — den krever dokumentasjon for at kjøpet fant sted. Bankutskrift, e-postbekreftelse fra nettbutikk og lignende er gyldige alternativer.' },
          { id: 'c', label: 'Butikken avgjør skjønnsmessig om de vil hjelpe uten kvittering', isCorrect: false, feedback: 'Reklamasjonsretten er en lovfestet rettighet, ikke en skjønnsmessig gunst. Butikken kan be om dokumentasjon, men kan ikke nekte hjelp bare fordi kvitteringen mangler.' },
          { id: 'd', label: 'Kunden kan be om kopi av kvitteringen fra butikken via kasselogg', isCorrect: false, feedback: 'Å be om kopi er én mulighet, men det er ikke slik at kunden er avhengig av det. Mange former for kjøpsdokumentasjon er juridisk akseptable.' },
        ],
        espenTip: 'Kvittering er bekvemt, men ikke obligatorisk. Bank-app viser hva du betalte og når — det holder i de fleste tilfeller.',
      },
      {
        id: 'klag-2-5',
        icon: '🕐',
        title: 'Reklamasjon innen rimelig tid',
        context: 'En kunde oppdager en feil på et plagg kjøpt for ett år siden. Feilen har åpenbart vært der fra starten, men kunden la ikke merke til det.',
        question: 'Hva sier loven om tidspunktet for reklamasjon?',
        choices: [
          { id: 'a', label: 'Reklamasjonsretten utløper når feilen oppdages, uavhengig av kjøpstidspunktet', isCorrect: false, feedback: 'Reklamasjonsretten har en absolutt maksimal grense (2 eller 5 år fra kjøp) uavhengig av oppdagelsestidspunktet.' },
          { id: 'b', label: 'Kunden må reklamere innen rimelig tid etter at feilen ble oppdaget, men reklamasjonsretten varer i minst 2 år fra kjøp', isCorrect: true, feedback: 'Riktig! Loven krever at man reklamerer «innen rimelig tid» etter at feilen oppdages — normalt 2 måneder. Men dette starter fra oppdagelsen, ikke kjøpet. Reklamasjonsretten varer minst 2 år fra kjøp.' },
          { id: 'c', label: 'Etter ett år er reklamasjonsretten alltid utløpt', isCorrect: false, feedback: 'Reklamasjonsretten varer minst 2 år (5 år for varige varer). Ett år er godt innenfor reklamasjonsperioden.' },
          { id: 'd', label: 'Kunden kan reklamere når som helst innen fem år uavhengig av hva slags produkt det er', isCorrect: false, feedback: '5-årsregelen gjelder for varige varer som er laget for å vare mer enn to år. For ordinære klær gjelder 2-årsregelen.' },
        ],
        espenTip: '2 måneder fra du oppdager feilen er tommelfingerregelen for «rimelig tid». Vent ikke — men reklamasjonsretten din er ikke over bare fordi du venter litt.',
      },
    ],
  },
  {
    phaseNumber: 3,
    icon: '🔄',
    title: 'LAST-modellen',
    quote: 'Lytt først — aldri forsvare seg',
    practical: 'Listen → Apologize → Solve → Thank. Eks: Kunde returnerer sko i feil størrelse → lytt uten å avbryte → beklage opplevelsen → bytt umiddelbart → "Takk for at du tok kontakt, vi setter stor pris på det."',
    glossaryTerm: 'LAST-modellen',
    exercises: [
      {
        id: 'klag-3-1',
        icon: '🔄',
        title: 'LAST-sekvensen i praksis',
        context: 'En kunde er sint over at han mottok feil vare. Den ansatte starter med å si: «Beklager, la oss ordne dette med en gang. Hva fikk du levert?»',
        question: 'Hvilke steg i LAST-modellen hopper den ansatte over, og hva er konsekvensen?',
        choices: [
          { id: 'a', label: 'Den ansatte hopper over Listen-fasen og risikerer å gå rett til løsning uten full forståelse av problemet', isCorrect: true, feedback: 'Riktig! Ved å tilby løsning umiddelbart hopper man over aktiv lytting. Kunden trenger å få fortelle sin versjon før man beveger seg til handling — uten dette kan man tilby feil løsning.' },
          { id: 'b', label: 'Den ansatte har gjort alt riktig ved å beklage og tilby løsning raskt', isCorrect: false, feedback: 'Beklaging og løsning er gode instinkter, men aktiv lytting kommer FØRST. Kunden trenger å bli hørt før løsning tilbys.' },
          { id: 'c', label: 'Den ansatte hopper over Thank-fasen som er den viktigste', isCorrect: false, feedback: 'Thank kommer til slutt og er ikke det primære problemet her. Sekvensen LAST er designet slik at Listen alltid er først.' },
          { id: 'd', label: 'LAST-modellen sier at man skal løse problemet uten å stille spørsmål', isCorrect: false, feedback: 'LAST sier det stikk motsatte — Listen (lytte aktivt) er det første og viktigste steget. Spørsmål er en del av lytteprosessen.' },
        ],
        espenTip: 'LAST = Listen, Apologize, Solve, Thank. Den er i denne rekkefølgen av en grunn. Hopp ikke over L.',
      },
      {
        id: 'klag-3-2',
        icon: '🙏',
        title: 'Beklagelse vs ansvarsinnrømmelse',
        context: 'En ansatt er redd for å si «beklager» fordi han tror det automatisk betyr at butikken erkjenner juridisk ansvar.',
        question: 'Hva er riktig forståelse av beklagelsens rolle i LAST-modellen?',
        choices: [
          { id: 'a', label: 'Den ansatte har rett — en beklagelse er en juridisk ansvarserkjennelse og bør unngås', isCorrect: false, feedback: 'En empatisk beklagelse av kundens opplevelse er ikke en juridisk ansvarserkjennelse. Det er et uttrykk for empati, ikke for juridisk skyld.' },
          { id: 'b', label: 'En beklagelse handler om å anerkjenne kundens opplevelse og frustrasjon — ikke om å erkjenne feil', isCorrect: true, feedback: 'Riktig! «Jeg beklager at du opplevde dette» er en empatisk respons som validerer kundens følelse uten å ta stilling til skyldspørsmålet. Det er to forskjellige ting.' },
          { id: 'c', label: 'Man bør bare beklage hvis man er 100% sikker på at bedriften har gjort en feil', isCorrect: false, feedback: 'Å vente på juridisk klarhet før man uttrykker empati gjør kunden mer frustrert og eskalerer situasjonen. Empati kan uttrykkes uavhengig av skyldspørsmålet.' },
          { id: 'd', label: 'Beklagelsen bør komme til slutt i prosessen etter at saken er løst', isCorrect: false, feedback: 'I LAST-modellen kommer beklagelsen tidlig (A i LAST) — etter lytting men før løsning. Det er den emosjonelle broen mellom lytting og handling.' },
        ],
        espenTip: '«Jeg beklager at du opplevde dette» er ikke det samme som «vi erkjenner at vi har gjort feil». Skill mellom empati og juridisk ansvar.',
      },
      {
        id: 'klag-3-3',
        icon: '🛠️',
        title: 'Solve-fasen: tilby riktig løsning',
        context: 'Etter å ha lyttet og beklaget, er det tid for Solve. Kunden klager på at en vare de kjøpte ikke fungerer som forventet.',
        question: 'Hva er best praksis i Solve-fasen?',
        choices: [
          { id: 'a', label: 'Tilby den løsningen du synes er mest praktisk for butikken', isCorrect: false, feedback: 'Solve-fasen handler om kundens behov, ikke butikkens praktiske hensyn. En løsning som primært tjener butikken vil oppleves som utilstrekkelig av kunden.' },
          { id: 'b', label: 'Tilby minst ett konkret alternativ og involver kunden i å velge løsning', isCorrect: true, feedback: 'Riktig! Å involvere kunden i løsningsvalget gir dem kontroll og øker sannsynligheten for at de er fornøyde med utfallet. Kunden har gjerne en preferanse.' },
          { id: 'c', label: 'Alltid gi kunden pengene tilbake fordi det er den eneste løsningen kunder aksepterer', isCorrect: false, feedback: 'Pengene tilbake er ikke alltid løsningen kunden ønsker — noen vil heller ha en ny vare eller reparasjon. Spør hva de foretrekker.' },
          { id: 'd', label: 'Si at du skal sjekke med leder og komme tilbake — aldri ta en beslutning alene', isCorrect: false, feedback: 'Unødvendig eskalering til leder for ordinære reklamasjonssaker er tidkrevende og signaliserer manglende kompetanse. Kjenn dine fullmakter og ta beslutninger innenfor dem.' },
        ],
        espenTip: 'Spør kunden: «Hva ville du at vi skulle gjøre?» — svaret overrasker deg ofte, og er sjelden like kostbart som du fryktet.',
      },
      {
        id: 'klag-3-4',
        icon: '🙌',
        title: 'Thank-fasen: avslutt riktig',
        context: 'Klagen er løst og kunden virker fornøyd. Den ansatte sier: «Der ja, da var det ordnet» og begynner å gjøre noe annet.',
        question: 'Hva mangler fra LAST-modellens siste steg?',
        choices: [
          { id: 'a', label: 'Ingenting — saken er løst og det er det viktigste', isCorrect: false, feedback: 'Thank-fasen er ikke bare en formalitet — det er en mulighet til å transformere en negativ opplevelse til noe positivt og styrke relasjonen.' },
          { id: 'b', label: 'En oppriktig takk for at kunden tok kontakt og ga deg muligheten til å løse problemet', isCorrect: true, feedback: 'Riktig! «Takk for at du tok kontakt» er ikke bare høflighet — det signaliserer at du ser klagen som en gave og setter pris på at kunden ga deg en sjanse fremfor å bare forsvinne.' },
          { id: 'c', label: 'Et tilbud om kompensasjon for ulempene kunden har hatt', isCorrect: false, feedback: 'Kompensasjon kan være relevant i noen tilfeller, men er ikke det LAST-modellen beskriver som Thank-fasen. Takken handler om relasjonen, ikke om ytterligere ytelser.' },
          { id: 'd', label: 'En skriftlig bekreftelse på at saken er løst', isCorrect: false, feedback: 'Skriftlig dokumentasjon kan være nyttig for kompliserte saker, men er ikke kjernen i Thank-fasen. Det handler om den personlige avslutningen på interaksjonen.' },
        ],
        espenTip: 'Den siste setningen kunden hører er den de husker best. Gjør den god: «Takk for at du sa ifra — det setter vi stor pris på.»',
      },
      {
        id: 'klag-3-5',
        icon: '🎯',
        title: 'LAST i komplekse situasjoner',
        context: 'En kunde er sint og avbryter den ansatte flere ganger mens de prøver å lytte. Kunden vil ha umiddelbar løsning og vil ikke «prate om det».',
        question: 'Hva er riktig tilnærming når en sint kunde aktivt motarbeider LAST-sekvensen?',
        choices: [
          { id: 'a', label: 'Gi etter og hopp rett til Solve siden kunden vil ha det slik', isCorrect: false, feedback: 'Å hoppe direkte til løsning uten forståelse risikerer å tilby feil løsning. Og en vellykket løsning alene bygger sjelden relasjon — kunden forlater fortsatt sint.' },
          { id: 'b', label: 'Tilpasse hastigheten men holde fast i sekvensen: kort validering, rask beklagelse, løsning, takk', isCorrect: true, feedback: 'Riktig! LAST er fleksibel. Med en utålmodig kunde kan du komprimere L og A til én kort setning, gå raskt til S, og avslutte med T. Sekvensen fungerer, bare i et raskere tempo.' },
          { id: 'c', label: 'Kalle inn en leder fordi situasjonen er utenfor normal prosedyre', isCorrect: false, feedback: 'En sint, utålmodig kunde er ikke utenfor normal prosedyre — det er en vanlig klagesituasjon. LAST-kompetansen dekker nettopp dette.' },
          { id: 'd', label: 'Be kunden komme tilbake når de har roet seg ned, for å sikre en god prosess', isCorrect: false, feedback: 'Å be noen komme tilbake «når de er roet ned» er et avvisningssignal og vil eskalere frustrasjonen kraftig.' },
        ],
        espenTip: 'LAST er et rammeverk, ikke et manus. Med en utålmodig kunde: ti sekunder lytting, én setning empati, umiddelbar handling, én avsluttende takk.',
      },
    ],
  },
  {
    phaseNumber: 4,
    icon: '🗣️',
    title: 'Kroppsspråk og tone',
    quote: '55% av kommunikasjon er kroppsspråk',
    practical: 'Ikke kryss armene, ikke sukk, ikke se på klokken. Smil og nikk viser at du hører etter. Senk stemmen og snakk rolig — selv om kunden er opprørt.',
    exercises: [
      {
        id: 'klag-4-1',
        icon: '💪',
        title: 'Forsvarlig kroppsspråk i klagesituasjoner',
        context: 'En ansatt lytter til en klage med korslagte armer, lett vipper bakover og rynker øyenbrynene.',
        question: 'Hva kommuniserer dette kroppsspråket til kunden?',
        choices: [
          { id: 'a', label: 'Konsentrasjon og profesjonell evaluering av klagen', isCorrect: false, feedback: 'Korslagte armer og bakovervippe kommuniserer ikke konsentrasjon — de kommuniserer lukkethet og distanse.' },
          { id: 'b', label: 'Defensivitet, lukkethet og skepsis — noe som forverrer klagesituasjonen', isCorrect: true, feedback: 'Riktig! Korslagte armer signaliserer defensivitet, bakovervippe signaliserer distanse, og rynkede øyenbryn signaliserer skepsis. Kombinasjonen forteller kunden at de ikke er velkomne.' },
          { id: 'c', label: 'Nøytralitet og upartiskhet som er viktig i klagesituasjoner', isCorrect: false, feedback: 'Dette er ikke nøytralt kroppsspråk — det er negativt. Nøytral holdning er oppreist, åpen og uten korslagte armer.' },
          { id: 'd', label: 'At den ansatte lytter nøye og tenker seg om', isCorrect: false, feedback: 'Rynkede øyenbryn kan faktisk signalisere konsentrasjon i noen kontekster, men kombinasjonen med korslagte armer og bakovervippe gjør det samlede signalet negativt.' },
        ],
        espenTip: 'Åpne armene — bokstavelig talt. Åpen kropp = åpent sinn. Det er det kunden trenger å se.',
      },
      {
        id: 'klag-4-2',
        icon: '📢',
        title: 'Tonefall og eskalering',
        context: 'En kunde hever stemmen i en klagesituasjon. Den ansatte svarer med å heve stemmen tilsvarende og snakke raskere.',
        question: 'Hva er den typiske konsekvensen av å matche en opprørt kundes stemmeintensitet?',
        choices: [
          { id: 'a', label: 'Kunden roer seg fordi de ser at den ansatte er like engasjert', isCorrect: false, feedback: 'Å heve stemmen fremstår som konfronterende, ikke engasjert. Det signaliserer konkurranse om dominans, ikke problemløsning.' },
          { id: 'b', label: 'Situasjonen eskalerer i et gjensidig mønster av høyere og høyere stemmer', isCorrect: true, feedback: 'Riktig! Emosjonell smitte fungerer speilet — matcher du intensiteten, eskalerer begge parter. Den profesjonelle teknikken er tvert imot å SENKE tonen, noe som gradvis trekker kunden ned.' },
          { id: 'c', label: 'Kunden føler seg respektert fordi den ansatte tar dem på alvor', isCorrect: false, feedback: 'Høyt tempo og hevet stemme kommuniserer ikke respekt — det kommuniserer stress og konfrontasjon.' },
          { id: 'd', label: 'Andre kunder i butikken forstår at den ansatte forsvarer bedriften', isCorrect: false, feedback: 'Andre kunder vil oppfatte konflikten og bli ubehagelige. Det er aldri et mål å «vinne» en høylytt klagesituasjon.' },
        ],
        espenTip: 'Jo høyere kunden snakker, jo lavere bør du svare. Det er motintuitivt men effektivt — prøv det.',
      },
      {
        id: 'klag-4-3',
        icon: '👀',
        title: 'Øyekontakt under klagebehandling',
        context: 'En ansatt ser ned i datamaskinen mens kunden forklarer problemet, og hevder at de hører etter.',
        question: 'Hva er effekten av mangelfull øyekontakt i denne situasjonen?',
        choices: [
          { id: 'a', label: 'Ingen effekt — det viktigste er at den ansatte faktisk hører hva kunden sier', isCorrect: false, feedback: 'Kommunikasjon er ikke bare hva du hører, men hva kunden oppfatter. Mangelfull øyekontakt sender et tydelig signal om desinteresse uavhengig av hva du faktisk gjør.' },
          { id: 'b', label: 'Kunden oppfatter det som desinteresse og at problemet ikke tas på alvor', isCorrect: true, feedback: 'Riktig! Øyekontakt er en av de viktigste ikke-verbale signalene for oppmerksomhet. Å se ned i en skjerm under lytting kommuniserer tydelig at noe annet er viktigere enn kunden.' },
          { id: 'c', label: 'Den ansatte virker mer profesjonell fordi de tar notater', isCorrect: false, feedback: 'Å notere i en skjerm kan virke profesjonelt i noen kontekster, men under en klagesituasjon prioriteres menneskelig kontakt. Se opp fra skjermen.' },
          { id: 'd', label: 'Kunden setter pris på at den ansatte er effektiv og jobber mens de lytter', isCorrect: false, feedback: 'Kunder i klagesituasjoner trenger å føle seg sett og hørt som mennesker. Multitasking signaliserer at saken er rutinemessig og upersonlig.' },
        ],
        espenTip: 'Lukk laptopen. Legg bort telefonen. Se på kunden. De 90 sekundene det tar å lytte med full oppmerksomhet er aldri bortkastet.',
      },
      {
        id: 'klag-4-4',
        icon: '😮‍💨',
        title: 'Sukk og tydelig frustrasjon',
        context: 'En ansatt sukker synlig når en kunde begynner å forklare en komplisert klage. Den ansatte gjør det ubevisst.',
        question: 'Hva er konsekvensen av dette selv om det er ubevisst?',
        choices: [
          { id: 'a', label: 'Ingen konsekvens siden det var ubevisst og kunden forstår det', isCorrect: false, feedback: 'Kunder tolker kroppsspråk ubevisst, uavhengig av intensjonen bak det. Ubevisste signaler er ikke unnskyldbare — effekten er den samme.' },
          { id: 'b', label: 'Kunden opplever seg som en byrde og vil enten eskalere eller trekke seg unødvendig', isCorrect: true, feedback: 'Riktig! Et sukk kommuniserer tydelig «dette er slitsomt for meg». Kunden tolker det som at de er en belastning — noe som enten utløser sinne (eskalering) eller skam (de trekker seg). Begge deler er dårlig.' },
          { id: 'c', label: 'Den ansatte fremstår som ærlig og transparent, noe kunder setter pris på', isCorrect: false, feedback: 'Ærlighet om profesjonell frustrasjon er ikke en dyd i klagebehandling. Profesjonalitet betyr å håndtere det kunden ser uavhengig av egne følelser.' },
          { id: 'd', label: 'Det er lett for kunden å overse, spesielt hvis den ansatte raskt retter opp med positive ord', isCorrect: false, feedback: 'Kroppsspråk registreres dypere enn ord. Et sukk som etterfulgt av varme ord skaper kognitiv dissonans — kunden stoler på sukket, ikke ordene.' },
        ],
        espenTip: 'Kroppsspråket ditt avslører deg selv om du prøver å skjule det. Øv på kontrollert åpen holdning — det er en treningsbar ferdighet.',
      },
      {
        id: 'klag-4-5',
        icon: '🎭',
        title: 'Konsistens mellom verbal og ikke-verbal kommunikasjon',
        context: 'En ansatt sier «selvfølgelig skal vi hjelpe deg med det!» med et flatt ansiktsuttrykk og armer hengende passivt langs siden.',
        question: 'Hva vil kunden sannsynligvis oppfatte?',
        choices: [
          { id: 'a', label: 'Positiv vilje til å hjelpe fordi ordene er klare og tydelige', isCorrect: false, feedback: 'Ord alene er ikke tilstrekkelig. Mehrabians forskning viser at kroppsspråk (55%) og tonefall (38%) dominerer over ord (7%) i kommunikasjon av holdninger.' },
          { id: 'b', label: 'Mangel på entusiasme og genuint engasjement, til tross for de positive ordene', isCorrect: true, feedback: 'Riktig! Når verbal og ikke-verbal kommunikasjon er inkonsistente, stoler vi på det ikke-verbale. Flatt uttrykk og passiv holdning undergraver de positive ordene.' },
          { id: 'c', label: 'Profesjonell nøytralitet som er passende i en servicekontekst', isCorrect: false, feedback: 'Nøytralitet er ikke det optimale i klagebehandling — empati og engasjement er det som trengs. Passivt kroppsspråk signaliserer likegyldighet, ikke nøytralitet.' },
          { id: 'd', label: 'At den ansatte er sliten og trenger en pause', isCorrect: false, feedback: 'Kunden tolker signalet som relatert til dem og saken, ikke til den ansattes generelle dagsform. Persepsjonsmessig handler alt om dem.' },
        ],
        espenTip: 'Krop og ord må peke i samme retning. Øv foran et speil: si det med kroppen, ikke bare med munnen.',
      },
    ],
  },
  {
    phaseNumber: 5,
    icon: '📋',
    title: 'Dokumentasjon og oppfølging',
    quote: 'Klager som registreres kan forbedre hele bedriften',
    practical: 'Registrer: dato, årsak, løsning, kundens tilfredshet. Mønstre i klager avslører produktfeil og servicebehov — og gir deg gull til leverandørmøter.',
    exercises: [
      {
        id: 'klag-5-1',
        icon: '📝',
        title: 'Hva bør dokumenteres ved en klage?',
        context: 'En butikksjef vil implementere et system for å lære av klager. Han spør deg hva som bør registreres for hver klage.',
        question: 'Hvilken informasjon er MEST verdifull å systematisk dokumentere?',
        choices: [
          { id: 'a', label: 'Kundens navn og kontaktinformasjon for oppfølging', isCorrect: false, feedback: 'Kontaktinfo er nyttig for oppfølging av enkeltklager, men det gir ikke systeminformasjon om mønstre og trender.' },
          { id: 'b', label: 'Dato, årsak til klagen, løsning valgt og kundens tilfredshet med løsningen', isCorrect: true, feedback: 'Riktig! Disse fire datapunktene gir deg systematisk informasjon: når skjedde det, hva var problemet, hva løste det, og var kunden fornøyd. Mønstre i disse dataene er ekstremt verdifulle.' },
          { id: 'c', label: 'Hvem av de ansatte som var involvert i situasjonen', isCorrect: false, feedback: 'Individuell ansvarliggjøring uten kontekst skaper fryktkultur, ikke læring. Systemfokus er mer verdifullt enn individfokus i klageregistrering.' },
          { id: 'd', label: 'Produktets pris og om kunden fikk refusjon eller ikke', isCorrect: false, feedback: 'Økonomiske data er nyttige, men gir ikke informasjon om årsak og trender. Årsaksanalysen er det mest verdifulle.' },
        ],
        espenTip: 'Dokumenter klager som en lege dokumenterer symptomer — du leter etter mønstre som kan diagnostisere systemproblemer.',
      },
      {
        id: 'klag-5-2',
        icon: '📊',
        title: 'Mønstre i klagedata',
        context: 'Etter tre måneder med systematisk klageregistrering ser du at 40% av klagene handler om feil på én bestemt produktkategori.',
        question: 'Hva er den viktigste handlingen basert på denne innsikten?',
        choices: [
          { id: 'a', label: 'Trene de ansatte bedre i å håndtere klager på denne produktkategorien', isCorrect: false, feedback: 'Bedre klagetrening er defensivt — det hjelper deg å håndtere symptomene bedre, men løser ikke rotproblemet med produktkategorien.' },
          { id: 'b', label: 'Ta klagedataene til leverandørmøtet og kreve produktforbedring eller bytte leverandør', isCorrect: true, feedback: 'Riktig! Klagedata er forhandlingskapital. 40% av klagene på én kategori er et sterkt argument for leverandøren om at de må forbedre produktkvaliteten.' },
          { id: 'c', label: 'Slutte å selge produktkategorien inntil videre', isCorrect: false, feedback: 'Å slutte å selge er en drastisk og muligens unødvendig reaksjon. Problemet kan løses med leverandøren, og inntektstapet av å fjerne kategorien er sannsynligvis for høyt.' },
          { id: 'd', label: 'Varsle Forbrukertilsynet om potensielt farlige produkter', isCorrect: false, feedback: 'Forbrukertilsynet er aktuelt ved helse- eller sikkerhetsrisikoer. Kvalitetsklager tas normalt opp med leverandøren som første steg.' },
        ],
        espenTip: 'Klagedataene dine er gull i leverandørmøter. «Vi har 47 klager på denne produktlinjen siste kvartal» er et argument ingen leverandør kan ignorere.',
      },
      {
        id: 'klag-5-3',
        icon: '🤝',
        title: 'Oppfølging etter klagebehandling',
        context: 'En kunde hadde en alvorlig klage som ble løst godt. Noen dager er gått og den ansatte tenker på om de bør ta kontakt med kunden.',
        question: 'Hva anbefaler god klagebehandlingspraksis i denne situasjonen?',
        choices: [
          { id: 'a', label: 'Ikke ta kontakt — kunden er sannsynligvis glad for at saken er avsluttet og vil ikke bli minnet om den', isCorrect: false, feedback: 'Proaktiv oppfølging er et tegn på at bedriften tar kunden på alvor. De fleste kunder setter pris på det og opplever det som omsorg, ikke irritasjon.' },
          { id: 'b', label: 'Ta kontakt for å forsikre seg om at kunden er fornøyd og for å vise genuint engasjement', isCorrect: true, feedback: 'Riktig! Proaktiv oppfølging er et kraftig serviceverktøy. Det viser at kunden er viktig nok til å følge opp, og gir deg mulighet til å luke ut problemer som gjenstår.' },
          { id: 'c', label: 'Sende en standardisert tilfredshetsmåling via e-post', isCorrect: false, feedback: 'En standardisert spørreundersøkelse er upersonlig og kommuniserer rutinehåndtering. En personlig oppfølging er mye mer effektiv for å bygge lojalitet.' },
          { id: 'd', label: 'Kun ta kontakt hvis kunden ber om det', isCorrect: false, feedback: 'Passiv venting på at kunden tar kontakt er ikke proaktiv service. De beste serviceopplevelsene er de der bedriften overrasker positivt uten at kunden ber om det.' },
        ],
        espenTip: 'En telefonoppringning to dager etter en klage er det mest kostnadseffektive loyalitetstiltaket som finnes. De fleste bedrifter gjør det aldri.',
      },
      {
        id: 'klag-5-4',
        icon: '🔍',
        title: 'Klageregistrering og personvern',
        context: 'En butikk vil opprette et digitalt klagedokumentasjonssystem med detaljert informasjon om kunder og hendelser.',
        question: 'Hva er den viktigste juridiske hensikten å ta med i systemdesignet?',
        choices: [
          { id: 'a', label: 'GDPR og personvernlovgivningen setter grenser for hvilke persondata som kan lagres og hvor lenge', isCorrect: true, feedback: 'Riktig! Klageregistre med personopplysninger er underlagt GDPR. Man kan ikke lagre mer data enn nødvendig (dataminimering), og ikke lenger enn nødvendig (lagringstid).' },
          { id: 'b', label: 'Systemet bør lastes opp til skyen for å sikre tilgjengelighet', isCorrect: false, feedback: 'Cloudlagring er et teknisk valg, ikke en juridisk forpliktelse. GDPR gjelder uavhengig av lagringsform.' },
          { id: 'c', label: 'Alle ansatte bør ha tilgang til alle klager for å lære av hverandre', isCorrect: false, feedback: 'Åpen tilgang til personopplysninger er problematisk under GDPR. Tilgang bør begrenses til de som har tjenstlig behov.' },
          { id: 'd', label: 'Systemet bør integreres med butikkens CRM for bedre kundeprofiler', isCorrect: false, feedback: 'CRM-integrasjon kan være nyttig, men er ikke det viktigste hensynet. GDPR-compliance er den juridiske forpliktelsen som must håndteres.' },
        ],
        espenTip: 'GDPR gjelder for alle klagesystemer med personopplysninger. Dataminimering er regelen: samle bare det du faktisk trenger.',
      },
      {
        id: 'klag-5-5',
        icon: '📈',
        title: 'Bruk av klagestatistikk i forbedring',
        context: 'En butikk har registrert klager systematisk i ett år og vil nå bruke dataene til forbedring.',
        question: 'Hvilken bruk av klagestatistikken gir STØRST strategisk verdi for bedriften?',
        choices: [
          { id: 'a', label: 'Presentere statistikken for ansatte som motivasjon til å unngå klager', isCorrect: false, feedback: 'Motivasjonsbruk er sekundær. Den primære verdien av klagestatistikk er å identifisere systemfeil som kan forbedres.' },
          { id: 'b', label: 'Identifisere gjentakende årsaker (mønstre) og implementere systemiske forbedringer for å fjerne rotårsaker', isCorrect: true, feedback: 'Riktig! Mønstre i klagedata avslører systemfeil — ikke enkeltpersonfeil. Å fjerne rotårsaker gir varig reduksjon i antall klager, noe ingen mengde opplæring kan oppnå alene.' },
          { id: 'c', label: 'Rapportere statistikken til Forbrukertilsynet som en del av god selskapsstyring', isCorrect: false, feedback: 'Intern klagestatistikk er ikke noe som rapporteres til Forbrukertilsynet under normale omstendigheter. Den brukes internt til forbedring.' },
          { id: 'd', label: 'Sammenligne klagetallene med bransjestandard og bruke det i markedsføring', isCorrect: false, feedback: 'Markedsføringsbruk er mulig i noen kontekster, men er ikke den primære strategiske verdien. Intern forbedring er hovedformålet.' },
        ],
        espenTip: 'Hvert klage er et signal. Nok signaler avslører et mønster. Et mønster forteller deg hva du bør fikse neste — ikke hvem du bør straffe.',
      },
    ],
  },
]

export default function KlagebehandlingModule() {
  return (
    <DrawerModule
      moduleCode="KS2"
      moduleTitle="Klagebehandling og reklamasjon"
      moduleIcon="📩"
      storageKey="learning-kultur-klagebehandling"
      completeRoute="/learning/kultur/klagebehandling/complete"
      phases={PHASES}
      intro="Klager er en mulighet til å beholde en kunde. Undersøkelser viser at en kunde hvis klage blir håndtert godt, blir mer lojal enn en kunde som aldri har klaget. Forbrukerkjøpsloven gir kunden rettigheter du må kjenne."
      vissteduAt="En misfornøyd kunde forteller i snitt 9–15 andre om opplevelsen. En fornøyd klagebehandling kan snu dette til positiv omtale."
      espenSier="Husker du sist du klaget på noe? Følte du deg hørt? Hva ville du at den ansatte skulle gjort annerledes?"
      presentationLink={{ route: '/learning/presentations/klaghandtering', description: 'Klagehåndtering — en visuell gjennomgang av LYTT-metoden' }}
    />
  )
}
