import DrawerModule from '../shared/DrawerModule'
import type { DrawerPhase } from '../shared/DrawerModule'

export const PHASES: DrawerPhase[] = [
  {
    phaseNumber: 1,
    icon: '📡',
    title: 'Kommunikasjonsmodellen',
    quote: 'Det du sa og det de hørte er to forskjellige ting — inntil du har sjekket.',
    content: 'Shannon-Weaver-modellen fra 1949 er fremdeles det beste verktøyet for å forstå hva som kan gå galt i kommunikasjon. Modellen beskriver en sender som koder et budskap, sender det gjennom en kanal, hvorpå mottakeren dekoder det og gir tilbakemelding. I service-sammenheng er «støy» — det som forstyrrer budskapet — ikke bare fysisk lyd, men alt som påvirker tolkning: fagsjargong kunden ikke forstår, følelsesmessig tilstand (en stresset kunde hører annerledes), telefonkvalitet, kulturelle antakelser og misforståtte tonefall. En ansatt i Elkjøp som forklarer forskjellen på to TV-er ved å bruke tekniske spesifikasjoner som «120Hz refresh rate» og «HDR10+» sender et budskap, men kunden som egentlig ville vite «hvilken er best til fotball?» mottar noe helt annet. Profesjonell kommunikasjon betyr å ta ansvar for at budskapet faktisk landes hos mottakeren, ikke bare at det ble sendt.',
    subpoints: [
      { label: 'SENDER', text: 'Den som initierer kommunikasjonen og koder budskapet — i service er det like ofte kunden som er sender, og du som er mottaker.' },
      { label: 'BUDSKAP', text: 'Det som ønskes kommunisert — innhold, følelse og intensjon — disse tre er ikke alltid de samme og skaper mye misforståelse.' },
      { label: 'KANAL', text: 'Medium for kommunikasjonen: ansikt-til-ansikt, telefon, e-post, chat — valg av kanal påvirker hvilke deler av budskapet som kommer frem.' },
      { label: 'STØY', text: 'Alt som forstyrrer forståelsen mellom sender og mottaker — fra tekniske problemer til kulturelle filtre og følelsesmessige tilstander.' },
      { label: 'TILBAKEMELDING', text: 'Mottakerens respons som bekrefter at budskapet er mottatt og forstått — uten tilbakemelding vet du ikke om kommunikasjonen lyktes.' },
    ],
    practical: 'Avslutt alltid viktige beskjeder med en bekreftende spørsmål: «Er det noe av dette som er uklart?» — det er det raskeste verktøyet for å sjekke om kommunikasjonen faktisk landde.',
    glossaryTerm: 'Kommunikasjonsmodellen',
    exercises: [
      {
        id: 'kom-1-1',
        icon: '📡',
        title: 'Støy i kommunikasjonen',
        context: 'En kunde ringer til Elkjøp for å spørre om de har en bestemt TV på lager. Den ansatte svarer med produktkoden og tekniske spesifikasjoner, men kunden forstår ingenting.',
        question: 'Hva er den primære årsaken til at kommunikasjonen sviktet i dette tilfellet?',
        choices: [
          { id: 'a', label: 'Dårlig telefonkvalitet skapte teknisk støy', isCorrect: false, feedback: 'Telefonkvalitet kan skape støy, men det er ikke årsaken beskrevet her. Problemet er at innholdet i meldingen ikke tilpasses mottakeren.' },
          { id: 'b', label: 'Fagsjargong som kunden ikke forstår fungerer som semantisk støy', isCorrect: true, feedback: 'Riktig! Fagsjargong og tekniske termer som mottakeren ikke kjenner til er et klassisk eksempel på semantisk støy — budskapet sendes, men kan ikke dekodes av mottakeren.' },
          { id: 'c', label: 'Kunden lytter ikke godt nok til beskjeden', isCorrect: false, feedback: 'Det er ikke grunnlag for å si at kunden ikke lytter. Ansvaret for at budskapet lander ligger hos senderen, ikke mottakeren.' },
          { id: 'd', label: 'Den ansatte valgte feil kanal ved å bruke telefon', isCorrect: false, feedback: 'Telefon er en helt grei kanal for denne typen henvendelse. Problemet er innholdet og språket som brukes, ikke kanalen.' },
        ],
        espenTip: 'Husk: budskapet er ikke sendt før det er forstått. Senderens jobb er å tilpasse seg mottakeren — ikke omvendt.',
      },
      {
        id: 'kom-1-2',
        icon: '🔄',
        title: 'Tilbakemeldingens rolle',
        context: 'En leder gir en ansatt instruksjoner om hvordan en oppgave skal løses. Den ansatte nikker og sier «ja» uten å si noe mer. Neste dag er oppgaven løst helt feil.',
        question: 'Hva burde lederen ha gjort for å sikre at kommunikasjonen lyktes?',
        choices: [
          { id: 'a', label: 'Skrevet ned instruksjonene og gitt dem til den ansatte', isCorrect: false, feedback: 'Skriftlige instruksjoner kan hjelpe, men garanterer ikke forståelse. Problemet er mangel på bekreftende tilbakemelding, ikke format.' },
          { id: 'b', label: 'Bedt den ansatte om å repetere instruksjonene med egne ord', isCorrect: true, feedback: 'Riktig! Å be mottakeren oppsummere med egne ord er den sikreste måten å bekrefte at budskapet er forstått korrekt, ikke bare «hørt».' },
          { id: 'c', label: 'Snakket saktere og tydeligere', isCorrect: false, feedback: 'Tempo og tydelighet løser ikke problemet her. Den ansatte sa «ja», noe som antyder at de hørte — problemet er at de ikke forstod.' },
          { id: 'd', label: 'Valgt en mer erfaren ansatt til oppgaven', isCorrect: false, feedback: 'Dette unngår kommunikasjonsproblemet heller enn å løse det. Kommunikasjonsmodellen handler om å sikre forståelse, ikke velge bort vanskeligheter.' },
        ],
        espenTip: 'Et nikk og et «ja» bekrefter bare at mottakeren hørte lyden — ikke at de forstod budskapet.',
      },
      {
        id: 'kom-1-3',
        icon: '📻',
        title: 'Kanalvalg i service',
        context: 'En kunde har sendt en bekymringsmelding på chat om en alvorlig feil med et produkt de kjøpte. Problemet er komplisert og kunden virker frustrert.',
        question: 'Hvilken kanal er best egnet for å håndtere denne situasjonen videre?',
        choices: [
          { id: 'a', label: 'Svare på chatten med en detaljert skriftlig forklaring', isCorrect: false, feedback: 'Chat er dårlig egnet for kompliserte, følelsesladede saker. Skriftlig kommunikasjon mister tonefall og kan eskalere frustrasjonen.' },
          { id: 'b', label: 'Be kunden ta kontakt igjen neste dag når du har mer tid', isCorrect: false, feedback: 'Dette signaliserer at kundens problem ikke er viktig nok til å håndtere nå, noe som vil forverre situasjonen.' },
          { id: 'c', label: 'Ringe kunden for å snakke gjennom problemet direkte', isCorrect: true, feedback: 'Riktig! Telefon er best for kompliserte og følelsesladede saker. Stemmekommunikasjon tillater tonefall og umiddelbar tilbakemelding, noe chat ikke kan.' },
          { id: 'd', label: 'Sende en e-post med spørreskjema for å kartlegge problemet', isCorrect: false, feedback: 'Et spørreskjema skaper ytterligere avstand og forsinkelse. Kunden er allerede frustrert og trenger umiddelbar menneskelig kontakt.' },
        ],
        espenTip: 'Jo mer komplisert og følelsesladet saken er, desto rikere kanal trenger du — chat og e-post er fattige kanaler, telefon og ansikt-til-ansikt er rike.',
      },
      {
        id: 'kom-1-4',
        icon: '🎯',
        title: 'Budskapet og intensjonen',
        context: 'En leder sier til en ansatt: «Det er bra du fikk ryddet lageret» med en nøytral tone og et flatt ansiktsuttrykk. Den ansatte tolker det som kritikk.',
        question: 'Hva forklarer misforståelsen best i lys av kommunikasjonsmodellen?',
        choices: [
          { id: 'a', label: 'Budskapet var formulert negativt og ansatt reagerte riktig', isCorrect: false, feedback: 'Selve ordene er positive. Problemet er ikke formuleringen, men et gap mellom intensjon, tonefall og den ansattes tolkning.' },
          { id: 'b', label: 'Kanalen var uegnet — lederen burde ha sendt en e-post', isCorrect: false, feedback: 'Kanalen er ikke problemet her. En e-post ville heller ikke løst gapet mellom tonefall og intensjon.' },
          { id: 'c', label: 'Støy oppstod fordi tonefallet ikke stemte med budskapet, og mottakeren dekodede negativt', isCorrect: true, feedback: 'Riktig! Nøytral eller flat tone kan tolkes som sarkasme eller likegyldighet. Budskap, tonefall og kroppsspråk må stemme overens for at mottakeren skal dekode riktig.' },
          { id: 'd', label: 'Den ansatte er for sensitiv og bør lære seg å ta ros bedre', isCorrect: false, feedback: 'Mottakerens tolkning er ikke irrfasjonal — tonefall er en del av kommunikasjonen. Senderen bærer ansvaret for at intensjonen kommuniseres tydelig.' },
        ],
        espenTip: 'Innhold, tonefall og kroppsspråk må peke i samme retning — ellers vil mottakeren stole på det ikke-verbale fremfor ordene.',
      },
      {
        id: 'kom-1-5',
        icon: '💬',
        title: 'Bekreftelsesspørsmål i praksis',
        context: 'Du skal forklare en ny kollega en komplisert prosedyre for kasseoppgjør på slutten av vakten. Prosedyren har flere steg som er lette å blande.',
        question: 'Hva er det mest effektive du kan gjøre for å sjekke at kollegaen har forstått?',
        choices: [
          { id: 'a', label: 'Spørre «forstod du?» etter forklaringen', isCorrect: false, feedback: 'Dette er et lukket ja/nei-spørsmål. De fleste svarer «ja» for ikke å virke uvitende, selv om de ikke forstod alt.' },
          { id: 'b', label: 'Gjenta forklaringen to ganger for å sikre at den sitter', isCorrect: false, feedback: 'Gjentakelse øker ikke nødvendigvis forståelsen. Uten tilbakemelding fra kollegaen vet du fortsatt ikke om budskapet har landet.' },
          { id: 'c', label: 'Be kollegaen utføre prosedyren mens du ser på', isCorrect: true, feedback: 'Riktig! Praktisk demonstrasjon er den sikreste formen for tilbakemelding — du kan se nøyaktig hva kollegaen har forstått og hvor det eventuelt svikter.' },
          { id: 'd', label: 'Skrive ned prosedyren og gi den til kollegaen som referanse', isCorrect: false, feedback: 'Skriftlig dokumentasjon er nyttig som støtte, men gir ikke umiddelbar tilbakemelding om forståelsen. Kollegaen kan ha spørsmål som ikke dekkes av notatet.' },
        ],
        espenTip: 'Den beste tilbakemeldingen er handling — se hva folk gjør, ikke hva de sier de forstår.',
      },
    ],
  },
  {
    phaseNumber: 2,
    icon: '🎭',
    title: 'Verbalt vs ikke-verbalt språk',
    quote: 'Kroppen lyver aldri — selv når ordene gjør det.',
    content: 'Mehrabians forskning fra 1960-tallet viste at i kommunikasjon av følelser og holdninger bidrar kroppsspråk med 55%, tonefall med 38% og de faktiske ordene med bare 7%. Dette betyr at en «ja» kan bety «nei», en «det er ikke noe problem» kan kommunisere frustrasjon, og et smil kan redde en ellers keitete setning. For servicearbeidere er dette kritisk kunnskap: du kan aldri kommunisere profesjonelt bare ved å si de riktige ordene. Kroppsspråk inkluderer øyekontakt, ansiktsuttrykk, holdning, bevegelse og avstand til kunden — åpen kroppsholdning med lett helning fremover kommuniserer interesse og engasjement, mens korslagte armer og unnvikende blikk sender et helt annet signal.',
    subpoints: [
      { label: 'ØYEKONTAKT', text: 'Riktig mengde øyekontakt (ikke stirring) kommuniserer interesse og tillit — for lite oppfattes som usikkerhet eller desinteresse av norske kunder.' },
      { label: 'TONEFALL OG TEMPO', text: 'Et rolig, varmt tonefall beroliger en stresset kunde — NRK-journalister trenes eksplisitt i dette for å kommunisere troverdighet.' },
      { label: 'PROKSEMIKK', text: 'Avstand til kunden — i norsk service er omtrent én armlengdes avstand normen, og å bryte den uten grunn oppfattes som påtrengende.' },
    ],
    practical: 'Observer din egen kroppsholdning neste gang du snakker med en kunde — stå oppreist, gjør øyekontakt og smile genuint. Det koster ingenting og er det kraftigste serviceverktøyet du har.',
    exercises: [
      {
        id: 'kom-2-1',
        icon: '👁️',
        title: 'Mehrabians regel i service',
        context: 'En ansatt i resepsjonen sier «Hei, velkommen!» til en gjest, men ser ned i papirene sine og snakker med lav, uengasjert stemme.',
        question: 'Hva kommuniserer den ansatte faktisk ifølge Mehrabians forskning?',
        choices: [
          { id: 'a', label: 'En vennlig velkomst fordi ordene er korrekte og høflige', isCorrect: false, feedback: 'Mehrabians forskning viser at ord bare utgjør 7% av kommunikasjon av følelser. Ord alene er utilstrekkelig uten tilsvarende tonefall og kroppsspråk.' },
          { id: 'b', label: 'Likegyldighet og mangel på interesse, til tross for de riktige ordene', isCorrect: true, feedback: 'Riktig! Kroppsspråk (55%) og tonefall (38%) dominerer over ord (7%). Nedvendt blikk og uengasjert stemme kommuniserer manglende interesse, uansett hva ordene sier.' },
          { id: 'c', label: 'Profesjonalitet fordi den ansatte holder fokus på arbeidsoppgavene', isCorrect: false, feedback: 'Å holde seg til papirene mens man tar imot en gjest kommuniserer det stikk motsatte av profesjonell service — det signaliserer at gjesten er en forstyrrelse.' },
          { id: 'd', label: 'At gjesten ikke er viktig nok til å få full oppmerksomhet', isCorrect: false, feedback: 'Dette er nok konsekvensen, men det er ikke det Mehrabians forskning forklarer. Poenget er at tonefall og kroppsspråk er det dominerende kommunikasjonsmiddelet.' },
        ],
        espenTip: 'Mehrabians 55-38-7-regel gjelder spesielt for kommunikasjon av følelser og holdninger — og det er akkurat dette service handler om.',
      },
      {
        id: 'kom-2-2',
        icon: '🤝',
        title: 'Proksemikk i norsk servicesammenheng',
        context: 'En ansatt i en blomsterbutikk nærmer seg en kunde som ser på produkter og stiller seg svært tett inntil kunden for å hjelpe.',
        question: 'Hva er den mest sannsynlige effekten av dette i norsk servicekultur?',
        choices: [
          { id: 'a', label: 'Kunden føler seg ivaretatt og verdsatt av den personlige oppmerksomheten', isCorrect: false, feedback: 'Norsk kultur har generelt stor komfortsone rundt personlig rom. Det som oppfattes som omsorg i noen kulturer, kan oppleves som invasivt i en norsk kontekst.' },
          { id: 'b', label: 'Kunden oppfatter den ansatte som engasjert og interessert', isCorrect: false, feedback: 'Engasjement kommuniseres bedre gjennom blikk og åpen kroppsholdning enn ved å trenge seg inn i kundens personlige rom.' },
          { id: 'c', label: 'Kunden kan oppleve det som ubehagelig og påtrengende, og ønske å forlate butikken', isCorrect: true, feedback: 'Riktig! I norsk servicekultur er omtrent én armlengdes avstand normen. Å bryte den personlige sfæren uten grunn aktiverer et fluktinstinkt hos mange norske kunder.' },
          { id: 'd', label: 'Det har ingen effekt fordi norske kunder er vant til nær kundekontakt', isCorrect: false, feedback: 'Norske kunder er faktisk kjent for å ha relativt stor personlig komfortsone sammenlignet med mange andre kulturer, noe som gjør nær fysisk kontakt mer ubehagelig.' },
        ],
        espenTip: 'Observer hvor kunden posisjonerer seg — de signaliserer selv hvor komfortabel avstand de vil ha. Respekter det.',
      },
      {
        id: 'kom-2-3',
        icon: '🎤',
        title: 'Tonefall i konfliktfylte situasjoner',
        context: 'En irritert kunde hever stemmen og klager høylytt i kassen. Den ansatte svarer med en rolig, lav og varm stemme.',
        question: 'Hvorfor er denne tilnærmingen effektiv kommunikasjonsmessig?',
        choices: [
          { id: 'a', label: 'Rolig tonefall viser at den ansatte tar klagen seriøst og vil finne en løsning', isCorrect: false, feedback: 'Dette er delvis riktig, men forklarer ikke den kommunikasjonsmessige mekanismen. Det handler om noe dypere enn bare signalering.' },
          { id: 'b', label: 'Et rolig tonefall kan ha en regulerende effekt på kundens emosjonelle tilstand og dempe eskalering', isCorrect: true, feedback: 'Riktig! Rolig og lav stemme har en beviselig beroligende effekt — kunden speiler gradvis den ansattes tonefall. Å matche en aggressiv stemme vil derimot eskalere konflikten.' },
          { id: 'c', label: 'Rolig tonefall kommuniserer at den ansatte er overlegen i situasjonen', isCorrect: false, feedback: 'Overlegen holdning vil irritere kunden ytterligere. Målet er beroligelse og forståelse, ikke å demonstrere makt.' },
          { id: 'd', label: 'Lav stemme gjør det vanskelig for kunden å høre, noe som stopper konflikten', isCorrect: false, feedback: 'Dette er ikke mekanismen. Rolig tonefall virker gjennom emosjonell speiling — det er ikke sabotasje av kundens mulighet til å kommunisere.' },
        ],
        espenTip: 'Ikke match en aggressiv tone — senk din. Emosjonell smitte fungerer begge veier, og du bestemmer retningen.',
      },
      {
        id: 'kom-2-4',
        icon: '💪',
        title: 'Kroppsholdning og service-inntrykk',
        context: 'To ansatte jobber i samme butikk. Person A hjelper kunder med korslagte armer og læner seg mot veggen. Person B hjelper med åpen holdning, lett fremoverlent og nikker aktivt.',
        question: 'Hva vil kundene typisk oppleve som forskjellen mellom disse to?',
        choices: [
          { id: 'a', label: 'Person A oppfattes som mer profesjonell fordi de ser avslappede og selvsikre ut', isCorrect: false, feedback: 'Korslagte armer og veggstøtte kommuniserer lukkethet og desinteresse, ikke profesjonalitet. Selvsikkerhet kommuniseres gjennom oppreist og åpen holdning.' },
          { id: 'b', label: 'Det er ingen forskjell så lenge begge sier de riktige tingene', isCorrect: false, feedback: 'Kroppsspråk utgjør 55% av kommunikasjonen. En åpen holdning kommuniserer interesse og tilgjengelighet uavhengig av hva man sier.' },
          { id: 'c', label: 'Person B oppfattes som mer imøtekommende, interessert og tilgjengelig', isCorrect: true, feedback: 'Riktig! Åpen kroppsholdning, fremoverlening og aktiv nikking kommuniserer engasjement og interesse. Korslagte armer og veggstøtte sender et signal om lukkethet og manglende interesse.' },
          { id: 'd', label: 'Person A oppfattes som mer nøytral og dermed tryggere for usikre kunder', isCorrect: false, feedback: 'Usikre kunder trenger nettopp varme og tilgjengelighet — ikke nøytralitet. Lukket kroppsspråk øker ikke trygghetsfølelsen.' },
        ],
        espenTip: 'Åpen kroppsholdning koster ingenting og kommuniserer mer enn du tror. Det er det billigste serviceverktøyet du har.',
      },
      {
        id: 'kom-2-5',
        icon: '😊',
        title: 'Ekte vs uekte smil i service',
        context: 'Forskning på service viser at kunder ofte kan skille et genuint smil fra et «plastet» smil uten å klare å sette ord på hvorfor de føler forskjellen.',
        question: 'Hva er den kommunikasjonsmessige forklaringen på dette fenomenet?',
        choices: [
          { id: 'a', label: 'Kunder er generelt mistenksomme og tolker alt negativt', isCorrect: false, feedback: 'Det er ingen grunn til å anta at kunder generelt er mistenksomme. Forskning viser at dette er en menneskelig evne til å lese ikke-verbale signaler.' },
          { id: 'b', label: 'Et genuint smil (Duchenne-smil) aktiverer øyemusklene og er visuelt annerledes enn et plastet smil', isCorrect: true, feedback: 'Riktig! Duchenneomils involverer øyemusklene og er vanskelig å falle. Et plastet smil aktiverer bare munnen. Hjernen vår er utrolig god til å oppdage denne forskjellen, selv ubevisst.' },
          { id: 'c', label: 'Tone i stemmen avslører alltid om et smil er genuint', isCorrect: false, feedback: 'Stemmetone er en annen kommunikasjonskanal. Smileets autentisitet leses primært visuelt gjennom ansiktsuttrykket, ikke lydlig.' },
          { id: 'd', label: 'Kunder bruker tidligere negative erfaringer til å tolke smil som uekte', isCorrect: false, feedback: 'Dette er en for spesifikk forklaring. Den mer grunnleggende forklaringen er at mennesker har en evolusjonsbasert evne til å lese ikke-verbale sosiale signaler.' },
        ],
        espenTip: 'Du kan ikke late som at du bryr deg — det vises. Den enkleste veien til et genuint smil er å faktisk like å hjelpe mennesker.',
      },
    ],
  },
  {
    phaseNumber: 3,
    icon: '👂',
    title: 'Aktiv lytting',
    quote: 'De fleste lytter ikke for å forstå — de lytter for å svare.',
    content: 'Aktiv lytting er den ferdigheten de færreste behersker, og den som gir størst utbytte i kundeservice. Forskjellen mellom å høre og å lytte er at høring er passiv og automatisk, mens lytting er aktiv og bevisst. Aktiv lytting betyr å gi full oppmerksomhet, bekjempe impulsen til å begynne å formulere svar mens den andre snakker, stille åpne oppfølgingsspørsmål og oppsummere det du har hørt for å bekrefte forståelsen. Nordea har investert tungt i å trene kundeservicemedarbeidere i aktiv lytting, fordi de oppdaget at de fleste klager ikke egentlig handlet om selve saken, men om at kunden følte seg ikke hørt.',
    subpoints: [
      { label: 'ÅPNE SPØRSMÅL', text: 'Spørsmål som begynner med «hva», «hvordan» og «kan du fortelle mer» inviterer til utfyllende svar og gir deg mye mer informasjon enn ja/nei-spørsmål.' },
      { label: 'OPPSUMMERING', text: 'Repeter det viktigste av det kunden sa med egne ord: «Så det du sier er...» — dette bekrefter forståelse og viser at du har lyttet.' },
      { label: 'VALIDERING', text: 'Anerkjenn kundens følelse uten nødvendigvis å være enig i saken: «Jeg forstår at dette oppleves som frustrerende» er kraftfullt uten å være en innrømmelse.' },
    ],
    practical: 'Øv på å la kunden fullføre setningen sin uten å avbryte — det er vanskeligere enn det høres ut, men det er selve kjernen i aktiv lytting.',
    glossaryTerm: 'Aktiv lytting',
    exercises: [
      {
        id: 'kom-3-1',
        icon: '👂',
        title: 'Høre vs lytte',
        context: 'En kunde forteller om et problem med en vare mens den ansatte allerede formulerer svaret i hodet og venter på en pause for å snakke.',
        question: 'Hva beskriver denne atferden best?',
        choices: [
          { id: 'a', label: 'Effektiv kommunikasjon fordi den ansatte er forberedt og rask til å svare', isCorrect: false, feedback: 'Rask respons uten å ha lyttet ferdig risikerer å gi feil svar. Effektivitet i service handler om å løse riktig problem, ikke om å svare raskt.' },
          { id: 'b', label: 'Passiv høring fremfor aktiv lytting — den ansatte er fokusert på å svare, ikke å forstå', isCorrect: true, feedback: 'Riktig! Å formulere svar mens den andre snakker er et klassisk tegn på passiv høring. Aktiv lytting krever at man er fullt til stede i mottakermodus frem til kunden er ferdig.' },
          { id: 'c', label: 'Et tegn på høy kompetanse fordi den ansatte kan multitaske', isCorrect: false, feedback: 'Kognitiv multitasking under lytting er en illusjon — hjernen kan ikke lytte aktivt og formulere svar simultant. Det ene går på bekostning av det andre.' },
          { id: 'd', label: 'Normal atferd som ikke påvirker kommunikasjonskvaliteten', isCorrect: false, feedback: 'Forskning viser at den som formulerer svar mens den lytter, mister 20-40% av informasjonen i budskapet. Det er en betydelig svikt i kommunikasjonskvaliteten.' },
        ],
        espenTip: 'Prøv å lytte til siste ord i kundens setning — da tvinges du til å vente og høre faktisk hva de sier.',
      },
      {
        id: 'kom-3-2',
        icon: '❓',
        title: 'Åpne vs lukkede spørsmål',
        context: 'En kunde kommer inn i en skobutikk og ser usikker ut. Den ansatte ønsker å forstå kundens behov.',
        question: 'Hvilken spørsmålsformulering vil gi mest nyttig informasjon om kundens behov?',
        choices: [
          { id: 'a', label: '«Er du på jakt etter noe spesielt?»', isCorrect: false, feedback: 'Dette er et lukket ja/nei-spørsmål. Kunden kan svare «nei» og den ansatte sitter igjen uten noen informasjon om behovet.' },
          { id: 'b', label: '«Leter du etter sko?»', isCorrect: false, feedback: 'I en skobutikk er dette et åpenbart spørsmål. Det gir ingen nyttig informasjon og viser at den ansatte ikke har tenkt gjennom hva de egentlig trenger å vite.' },
          { id: 'c', label: '«Hva slags anledning leter du sko til?»', isCorrect: true, feedback: 'Riktig! Dette er et åpent spørsmål som inviterer til et utfyllende svar. Det gir umiddelbart nyttig informasjon om behov, budsjett og preferanser.' },
          { id: 'd', label: '«Vil du ha hjelp?»', isCorrect: false, feedback: 'Et lukket ja/nei-spørsmål som kan avslutte kontakten raskt. Åpne spørsmål åpner for dialog, lukkede spørsmål avslutter den.' },
        ],
        espenTip: 'Start spørsmål med «hva», «hvordan», «kan du fortelle» — disse ordene tvinger frem et utfyllende svar.',
      },
      {
        id: 'kom-3-3',
        icon: '🔄',
        title: 'Oppsummeringens funksjon',
        context: 'Etter at en kunde har forklart et komplisert problem med en bestilling, sier den ansatte: «Så for å forsikre meg om at jeg forstår riktig: du bestilte varen for to uker siden, den ankom med feil farge, og du trenger den riktige versjonen innen fredag?»',
        question: 'Hva oppnår den ansatte med denne teknikken?',
        choices: [
          { id: 'a', label: 'Skviser tid ved å repetere det kunden allerede har sagt', isCorrect: false, feedback: 'Oppsummering tar faktisk kortere tid enn å løse feil problem. Det er en investering som sparer tid i det lange løp.' },
          { id: 'b', label: 'Bekrefter forståelse, viser at kunden har blitt lyttet til, og gir kunden mulighet til å korrigere eventuelle misforståelser', isCorrect: true, feedback: 'Riktig! Oppsummering tjener tre formål: det bekrefter forståelsen, signaliserer at kunden har blitt hørt, og gir kunden mulighet til å korrigere.' },
          { id: 'c', label: 'Dokumenterer klagen for å beskytte seg selv juridisk', isCorrect: false, feedback: 'Oppsummering er et kommunikasjonsverktøy, ikke et juridisk verktøy. Formålet er bedre forståelse og relasjonsbygging.' },
          { id: 'd', label: 'Viser overfor andre kunder at de ansatte jobber effektivt', isCorrect: false, feedback: 'Oppsummering er rettet mot kunden som snakker, ikke mot tilskuere. Det handler om å forstå — ikke å demonstrere kompetanse.' },
        ],
        espenTip: '«Så det du sier er...» er de fem kraftigste ordene i kundeservice. De viser at du faktisk lyttet.',
      },
      {
        id: 'kom-3-4',
        icon: '💙',
        title: 'Validering av følelser',
        context: 'En kunde er svært opprørt fordi en gave de bestilte ikke kom fram til jul. Den ansatte sier: «Jeg forstår at dette er frustrerende, spesielt siden det var en julegave. La meg se hva vi kan gjøre.»',
        question: 'Hva er styrken ved denne responsen sammenlignet med å gå rett på løsning?',
        choices: [
          { id: 'a', label: 'Den er raskere fordi man slipper å diskutere følelser', isCorrect: false, feedback: 'Validering av følelser tar faktisk ikke lenger tid — det er én setning. Å hoppe rett til løsning uten validering risikerer å eskalere situasjonen.' },
          { id: 'b', label: 'Den anerkjenner kundens følelsesmessige tilstand uten å ta skyld, noe som reduserer defensivitet og åpner for løsning', isCorrect: true, feedback: 'Riktig! Validering signaliserer at kunden er forstått som person, ikke bare som et «problem å løse». Dette reduserer emosjonelt forsvar og gjør kunden mer mottakelig for løsninger.' },
          { id: 'c', label: 'Den innrømmer ansvar og gir kunden et juridisk grunnlag for kompensasjon', isCorrect: false, feedback: '«Jeg forstår at dette er frustrerende» er ikke en innrømmelse av feil — det er anerkjennelse av følelse. Det er et viktig skille.' },
          { id: 'd', label: 'Den kjøper tid slik at den ansatte kan tenke seg om', isCorrect: false, feedback: 'Validering er et genuint kommunikasjonsverktøy, ikke en forsinkelsestaktikk. Kunder merker forskjellen.' },
        ],
        espenTip: 'Du kan anerkjenne en følelse uten å være enig i saken. «Jeg forstår at dette er frustrerende» er ikke det samme som «du har rett».',
      },
      {
        id: 'kom-3-5',
        icon: '🔕',
        title: 'Avbrytelse som kommunikasjonsbarriere',
        context: 'En kunde er halvveis i å forklare sitt problem når den ansatte avbryter og tilbyr en løsning de tror er riktig. Kunden ser forvirret ut og sier «nei, det er ikke det problemet».',
        question: 'Hva er den primære konsekvensen av å avbryte kunden for tidlig?',
        choices: [
          { id: 'a', label: 'Kunden opplever seg respektert fordi den ansatte er proaktiv og kompetent', isCorrect: false, feedback: 'Avbrytelse kommuniserer det motsatte av respekt — det signaliserer at den ansattes antagelse er viktigere enn kundens forklaring.' },
          { id: 'b', label: 'Man risikerer å tilby feil løsning og signaliserer at kundens fullstendige budskap ikke er verdt å høre', isCorrect: true, feedback: 'Riktig! Tidlig avbrytelse har to negative effekter: du mister informasjon som fører til feil løsning, og du sender et signal om at kunden ikke er verdt å lytte til.' },
          { id: 'c', label: 'Det effektiviserer servicen ved å kutte unødvendig forklaring', isCorrect: false, feedback: 'Det er ikke effektivt å løse feil problem raskt. Feil løsning krever ytterligere runder og tar mer tid totalt enn om man hadde lyttet ferdig fra starten.' },
          { id: 'd', label: 'Det har minimal effekt fordi den ansatte uansett forstod problemet', isCorrect: false, feedback: 'I dette tilfellet er konsekvensen eksplisitt: kunden sier «det er ikke det problemet». Antagelsen var feil fordi man ikke lyttet ferdig.' },
        ],
        espenTip: 'La kunden fullføre den første setningen sin. De fleste ansatte avbryter for tidlig — ventetiden er kortere enn du tror.',
      },
    ],
  },
  {
    phaseNumber: 4,
    icon: '🔄',
    title: 'Tilpasning av kommunikasjon til ulike kunder',
    quote: 'Den beste kommunikatoren er den som gjør seg forstått, ikke den som snakker mest presist.',
    content: 'Profesjonell kommunikasjon krever at du raskt leser hvem du snakker med og tilpasser deg deretter. En eldre kunde som er usikker på selvbetjeningskassen på COOP trenger tydelig, rolig og ikke-fordømmende veiledning — teknisk sjargong og rask instruksjon vil gjøre ting verre. En sint kunde som nettopp har oppdaget at varen er utsolgt trenger først å bli hørt og forstått, og dernest en løsning — å komme rett til «vi kan bestille det inn» uten å ha anerkjent frustrasjonen vil eskalere konflikten. Evnen til å skifte kommunikasjonsstil basert på situasjon og person kalles kode-switching, og er en av de viktigste profesjonelle ferdighetene i en servicerolle.',
    subpoints: [
      { label: 'DEN SINTE KUNDEN', text: 'La dem fullføre, valider følelsen, unngå defensiv reaksjon og fokuser deretter på løsning — Posten Norges kundeservice trener ansatte eksplisitt på denne sekvensen.' },
      { label: 'DEN USIKRE KUNDEN', text: 'Still åpne spørsmål for å forstå behovet, tilby tydelige anbefalinger og bekreft valget — usikre kunder trenger trygghet, ikke valgparalyserende optioner.' },
      { label: 'DEN TRAVLE KUNDEN', text: 'Vær effektiv og presis, respekter tiden deres og unngå unødvendig smalltalk — signaler som blikk på klokke og korte svar forteller deg hva de trenger.' },
    ],
    practical: 'Bruk de første 10 sekundene av en kundekontakt til å lese alder, humør og kommunikasjonsstil — den tilpasningen gjøres ubevisst av de beste servicemedarbeiderne.',
    exercises: [
      {
        id: 'kom-4-1',
        icon: '😤',
        title: 'Møte den sinte kunden',
        context: 'En kunde kommer rasende inn i butikken og sier høyt at de er utrolig misfornøyd med et produkt de kjøpte i går. Andre kunder hører på.',
        question: 'Hva bør være din FØRSTE respons?',
        choices: [
          { id: 'a', label: 'Forklare bedriftens retningslinjer for retur og reklamasjon umiddelbart', isCorrect: false, feedback: 'Regler og prosedyrer løser ikke et emosjonelt ladet øyeblikk. Kunden er i følelsesmodus og trenger å bli hørt før de er klare for løsningsinformasjon.' },
          { id: 'b', label: 'Be kunden roe seg ned fordi andre kunder er tilstede', isCorrect: false, feedback: 'Å be noen «roe seg ned» eskalerer nesten alltid konflikten fordi det invaliderer følelsen deres og fremstår som kommanderende.' },
          { id: 'c', label: 'Lytte uten å avbryte, validere frustrasjonen og vise at du tar dette seriøst', isCorrect: true, feedback: 'Riktig! Den sinte kunden trenger først å bli hørt og forstått. Valider følelsen («Jeg forstår at du er frustrert») før du beveger deg mot løsning.' },
          { id: 'd', label: 'Spørre hvem som solgte kunden varen for å finne ut hvem som har ansvaret', isCorrect: false, feedback: 'Ansvarsplassering er irrelevant for kunden og kan oppfattes som defensivt og skyldfordeling. Kunden vil ha en løsning, ikke vite hvem som hadde feil.' },
        ],
        espenTip: 'LAST-modellen: Listen, Apologize, Solve, Thank. Du kan ikke hoppe over L-en — listen er nøkkelen til resten.',
      },
      {
        id: 'kom-4-2',
        icon: '😕',
        title: 'Den usikre kunden',
        context: 'En eldre dame ser lenge på to ulike støvsugere uten å bestemme seg. Hun virker usikker og litt overveldret av valgene.',
        question: 'Hvilken tilnærming er mest effektiv for å hjelpe henne?',
        choices: [
          { id: 'a', label: 'Gi henne en detaljert sammenligning av alle tekniske spesifikasjoner for begge støvsugerne', isCorrect: false, feedback: 'Mer informasjon øker ikke beslutningsevnen når en kunde allerede er overveldet. For mange valg og detaljer forsterker usikkerhet fremfor å løse den.' },
          { id: 'b', label: 'La henne se seg litt mer og stå tilgjengelig uten å forstyrre', isCorrect: false, feedback: 'En usikker kunde vil sjelden ta en beslutning alene. De trenger aktivt hjelp og anbefalinger, ikke bare tilgjengelighet.' },
          { id: 'c', label: 'Stille ett åpent spørsmål om behovet og deretter gi en tydelig anbefaling', isCorrect: true, feedback: 'Riktig! Usikre kunder trenger å bli guidet. Et enkelt åpent spørsmål («hva skal støvsugeren brukes til?») gir deg nok informasjon til å gi én klar anbefaling — det er det de trenger.' },
          { id: 'd', label: 'Spørre hva budsjettet er og starte med de billigste alternativene', isCorrect: false, feedback: 'Å starte med budsjett er ikke feil, men en usikker kunde trenger trygghet gjennom anbefaling, ikke en ny faktor å ta stilling til.' },
        ],
        espenTip: 'Usikre kunder vil ha noen å stole på — gi dem én klar anbefaling, ikke et valg mellom fem alternativer.',
      },
      {
        id: 'kom-4-3',
        icon: '⏱️',
        title: 'Den travle kunden',
        context: 'En mann i dress rusher inn, ser raskt på klokken og spør kjapt etter en bestemt vare. Han virker stresset og har travelt.',
        question: 'Hva er den riktige kommunikasjonstilnærmingen?',
        choices: [
          { id: 'a', label: 'Ta deg god tid til å fortelle om alle andre lignende produkter de kanskje vil like', isCorrect: false, feedback: 'Mersalg er upassende her. Kunden har signalisert tidspress og vil ha hjelp til å finne det de kom for — ikke et utvidet salgsopplegg.' },
          { id: 'b', label: 'Bruke de normalt høflige introduksjonsfrasene for å vise profesjonalitet', isCorrect: false, feedback: 'Formelle introduksjoner og unødvendig smalltalk respekterer ikke kundens tidspress. Profesjonalitet betyr å lese situasjonen og tilpasse seg.' },
          { id: 'c', label: 'Gi et kort og presist svar og tilby umiddelbar hjelp til å finne varen', isCorrect: true, feedback: 'Riktig! Den travle kunden kommuniserer et klart behov: effektivitet. Kort og presis kommunikasjon viser respekt for tiden deres og er den mest profesjonelle tilnærmingen i denne situasjonen.' },
          { id: 'd', label: 'Spørre om de har god tid slik at du kan gi skikkelig hjelp', isCorrect: false, feedback: 'Dette ignorerer kundens tydelige tidspress. De har allerede kommunisert at de ikke har god tid — å spørre om det virker uoppmerksomt.' },
        ],
        espenTip: 'En kunde som ser på klokken og gir korte svar sier: «Respekter tiden min.» Hør det.',
      },
      {
        id: 'kom-4-4',
        icon: '🔀',
        title: 'Kode-switching mellom kommunikasjonsstiler',
        context: 'Du har nettopp hjulpet en teknologikyndig ung kunde med å velge en laptop. Nå henvender en eldre mann seg og spør om det samme produktet.',
        question: 'Hva er riktig tilnærming når du bytter til den eldre kunden?',
        choices: [
          { id: 'a', label: 'Bruke samme tekniske forklaring som til den forrige kunden for konsistens', isCorrect: false, feedback: 'Konsistens i innhold er irrelevant hvis kommunikasjonsstilen ikke passer mottakeren. Begge kunder trenger tilpasset kommunikasjon, ikke lik kommunikasjon.' },
          { id: 'b', label: 'Tilpasse språket, tempoet og eksemplene til den eldre kundens referanserammer', isCorrect: true, feedback: 'Riktig! Kode-switching betyr å skifte kommunikasjonsstil basert på hvem du snakker med. Hverdagseksempler og roligere tempo er mer effektivt enn teknisk sjargong for mange eldre kunder.' },
          { id: 'c', label: 'Anta at den eldre mannen ikke er interessert i tekniske produkter', isCorrect: false, feedback: 'Å anta noe basert på alder er en fordom. Den eldre kunden henvendte seg aktivt og har en interesse — tilpass kommunikasjonen, ikke forventningene.' },
          { id: 'd', label: 'Snakke høyere og saktere fordi eldre kunder hører dårlig', isCorrect: false, feedback: 'Å generalisere om hørselen til eldre kunder er respektløst. Kode-switching handler om å tilpasse seg individet basert på observasjoner, ikke om å projisere aldersbaserte antagelser.' },
        ],
        espenTip: 'De beste servicemedarbeiderne bytter stil sømløst. Det handler ikke om å være falsk — det handler om å møte folk der de er.',
      },
      {
        id: 'kom-4-5',
        icon: '📊',
        title: 'Å lese de første 10 sekundene',
        context: 'En ny kunde trer inn i butikken. Du har 10 sekunder til å vurdere hvem du snakker med og tilpasse tilnærmingen din.',
        question: 'Hvilke observasjoner er MEST nyttige for å tilpasse kommunikasjonsstilen?',
        choices: [
          { id: 'a', label: 'Klær og merker de bruker for å anslå kjøpekraft', isCorrect: false, feedback: 'Kjøpekraft basert på klær er en upålitelig og potensielt diskriminerende vurdering. Det er heller ikke det som primært hjelper deg å kommunisere effektivt.' },
          { id: 'b', label: 'Ganglag, ansiktsuttrykk, tempo og kroppsspråk som signalerer humør og hastverk', isCorrect: true, feedback: 'Riktig! Disse signalene gir deg informasjon om emosjonell tilstand og tidspres — de to viktigste faktorene for å velge riktig kommunikasjonsstil i øyeblikket.' },
          { id: 'c', label: 'Alder og kjønn for å kategorisere kunden i riktig serviceprofil', isCorrect: false, feedback: 'Kategorisering basert på demografi er en kilde til fordommer og feilinformasjon. Individuelle atferdssignaler er langt mer pålitelige.' },
          { id: 'd', label: 'Hva de ser på i butikken for å starte med relevante produkter', isCorrect: false, feedback: 'Produktinteresse hjelper med salgsdialogen, men forteller deg lite om kommunikasjonsstil. Humør og hastverk er de mest kritiske variablene.' },
        ],
        espenTip: 'Hjernen din leser kroppsspråk raskere enn du er bevisst på det. Lær å stole på det inntrykket — det er oftest riktig.',
      },
    ],
  },
  {
    phaseNumber: 5,
    icon: '💻',
    title: 'Digital kommunikasjon og profesjonalitet',
    quote: 'Det skrevne ordet huskes lenger enn det talte — skriv deretter.',
    content: 'Digital kommunikasjon i en jobbsammenheng — e-post, chat, SMS og sosiale medier — har andre regler enn muntlig kommunikasjon, og disse reglene brytes hyppig med negative konsekvenser. E-post egner seg for formelle henvendelser, dokumentasjon og komplekse saker som trenger skriftlig spor. Chat og SMS egner seg for rask, enkel avklaring. Telefon er best når noe er komplisert, følelsesladet eller potensielt kontroversielt — tone av stemme eliminerer mange misforståelser som skrift skaper. Svartid er en form for kommunikasjon: en norsk forbruker som venter mer enn 24 timer på e-postsvar danner et inntrykk av bedriften.',
    subpoints: [
      { label: 'KANAL-MATCHING', text: 'Velg kommunikasjonskanal basert på budskapets kompleksitet og følelsesmessige vekt — aldri gi en oppsigelse eller alvorlig kritikk på chat.' },
      { label: 'SVARTID', text: 'Norsk servicestandard forventer svar på e-post innen én arbeidsdag og chat innen minutter — avvik fra dette sender et signal om prioritering.' },
      { label: 'SKRIFTLIG TONE', text: 'Unngå ironi og humor i skrift med kunder du ikke kjenner — det som er morsomt i tale kan oppfattes som sarkasme i tekst.' },
    ],
    practical: 'Les alltid e-poster høyt for deg selv før du sender dem — det er den raskeste måten å oppdage tone-problemer på.',
    exercises: [
      {
        id: 'kom-5-1',
        icon: '📧',
        title: 'Riktig kanalvalg for vanskelig beskjed',
        context: 'Du må informere en fast kunde om at det produktet de regnet med å få levert denne uken, ikke er tilgjengelig og leveransen er utsatt med to uker.',
        question: 'Hvilken kommunikasjonskanal er best egnet for denne meldingen?',
        choices: [
          { id: 'a', label: 'En kort SMS for rask informasjon', isCorrect: false, feedback: 'SMS er for upersonlig og for kort til å håndtere en skuffende beskjed på en god måte. Det risikerer å virke likegyldig.' },
          { id: 'b', label: 'En automatisk e-post med standardformulering', isCorrect: false, feedback: 'En automatisk standardformulering kommuniserer lav prioritet og er upersonlig. For en fast kunde er dette upassende.' },
          { id: 'c', label: 'En personlig telefonsamtale etterfulgt av en skriftlig bekreftelse på e-post', isCorrect: true, feedback: 'Riktig! For skuffende nyheter er telefon best: du kan tone justere, beklage genuint og besvare spørsmål. E-post etterpå sikrer skriftlig dokumentasjon.' },
          { id: 'd', label: 'En melding på sosiale medier for å nå kunden raskest mulig', isCorrect: false, feedback: 'Sosiale medier er upassende for personlig forretningskommunikasjon. Både synligheten og formatet er feil for denne typen melding.' },
        ],
        espenTip: 'Tommelfingerregel: jo mer ubehagelig budskapet er, desto rikere kanal trenger du. Telefon slår alltid e-post for vanskelige beskjeder.',
      },
      {
        id: 'kom-5-2',
        icon: '⏰',
        title: 'Svartid som kommunikasjon',
        context: 'En potensiell ny bedriftskunde sender en e-post fredag ettermiddag med spørsmål om en tilbudsforespørsel. Du ser e-posten mandag morgen.',
        question: 'Hva er den profesjonelle svartiden, og hva kommuniserer det om bedriften?',
        choices: [
          { id: 'a', label: 'Svar så raskt som mulig mandag morgen — norsk standard er én arbeidsdag og rask respons signaliserer profesjonalitet', isCorrect: true, feedback: 'Riktig! Norsk servicestandard er svar innen én arbeidsdag. Å svare raskt mandag kommuniserer at bedriften er responsiv og tar henvendelser seriøst.' },
          { id: 'b', label: 'Vent til tirsdag for å ikke virke for ivrig', isCorrect: false, feedback: 'I norsk forretningskultur kommuniserer forsinkelse likegyldighet, ikke selvsikkerhet. «Ikke virke for ivrig» er ikke en relevant strategi i B2B-kommunikasjon.' },
          { id: 'c', label: 'Send et automatisk svar om at e-posten er mottatt og vil bli besvart innen fem dager', isCorrect: false, feedback: 'Fem dager er langt over norsk standard og kan føre til at kunden søker tilbud hos konkurrenter. Et automatisk svar er heller ikke det samme som reell oppfølging.' },
          { id: 'd', label: 'Ring direkte mandag morgen for å imponere med personlig oppfølging', isCorrect: false, feedback: 'Ringing uten varsel kan oppleves som påtrengende i en første forretningskontakt. E-post er riktig kanal når henvendelsen kom via e-post.' },
        ],
        espenTip: 'Svartid er en stilltiende beskjed om din prioritering. En rask respons sier: «du er viktig for oss».',
      },
      {
        id: 'kom-5-3',
        icon: '✍️',
        title: 'Skriftlig tone med kunder',
        context: 'En kunde klager på e-post over lang leveringstid. Du svarer med: «Kjære [navn], med referanse til din henvendelse av dags dato, vil vi herved meddele at din pakke er under prosessering.»',
        question: 'Hva er problemet med denne e-posttonen?',
        choices: [
          { id: 'a', label: 'Den er for lang og burde vært kortere', isCorrect: false, feedback: 'Lengde er ikke primærproblemet her. En lengre, men varm og forklarende e-post ville vært bedre enn en kort byråkratisk én.' },
          { id: 'b', label: 'Formuleringen er byråkratisk og upersonlig, noe som øker kundens frustrasjon fremfor å dempe den', isCorrect: true, feedback: 'Riktig! «Med referanse til din henvendelse av dags dato» er gammeldags kontorjargong som skaper avstand. En frustrert kunde trenger varme og tydelighet, ikke byråkratisk formalitet.' },
          { id: 'c', label: 'Den starter med «Kjære» som er for formelt for norsk e-postkultur', isCorrect: false, feedback: '«Kjære» er litt formelt men ikke primærproblemet. Hele den byråkratiske stilen er problemet, ikke bare hilsefrasen.' },
          { id: 'd', label: 'Den inneholder for lite informasjon om hva som faktisk skjer med pakken', isCorrect: false, feedback: 'Manglende informasjon er et problem, men ikke det primære her. Tonen — kold og byråkratisk — er det som forverrer kundeopplevelsen.' },
        ],
        espenTip: 'Test e-posten din: ville du sagt det slik ansikt til ansikt? Hvis ikke, omskriv til naturlig norsk.',
      },
      {
        id: 'kom-5-4',
        icon: '😂',
        title: 'Humor og ironi i digital kommunikasjon',
        context: 'En ansatt svarer på en kundehenvendelse om forsinkelse med: «Haha, ja logistikk er alltid et sjansespill! Men vi lover det kommer fram... til slutt 😉»',
        question: 'Hva er risikoen med denne tilnærmingen?',
        choices: [
          { id: 'a', label: 'E-mojibruk er upassende i all profesjonell kommunikasjon', isCorrect: false, feedback: 'Emojier kan brukes profesjonelt i noen sammenhenger, men er ikke primærproblemet her. Kombinasjonen av humor, ironi og uklare løfter er det virkelige problemet.' },
          { id: 'b', label: 'Ironi og humor i skrift kan tolkes som sarkasme av en frustrert kunde og undergraver tillit', isCorrect: true, feedback: 'Riktig! Ironi og humor mister tonefall i skrift og kan tolkes stikk motsatt av intensjonen. En frustrert kunde vil lese «sjansespill» og «til slutt» som lite seriøst og respektløst.' },
          { id: 'c', label: 'Meldingen er for lang og burde vært kortere', isCorrect: false, feedback: 'Lengde er ikke problemet her. To setninger er ikke for langt — det er tonen og innholdet som er problemet.' },
          { id: 'd', label: 'Humor viser at de ansatte ikke tar jobben seriøst', isCorrect: false, feedback: 'Humor kan absolutt brukes profesjonelt i riktige kontekster. Problemet her er at humor brukes i en situasjon der kunden allerede er bekymret og trenger trygghet, ikke underholdning.' },
        ],
        espenTip: 'Skriv som du ville sagt det til din beste kundes ansikt under press. Ikke som du ville skrevet til en kompis.',
      },
      {
        id: 'kom-5-5',
        icon: '🤖',
        title: 'Chatbots og menneskelig eskalering',
        context: 'En kunde har brukt 20 minutter på å prøve å løse et problem via bankens chatbot uten å komme videre. Kunden er nå frustrert og eskalerer til menneskelig support.',
        question: 'Hva er det FØRSTE en menneskelig servicemedarbeider bør gjøre?',
        choices: [
          { id: 'a', label: 'Sende kunden tilbake til chatboten fordi den håndterer de fleste saker', isCorrect: false, feedback: 'Kunden har allerede brukt 20 minutter på chatboten uten resultat. Å sende dem tilbake kommuniserer at du ikke hørte hva de nettopp sa.' },
          { id: 'b', label: 'Anerkjenne frustrasjonen, bekrefte at de er i riktig kanal nå, og starte på nytt med aktiv lytting', isCorrect: true, feedback: 'Riktig! Etter 20 minutter med en chatbot er kunden frustrert. Det første menneskelige møtet må validere opplevelsen og signalisere at situasjonen er under kontroll — før man løser selve saken.' },
          { id: 'c', label: 'Be kunden oppsummere hva de forsøkte i chatboten', isCorrect: false, feedback: 'Å be kunden repetere alt de allerede har prøvd øker frustrasjonen. En god servicemedarbeider henter informasjonen smart uten å legge bevisbyrden på kunden.' },
          { id: 'd', label: 'Umiddelbart eskalere saken til en overordnet fordi det er et komplisert problem', isCorrect: false, feedback: 'Eskalering uten å prøve selv signaliserer manglende kompetanse og gir kunden enda en omvei. Prøv å løse det selv, med eskalering som siste utvei.' },
        ],
        espenTip: 'Når kunden har brukt tid og energi uten resultat, er det første du skal gjøre å anerkjenne det. De trenger å føle at kampen er over nå.',
      },
    ],
  },
]

export default function KommunikasjonModule() {
  return (
    <DrawerModule
      moduleCode="KS1"
      moduleTitle="Profesjonell kommunikasjon"
      moduleIcon="💬"
      storageKey="learning-kultur-kommunikasjon"
      completeRoute="/learning/kultur/kommunikasjon/complete"
      phases={PHASES}
      intro="Profesjonell kommunikasjon er den ferdigheten som skiller gode servicearbeidere fra fremragende. Det handler ikke bare om å si de riktige ordene — det handler om å forstå at kommunikasjon er en toveis prosess der meningen skapes i møtet mellom sender og mottaker. I dette modulet utforsker vi kommunikasjonens mekanismer, fra den klassiske modellen til aktiv lytting og digital profesjonalitet."
      vissteduAt="Forskning fra Harvard Business Review viser at 60–70% av alle kundetap skyldes at kunden følte seg likegyldig behandlet — ikke dårlig behandlet, bare ignorert og ikke sett. Den enkleste måten å beholde kunder på er å kommunisere på en måte som gjør dem trygge på at de betyr noe for deg."
      espenSier="Kommunikasjon er den ene ferdigheten som skiller de servicemedarbeiderne som kundene husker og savner fra de som bare var der. Det er ikke noe mystisk ved det — det handler om å være genuint til stede i møtet med et annet menneske. Alt teknikken gjør er å hjelpe deg å vise det du allerede føler."
      presentationLink={{ route: '/learning/presentations/kommunikasjon', description: 'Kommunikasjon — en visuell gjennomgang av kommunikasjonsmodellen' }}
    />
  )
}
