import DrawerModule from '../../shared/DrawerModule'
import type { DrawerPhase } from '../../shared/DrawerModule'

export const phases: DrawerPhase[] = [
  {
    phaseNumber: 1,
    icon: '💰',
    title: 'Pris og kalkulasjon — matematikken bak overskudd',
    quote: 'Pris er det eneste elementet i markedsmiksen som gir inntekt — alt annet er kostnader.',
    content: 'Prissetting er en av de viktigste og mest undervurderte ferdighetene i serviceyrket. Mange bedrifter sliter ikke fordi de selger for lite — de sliter fordi de setter feil pris. For lav pris betyr at arbeidsinnsatsen ikke betales. For høy pris betyr at kundene velger konkurrenten. Riktig pris er det punktet der bedriften dekker alle sine kostnader, er konkurransedyktig i markedet, og gir eieren en rimelig avkastning for risikoen hun tar. Dette krever forståelse for kostnadsstrukturen, konkurrentenes priser og kundenes betalingsvilje — og det starter med kalkulasjon.',
    subpoints: [
      { label: 'KOSTNADSDEKNING', text: 'Prisen må minst dekke alle kostnader forbundet med produktet eller tjenesten — på kort sikt de variable, på lang sikt også de faste.' },
      { label: 'KONKURRANSEDYKTIGHET', text: 'Markedet setter et tak: kunden sammenligner alltid med alternativer. Prisen kan ikke settes isolert fra konkurrentenes prisnivå.' },
      { label: 'LØNNSOMHET', text: 'Over kostnadsdekningsnivået skal prisen også gi rom for fortjeneste — ellers er det ingen grunn til å drive bedriften.' },
    ],
    practical: 'Tenk på en lokal kafé. Hva tror du er de tre viktigste kostnadene de må dekke med prisen på en kopp kaffe? Ranger dem fra størst til minst.',
    exercises: [
      {
        id: 'pk-1-1',
        icon: '💰',
        title: 'Hvorfor er prissetting kritisk?',
        question: 'En liten butikk selger produkter under selvkost «for å tiltrekke kunder». Hva er den sannsynlige langsiktige konsekvensen?',
        choices: [
          { id: 'a', label: 'Butikken vil vokse raskt fordi mange kunder kommer for de lave prisene', isCorrect: false, feedback: 'Mange kunder + priser under selvkost = raskere konkurs. Volumet forverrer situasjonen fordi hvert salg øker tapet.' },
          { id: 'b', label: 'Butikken vil gå konkurs fordi de taper penger på hvert eneste salg', isCorrect: true, feedback: 'Riktig! Ingen bedrift overlever på sikt med priser under selvkost — tapet akkumuleres med hvert salg. Lave priser kan brukes kortsiktig som strategi, men ikke som permanent modell.' },
          { id: 'c', label: 'Butikken vil bli mer effektiv og redusere kostnadene over tid', isCorrect: false, feedback: 'Kostnadseffektivisering er alltid bra, men det løser ikke det fundamentale problemet: om du selger under selvkost, taper du penger uansett effektivitet.' },
          { id: 'd', label: 'Leverandørene vil gi butikken bedre priser fordi de kjøper mer volum', isCorrect: false, feedback: 'Volumrabatter er mulig, men selv med lavere innkjøpspris vil butikken tape penger hvis salgsprisen er under den nye selvkosten.' },
        ],
        espenTip: 'Å «lokke kunder» med priser under kostpris kan fungere en kort periode som introduksjonstilbud — men aldri som forretningsmodell.',
      },
      {
        id: 'pk-1-2',
        icon: '💰',
        title: 'Tre faktorer i prissetting',
        question: 'En ny frisørsalong skal sette priser. Hvilke tre faktorer bør veie tyngst i beslutningen?',
        choices: [
          { id: 'a', label: 'Hva eieren synes er rettferdig, hva bransjeforeningen anbefaler, og hva som ser pent ut på prislisten', isCorrect: false, feedback: 'Disse faktorene er lite relevante. Prissetting er en strategisk og matematisk øvelse, ikke en estetisk en.' },
          { id: 'b', label: 'Egne kostnader (selvkost), konkurrentenes prisnivå og kundenes betalingsvilje', isCorrect: true, feedback: 'Riktig! Dette er de tre grunnpilarene i enhver prisstrategi: kostnadsdekning sikrer overlevelse, konkurransekartlegging gir markedsreferansen, og betalingsvilje avgjør hvor mye kunden faktisk vil betale.' },
          { id: 'c', label: 'Hva som er vanligst i bransjen, hva nabosalongen tar, og hva kundene klager over', isCorrect: false, feedback: 'Konkurrentkartlegging er én viktig faktor, men uten å kjenne egne kostnader og kundenes betalingsvilje er prisbildet ufullstendig.' },
          { id: 'd', label: 'Momsandel, arbeidsgiverkostnader og fraværsprosent', isCorrect: false, feedback: 'Disse er innsatsfaktorer i kostnadsberegningen, men de er ikke de overordnede faktorene som bør styre selve prissettingsbeslutningen.' },
        ],
        espenTip: 'Kostnader setter gulvet (du kan ikke gå under), markedet setter taket (kunden velger konkurrenten over dette), og din posisjonering bestemmer hvor i intervallet du legger deg.',
      },
      {
        id: 'pk-1-3',
        icon: '💰',
        title: 'Pris og volum',
        question: 'Hva er sammenhengen mellom pris og salgsvolum i de fleste markeder?',
        choices: [
          { id: 'a', label: 'Høyere pris gir alltid høyere volum fordi kundene oppfatter det som bedre kvalitet', isCorrect: false, feedback: 'Kvalitetsoppfatning kan øke ved høyere pris for luksusvarer, men i de fleste markeder reduserer høyere pris salgsvolum.' },
          { id: 'b', label: 'Lavere pris gir høyere volum, men ikke nødvendigvis høyere fortjeneste', isCorrect: true, feedback: 'Riktig! Lavere pris øker typisk volumet, men om fortjenesten stiger avhenger av marginen per enhet. En 10 % prisreduksjon krever ofte 20–30 % volumøkning for å kompensere — avhengig av dekningsgraden.' },
          { id: 'c', label: 'Pris og volum er uavhengige av hverandre', isCorrect: false, feedback: 'I de fleste markeder er det en klar sammenheng — dette kalles priselastisitet. Jo mer elastisk markedet er, desto sterkere reagerer volumet på prisendringer.' },
          { id: 'd', label: 'Lavere pris gir alltid høyere fortjeneste fordi man selger mer', isCorrect: false, feedback: 'Feil! Lavere pris + høyere volum kan gi lavere total fortjeneste hvis marginen er tynn. Volumøkningen må mer enn kompensere for prisreduksjonen.' },
        ],
        espenTip: 'Regn alltid ut: hva er dekningsbidraget per enhet? En 10 % prisreduksjon kan kreve 50 % mer volum for å gi samme fortjeneste — alt avhenger av din dekningsgrad.',
      },
    ],
  },
  {
    phaseNumber: 2,
    icon: '📊',
    title: 'Pris — det eneste elementet som gir inntekt',
    quote: 'Produkt, plass og påvirkning koster penger. Pris er det eneste konkurransemiddelet som tilfører bedriften inntekt.',
    content: 'I markedsmiksens fire P-er (Produkt, Pris, Plass, Påvirkning) skiller Pris seg fundamentalt fra de tre andre: de øvrige P-ene representerer kostnader og investeringer. Prisen er den eneste variabelen som direkte genererer inntekt. Dette betyr at prisvalget har en uforholdsmessig stor innvirkning på lønnsomheten. En 1 % økning i pris (uten volumtap) gir typisk en 10–15 % forbedring i driftsresultatet fordi hele økningen faller rett til bunnlinjen. Riktig pris balanserer tre hensyn: hva kunden er villig til å betale, hva konkurrentene tar, og hva som dekker bedriftens kostnader med en akseptabel margin.',
    subpoints: [
      { label: 'DE FIRE P-ER', text: 'Produkt (utvikle og tilpasse tilbudet), Pris (fastsette verdi i kroner), Plass (distribuere til kunden), Påvirkning (markedsføre og kommunisere). Kun Pris genererer direkte inntekt.' },
      { label: 'PRISENS TREFOLDIGE ROLLE', text: 'Pris som kostnadsdekning (matematikk), pris som konkurransesignal (markedsposisjonering), og pris som verdiutrykk (kunden tolker pris som kvalitetsindikator).' },
      { label: 'PRIS OG LØNNSOMHET', text: 'En 1 % prisøkning med stabilt volum gir typisk 10–15 % forbedring i driftsresultatet. Det er den kraftigste enkeltspaken i lønnsomhetsarbeidet.' },
    ],
    practical: 'Tenk på en butikk som selger sportsutstyr. Hvordan brukes pris som signal? Hva sier en høy pris om et produkt? Hva sier en lav pris? Når kan lav pris faktisk skade salget?',
    exercises: [
      {
        id: 'pk-2-1',
        icon: '📊',
        title: 'De fire P-er og inntekt',
        question: 'Hvilken av de fire P-ene i markedsmiksen genererer direkte inntekt for bedriften?',
        choices: [
          { id: 'a', label: 'Produkt — fordi produktet er det kunden kjøper', isCorrect: false, feedback: 'Produktet er det bedriften tilbyr — men selve produktutviklingen og produksjonen er en kostnad. Inntekten oppstår i prisingen, ikke i produktet isolert.' },
          { id: 'b', label: 'Pris — fordi den representerer det kunden betaler og bedriften mottar', isCorrect: true, feedback: 'Riktig! Pris er den eneste av de fire P-ene som direkte genererer inntekt. De tre andre (produkt, plass, påvirkning) representerer kostnader og investeringer.' },
          { id: 'c', label: 'Påvirkning — fordi markedsføringen tiltrekker kunder og øker omsetningen', isCorrect: false, feedback: 'Markedsføring øker volumet, men er i seg selv en kostnad. Det er prisen som bestemmer inntekten per solgte enhet.' },
          { id: 'd', label: 'Plass — fordi distribusjon når ut til flest mulig kunder', isCorrect: false, feedback: 'Distribusjon øker tilgjengelighet og potensielt volum, men er en kostnad. Inntekten per transaksjon bestemmes av prisen.' },
        ],
        espenTip: 'Husk: Produkt, Plass og Påvirkning er alle kostnader. Pris er inntekten. Derfor har prisvalget direkte og umiddelbar effekt på bunnlinjen.',
      },
      {
        id: 'pk-2-2',
        icon: '📊',
        title: 'Pris som balanse',
        question: 'En restaurant ønsker å finne riktig pris på en ny rett. Hvilke tre hensyn må balanseres?',
        choices: [
          { id: 'a', label: 'Kokkens mening, restaurantsjefens mening, og gjestenes mening', isCorrect: false, feedback: 'Synspunkter er verdifulle innspill, men ikke et prissettingsrammeverk. Prissetting krever fakta om kostnader, marked og betalingsvilje.' },
          { id: 'b', label: 'Ingredienskostnad, konkurrentenes priser og hva gjestene er villige til å betale', isCorrect: true, feedback: 'Riktig! Disse tre er klassikerne: kostnad (gulvet), konkurrenter (markedsreferansen) og betalingsvilje (taket). Prisen bør ligge i spenningsfeltet mellom dem.' },
          { id: 'c', label: 'Mva-sats, kassesystem og åpningstider', isCorrect: false, feedback: 'Mva-satsen påvirker sluttprisen, men er ikke en selvstendig prissettingsfaktor. Kassesystem og åpningstider er operative valg, ikke prisfaktorer.' },
          { id: 'd', label: 'Sesong, beliggenhet og antall ansatte', isCorrect: false, feedback: 'Disse faktorene påvirker etterspørsel og kostnader indirekte, men er ikke de tre primære hensynene i selve prissettingsbeslutningen.' },
        ],
        espenTip: 'Pris = balansen mellom hva det koster deg, hva markedet aksepterer, og hva din posisjonering tåler. Feil i én av de tre gir enten tap eller tapte kunder.',
      },
      {
        id: 'pk-2-3',
        icon: '📊',
        title: 'Pris som kvalitetssignal',
        question: 'En ny hotellkjede setter priser 30 % lavere enn konkurrentene for å tiltrekke kunder. Hva er den potensielle ulempen med denne strategien?',
        choices: [
          { id: 'a', label: 'Ingen — lave priser tiltrekker alltid flest kunder og gir mest omsetning', isCorrect: false, feedback: 'I praksis kan lav pris skade bedriften på to måter: det sender et kvalitetssignal som kan frastøte kunder som ønsker god standard, og det gir lavere margin per gjest.' },
          { id: 'b', label: 'Kunder kan tolke lav pris som et signal om lav kvalitet og velge konkurrenten', isCorrect: true, feedback: 'Riktig! Pris kommuniserer kvalitet. I overnattingsmarkedet er dette særlig tydelig: mange gjester unngår det billigste alternativet fordi de frykter dårlig standard.' },
          { id: 'c', label: 'Lav pris er ulovlig etter Pristiltaksloven', isCorrect: false, feedback: 'Pristiltaksloven gjelder urimelig HØYE priser, ikke lave. Det er i utgangspunktet fullt lovlig å sette lave priser — unntaket er systematisk underprising for å eliminere konkurrenter (rovprising).' },
          { id: 'd', label: 'Konkurrentene vil automatisk senke sine priser og eliminere fordelen', isCorrect: false, feedback: 'Prisrespons fra konkurrenter er mulig, men er ikke den primære bekymringen. Det viktigste er at lav pris kan ødelegge posisjoneringen.' },
        ],
        espenTip: 'I premium-segmentet kan en prisøkning faktisk øke salget — fordi kunden tolker høy pris som bevis på kvalitet. Dette kalles «Veblen-effekten».',
      },
    ],
  },
  {
    phaseNumber: 3,
    icon: '🧱',
    title: 'Faste og variable kostnader',
    quote: 'Du kan ikke sette riktig pris før du vet hvilke kostnader som faktisk endrer seg.',
    content: 'All kalkulasjon starter med å skille mellom to kostnadstyper. Faste kostnader påløper uavhengig av om du selger ett eller tusen produkter — husleie, forsikring og lønn til fast ansatte er typiske eksempler. Variable kostnader stiger eller faller i takt med aktivitetsnivået — råvarer, emballasje og provisjon er typiske eksempler. Denne inndelingen er ikke bare bokføring: den avgjør hvilken kalkulasjonsmetode du bør bruke og hva som faktisk er minimumspris for et enkelt salg.',
    subpoints: [
      { label: 'FASTE KOSTNADER', text: 'Påløper uavhengig av produksjons- eller salgsvolum. Eksempel: husleie 20 000 kr/mnd er det samme enten du selger 10 eller 10 000 enheter.' },
      { label: 'VARIABLE KOSTNADER', text: 'Øker proporsjonalt med aktiviteten. Kjøper du inn 100 varer til 50 kr stykket, er den variable innkjøpskostnaden 5 000 kr — dobler du salget, dobles denne kostnaden.' },
      { label: 'TOTALE KOSTNADER', text: 'Summen av alle faste og variable kostnader i en periode. Break-even nås når totale inntekter akkurat dekker totale kostnader.' },
    ],
    practical: 'List opp kostnadene for en liten kafé. Sorter dem i faste og variable. Hvilke av kostnadene vil stige hvis kaféen dobler antall solgte kopper kaffe per dag?',
    exercises: [
      {
        id: 'pk-3-1',
        icon: '🧱',
        title: 'Faste vs variable — definisjon',
        question: 'Hva kjennetegner en fast kostnad?',
        choices: [
          { id: 'a', label: 'Den er alltid større enn variable kostnader', isCorrect: false, feedback: 'Størrelse har ingenting med definisjonen å gjøre. En fast kostnad kan godt være liten (50 kr/mnd for programvare) og en variabel kostnad kan være enorm (råvarekostnader i produksjon).' },
          { id: 'b', label: 'Den påløper uavhengig av produksjons- eller salgsvolum', isCorrect: true, feedback: 'Riktig! Det er nettopp volum-uavhengigheten som definerer en fast kostnad. Husleien er den samme enten butikken selger 5 eller 500 produkter i måneden.' },
          { id: 'c', label: 'Den kan ikke reduseres ved innsparinger', isCorrect: false, feedback: 'Faste kostnader kan godt reduseres — for eksempel ved å flytte til billigere lokaler. «Fast» betyr at kostnaden ikke endres med volumet, ikke at den er uforanderlig for alltid.' },
          { id: 'd', label: 'Den betales én gang og gjentar seg ikke', isCorrect: false, feedback: 'Det er en engangskostnad — en annen kategori. Faste kostnader gjentar seg typisk hver måned (husleie, forsikring, faste lønninger).' },
        ],
        espenTip: 'Spør deg selv: «Vil denne kostnaden endre seg hvis vi selger dobbelt så mye i morgen?» Nei = fast. Ja = variabel.',
      },
      {
        id: 'pk-3-2',
        icon: '🧱',
        title: 'Klassifisering av kostnader',
        question: 'En sportsbutikk selger joggesko. Hvilken av disse er en variabel kostnad?',
        choices: [
          { id: 'a', label: 'Husleie for butikklokalet', isCorrect: false, feedback: 'Husleien betales uavhengig av om butikken selger én eller tusen par sko i måneden. Den er en typisk fast kostnad.' },
          { id: 'b', label: 'Lønn til butikksjef i fast stilling', isCorrect: false, feedback: 'Fast lønn til fast ansatt er en fast kostnad — den endres ikke med antall solgte par sko.' },
          { id: 'c', label: 'Innkjøpspris for skoparet som selges', isCorrect: true, feedback: 'Riktig! Innkjøpsprisen per sko øker direkte med antall solgte par — et typisk eksempel på variabel kostnad.' },
          { id: 'd', label: 'Årsabonnement på kasseapparatsystem', isCorrect: false, feedback: 'Et årsabonnement med fast pris er en fast kostnad — det endres ikke med salgsvolum.' },
        ],
        espenTip: 'For en butikk er innkjøpsverdien av solgte varer (varekostnad) alltid variabel — det er selve kjernen i handelskalkulasjonen.',
      },
      {
        id: 'pk-3-3',
        icon: '🧱',
        title: 'Break-even',
        question: 'Hva betyr det at en bedrift er på «break-even»?',
        choices: [
          { id: 'a', label: 'Bedriften har tjent nok til å betale alle variable kostnader', isCorrect: false, feedback: 'Break-even krever at bedriften dekker ALLE kostnader — både faste og variable. Å kun dekke variable kostnader gir et positivt dekningsbidrag, men ikke break-even.' },
          { id: 'b', label: 'Bedriftens totale inntekter er lik totale kostnader — hverken overskudd eller underskudd', isCorrect: true, feedback: 'Riktig! Break-even er nullpunktet der alle kostnader er dekket. Selger bedriften én enhet til, begynner den å tjene penger.' },
          { id: 'c', label: 'Bedriften har solgt et like stort antall enheter som antall ansatte', isCorrect: false, feedback: 'Det er ingen sammenheng mellom antall ansatte og break-even. Break-even beregnes som: Faste kostnader ÷ Dekningsbidrag per enhet.' },
          { id: 'd', label: 'Bedriften har betalt tilbake alle lån og er gjeldfri', isCorrect: false, feedback: 'Break-even handler om driftslønnsomhet, ikke gjeld.' },
        ],
        espenTip: 'Break-even er svaret på: «Hvor mange enheter MÅ vi selge bare for å overleve?» Alt over det er fortjeneste.',
      },
      {
        id: 'pk-3-4',
        icon: '🧱',
        title: 'Blandet eksempel',
        question: 'En frisørsalong betaler 15 000 kr/mnd i husleie og bruker 40 kr i forbruksmateriell per kunde. Hvilken kostnad er variabel?',
        choices: [
          { id: 'a', label: 'Husleien på 15 000 kr', isCorrect: false, feedback: 'Husleien er fast — den er den samme uansett hvor mange kunder salongen betjener i måneden.' },
          { id: 'b', label: '40 kr i forbruksmateriell per kunde', isCorrect: true, feedback: 'Riktig! Denne kostnaden øker direkte med antall kunder: 10 kunder = 400 kr, 100 kunder = 4 000 kr. Det er definisjonen på variabel kostnad.' },
          { id: 'c', label: 'Begge er variable kostnader', isCorrect: false, feedback: 'Husleien er en typisk fast kostnad. Den varierer ikke med antall kunder.' },
          { id: 'd', label: 'Ingen av dem er variable', isCorrect: false, feedback: 'Forbruksmateriell per kunde er en klar variabel kostnad — den øker med antall kunder betjent.' },
        ],
        espenTip: 'I tjenestenæringen er forbruksmateriell per kunde den vanligste variable kostnaden — de fleste andre kostnader (lokaler, lønn) er faste.',
      },
    ],
  },
  {
    phaseNumber: 4,
    icon: '📐',
    title: 'Selvkostmetoden',
    quote: 'Selvkostprisen forteller deg hva det koster å produsere — markedet forteller deg om noen vil betale det.',
    content: 'I selvkostmetoden fordeles samtlige kostnader — både faste og variable — på hvert enkelt produkt eller tjeneste. Metoden gir en fullstendig kostnadsoversikt og brukes typisk ved langsiktig prissetting, anbud og vurdering av om et produkt i det hele tatt er lønnsomt å tilby. Ulempen er at den krever en fordelingsnøkkel for faste kostnader — og den nøkkelen er alltid et skjønnsmessig valg. En butikk som fordeler husleien per solgt enhet, vil få helt ulik selvkost avhengig av om den selger 100 eller 1 000 enheter.',
    subpoints: [
      { label: 'SELVKOST', text: 'Innkjøpspris/produksjonskostnad + andel av faste kostnader + andel av faste salgskostnader = total selvkost per enhet.' },
      { label: 'FORDELINGSNØKKEL', text: 'Metoden for å fordele faste kostnader på enkeltprodukter. Kan baseres på antall enheter, omsetningsandel eller areal — valget påvirker resultatet.' },
      { label: 'BRUKSOMRÅDE', text: 'Selvkostkalkylen er best egnet for langsiktig prissetting der alle kostnader faktisk må dekkes over tid — ikke for enkeltordrer ved ledig kapasitet.' },
    ],
    practical: 'En sykkelbutikk selger 200 sykler per måned. Faste kostnader er 60 000 kr/mnd. Innkjøpspris per sykkel er 1 500 kr. Hva er selvkosten per sykkel? (60 000 ÷ 200 + 1 500 = 1 800 kr)',
    exercises: [
      {
        id: 'pk-4-1',
        icon: '📐',
        title: 'Selvkost — definisjon',
        question: 'Hva inngår i selvkosten for et produkt?',
        choices: [
          { id: 'a', label: 'Kun innkjøpsprisen fra leverandøren', isCorrect: false, feedback: 'Innkjøpspris er bare startpunktet. Selvkost inkluderer alle kostnader knyttet til å produsere og selge varen — inkludert en andel av de faste kostnadene.' },
          { id: 'b', label: 'Summen av alle faste og variable kostnader fordelt på enheten', isCorrect: true, feedback: 'Riktig! Selvkost er den totale kostnaden per enhet, inkludert en beregnet andel av faste kostnader. Dette er minimumsprisen for langsiktig lønnsomhet.' },
          { id: 'c', label: 'Kun variable kostnader direkte knyttet til produksjonen', isCorrect: false, feedback: 'Det er bidragskalkylen som kun bruker variable kostnader. Selvkostkalkylen inkluderer også en andel av faste kostnader.' },
          { id: 'd', label: 'Innkjøpspris pluss ønsket fortjeneste per enhet', isCorrect: false, feedback: 'Fortjeneste er ikke en del av selvkosten — den legges til etter at selvkosten er beregnet. Selvkost = kostnad. Pris = selvkost + fortjeneste.' },
        ],
        espenTip: 'Husk: selvkost er det absolutte minimumsnivå for prisen på lang sikt. Selger du konsekvent under selvkost, går bedriften konkurs.',
      },
      {
        id: 'pk-4-2',
        icon: '📐',
        title: 'Beregning av selvkost',
        question: 'En kafé selger 500 kopper kaffe per dag. Faste daglige kostnader er 4 090 kr. Variable kostnader er 8 kr per kopp. Hva er omtrentlig selvkost per kopp?',
        choices: [
          { id: 'a', label: '8 kr', isCorrect: false, feedback: '8 kr er kun de variable kostnadene. Selvkost inkluderer også en andel av faste kostnader.' },
          { id: 'b', label: '16 kr', isCorrect: true, feedback: 'Riktig! Faste kostnader per kopp: 4 090 kr ÷ 500 kopper ≈ 8 kr. Variabel: 8 kr. Selvkost: 8 + 8 = 16 kr per kopp.' },
          { id: 'c', label: '4 kr', isCorrect: false, feedback: '4 kr er omtrent halvparten av riktig svar. Faste kostnader per dag ÷ antall kopper + variable kostnader per kopp.' },
          { id: 'd', label: '90 kr', isCorrect: false, feedback: '90 kr er ikke et meningsfullt tall her. Husk å dele de faste kostnadene på antall enheter.' },
        ],
        espenTip: 'Alltid to steg: (1) Beregn faste kostnader per enhet ved å dele på forventet volum. (2) Legg til variable kostnader per enhet. Summen er selvkost.',
      },
      {
        id: 'pk-4-3',
        icon: '📐',
        title: 'Svakhet ved selvkostkalkylen',
        question: 'Hva er den største svakheten ved selvkostkalkylen?',
        choices: [
          { id: 'a', label: 'Den inkluderer ikke variable kostnader', isCorrect: false, feedback: 'Selvkostkalkylen inkluderer absolutt variable kostnader — den inkluderer alle kostnader, både faste og variable.' },
          { id: 'b', label: 'Fordelingen av faste kostnader er alltid skjønnsmessig og avhenger av antatt volum', isCorrect: true, feedback: 'Riktig! Fordelingsnøkkelen for faste kostnader er et valg — og selvkosten per enhet endres dramatisk avhengig av om du antar høyt eller lavt salgsvolum.' },
          { id: 'c', label: 'Den er for komplisert til å bruke i praksis', isCorrect: false, feedback: 'Selvkostkalkylen er faktisk enkel i prinsippet — det er tolkningen av resultatet som krever erfaring.' },
          { id: 'd', label: 'Den gir alltid for lav pris', isCorrect: false, feedback: 'Selvkostkalkylen gir verken systematisk for lav eller for høy pris. Resultatet avhenger av forutsetningene.' },
        ],
        espenTip: 'En selvkostkalkyle basert på 1 000 solgte enheter gir dobbelt så høy selvkost per enhet som en kalkyle basert på 2 000 enheter. Volum-antagelsen er alt.',
      },
      {
        id: 'pk-4-4',
        icon: '📐',
        title: 'Selvkost og prissetting',
        question: 'En butikk beregner selvkost per enhet til 120 kr og vil ha 25 % fortjeneste på selvkost. Hva blir salgsprisen?',
        choices: [
          { id: 'a', label: '90 kr', isCorrect: false, feedback: '90 kr er 75 % av selvkost — det blir en pris under selvkost, noe som gir tap.' },
          { id: 'b', label: '145 kr', isCorrect: false, feedback: 'Nærme, men ikke helt. 25 % av 120 kr = 30 kr. Salgspris = 120 + 30 = 150 kr.' },
          { id: 'c', label: '150 kr', isCorrect: true, feedback: 'Riktig! 25 % fortjeneste på selvkost: 120 × 0,25 = 30 kr fortjeneste. Salgspris = 120 + 30 = 150 kr.' },
          { id: 'd', label: '160 kr', isCorrect: false, feedback: 'Det ville tilsvart 33 % fortjeneste. 25 % av 120 kr er 30 kr, ikke 40 kr.' },
        ],
        espenTip: 'Fortjeneste PÅ selvkost betyr at du regner prosenten av kostnaden. Fortjeneste I salgspris (dekningsgrad) er en annen beregning — en vanlig forvirringskilde.',
      },
    ],
  },
  {
    phaseNumber: 5,
    icon: '🔀',
    title: 'Bidragsmetoden',
    quote: 'Faste kostnader løper uansett — det relevante spørsmålet er om et salg dekker sin del av de variable kostnadene.',
    content: 'I bidragsmetoden fordeles kun de variable kostnadene på produktet. De faste kostnadene behandles som periodekostnader som bedriften må dekke gjennom sum av alle bidrag fra alle salg. Differansen mellom salgspris og variable kostnader er dekningsbidraget (DB) — og summen av alle DB over en periode skal dekke de faste kostnadene og gi overskudd. Metoden er uvurderlig ved ledig kapasitet: skal du ta imot en ekstraordre som kun dekker variable kostnader pluss litt til, er svaret alltid ja — fordi de faste kostnadene løper uansett.',
    subpoints: [
      { label: 'BIDRAGSMETODEN', text: 'Fordeler kun variable kostnader på produktet. DB = Salgspris − Variable kostnader per enhet. De faste kostnadene holdes utenfor enkeltproduktet.' },
      { label: 'DEKNINGSBIDRAG (DB)', text: 'Det beløpet hvert salg «bidrar» med til å dekke faste kostnader og eventuelt gi overskudd. Positivt DB = bidraget er positivt. Negativt DB = tapet øker for hvert salg.' },
      { label: 'BRUKSOMRÅDE', text: 'Kortsiktige prisbeslutninger, ekstraordrer og situasjoner med ledig kapasitet. Spørsmålet er ikke «dekker prisen selvkost?» men «er prisen over variable kostnader?»' },
    ],
    practical: 'En trykkeri har ledig kapasitet på fredager. En kunde tilbyr å betale 800 kr for en jobb der variable kostnader er 600 kr. Faste kostnader per dag er 2 000 kr. Bør de ta jobben? (Ja — DB = 800 − 600 = 200 kr. Bedre enn 0 kr ved ledig kapasitet.)',
    exercises: [
      {
        id: 'pk-5-1',
        icon: '🔀',
        title: 'Bidragsmetoden — definisjon',
        question: 'Hva fordeles på produktet i bidragsmetoden?',
        choices: [
          { id: 'a', label: 'Alle kostnader — både faste og variable', isCorrect: false, feedback: 'Det er selvkostmetoden som fordeler alle kostnader på produktet. Bidragsmetoden fordeler kun variable kostnader.' },
          { id: 'b', label: 'Kun variable kostnader — faste kostnader er periodekostnader', isCorrect: true, feedback: 'Riktig! I bidragsmetoden fordeles kun variable kostnader på enkeltproduktet. De faste kostnadene behandles som en samlet periodevkostnad som alle bidrag samlet må dekke.' },
          { id: 'c', label: 'Kun faste kostnader — variable kostnader avskrives separat', isCorrect: false, feedback: 'Det er omvendt fra riktig svar. Bidragsmetoden knytter variable kostnader til produktet; faste kostnader holdes på periodenivå.' },
          { id: 'd', label: 'Variable kostnader og halvparten av de faste kostnadene', isCorrect: false, feedback: 'Bidragsmetoden fordeler ingen del av faste kostnader på enkeltproduktet. De faste kostnadene holdes helt utenfor produktkalkylen.' },
        ],
        espenTip: 'Huskeregel: Bidragsmetode = kun variable på produktet. Selvkostmetode = alt på produktet. Valget avhenger av om du planlegger langsiktig (selvkost) eller tar en kortsiktig beslutning (bidrag).',
      },
      {
        id: 'pk-5-2',
        icon: '🔀',
        title: 'Bidrag vs selvkost — forskjellen',
        question: 'Hva er den viktigste forskjellen mellom bidragsmetoden og selvkostmetoden?',
        choices: [
          { id: 'a', label: 'Bidragsmetoden brukes kun i industri, selvkostmetoden kun i handel', isCorrect: false, feedback: 'Begge metoder brukes i alle bransjer — valget avhenger av formålet med kalkylen, ikke bransjen.' },
          { id: 'b', label: 'Bidragsmetoden fordeler kun variable kostnader på produktet; selvkostmetoden fordeler alle kostnader', isCorrect: true, feedback: 'Riktig! Bidragsmetoden fokuserer på hva et enkelt salg bidrar med (DB). Selvkostmetoden beregner den totale kostnaden per enhet inkludert faste kostnader.' },
          { id: 'c', label: 'Selvkostmetoden gir alltid lavere pris enn bidragsmetoden', isCorrect: false, feedback: 'Det er omvendt: selvkostmetoden gir høyere minimumspris fordi den inkluderer faste kostnader. Bidragsmetoden gir den absolutte minimumsprisen.' },
          { id: 'd', label: 'De er identiske men bruker ulike navn i ulike bransjer', isCorrect: false, feedback: 'De er to fundamentalt ulike metoder med ulikt kostnadsgrunnlag, ulike resultater og ulike bruksformål.' },
        ],
        espenTip: 'Bidragsmetode = kortsiktig minimumspris (kun variable). Selvkostmetode = langsiktig overlevelsespris (alle kostnader). Du trenger begge.',
      },
      {
        id: 'pk-5-3',
        icon: '🔀',
        title: 'Når brukes bidragsmetoden?',
        question: 'En fabrikk har ledig produksjonskapasitet lørdag kveld. En kunde tilbyr å betale 500 kr for en ordre der variable kostnader er 350 kr. Bør fabrikken akseptere?',
        choices: [
          { id: 'a', label: 'Nei — prisen dekker ikke selvkost', isCorrect: false, feedback: 'Selvkostlogikken gjelder for langsiktig planlegging, ikke for enkeltordrer med ledig kapasitet. Faste kostnader løper uansett — det relevante er om 500 kr gir positivt DB.' },
          { id: 'b', label: 'Ja — dekningsbidraget er positivt (500 − 350 = 150 kr)', isCorrect: true, feedback: 'Riktig! DB = 500 − 350 = 150 kr. Alternativet er ledig kapasitet som gir 0 kr i bidrag. 150 kr er bedre enn 0 kr — og de faste kostnadene løper uansett.' },
          { id: 'c', label: 'Bare hvis kunden betaler i forkant', isCorrect: false, feedback: 'Betalingstidspunktet er ikke det avgjørende. Det relevante spørsmålet er om prisen gir positivt dekningsbidrag.' },
          { id: 'd', label: 'Nei — å ta ordrer til lav pris skaper forventninger om lave priser fremover', isCorrect: false, feedback: 'Dette er et legitimt strategisk hensyn, men i den rene kalkulasjonslogikken er positivt DB ved ledig kapasitet alltid bedre enn ingen ordre.' },
        ],
        espenTip: 'Tommelfingerregel: ved ledig kapasitet, aksepter enhver ordre med positivt dekningsbidrag. Ledig kapasitet gir 0 kr — positivt DB er alltid bedre.',
      },
      {
        id: 'pk-5-4',
        icon: '🔀',
        title: 'Dekningsbidragsgrad',
        question: 'Et produkt selges for 200 kr. Variable kostnader er 80 kr. Hva er dekningsbidragsgraden?',
        choices: [
          { id: 'a', label: '40 %', isCorrect: false, feedback: '40 % er forholdet mellom variable kostnader og salgspris (80 ÷ 200). DB-graden beregnes av dekningsbidraget.' },
          { id: 'b', label: '60 %', isCorrect: true, feedback: 'Riktig! DB = 200 − 80 = 120 kr. DB-grad = 120 ÷ 200 = 0,60 = 60 %. Dette betyr at 60 % av hver salgskrone bidrar til faste kostnader og overskudd.' },
          { id: 'c', label: '80 %', isCorrect: false, feedback: '80 kr er de variable kostnadene i kroner — ikke graden. DB-grad = DB ÷ Salgspris × 100.' },
          { id: 'd', label: '150 %', isCorrect: false, feedback: 'En DB-grad over 100 % er matematisk umulig — dekningsbidraget kan aldri overstige salgsprisen.' },
        ],
        espenTip: 'DB-grad forteller deg: av hver krone jeg selger for, hvor mange øre overlever etter variable kostnader? 60 % DB-grad betyr 60 øre per krone til faste kostnader og fortjeneste.',
      },
    ],
  },
  {
    phaseNumber: 6,
    icon: '📚',
    title: 'Sentrale begreper med formler',
    quote: 'Fem begreper — mester du dem, mester du kalkulasjon.',
    content: 'Kalkulasjon har et kjernevokabular som alle som jobber i serviceyrket bør beherske. Begrepene henger tett sammen: selvkosten er terskelen for langsiktig overlevelse, dekningsbidraget måler om et enkelt salg bidrar positivt, dekningsgraden viser lønnsomhetsprosenten av salgsprisen, avansen er påslaget på innkjøpspris, og skillet mellom faste og variable kostnader bestemmer hvilken metode som er riktig å bruke. Å bruke disse korrekt — og ikke blande dem — er avgjørende for å ta gode prisbeslutninger.',
    subpoints: [
      { label: 'SELVKOST', text: 'Selvkost = Variable kostnader + (Faste kostnader ÷ Forventet volum). Minimumsprisen for langsiktig lønnsomhet.' },
      { label: 'DEKNINGSBIDRAG OG -GRAD', text: 'DB = Salgspris − Variable kostnader. DB-grad = DB ÷ Salgspris × 100. Viser hva som bidrar til faste kostnader og fortjeneste.' },
      { label: 'AVANSE', text: 'Avanse (kr) = Salgspris − Innkjøpspris. Avanse (%) = Avanse ÷ Innkjøpspris × 100. Regnes ALLTID av innkjøpspris — ikke salgspris.' },
    ],
    practical: 'En vare kjøpes inn for 300 kr og selges for 450 kr. Beregn: (1) Avanse i kr og %, (2) DB i kr, (3) Dekningsgrad i %. Svar: Avanse = 150 kr = 50 %. DB = 150 kr. Dekningsgrad = 150 ÷ 450 = 33 %.',
    exercises: [
      {
        id: 'pk-6-1',
        icon: '📚',
        title: 'Formel for dekningsbidrag',
        question: 'En butikk kjøper inn en vare for 180 kr og selger den for 270 kr. Hva er dekningsbidraget?',
        choices: [
          { id: 'a', label: '180 kr', isCorrect: false, feedback: '180 kr er innkjøpsprisen. DB = Salgspris − Variable kostnader = 270 − 180 = 90 kr.' },
          { id: 'b', label: '90 kr', isCorrect: true, feedback: 'Riktig! DB = Salgspris − Variable kostnader = 270 − 180 = 90 kr. Dette beløpet bidrar til å dekke faste kostnader og fortjeneste.' },
          { id: 'c', label: '270 kr', isCorrect: false, feedback: '270 kr er salgsprisen — ikke dekningsbidraget. Du må trekke fra variable kostnader.' },
          { id: 'd', label: '450 kr', isCorrect: false, feedback: '450 kr er summen av innkjøpspris og salgspris — et meningsløst tall her. DB = 270 − 180 = 90 kr.' },
        ],
        espenTip: 'DB er alltid: hva du selger for minus hva de variable kostnadene kosta deg. Alt over er «bidraget» til å dekke husleie, lønn og til slutt fortjeneste.',
      },
      {
        id: 'pk-6-2',
        icon: '📚',
        title: 'Formel for avanse',
        question: 'En klesbutikk kjøper inn en jakke for 500 kr og selger den for 750 kr. Hva er avansen i prosent?',
        choices: [
          { id: 'a', label: '33 %', isCorrect: false, feedback: '33 % er dekningsgraden (250 ÷ 750). Avanse beregnes av innkjøpsprisen.' },
          { id: 'b', label: '50 %', isCorrect: true, feedback: 'Riktig! Avanse = (750 − 500) ÷ 500 = 250 ÷ 500 = 50 %. Avansen regnes alltid av innkjøpsprisen.' },
          { id: 'c', label: '67 %', isCorrect: false, feedback: 'Sjekk regnestykket: (750 − 500) ÷ 500 = 250 ÷ 500 = 50 %, ikke 67 %.' },
          { id: 'd', label: '100 %', isCorrect: false, feedback: '100 % avanse ville betydd at salgsprisen er dobbelt av innkjøpspris (500 → 1 000 kr). Her er salgsprisen 750 kr.' },
        ],
        espenTip: 'Avanse % = (Salgspris − Innkjøpspris) ÷ Innkjøpspris × 100. Husk: ALLTID dele på innkjøpspris, ikke salgspris.',
      },
      {
        id: 'pk-6-3',
        icon: '📚',
        title: 'Formel for dekningsgrad',
        question: 'Samme jakke: innkjøp 500 kr, salgspris 750 kr. Hva er dekningsgraden?',
        choices: [
          { id: 'a', label: '50 %', isCorrect: false, feedback: '50 % er avansen (beregnet av innkjøpspris). Dekningsgraden beregnes av salgsprisen.' },
          { id: 'b', label: '67 %', isCorrect: false, feedback: 'Sjekk: DB = 750 − 500 = 250 kr. Dekningsgrad = 250 ÷ 750 ≈ 33 %, ikke 67 %.' },
          { id: 'c', label: '33 %', isCorrect: true, feedback: 'Riktig! DB = 750 − 500 = 250 kr. Dekningsgrad = 250 ÷ 750 ≈ 33 %. Merk: dekningsgraden er alltid lavere enn avansen for samme vare.' },
          { id: 'd', label: '25 %', isCorrect: false, feedback: 'Sjekk: DB = 250 kr. Dekningsgrad = 250 ÷ 750 = 0,333 = 33 %, ikke 25 %.' },
        ],
        espenTip: 'Dekningsgrad % = DB ÷ Salgspris × 100. ALLTID dele på salgspris. Og husk: dekningsgraden er alltid lavere enn avansen for samme transaksjonen.',
      },
      {
        id: 'pk-6-4',
        icon: '📚',
        title: 'Selvkost — formel',
        question: 'En bokhandel selger 400 bøker per måned. Månedlige faste kostnader: 32 000 kr. Innkjøpspris per bok: 120 kr. Hva er selvkosten per bok?',
        choices: [
          { id: 'a', label: '120 kr', isCorrect: false, feedback: '120 kr er kun innkjøpsprisen. Selvkost inkluderer også en andel av de faste kostnadene.' },
          { id: 'b', label: '200 kr', isCorrect: true, feedback: 'Riktig! Faste kostnader per bok = 32 000 ÷ 400 = 80 kr. Selvkost = 120 + 80 = 200 kr.' },
          { id: 'c', label: '80 kr', isCorrect: false, feedback: '80 kr er andelen av faste kostnader per bok (32 000 ÷ 400). Selvkost = innkjøpspris + andel faste kostnader = 120 + 80 = 200 kr.' },
          { id: 'd', label: '152 kr', isCorrect: false, feedback: 'Sjekk beregningen: Faste per bok = 32 000 ÷ 400 = 80 kr. Selvkost = 120 + 80 = 200 kr.' },
        ],
        espenTip: 'Selvkost per enhet = Variable kostnader per enhet + (Totale faste kostnader ÷ Forventet volum). Alltid to ledd.',
      },
    ],
  },
  {
    phaseNumber: 7,
    icon: '🏨',
    title: 'Praktisk eksempel: hotellbransjen',
    quote: 'Kan du selge et rom til 600 kr når selvkosten er 1 200 kr? Ja — hvis det er tirsdag kveld og rommet ellers står tomt.',
    content: 'Hotellbransjen er lærebokeksempelet på bidragskalkyle i praksis. Høye faste kostnader (bygning, fast personale, vedlikehold) løper uansett om hotellet er fullt eller tomt. De variable kostnadene per rom er derimot lave: renhold, frokostingredieneer, såpe og gjesteartikler — gjerne 200–400 kr per rom per natt. Resultatet er at ethvert rom solgt over variable kostnader gir et positivt dekningsbidrag. Et rom til 600 kr med variable kostnader på 300 kr gir DB = 300 kr — selv om selvkosten er 1 200 kr. Alternativet — å ikke selge rommet — gir DB = 0 kr, men de faste kostnadene påløper like fullt.',
    subpoints: [
      { label: 'FORUTSETNINGENE', text: '50 tomme rom en tirsdag. Faste kostnader (bygning, fast personale): 1 200 kr per rom per natt fordelt. Variable kostnader (renhold, frokost, forbruksvarer): 300 kr per rom.' },
      { label: 'DYNAMISK PRISING', text: 'Hotellet setter prisen til 600 kr via booking-aggregator. DB = 600 − 300 = 300 kr per rom. 50 rom × 300 kr = 15 000 kr i ekstra DB — mot 0 kr om rommene står tomme.' },
      { label: 'LOGIKKEN', text: 'De faste kostnadene (1 200 kr/rom) løper uansett. Prisen trenger ikke dekke selvkost (1 500 kr) — den trenger bare overskride variable kostnader (300 kr) for å bidra positivt.' },
    ],
    practical: 'Hotellet har 50 tomme rom. Variable kostnader er 300 kr/rom. En reiseagent tilbyr å fylle 30 rom til 500 kr per rom. Beregn: (1) DB per rom, (2) Samlet DB, (3) Bør hotellet takke ja? Svar: DB = 200 kr. Samlet = 6 000 kr. Ja.',
    exercises: [
      {
        id: 'pk-7-1',
        icon: '🏨',
        title: 'DB-beregning for hotellet',
        question: 'Et hotellrom selges for 750 kr. Variable kostnader er 300 kr per rom. Hva er dekningsbidraget per rom?',
        choices: [
          { id: 'a', label: '300 kr', isCorrect: false, feedback: '300 kr er de variable kostnadene, ikke dekningsbidraget. DB = Salgspris − Variable kostnader = 750 − 300 = 450 kr.' },
          { id: 'b', label: '750 kr', isCorrect: false, feedback: '750 kr er salgsprisen. Dekningsbidraget er det som gjenstår etter at variable kostnader er trukket fra.' },
          { id: 'c', label: '450 kr', isCorrect: true, feedback: 'Riktig! DB = Salgspris − Variable kostnader = 750 − 300 = 450 kr. Dette bidraget brukes til å dekke de faste kostnadene (bygning, fast personale).' },
          { id: 'd', label: '1 050 kr', isCorrect: false, feedback: '1 050 kr er summen av pris og variable kostnader — husk at du skal trekke fra, ikke legge til.' },
        ],
        espenTip: 'DB er bidraget til å dekke faste kostnader. Høyt DB per enhet betyr at du trenger å selge færre rom for å nå break-even.',
      },
      {
        id: 'pk-7-2',
        icon: '🏨',
        title: 'Ledig kapasitet — ta ordren?',
        question: 'Hotellet har 50 tomme rom en tirsdag. Selvkost per rom er 1 500 kr, men variable kostnader er 300 kr. En nettagent tilbyr å fylle 30 rom til 600 kr per rom. Hva bør hotellet gjøre?',
        choices: [
          { id: 'a', label: 'Avslå — prisen er langt under selvkost på 1 500 kr', isCorrect: false, feedback: 'Selvkostlogikken gjelder for langsiktig prissetting, ikke for enkeltordrer med ledig kapasitet. De faste kostnadene løper uansett — det relevante er om 600 kr gir positivt DB.' },
          { id: 'b', label: 'Akseptere — hvert rom gir positivt dekningsbidrag på 300 kr (600 − 300)', isCorrect: true, feedback: 'Riktig! DB = 600 − 300 = 300 kr per rom. 30 rom × 300 kr = 9 000 kr ekstra DB. Alternativet er 0 kr — rommene står tomme og faste kostnader løper uansett.' },
          { id: 'c', label: 'Akseptere kun hvis de kan forhandle prisen opp til 900 kr', isCorrect: false, feedback: 'Å forhandle er ikke feil — men å avslå et tilbud over variable kostnader betyr å gå glipp av 9 000 kr i DB.' },
          { id: 'd', label: 'Avslå — lavprisgjester skader hotellets omdømme', isCorrect: false, feedback: 'Omdømme er en legitim bekymring i noen tilfeller, men i dette spørsmålet er fokuset på den rene kalkulasjonslogikken.' },
        ],
        espenTip: 'Spørsmålet ved ledig kapasitet er aldri «dekker prisen selvkost?», men «er prisen over variable kostnader?» Svaret avgjør om du bør si ja eller nei.',
      },
      {
        id: 'pk-7-3',
        icon: '🏨',
        title: 'Regneoppgave — total DB',
        question: 'Hotellet har 50 tomme rom. Variable kostnader: 300 kr/rom. Alle 50 rom selges for 600 kr per rom. Hva er samlet dekningsbidrag fra disse 50 rommene?',
        choices: [
          { id: 'a', label: '15 000 kr', isCorrect: true, feedback: 'Riktig! DB per rom = 600 − 300 = 300 kr. Samlet DB = 300 kr × 50 rom = 15 000 kr. Disse 15 000 kr bidrar til å dekke de faste kostnadene.' },
          { id: 'b', label: '30 000 kr', isCorrect: false, feedback: '30 000 kr er total salgsinntekt (600 × 50). Du må trekke fra variable kostnader: 300 × 50 = 15 000 kr. DB = 30 000 − 15 000 = 15 000 kr.' },
          { id: 'c', label: '60 000 kr', isCorrect: false, feedback: '60 000 kr er ikke riktig. Salgsinntekt = 600 × 50 = 30 000 kr. Variable kostnader = 300 × 50 = 15 000 kr. DB = 15 000 kr.' },
          { id: 'd', label: '75 000 kr', isCorrect: false, feedback: '75 000 kr er selvkost × antall rom (1 500 × 50). Det er ikke DB. DB = (600 − 300) × 50 = 15 000 kr.' },
        ],
        espenTip: 'Alltid: DB per enhet × antall enheter = samlet DB. Her: 300 kr × 50 rom = 15 000 kr — mot 0 kr hvis rommene hadde stått tomme.',
      },
      {
        id: 'pk-7-4',
        icon: '🏨',
        title: 'Dynamisk prising — logikken',
        question: 'Hvorfor bruker hoteller dynamisk prising og selger rom til ulike priser til ulike tider?',
        choices: [
          { id: 'a', label: 'Fordi de ønsker å straffe kunder som bestiller sent', isCorrect: false, feedback: 'Dynamisk prising er en inntektsoptimaliserings-strategi, ikke en straffe-mekanisme. Poenget er å fylle kapasitet, ikke å straffe noen.' },
          { id: 'b', label: 'Fordi de liker å variere prisene for å teste markedet', isCorrect: false, feedback: 'Testing er en bieffekt, ikke formålet. Dynamisk prising er begrunnet av bidragslogikken: ved ledig kapasitet er ethvert positivt DB bedre enn tomt rom.' },
          { id: 'c', label: 'Fordi faste kostnader løper uansett, og ethvert salg over variable kostnader gir positivt dekningsbidrag', isCorrect: true, feedback: 'Riktig! Det er nøyaktig bidragskalkylelogikken: faste kostnader (bygning, fast personale) er allerede bundet. Et rom til lav pris som dekker variable kostnader bidrar positivt — tomt rom gir null.' },
          { id: 'd', label: 'Fordi variable kostnader øker dramatisk nær innsjekk', isCorrect: false, feedback: 'Variable kostnader per gjest endrer seg ikke vesentlig med bookingstidspunkt. Poenget er tvert imot at de variable kostnadene er lave og stabile.' },
        ],
        espenTip: 'Neste gang du ser et hotellrom til halv pris på en tirsdag: det er ikke en feil — det er bidragskalkyle i praksis.',
      },
    ],
  },
  {
    phaseNumber: 8,
    icon: '📣',
    title: 'Prisstrategier',
    quote: 'Pris er ikke bare et tall — det er et signal, en strategi og et løfte til kunden.',
    content: 'Valg av prisstrategi er en av de viktigste strategiske beslutningene en bedrift tar. Markedsskumming starter høyt for å ta ut betalingsvilje hos tidlige kjøpere, og senker prisen gradvis. Penetrasjonsprising starter lavt for å vinne markedsandeler raskt. Psykologisk prising utnytter at vi leser priser fra venstre og vektlegger første siffer. Dynamisk prising varierer prisen i sanntid basert på etterspørsel og kapasitetsutnyttelse — og er nå teknologisk tilgjengelig for selv små bedrifter gjennom booking-systemer og nettbutikker.',
    subpoints: [
      { label: 'SKUMMING', text: 'Høy inngangspris for å ta ut maksimal betalingsvilje hos entusiastiske tidlige kjøpere. Deretter gradvis prisreduksjon. Eksempel: ny iPhone til 15 000 kr, to år senere 8 000 kr.' },
      { label: 'PENETRASJON', text: 'Lav inngangspris for å vinne markedsandeler raskt og skape vaner. Eksempel: nye matleverings-apper med gratis levering og rabatter det første halvåret.' },
      { label: 'PSYKOLOGISK OG DYNAMISK', text: 'Psykologisk: 199 kr i stedet for 200 kr — kunden kategoriserer ut fra første siffer. Dynamisk: variable priser basert på tid, etterspørsel og ledig kapasitet (fly, hotell, Ruter).' },
    ],
    practical: 'Finn ett eksempel på markedsskumming og ett eksempel på penetrasjonsprising i norsk næringsliv. Hva er risikoen ved hver strategi?',
    exercises: [
      {
        id: 'pk-8-1',
        icon: '📣',
        title: 'Psykologisk prising',
        question: 'Hvorfor setter butikker priser som 299 kr i stedet for 300 kr?',
        choices: [
          { id: 'a', label: 'For å spare kunden for 1 kr og vise sosial ansvarlighet', isCorrect: false, feedback: '1 kr i sparing er ikke motivasjonen. Det handler om psykologi: kunden leser prisen fra venstre og vektlegger 2-tallet fremfor 3-tallet.' },
          { id: 'b', label: 'Fordi det er et lovkrav å unngå runde tall i prismerking', isCorrect: false, feedback: 'Det finnes ingen slik lovbestemmelse. Praksisen er helt frivillig og basert på atferdsøkonomi.' },
          { id: 'c', label: 'Fordi kunder oppfatter 299 kr som vesentlig billigere enn 300 kr — det første sifferet dominerer prisopplevelsen', isCorrect: true, feedback: 'Riktig! Forskning viser at kunder kategoriserer 299 kr som «200-kroners-klassen» fordi vi leser priser fra venstre. Effekten er størst ved runde tallgrenser.' },
          { id: 'd', label: 'For å gjøre kasseoppgjøret lettere med veksel', isCorrect: false, feedback: 'Tvert imot — runde priser gjør kasseoppgjøret enklere. Psykologisk prising er begrunnet i kundepsykologi, ikke praktisk kassahåndtering.' },
        ],
        espenTip: 'Neste gang du handler: se etter priser som slutter på 9 eller 95. Det er ikke tilfeldigheter — det er systematisk atferdsøkonomi i praksis.',
      },
      {
        id: 'pk-8-2',
        icon: '📣',
        title: 'Markedsskumming',
        question: 'Apple lanserer ny iPhone til 15 000 kr. To år senere koster den 8 000 kr. Hvilken prisstrategi er dette?',
        choices: [
          { id: 'a', label: 'Penetrasjonsprising', isCorrect: false, feedback: 'Penetrasjonsprising starter MED lav pris for å vinne markedsandeler raskt. Apple gjør det motsatte.' },
          { id: 'b', label: 'Kostnadsorientert prising', isCorrect: false, feedback: 'Apples priser er primært basert på betalingsvilje og merkevare, ikke kun produksjonskostnad.' },
          { id: 'c', label: 'Markedsskumming (price skimming)', isCorrect: true, feedback: 'Riktig! Markedsskumming starter med høy pris for å maksimere inntektene fra kunder med høy betalingsvilje (tidlige adoptere), deretter senkes prisen for å nå bredere segmenter.' },
          { id: 'd', label: 'Dynamisk prising', isCorrect: false, feedback: 'Dynamisk prising varierer prisen i sanntid basert på etterspørsel. Apples prinsipp er mer strukturert og langsiktig — typisk markedsskumming.' },
        ],
        espenTip: 'Markedsskumming funker best for innovative produkter med entusiastiske tidligkjøpere og uten sterk konkurranse ved lansering.',
      },
      {
        id: 'pk-8-3',
        icon: '📣',
        title: 'Penetrasjonsprising',
        question: 'Et nytt matleveringsselskap tilbyr gratis levering og rabatterte priser det første halvåret for å vinne kunder. Hvilken prisstrategi er dette?',
        choices: [
          { id: 'a', label: 'Markedsskumming', isCorrect: false, feedback: 'Markedsskumming starter MED høy pris. Her starter selskapet med lav pris — det er det motsatte.' },
          { id: 'b', label: 'Penetrasjonsprising', isCorrect: true, feedback: 'Riktig! Penetrasjonsprising bruker lav inngangspris for å vinne markedsandeler raskt og skape vaner hos kundene. Når posisjonen er etablert, kan prisen gradvis økes.' },
          { id: 'c', label: 'Psykologisk prising', isCorrect: false, feedback: 'Psykologisk prising handler om prispresentasjon (199 kr vs 200 kr), ikke om å starte lavt for å vinne markedsandeler.' },
          { id: 'd', label: 'Kostnadsorientert prising', isCorrect: false, feedback: 'Kostnadsorientert prising setter pris basert på kostnader og ønsket margin. En bevisst underpris for å vinne markedet er penetrasjonsprising.' },
        ],
        espenTip: 'Penetrasjonsprising er risikabelt: kunder som kom for billigprisen forsvinner gjerne når prisen stiger. Wolt og Foodora har opplevd dette med abonnementsrabatter.',
      },
      {
        id: 'pk-8-4',
        icon: '📣',
        title: 'Dynamisk prising',
        question: 'Ruter øker prisene under rush og senker dem på stille tider. Et hotell selger rom billigere på tirsdag enn på fredag. Hva er fellesnevneren?',
        choices: [
          { id: 'a', label: 'Begge bruker penetrasjonsprising for å vinne nye kunder', isCorrect: false, feedback: 'Penetrasjonsprising er en langsiktig strategi for nye aktører. Ruter og hotellet er etablerte — de optimaliserer kapasitetsutnyttelsen, ikke markedsandelen.' },
          { id: 'b', label: 'Begge bruker dynamisk prising for å optimalisere inntekter basert på etterspørsel og kapasitet', isCorrect: true, feedback: 'Riktig! Dynamisk prising varierer priser i sanntid (eller etter mønster) for å maksimere dekningsbidraget ved å balansere pris og kapasitetsutnyttelse.' },
          { id: 'c', label: 'Begge bryter Markedsføringsloven ved å diskriminere kunder', isCorrect: false, feedback: 'Dynamisk prising er fullt lovlig — det er ingen diskriminering å tilby ulike priser til ulike tider, så lenge prisene ikke er diskriminerende basert på personkjennetegn.' },
          { id: 'd', label: 'Begge bruker psykologisk prising for å få kunder til å føle de får rabatt', isCorrect: false, feedback: 'Psykologisk prising handler om prispresentasjon (199 kr). Dynamisk prising handler om reelle prisvariasjoner basert på etterspørsel og kapasitet.' },
        ],
        espenTip: 'Dynamisk prising er fremtiden — og den er allerede her. Nettbutikker, flyselskaper, hoteller og nå stadig flere restauranter bruker algoritmer til å sette optimal pris hvert øyeblikk.',
      },
    ],
  },
  {
    phaseNumber: 9,
    icon: '⚠️',
    title: 'Vanlige misforståelser — avanse vs dekningsgrad',
    quote: 'Denne ene forvirringen har kostet utallige butikkeiere dyrt.',
    content: 'Den vanligste kalkulasjonsfeilen blant nye butikkeiere er å blande sammen avanse og dekningsgrad. De beregnes med ulikt grunnlag og gir ulike prosenttall for samme vare. Et produkt kjøpt inn for 100 kr og solgt for 150 kr gir 50 kr avanse = 50 % avanse (av innkjøpspris), men kun 33 % dekningsgrad (av salgspris). Den som tror de har 50 % av salgsprisen tilgjengelig til faste kostnader og fortjeneste, har faktisk bare 33 %. Differansen kan se liten ut — men med månedlige faste kostnader på hundre tusen kroner kan feilberegningen bety konkurs.',
    subpoints: [
      { label: 'AVANSE', text: 'Påslag regnet av INNKJØPSPRISEN. Eksempel: innkjøp 100 kr, avanse 50 % → salgspris 150 kr. Avanse i kr = 50. Avanse i % = 50 ÷ 100 = 50 %.' },
      { label: 'DEKNINGSGRAD', text: 'Dekningsbidrag regnet av SALGSPRISEN. Samme vare: DB = 150 − 100 = 50 kr. Dekningsgrad = 50 ÷ 150 = 33 %. Dekningsgraden er ALLTID lavere enn avansen.' },
      { label: 'HUSKEREGEL', text: 'Avanse = av innkjøpspris (det du betalte). Dekningsgrad = av salgspris (det du mottok). Aldri bland disse to grunnlagene.' },
    ],
    practical: 'En klesbutikk kjøper inn alle varer med 80 % avanse. Hva er dekningsgraden? (Innkjøp = 100, salgspris = 180. DB = 80. Dekningsgrad = 80 ÷ 180 = 44 %). Månedlige faste kostnader er 90 000 kr. Hva må omsetningen minst være? (90 000 ÷ 0,44 = 204 545 kr)',
    exercises: [
      {
        id: 'pk-9-1',
        icon: '⚠️',
        title: 'Avanse — beregning',
        question: 'En butikk kjøper inn en vare for 200 kr og selger den for 300 kr. Hva er avansen i prosent?',
        choices: [
          { id: 'a', label: '33 %', isCorrect: false, feedback: '33 % er dekningsgraden (100 ÷ 300). Avansen beregnes av innkjøpsprisen, ikke salgsprisen.' },
          { id: 'b', label: '50 %', isCorrect: true, feedback: 'Riktig! Avanse = (Salgspris − Innkjøpspris) ÷ Innkjøpspris = (300 − 200) ÷ 200 = 100 ÷ 200 = 50 %.' },
          { id: 'c', label: '100 %', isCorrect: false, feedback: '100 % avanse ville betydd at salgsprisen er dobbelt av innkjøpspris (200 kr → 400 kr). Her er salgsprisen 300 kr.' },
          { id: 'd', label: '150 %', isCorrect: false, feedback: '150 kr er ikke avansen — 100 kr er påslaget (300 − 200). 150 % ville vært et påslag på 300 kr.' },
        ],
        espenTip: 'Avanse = påslag ÷ innkjøpspris × 100. Alltid deler du på det du kjøpte for, ikke det du solgte for.',
      },
      {
        id: 'pk-9-2',
        icon: '⚠️',
        title: 'Dekningsgrad — beregning',
        question: 'Samme vare: innkjøp 200 kr, salgspris 300 kr. Hva er dekningsgraden?',
        choices: [
          { id: 'a', label: '50 %', isCorrect: false, feedback: '50 % er avansen (beregnet av innkjøpspris). Dekningsgraden beregnes av salgsprisen.' },
          { id: 'b', label: '66 %', isCorrect: false, feedback: 'Sjekk beregningen: DB = 300 − 200 = 100 kr. Dekningsgrad = 100 ÷ 300 ≈ 33 %, ikke 66 %.' },
          { id: 'c', label: '33 %', isCorrect: true, feedback: 'Riktig! DB = 300 − 200 = 100 kr. Dekningsgrad = 100 ÷ 300 ≈ 33 %. Legg merke til at dekningsgraden (33 %) alltid er lavere enn avansen (50 %) for samme produkt.' },
          { id: 'd', label: '100 %', isCorrect: false, feedback: '100 % dekningsgrad ville betydd at salgsprisen er ren fortjeneste med null varekostnad.' },
        ],
        espenTip: 'Dekningsgrad = DB ÷ Salgspris × 100. Alltid deler du på det du solgte for. Dekningsgraden er ALLTID lavere enn avansen for samme transaksjonen.',
      },
      {
        id: 'pk-9-3',
        icon: '⚠️',
        title: 'Hvorfor er feilen farlig?',
        question: 'En butikk setter 50 % avanse på alle varer og planlegger budsjettet med 50 % av omsetningen til å dekke faste kostnader. Hva er problemet?',
        choices: [
          { id: 'a', label: 'Ingen problem — 50 % avanse betyr at 50 % av salgsprisen er disponibelt', isCorrect: false, feedback: 'Dette er nettopp feilforståelsen! 50 % avanse er IKKE det samme som 50 % av salgsprisen. Med 50 % avanse er dekningsgraden kun 33 %.' },
          { id: 'b', label: 'Butikken overvurderer disponibelt beløp til faste kostnader med 17 prosentpoeng — og risikerer underskudd', isCorrect: true, feedback: 'Riktig! 50 % avanse = 33 % dekningsgrad. Hvis budsjettet er basert på 50 % dekningsgrad, mangler butikken 17 % av omsetningen til å dekke faste kostnader. Med høy omsetning kan dette utgjøre hundretusener.' },
          { id: 'c', label: 'Avansen er for lav — butikken bør ha minst 80 % avanse', isCorrect: false, feedback: 'Avansens «riktige» nivå avhenger av kostnadssstrukturen. Problemet her er ikke avansens størrelse, men at budsjettplanleggingen bruker feil grunnlag.' },
          { id: 'd', label: 'Det er ingen forskjell — avanse og dekningsgrad er det samme', isCorrect: false, feedback: 'De er ikke det samme. Avanse = av innkjøpspris. Dekningsgrad = av salgspris. For samme vare gir de ulike prosenttall.' },
        ],
        espenTip: 'Jeg har sett butikker gå konkurs fordi de trodde 40 % avanse ga 40 % til faste kostnader — men de hadde bare 29 % dekningsgrad.',
      },
      {
        id: 'pk-9-4',
        icon: '⚠️',
        title: 'Minste nødvendige dekningsgrad',
        question: 'En butikk har månedlige faste kostnader på 60 000 kr og forventer omsetning på 200 000 kr. Hva er den minste dekningsgraden som gir break-even?',
        choices: [
          { id: 'a', label: '20 %', isCorrect: false, feedback: '20 % av 200 000 kr = 40 000 kr i DB — ikke nok til å dekke 60 000 kr i faste kostnader.' },
          { id: 'b', label: '30 %', isCorrect: true, feedback: 'Riktig! Break-even krever at DB = Faste kostnader. DB = 30 % av 200 000 kr = 60 000 kr = akkurat lik de faste kostnadene. Under 30 % gir underskudd.' },
          { id: 'c', label: '40 %', isCorrect: false, feedback: '40 % av 200 000 kr = 80 000 kr i DB — 20 000 kr over break-even. Det er bedre enn nødvendig, men ikke minimumet.' },
          { id: 'd', label: '60 %', isCorrect: false, feedback: '60 % av 200 000 kr = 120 000 kr — langt over break-even. Minimumet er 60 000 ÷ 200 000 = 30 %.' },
        ],
        espenTip: 'Minste nødvendige dekningsgrad = Faste kostnader ÷ Forventet omsetning × 100. Dette er det første regnestykket en ny butikkeier bør gjøre.',
      },
    ],
  },
  {
    phaseNumber: 10,
    icon: '⚖️',
    title: 'Lovverk og oppsummering',
    quote: 'Riktig pris er ikke bare god matematikk — det er også god jus.',
    content: 'Prissetting skjer innenfor et juridisk rammeverk. Pristiltaksloven gir myndighetene hjemmel til å gripe inn mot urimelig høye priser — særlig aktuell i krisetider eller ved misbruk av monopolstilling. Markedsføringsloven setter strenge krav til bruk av «ordinær pris» og «før-/nå-priser» i reklame: varen må faktisk ha vært solgt til den oppgitte ordinære prisen i rimelig tid og omfang. Forbrukertilsynet håndhever begge lover aktivt og har gitt flere norske aktører bøter for manipulerende prismarkedsføring. Riktig kalkulasjon, riktig prisstrategi og etterlevelse av lovverket er tre separate, men likeverdige pilarer i profesjonell prissetting.',
    subpoints: [
      { label: 'PRISTILTAKSLOVEN', text: 'Regulerer urimelig høye priser. Aktuell ved monopolsituasjoner, kriser og når markedsmekanismene svikter. Hjemler prisregulering fra myndighetene.' },
      { label: 'MARKEDSFØRINGSLOVEN', text: 'Regulerer prismarkedsføring — særlig § 12 om bruk av ordinær pris og salgskampanjer. Varen må ha vært solgt til den høyere prisen i rimelig tid og omfang.' },
      { label: 'OPPSUMMERING', text: 'Riktig pris balanserer tre hensyn: kostnadsdekning (selvkost og bidrag), konkurranseposisjon (prisstrategier) og lovlighet (Pristiltaksloven, Markedsføringsloven). Mester du disse, mester du prissetting.' },
    ],
    practical: 'Finn et eksempel på en norsk kampanje som har fått kritikk fra Forbrukertilsynet for ulovlig prismarkedsføring. Hva gjorde selskapet, og hva ble konsekvensen?',
    exercises: [
      {
        id: 'pk-10-1',
        icon: '⚖️',
        title: 'Pristiltaksloven',
        question: 'Hva regulerer Pristiltaksloven?',
        choices: [
          { id: 'a', label: 'Krav om at alle butikker skal vise priser inklusiv mva på prislapp', isCorrect: false, feedback: 'Prismerkingsplikten følger av prismerkeforskriften, ikke Pristiltaksloven. Pristiltaksloven handler om prisnivået, ikke prismerking.' },
          { id: 'b', label: 'Forbud mot priser som er urimelig høye sett i lys av normale markedsforhold', isCorrect: true, feedback: 'Riktig! Pristiltaksloven gir myndighetene hjemmel til å gripe inn mot urimelig høye priser — for eksempel under kriser eller ved monopolsituasjoner.' },
          { id: 'c', label: 'Krav om at alle varer skal selges til samme pris i hele landet', isCorrect: false, feedback: 'Det er ingen lov som krever lik pris over hele landet. Pristiltaksloven handler om å forebygge misbruk, ikke om å standardisere priser.' },
          { id: 'd', label: 'Forbud mot å sette priser under selvkost', isCorrect: false, feedback: 'Det finnes visse regler om underprising for dominerende aktører i konkurranseloven, men det er ikke Pristiltakslovens primære formål.' },
        ],
        espenTip: 'Pristiltaksloven brukes sjelden i fredstid, men kom til sin rett under koronapandemien da håndspreitholdere ble solgt for mange ganger normal pris.',
      },
      {
        id: 'pk-10-2',
        icon: '⚖️',
        title: 'Markedsføringsloven og før-/nå-priser',
        question: 'En nettbutikk annonserer «Spar 50 %! Før 1 000 kr, nå 500 kr». Hva krever Markedsføringsloven for at denne annonsen er lovlig?',
        choices: [
          { id: 'a', label: 'At prisen er godkjent av Forbrukertilsynet på forhånd', isCorrect: false, feedback: 'Forbrukertilsynet godkjenner ikke priser på forhånd — de fører tilsyn og kan reagere i ettertid.' },
          { id: 'b', label: 'At varen faktisk har vært solgt til 1 000 kr i rimelig tid og omfang før kampanjen', isCorrect: true, feedback: 'Riktig! Loven krever at «ordinær pris» er reell — den må ha vært den faktiske prisen i en representativ periode. Å sette kunstig høy «før-pris» bare for å gjøre rabatten større er ulovlig.' },
          { id: 'c', label: 'At kunden informeres om hvor lenge kampanjen varer', isCorrect: false, feedback: 'Det er god praksis, men ikke hovedkravet knyttet til bruk av før-/nå-priser.' },
          { id: 'd', label: 'At annonsen er merket med hvem som har laget den', isCorrect: false, feedback: 'Avsendermerking er et krav for reklame i sosiale medier for å skille reklame fra redaksjonelt innhold — ikke det primære kravet for før-/nå-priser i vanlig reklame.' },
        ],
        espenTip: 'EU-direktivet om forbrukervern (2022) skjerpet reglene: «ordinær pris» skal nå typisk baseres på den laveste prisen de siste 30 dagene.',
      },
      {
        id: 'pk-10-3',
        icon: '⚖️',
        title: 'Lovbrudd i prismarkedsføring',
        question: 'En nettbutikk setter kunstig høy «veiledende pris» på alle varer i to dager, for deretter å annonsere «50 % rabatt» resten av måneden. Hva er problemet juridisk?',
        choices: [
          { id: 'a', label: 'Det er ikke noe problem — bedriften kan sette veiledende pris fritt', isCorrect: false, feedback: 'Det er et problem. Markedsføringsloven krever at den oppgitte «ordinære prisen» er reell og representativ. En kunstig høy pris satt i kun to dager er ikke reell.' },
          { id: 'b', label: 'Det bryter Markedsføringsloven fordi «ordinær pris» ikke er reell — kunden villedes til å tro rabatten er større enn den faktisk er', isCorrect: true, feedback: 'Riktig! Dette er klassisk villedende prismarkedsføring. Forbrukertilsynet har ilagt bøter for slike praksiser. Den oppgitte referanseprisen må reflektere den prisen varen faktisk er solgt til i representativt volum og tid.' },
          { id: 'c', label: 'Det bryter Pristiltaksloven fordi prisen er satt for høyt', isCorrect: false, feedback: 'Pristiltaksloven handler om urimelig høye priser generelt — ikke om prismarkedsføring og sammenligningspriser. Her er Markedsføringsloven relevant.' },
          { id: 'd', label: 'Det er kun ulovlig hvis Forbrukertilsynet oppdager det', isCorrect: false, feedback: 'Handlingen er ulovlig uavhengig av om den oppdages. Oppdagelse er kun forutsetning for håndhevelse, ikke for lovbruddet.' },
        ],
        espenTip: 'Black Friday-kampanjer er et typisk risikoområde. Forbrukertilsynet overvåker nettbutikker aktivt og sammenligner priser over tid for å avsløre kunstige referansepriser.',
      },
    ],
  },
]

export default function PrisOgKalkulasjonModule() {
  return (
    <DrawerModule
      moduleCode="OK-VG2-7"
      moduleTitle="Pris og kalkulasjon"
      moduleIcon="🧮"
      storageKey="learning-vg2-pris-og-kalkulasjon"
      completeRoute="/learning/vg2/okonomi/pris-og-kalkulasjon/complete"
      phases={phases}
      intro="Prissetting er en av de viktigste og mest undervurderte ferdighetene i serviceyrket. For mange bedrifter går med underskudd ikke fordi de selger for lite, men fordi de setter feil pris. Forstår du selvkost, dekningsbidrag og avanse — og klarer å holde dem fra hverandre — har du et solid grunnlag for å ta prisbeslutninger som faktisk holder bedriften lønnsom."
      vissteduAt="En undersøkelse blant norske småbedrifter viste at over 40 % av gründerne ikke skiller mellom avanse og dekningsgrad. De tror de har 50 % av salgsprisen til rådighet for faste kostnader og fortjeneste — men har egentlig bare 33 %."
      espenSier="Avanse og dekningsgrad er den kalkulasjonsfellen jeg ser oftest. Nye butikkeiere setter 50 % avanse og tror de er på trygg grunn — men 50 % avanse er bare 33 % dekningsgrad. Det er nok til å gå konkurs i et marked med høye leiekostnader."
      presentationLink={{ route: '/learning/presentations/pris-og-kalkulasjon', description: 'Pris og kalkulasjon — en visuell gjennomgang av prisstrategier og selvkost' }}
    />
  )
}
